/**
 * Semantic memory domain types for the MAM Memory Engine.
 *
 * Semantic memory stores **facts and knowledge** — timeless, decontextualised
 * assertions about the world that an agent has learned and wishes to consult
 * later. Unlike episodic memory (which records *experiences* anchored to a
 * window of time) or procedural memory (which records *how to do things*),
 * semantic memory is oriented around *what is true*: "the deploy pipeline runs
 * on Node 20", "the API key is rotated every 90 days", "the user prefers
 * TypeScript over JavaScript".
 *
 * Each unit of semantic knowledge is a {@link SemanticEntry}:
 *
 * - a mandatory human-readable **fact** string, e.g. `"the database is
 *   Postgres 16 and runs on the primary replica"`,
 * - an optional structured **subject / predicate / object** triple for callers
 *   that want to query facts relationally,
 * - an optional **embedding** vector so facts can be located by *meaning*
 *   rather than by literal substring,
 * - **tags**, a **source** attribution and a **confidence** score so that
 *   knowledge can be filtered, explained and decayed over time.
 *
 * The types in this module form the public contract shared by every other
 * layer of the semantic subsystem:
 *
 * - {@link SemanticEntry} / {@link MutableSemanticEntry} — the stored fact and
 *   its mutable builder form.
 * - {@link SemanticConfig} — construction/behaviour options for the store,
 *   index, retriever and lifecycle.
 * - {@link SemanticStats} — aggregate counters describing a store.
 * - {@link SemanticEntryOptions} — the options bag accepted by
 *   `SemanticStore.put`.
 * - {@link SemanticHit} — an entry paired with a similarity score.
 * - {@link SemanticPruneResult}, {@link SemanticDedupeResult},
 *   {@link SemanticDecayResult}, {@link SemanticNormalizeResult} — the result
 *   shapes emitted by the lifecycle layer.
 * - {@link SemanticLifecycleEvent} — payloads fired by the lifecycle event
 *   emitter.
 * - {@link RuntimeMemory} — the uniform memory contract implemented by
 *   {@link SemanticRuntimeAdapter} so semantic, episodic and working memory can
 *   be swapped behind a single consumer.
 *
 * The types are deliberately framework-agnostic and serialisable: every type
 * here can be round-tripped through {@link JSON} without loss, so a
 * {@link SemanticEntry} captured in one process can be persisted and restored
 * by another process or thread without schema migration.
 *
 * @packageDocumentation
 * @module semantic/types
 */

/**
 * Unique identifier for a semantic entry.
 *
 * Identifiers should be stable within a single store and are generally
 * generated by the caller or by {@link SemanticStore.put} when none is
 * supplied. The semantic layer treats them as opaque strings and never
 * inspects their internal structure, so any collision-free scheme is
 * acceptable within the scope of one {@link SemanticStore}.
 */
export type SemanticEntryId = string;

/**
 * Milliseconds-since-epoch timestamp.
 *
 * All wall-clock values in the semantic layer use epoch milliseconds so that
 * they interoperate cleanly with both {@link Date} and `performance.now()`
 * derived clocks, and so that age-based operations such as
 * `SemanticLifecycle.decayStale` do not need to deal with calendar
 * complexities.
 */
export type Timestamp = number;

/**
 * Confidence score attached to a fact, in `[0, 1]`.
 *
 * `1` means the fact is treated as certainly true; lower values mark it as
 * uncertain, inferred or decaying. Confidence is used by
 * {@link SemanticRetriever.byConfidence} for filtering and by
 * {@link SemanticLifecycle.decayStale} for time-based demotion, so a fact that
 * has not been re-confirmed for a long while gradually becomes less
 * retrievable by confidence and eventually eligible for pruning.
 */
export type Confidence = number;

/**
 * Free-form, unstructured metadata attached to a semantic entry.
 *
 * Metadata is intentionally untyped beyond `Record<string, unknown>`: it is
 * meant to carry domain-specific payloads (trace ids, model names, request
 * identifiers, user assertions) that the semantic layer does not need to
 * interpret but must preserve verbatim through serialisation. Values should be
 * JSON-serialisable to guarantee `toJSON`/`fromJSON` round-trips.
 */
export type SemanticMetadata = Record<string, unknown>;

/**
 * A single stored fact or unit of knowledge.
 *
 * Every entry carries a **fact** — the canonical, human-readable sentence that
 * expresses the knowledge. The optional {@link subject}, {@link predicate} and
 * {@link object} fields let callers additionally model the fact as a triple,
 * enabling relational queries such as `bySubject`. The optional
 * {@link embedding} is the vector used for meaning-based retrieval; when absent
 * it is computed on demand by the TF-IDF index from the fact text.
 *
 * The invariant maintained by {@link SemanticStore.put} and friends is that
 * `fact` is always non-empty and `createdAt` is always set; all other fields
 * are optional and defaulted consistently.
 *
 * @example
 * ```ts
 * const entry: SemanticEntry = {
 *   id: 'fact-42',
 *   fact: 'the database is Postgres 16 running on the primary replica',
 *   subject: 'database',
 *   predicate: 'version',
 *   object: 'Postgres 16',
 *   tags: ['infrastructure', 'database'],
 *   source: 'onboarding docs',
 *   confidence: 0.9,
 *   createdAt: Date.now(),
 * };
 * ```
 */
export interface SemanticEntry {
  /**
   * Unique identifier of the entry. See {@link SemanticEntryId}.
   */
  readonly id: SemanticEntryId;

  /**
   * The canonical, human-readable statement of the fact.
   *
   * This is the primary text indexed by the TF-IDF layer and the text used for
   * deduplication by {@link SemanticLifecycle.dedupe}. It must be non-empty.
   */
  readonly fact: string;

  /**
   * Optional subject of the fact, when modelled as a triple.
   *
   * The subject is the entity the fact is about — e.g. `'database'` in
   * "the database is Postgres 16".
   */
  readonly subject?: string;

  /**
   * Optional predicate of the fact, when modelled as a triple.
   *
   * The predicate is the relationship asserted — e.g. `'version'` in
   * "the database is Postgres 16".
   */
  readonly predicate?: string;

  /**
   * Optional object of the fact, when modelled as a triple.
   *
   * The object is what the subject is related to — e.g. `'Postgres 16'` in
   * "the database is Postgres 16".
   */
  readonly object?: string;

  /**
   * Optional embedding vector describing the meaning of the fact.
   *
   * When provided it is preserved verbatim and used directly by retrieval;
   * when omitted the TF-IDF index derives a vector from the entry's text.
   * If supplied, all entries for a store should share the same dimensionality.
   */
  readonly embedding?: readonly number[];

  /**
   * Optional tags for cross-cutting classification.
   *
   * Tags are lower-cased and deduplicated by the store, and can be queried
   * with {@link SemanticRetriever.byTag}.
   */
  readonly tags?: readonly string[];

  /**
   * Optional attribution of where the fact came from.
   *
   * Examples: `'onboarding docs'`, `'user conversation 2026-04-01'`,
   * `'inferred from logs'`. Useful for debugging and for trust-weighted
   * retrieval.
   */
  readonly source?: string;

  /**
   * Optional confidence in `[0, 1]`. Defaults to `1` when not supplied.
   * See {@link Confidence}.
   */
  readonly confidence?: Confidence;

  /**
   * Epoch-millisecond time at which the entry was first created.
   */
  readonly createdAt: Timestamp;

  /**
   * Epoch-millisecond time at which the entry was last modified, if ever.
   * Updated by `SemanticStore.update` and by lifecycle operations.
   */
  readonly updatedAt?: Timestamp;
}

/**
 * Mutable view of a semantic entry used while building or updating one.
 *
 * The store's mutation methods accept this builder variant because they may
 * normalise (lower-case tags, default confidence, fill timestamps) before
 * persisting; the persisted form is the immutable {@link SemanticEntry}.
 */
export interface MutableSemanticEntry {
  /** Unique identifier of the entry. See {@link SemanticEntryId}. */
  id: SemanticEntryId;
  /** The fact text. Must be non-empty. */
  fact: string;
  /** Optional triple subject. */
  subject?: string;
  /** Optional triple predicate. */
  predicate?: string;
  /** Optional triple object. */
  object?: string;
  /** Optional embedding vector. */
  embedding?: readonly number[];
  /** Optional tags. */
  tags?: readonly string[];
  /** Optional source attribution. */
  source?: string;
  /** Optional confidence in `[0, 1]`. */
  confidence?: Confidence;
  /** Optional creation timestamp; defaults to the store clock. */
  createdAt?: Timestamp;
  /** Optional last-modified timestamp; defaults to the store clock. */
  updatedAt?: Timestamp;
}

/**
 * Options accepted by {@link SemanticStore.put} for a single fact.
 *
 * Every option maps to an optional field of the stored {@link SemanticEntry};
 * fields not supplied are defaulted by the store (id auto-generated,
 * confidence `1`, timestamps set to the store clock, tags normalised).
 */
export interface SemanticEntryOptions {
  /**
   * Explicit identifier for the entry. When omitted, the store auto-generates
   * one.
   */
  readonly id?: SemanticEntryId;
  /** Optional triple subject. */
  readonly subject?: string;
  /** Optional triple predicate. */
  readonly predicate?: string;
  /** Optional triple object. */
  readonly object?: string;
  /** Optional embedding vector. */
  readonly embedding?: readonly number[];
  /** Optional tags; normalised (lower-cased, deduplicated) by the store. */
  readonly tags?: readonly string[];
  /** Optional source attribution. */
  readonly source?: string;
  /** Optional confidence in `[0, 1]`. Defaults to `1`. */
  readonly confidence?: Confidence;
  /** Optional creation timestamp; defaults to the store clock. */
  readonly createdAt?: Timestamp;
  /** Optional last-modified timestamp; defaults to the store clock. */
  readonly updatedAt?: Timestamp;
}

/**
 * Patch accepted by `SemanticStore.update`.
 *
 * Only the fields present in the patch are changed; absent fields keep their
 * stored values. Applying any field bumps the entry's `updatedAt` to the store
 * clock (unless the patch itself carries an explicit `updatedAt`).
 */
export type SemanticPatch = Partial<
  Pick<
    MutableSemanticEntry,
    'fact' | 'subject' | 'predicate' | 'object' | 'embedding' | 'tags' | 'source' | 'confidence'
  >
> & { readonly updatedAt?: Timestamp };

/**
 * Configuration options shared by the semantic store, index, retriever and
 * lifecycle.
 *
 * A {@link SemanticConfig} may be supplied to {@link SemanticStore} or to the
 * {@link createSemanticAdapter} factory to tune normalisation, validation and
 * default behaviours. All fields are optional; the defaults are chosen to be
 * safe for general use.
 */
export interface SemanticConfig {
  /**
   * Upper bound on the number of entries the store may hold. `0` (the default)
   * disables the cap. Used by {@link SemanticLifecycle.prune} as the target
   * size and by `SemanticStore.put` to reject writes that would exceed it when
   * the lifecycle is not in play.
   */
  readonly maxEntries?: number;

  /**
   * Preferred dimensionality for embedding vectors. When set, callers that
   * supply their own embeddings should match it; the TF-IDF index derives its
   * own dimension from the vocabulary and does not truncate.
   */
  readonly vectorDim?: number;

  /**
   * Default minimum cosine similarity (in `[0, 1]`) that a candidate entry must
   * reach before it is returned by {@link SemanticRetriever.search}. Defaults
   * to `0.1`.
   */
  readonly similarityThreshold?: number;

  /**
   * When `true` (default), entry {@link SemanticEntry.tags} are lower-cased
   * and deduplicated before being stored and indexed. Disable only when tag
   * casing is meaningful to the caller.
   */
  readonly normalizeTags?: boolean;

  /**
   * When `true` (default `true`), a copy of each entry is taken at record time
   * so that later mutation of the caller's object cannot corrupt the store.
   * Set to `false` only when entries are treated as immutable by the caller
   * and memory overhead matters.
   */
  readonly cloneEntries?: boolean;

  /**
   * Default limit applied by retrievers when the caller omits one. Must be
   * positive when set.
   */
  readonly defaultLimit?: number;

  /**
   * Optional clock used instead of `Date.now()` for all timestamps. Injecting
   * a clock makes the layer deterministic under test.
   */
  readonly now?: () => Timestamp;
}

/**
 * Aggregate statistics describing the contents of a semantic store.
 *
 * Returned by `SemanticStore.stats`, `SemanticIndex.stats` and
 * {@link SemanticRetriever.stats}. All fields are derived on demand rather
 * than cached, guaranteeing freshness at the cost of an O(n) scan for large
 * stores.
 */
export interface SemanticStats {
  /** Total number of entries currently stored. */
  readonly entries: number;

  /** Number of entries carrying at least one tag. */
  readonly taggedEntries: number;

  /** Total number of distinct tags observed across all entries. */
  readonly distinctTags: number;

  /** Total number of distinct triple subjects observed. */
  readonly distinctSubjects: number;

  /** Total number of distinct triple predicates observed. */
  readonly distinctPredicates: number;

  /** Total number of distinct triple objects observed. */
  readonly distinctObjects: number;

  /** Number of entries carrying an explicit embedding vector. */
  readonly embedded: number;

  /** Mean confidence across all entries, or `null` when the store is empty. */
  readonly averageConfidence: number | null;

  /** Epoch-millisecond timestamp of the oldest entry, or `null` when empty. */
  readonly oldestAt: Timestamp | null;

  /** Epoch-millisecond timestamp of the newest entry, or `null` when empty. */
  readonly newestAt: Timestamp | null;
}

/**
 * An individual hit produced by a semantic retrieval query.
 *
 * Wraps the matched entry together with a `score` in `[0, 1]` describing how
 * strongly the entry matches the query. Higher scores indicate stronger
 * relevance; for TF-IDF queries the score is a cosine similarity.
 */
export interface SemanticHit {
  /** The matched semantic entry itself. */
  readonly entry: SemanticEntry;

  /** Relevance score in `[0, 1]`. `1` indicates an exact vector match. */
  readonly score: number;
}

/**
 * Result of {@link SemanticLifecycle.prune}.
 *
 * Reports which entries were removed to bring the store back under
 * {@link SemanticConfig.maxEntries}.
 */
export interface SemanticPruneResult {
  /** Identifiers of the entries removed by the prune. */
  readonly removed: readonly SemanticEntryId[];

  /** Number of entries that remain in the store after pruning. */
  readonly kept: number;
}

/**
 * Result of {@link SemanticLifecycle.dedupe}.
 *
 * Deduplication merges entries whose fact text is identical (after
 * normalisation) into a single survivor. The survivor keeps the highest
 * confidence (latest-updated wins ties), and the union of tags.
 */
export interface SemanticDedupeResult {
  /** Number of duplicate groups that were collapsed into one survivor each. */
  readonly merged: number;

  /** Identifiers of the surviving entries. */
  readonly survivors: readonly SemanticEntryId[];

  /** Identifiers of the entries that were absorbed and removed. */
  readonly removed: readonly SemanticEntryId[];
}

/**
 * Result of {@link SemanticLifecycle.decayStale}.
 *
 * Decay lowers the confidence of entries that have not been updated for a long
 * time, making them progressively less retrievable and eventually pruneable.
 */
export interface SemanticDecayResult {
  /** Number of entries whose confidence was lowered. */
  readonly decayed: number;

  /** Identifiers of the entries that were decayed. */
  readonly ids: readonly SemanticEntryId[];

  /** The multiplier that was applied to each decayed confidence. */
  readonly factor: number;

  /** The floor below which confidence was never lowered. */
  readonly floor: Confidence;
}

/**
 * Result of {@link SemanticLifecycle.normalize}.
 *
 * Normalisation recomputes the TF-IDF vectors for every entry, which is useful
 * after the vocabulary or document frequencies change.
 */
export interface SemanticNormalizeResult {
  /** Number of entry vectors recomputed. */
  readonly vectors: number;
}

/**
 * Payload emitted by the semantic lifecycle event emitter.
 *
 * Each event carries enough context for observers to react without reaching
 * back into the store: the affected entry ids, the wall-clock time, and an
 * operation-specific `detail` value.
 */
export interface SemanticLifecycleEvent {
  /**
   * Discriminator naming the lifecycle operation that fired: `'prune'`,
   * `'dedupe'`, `'decay'` or `'normalize'`.
   */
  readonly type: 'prune' | 'dedupe' | 'decay' | 'normalize';

  /** The entry ids involved in the operation. */
  readonly ids: readonly SemanticEntryId[];

  /** Epoch-millisecond time at which the event was emitted. */
  readonly timestamp: Timestamp;

  /**
   * Operation-specific payload. For `'prune'` the number of entries removed;
   * for `'dedupe'` a {@link SemanticDedupeResult}; for `'decay'` a
   * {@link SemanticDecayResult}; for `'normalize'` the vector count.
   */
  readonly detail: unknown;
}

/**
 * Canonical serialisable shape produced by `SemanticStore.toJSON`.
 *
 * Persisting the store as a single object — rather than an array of entries —
 * gives the format room to grow (versioning, index caches) without breaking
 * existing dumps.
 */
export interface SemanticSnapshot {
  /** Format version. Bumped whenever the serialised layout changes. */
  readonly version: 1;

  /** The entries held by the store, keyed by entry id. */
  readonly entries: Record<SemanticEntryId, SemanticEntry>;

  /** Wall-clock time at which the snapshot was created. */
  readonly savedAt: Timestamp;
}

/**
 * Interface implemented by {@link SemanticRuntimeAdapter} to present semantic
 * memory behind a uniform, key/value-style memory surface.
 *
 * The adapter deliberately mirrors a memory contract (set/get/delete/has/keys/
 * clear/stats) so that a semantic store, a working-memory store and an
 * episodic store can be swapped behind the same consumer. Methods are
 * asynchronous so the interface is trivially implementable by persistent
 * backends as well as the in-memory adapter.
 */
export interface RuntimeMemory {
  /**
   * Store a value under a key.
   *
   * For the semantic adapter the key is an entry id and the value is coerced
   * to a fact: a string value becomes a fact directly, an object with a `fact`
   * field is treated as a partial entry, and anything else is stringified.
   * Optional metadata may supply tags, source, confidence or an embedding.
   */
  set(key: string, value: unknown, metadata?: SemanticMetadata): Promise<void>;

  /**
   * Retrieve the value stored under a key, or `undefined` when absent.
   */
  get(key: string): Promise<unknown>;

  /**
   * Remove the value stored under a key. Returns `true` if a value existed.
   */
  delete(key: string): Promise<boolean>;

  /**
   * Whether a key currently holds a value.
   */
  has(key: string): Promise<boolean>;

  /**
   * All currently-stored keys.
   */
  keys(): Promise<string[]>;

  /**
   * Remove all values.
   */
  clear(): Promise<void>;

  /**
   * Aggregate statistics about the current contents.
   */
  stats(): Promise<SemanticStats>;
}