"""
MAM Python Package.

Provides Python bindings for MAM (Machine Agent Modules) parsing, validation,
execution, and plugin management.

Example::

    from mam import parse_mam, validate, MAMModule

    result = parse_mam(open("module.mam.md").read())
    issues = validate(result.ast)
    module = MAMModule.from_ast(result.ast)
"""

from .ast import (
    AST,
    CODE_SECTION_NAMES,
    REQUIRED_SECTIONS,
    STANDARD_SECTIONS_ORDER,
    CodeBlock,
    ContentNode,
    FrontMatter,
    ListItem,
    MAMModule,
    NodeType,
    ParseError,
    ParseResult,
    Section,
    SectionType,
    SourceLocation,
    Table,
    TableRow,
    code_block_languages,
    count_code_blocks,
    find_section,
    has_front_matter,
    is_standard_section,
    section_count,
    section_names,
)
from .cache import (
    DEFAULT_CACHE_TTL_SECONDS,
    CacheEntry,
    CacheStats,
    ResultCache,
    create_result_cache,
    format_cache_stats,
    hash_cache_key,
    is_valid_cache_key,
)
from .cli import (
    build_parser,
    exit_code_for,
    format_ast,
    format_issues_compact,
    format_module_summary,
    run,
    version_header,
)
from .cli import (
    main as cli_main,
)
from .config import (
    CONFIG_FILENAME,
    DEFAULT_SDK_CONFIG,
    SUPPORTED_TARGETS,
    SDKConfig,
    find_sdk_config,
    is_supported_target,
    list_sdk_targets,
    load_sdk_config,
    merge_sdk_configs,
    resolve_sdk_config_path,
    save_sdk_config,
    validate_sdk_config,
)
from .diagnostics import (
    DiagnosticCheck,
    DiagnosticReport,
    DiagnosticStatus,
    check_imports,
    check_language_runtimes,
    check_python_version,
    format_diagnostics,
    run_diagnostics,
)
from .format import (
    format_ast_json,
    format_built_module,
    format_code_block_list,
    format_dependency_table,
    format_execution_report,
    format_front_matter,
    format_parse_errors,
    format_section_list,
    format_toc,
    format_validation_report,
)
from .format import (
    format_module_summary as format_ast_summary,
)
from .graph import (
    DependencyGraph,
    GraphEdge,
    GraphNode,
    build_graph,
    count_edges_by_label,
    count_nodes_by_type,
    edge_labels,
    filter_nodes,
    format_graph_text,
    has_edge,
    has_node,
    leaf_nodes,
    node_names,
    node_type,
    nodes_of_type,
    predecessors,
    reachable_from,
    root_nodes,
    successors,
    summarize_graph,
    topological_sort,
)
from .parser import (
    MAMParser,
    count_headings,
    detect_runtime,
    extract_code_blocks,
    extract_front_matter,
    normalize_mam,
    parse_mam,
    parse_mam_safe,
    split_sections,
    strip_code_blocks,
)
from .plugins import (
    Plugin,
    PluginHook,
    PluginLifecycle,
    PluginManager,
    PluginMeta,
    enabled_plugin_names,
    find_plugin,
    hook_count,
    plugin_has_hook,
    plugin_meta_dicts,
    require_plugin,
    sort_plugin_meta,
)
from .runtime import (
    ExecutionConfig,
    ExecutionContext,
    ExecutionResult,
    ExecutionStatus,
    MAMRuntime,
    count_successful,
    execute,
    execution_languages,
    failed_sections,
    format_execution_output,
    is_success,
    record_execution,
    summarize_execution,
    total_duration,
)
from .template import (
    STARTER_KINDS,
    get_starter_template,
    list_starter_kinds,
    new_module_starter,
    render_starter,
    starter_variables,
    validate_starter_name,
)
from .validator import (
    MAMValidator,
    ValidationIssue,
    ValidationRule,
    ValidationSeverity,
    count_issues_by_severity,
    filter_by_severity,
    has_errors,
    has_warnings,
    is_valid,
    issue_messages,
    summarize_issues,
    validate,
)

__all__ = [
    # AST types
    "AST",
    "CodeBlock",
    "ContentNode",
    "FrontMatter",
    "ListItem",
    "MAMModule",
    "NodeType",
    "ParseError",
    "ParseResult",
    "Section",
    "SectionType",
    "SourceLocation",
    "Table",
    "TableRow",
    "STANDARD_SECTIONS_ORDER",
    "REQUIRED_SECTIONS",
    "CODE_SECTION_NAMES",
    # Parser
    "parse_mam",
    "MAMParser",
    # Validator
    "validate",
    "MAMValidator",
    "ValidationIssue",
    "ValidationRule",
    "ValidationSeverity",
    # Runtime
    "execute",
    "MAMRuntime",
    "ExecutionResult",
    "ExecutionConfig",
    "ExecutionContext",
    "ExecutionStatus",
    # Plugins
    "Plugin",
    "PluginManager",
    "PluginHook",
    "PluginLifecycle",
    "PluginMeta",
    # CLI
    "cli_main",
    "build_parser",
    "run",
    "exit_code_for",
    "version_header",
    "format_ast",
    "format_issues_compact",
    "format_module_summary",
    # AST query helpers
    "has_front_matter",
    "section_count",
    "count_code_blocks",
    "code_block_languages",
    "section_names",
    "find_section",
    "is_standard_section",
    # Parser helpers
    "parse_mam_safe",
    "extract_front_matter",
    "split_sections",
    "strip_code_blocks",
    "count_headings",
    "extract_code_blocks",
    "normalize_mam",
    "detect_runtime",
    # Validator helpers
    "count_issues_by_severity",
    "has_errors",
    "has_warnings",
    "filter_by_severity",
    "issue_messages",
    "is_valid",
    "summarize_issues",
    # Runtime helpers
    "is_success",
    "count_successful",
    "failed_sections",
    "execution_languages",
    "total_duration",
    "summarize_execution",
    "record_execution",
    "format_execution_output",
    # Plugin helpers
    "enabled_plugin_names",
    "plugin_has_hook",
    "hook_count",
    "plugin_meta_dicts",
    "sort_plugin_meta",
    "find_plugin",
    "require_plugin",
    # Config
    "SDKConfig",
    "DEFAULT_SDK_CONFIG",
    "CONFIG_FILENAME",
    "SUPPORTED_TARGETS",
    "load_sdk_config",
    "save_sdk_config",
    "validate_sdk_config",
    "merge_sdk_configs",
    "resolve_sdk_config_path",
    "is_supported_target",
    "list_sdk_targets",
    "find_sdk_config",
    # Cache
    "ResultCache",
    "CacheEntry",
    "CacheStats",
    "DEFAULT_CACHE_TTL_SECONDS",
    "create_result_cache",
    "hash_cache_key",
    "format_cache_stats",
    "is_valid_cache_key",
    # Format
    "format_ast_json",
    "format_section_list",
    "format_validation_report",
    "format_execution_report",
    "format_code_block_list",
    "format_front_matter",
    "format_dependency_table",
    "format_toc",
    "format_built_module",
    "format_parse_errors",
    "format_ast_summary",
    # Graph
    "GraphNode",
    "GraphEdge",
    "DependencyGraph",
    "build_graph",
    "topological_sort",
    "node_names",
    "summarize_graph",
    "successors",
    "predecessors",
    "has_edge",
    "edge_labels",
    "leaf_nodes",
    "root_nodes",
    "nodes_of_type",
    "count_edges_by_label",
    "count_nodes_by_type",
    "has_node",
    "node_type",
    "reachable_from",
    "filter_nodes",
    "format_graph_text",
    # Template
    "STARTER_KINDS",
    "list_starter_kinds",
    "get_starter_template",
    "render_starter",
    "starter_variables",
    "new_module_starter",
    "validate_starter_name",
    # Diagnostics
    "DiagnosticStatus",
    "DiagnosticCheck",
    "DiagnosticReport",
    "check_python_version",
    "check_imports",
    "check_language_runtimes",
    "run_diagnostics",
    "format_diagnostics",
]
