/**
 * Episodic memory domain types for the MAM Memory Engine.
 *
 * Episodic memory stores discrete **experiences** — self-contained units of
 * lived time in which one or more actors perform actions, observe outcomes,
 * and leave behind an audit trail of events. Unlike semantic memory (which
 * stores timeless facts) or procedural memory (which stores how-to knowledge),
 * episodic memory is inherently *situated*: every episode is anchored to a
 * window of time, a set of participants, and a sequence of causally ordered
 * events.
 *
 * The types in this module form the public contract shared by every other
 * layer of the episodic subsystem:
 *
 * - {@link Episode} — a complete recorded experience with a start time, an
 *   ordered list of {@link EpisodeEvent}s, optional outcome and tags.
 * - {@link EpisodeEvent} — a single atomic step inside an episode.
 * - {@link EpisodeConfig} — construction/behaviour options for stores.
 * - {@link EpisodeStats} — aggregate counters describing a store or index.
 * - {@link EpisodeOptions} — query/retrieval options for finding episodes.
 *
 * The types are deliberately framework-agnostic and serialisable: every type
 * here can be round-tripped through {@link JSON} without loss, which means an
 * {@link Episode} captured in one process can be persisted to disk and
 * restored by another process or thread without any schema migration.
 *
 * @packageDocumentation
 * @module episodic/types
 */

/**
 * Unique identifier for an episode.
 *
 * Identifiers should be stable within a single store and are generally
 * generated by the caller (e.g. an `id()` utility, a UUID, or a counter
 * derived from wall-clock time). The episodic layer treats them as opaque
 * strings and never inspects their internal structure, so any scheme is
 * acceptable as long as it is collision-free within the scope of one
 * {@link EpisodicStore}.
 */
export type EpisodeId = string;

/**
 * Unique identifier for a single event inside an episode.
 *
 * Like {@link EpisodeId}, event identifiers are opaque to the episodic layer.
 * They are expected to be unique within the owning episode so that events can
 * be addressed individually (e.g. by {@link EpisodicLifecycle.trim} or by a
 * retrieval query that must pinpoint one step in a timeline).
 */
export type EventId = string;

/**
 * Milliseconds-since-epoch timestamp.
 *
 * All wall-clock values in the episodic layer use epoch milliseconds so that
 * they interoperate cleanly with both {@link Date} and `performance.now()`
 * derived clocks and so that date-range arithmetic (see
 * {@link EpisodicIndex.findByDateRange}) does not need to deal with calendar
 * complexities.
 */
export type Timestamp = number;

/**
 * Outcome classification for an episode.
 *
 * Episodes may end successfully, unsuccessfully, or ambiguously. The outcome
 * is distinct from the {@link EpisodeEvent.outcome} of any single event: the
 * episode outcome is the aggregate assessment of the whole experience, while
 * an event outcome describes the immediate consequence of that one action.
 *
 * Consumers such as {@link EpisodicRetriever.byOutcome} and the pattern
 * matcher in {@link EpisodicRetriever.pattern} use these canonical strings, so
 * custom outcomes should be carried in {@link Episode.metadata} rather than
 * added to this union.
 */
export type EpisodeOutcome =
  | 'success'
  | 'failure'
  | 'partial'
  | 'aborted'
  | 'unknown';

/**
 * Lightweight, unstructured metadata attached to an episode or event.
 *
 * Metadata is intentionally untyped beyond `Record<string, unknown>`: it is
 * meant to carry domain-specific payloads (request headers, model names,
 * environment identifiers, error stacks, user assertions) that the episodic
 * layer does not need to interpret but must preserve verbatim through
 * serialisation. Values should be JSON-serialisable to guarantee
 * {@link EpisodicStore.toJSON}/{@link EpisodicStore.fromJSON} round-trips.
 */
export type EpisodeMetadata = Record<string, unknown>;

/**
 * A single atomic step within an episode timeline.
 *
 * Each event records one thing that happened at one point in time: an actor
 * performed an {@link action} (optionally with a structured {@link payload})
 * and observed an {@link outcome}. Events are stored in insertion order by the
 * store and are treated as the authoritative chronological sequence of the
 * episode; timestamps are advisory and may be equal for events that happened
 * in rapid succession.
 *
 * @example
 * ```ts
 * const event: EpisodeEvent = {
 *   id: 'evt-1',
 *   actor: 'user',
 *   action: 'submit_form',
 *   payload: { form: 'checkout', values: { coupon: 'SAVE10' } },
 *   timestamp: Date.now(),
 *   outcome: { status: 'accepted', detail: '200 OK' },
 * };
 * ```
 */
export interface EpisodeEvent {
  /**
   * Globally or episode-locally unique identifier for this event.
   *
   * The episodic layer never auto-generates event ids; callers that build
   * events through the fluent {@link EpisodeRecorder} (in `integration.ts`)
   * supply their own ids, and the recorder surfaces events with a stable
   * identity that can be referenced during consolidation and trimming.
   */
  readonly id: EventId;

  /**
   * Identifier of the actor that performed the action, when known.
   *
   * Actors may be people (`'alice'`), system components (`'orchestrator'`),
   * tools (`'search-tool'`), agents (`'planner-agent'`), or anything else the
   * caller wishes to attribute. When `undefined`, the event is considered to
   * be unowned — e.g. a spontaneous environmental occurrence.
   */
  readonly actor?: string;

  /**
   * Canonical, low-cardinality name of the action performed.
   *
   * Action names are indexed by {@link EpisodicIndex} and used by the pattern
   * matcher in {@link EpisodicRetriever.pattern}, so they should be drawn from
   * a small controlled vocabulary (`'search'`, `'retry'`, `'confirm'`,
   * `'cancel'`) rather than being free-form sentences. Free-form notes belong
   * in {@link payload}.
   */
  readonly action: string;

  /**
   * Arbitrary structured data describing the action's inputs or context.
   *
   * Payloads are preserved verbatim and never parsed by the episodic layer.
   * They may be indexed by a downstream semantic layer, but the core index in
   * `index.ts` only indexes {@link action}, {@link actor}, {@link outcome}
   * and the owning episode's tags.
   */
  readonly payload?: EpisodeMetadata;

  /**
   * Epoch-millisecond time at which the event occurred.
   *
   * Defaults to the time the event was appended when not supplied by the
   * caller (see {@link EpisodicStore.appendEvent}).
   */
  readonly timestamp: Timestamp;

  /**
   * Immediate outcome observed as a result of the action, if any.
   *
   * A string outcome such as `'success'`, `'error'`, `'timeout'` or a richer
   * object with `status` and `detail` may be supplied. Event-level outcomes
   * are indexed by {@link EpisodicIndex} and can be queried with
   * {@link EpisodicRetriever.byOutcome}.
   */
  readonly outcome?: string | { status: string; detail?: string };
}

/**
 * A complete recorded experience: a temporally bounded sequence of events.
 *
 * An episode is the unit of *experience*. It bundles together:
 *
 * - a **name** for human-readable identification (optional, convenience only),
 * - the **window** of time it occupied (`startedAt` and optional `endedAt`),
 * - the ordered **events** that constitute its timeline,
 * - an optional aggregate **outcome**,
 * - **tags** for cross-cutting, non-hierarchical classification, and
 * - arbitrary **metadata** for caller-owned context.
 *
 * The invariant maintained by {@link EpisodicStore.recordEpisode} and friends
 * is that `events` are always stored in the order they were appended and that
 * `startedAt` is the minimum event timestamp seen at record time.
 *
 * @example
 * ```ts
 * const episode: Episode = {
 *   id: 'ep-42',
 *   name: 'Checkout flow attempt',
 *   startedAt: Date.now() - 60_000,
 *   events: [ /* ... *\/ ],
 *   tags: ['checkout', 'ecommerce'],
 *   outcome: 'failure',
 *   metadata: { traceId: 'abc-123', env: 'staging' },
 * };
 * ```
 */
export interface Episode {
  /**
   * Unique identifier of the episode. See {@link EpisodeId}.
   */
  readonly id: EpisodeId;

  /**
   * Human-readable label for the episode. Optional and purely descriptive;
   * retrieval never depends on it, so it may be duplicated across episodes.
   */
  readonly name?: string;

  /**
   * Epoch-millisecond time at which the episode began. May be earlier than
   * the first event's timestamp when events were appended retroactively.
   */
  readonly startedAt: Timestamp;

  /**
   * Epoch-millisecond time at which the episode ended, once known.
   *
   * A `null` value indicates the episode is still *in progress* and can be
   * appended to. {@link EpisodicStore.setOutcome} and
   * {@link EpisodicStore.updateEpisode} may be used to finalise the end time.
   */
  readonly endedAt?: Timestamp | null;

  /**
   * Chronological sequence of {@link EpisodeEvent}s. Stored in insertion
   * order; callers must append through {@link EpisodicStore.appendEvent} (or
   * the fluent recorder) to preserve ordering guarantees.
   */
  readonly events: readonly EpisodeEvent[];

  /**
   * Optional aggregate outcome of the whole episode. See
   * {@link EpisodeOutcome}.
   */
  readonly outcome?: EpisodeOutcome;

  /**
   * Optional set of tags for cross-cutting classification. Tags are
   * lower-cased and deduplicated by the store and index.
   */
  readonly tags?: readonly string[];

  /**
   * Caller-owned structured context. Preserved verbatim. See
   * {@link EpisodeMetadata}.
   */
  readonly metadata?: EpisodeMetadata;
}

/**
 * Mutable view of an episode used while building or updating one.
 *
 * The store's mutation methods accept a builder variant because they may
 * normalise (lower-case tags, fill defaults) before persisting; the persisted
 * form is the immutable {@link Episode}.
 */
export interface MutableEpisode {
  id: EpisodeId;
  name?: string;
  startedAt: Timestamp;
  endedAt?: Timestamp | null;
  events?: EpisodeEvent[];
  outcome?: EpisodeOutcome;
  tags?: string[];
  metadata?: EpisodeMetadata;
}

/**
 * Aggregate statistics describing the contents of an episodic store or index.
 *
 * Returned by {@link EpisodicStore.stats}, {@link EpisodicIndex.stats} and
 * {@link EpisodicRetriever.stats}. All fields are derived on demand rather
 * than cached, guaranteeing freshness at the cost of an O(n) scan for large
 * stores.
 */
export interface EpisodeStats {
  /**
   * Total number of episodes currently stored.
   */
  readonly episodes: number;

  /**
   * Total number of events across all stored episodes.
   */
  readonly events: number;

  /**
   * Number of episodes carrying at least one tag.
   */
  readonly taggedEpisodes: number;

  /**
   * Total number of distinct tags observed across all episodes.
   */
  readonly distinctTags: number;

  /**
   * Total number of distinct actors referenced by any stored event.
   */
  readonly distinctActors: number;

  /**
   * Total number of distinct action names referenced by any stored event.
   */
  readonly distinctActions: number;

  /**
   * Outcome histogram. Keys are {@link EpisodeOutcome} values; only outcomes
   * that appear at least once are present.
   */
  readonly outcomes: Readonly<Record<EpisodeOutcome, number>>;

  /**
   * Epoch-millisecond timestamp of the oldest episode's `startedAt`, or
   * `null` when the store is empty.
   */
  readonly oldestAt: Timestamp | null;

  /**
   * Epoch-millisecond timestamp of the newest episode's `startedAt`, or
   * `null` when the store is empty.
   */
  readonly newestAt: Timestamp | null;
}

/**
 * Configuration options shared by the episodic store, index and retriever.
 *
 * An {@link EpisodeConfig} may be supplied to {@link EpisodicStore} or
 * {@link createEpisodicAdapter} to tune normalisation, validation and default
 * behaviours. All fields are optional; the defaults are chosen to be safe for
 * general use.
 */
export interface EpisodeConfig {
  /**
   * When `true` (default), {@link Episode.tags} are lower-cased and
   * deduplicated before being stored and indexed. Disable only when
   * tag casing is meaningful to the caller.
   */
  readonly normalizeTags?: boolean;

  /**
   * When `true` (default `false`), episodes without at least one event are
   * rejected at record time. This prevents the accumulation of empty shells
   * but prevents recording experiences whose events arrive later.
   */
  readonly requireEvents?: boolean;

  /**
   * When `true` (default `true`), a copy of each episode is taken at record
   * time so that later mutation of the caller's object cannot corrupt the
   * store. Set to `false` only when episodes are treated as immutable by the
   * caller and memory overhead matters.
   */
  readonly cloneEpisodes?: boolean;

  /**
   * Upper bound on the number of events an episode may accumulate via
   * {@link EpisodicStore.appendEvent}. Events beyond this bound are rejected.
   * `0` (default) disables the limit.
   */
  readonly maxEventsPerEpisode?: number;

  /**
   * Default limit applied by retrievers when the caller omits one. Must be
   * positive when set.
   */
  readonly defaultLimit?: number;

  /**
   * When `true` (default `false`), {@link EpisodicIndex} eagerly rebuilds
   * itself after every mutation. When `false`, the index is rebuilt lazily on
   * the next query, which is cheaper for write-heavy workloads.
   */
  readonly eagerIndex?: boolean;

  /**
   * Optional clock used instead of `Date.now()` for all timestamps. Injecting
   * a clock makes the layer deterministic under test.
   */
  readonly now?: () => Timestamp;
}

/**
 * Options accepted by retrieval and search entry points.
 *
 * {@link EpisodicRetriever.pattern} and {@link EpisodicRetriever.recall}
 * accept rich option objects; the simpler entry points accept a bare
 * {@link limit} number, which is shorthand for
 * `{ limit }`. A `limit` of `0` means "no limit".
 */
export interface EpisodeOptions {
  /**
   * Maximum number of results to return. `0` means unbounded. Defaults to
   * {@link EpisodeConfig.defaultLimit} (or 20).
   */
  readonly limit?: number;

  /**
   * When `true`, results are returned with the most recent first. Defaults to
   * `true` for `recent()`-style queries and `false` for timeline queries.
   */
  readonly newestFirst?: boolean;

  /**
   * Optional filter that narrows results to episodes carrying at least one of
   * the given tags.
   */
  readonly tags?: readonly string[];

  /**
   * Optional filter restricting results to episodes whose `startedAt` falls
   * on or after this epoch-millisecond bound.
   */
  readonly from?: Timestamp;

  /**
   * Optional filter restricting results to episodes whose `startedAt` falls
   * on or before this epoch-millisecond bound.
   */
  readonly to?: Timestamp;

  /**
   * For {@link EpisodicRetriever.recall}: number of most recent context
   * episodes considered when scoring, even when they would not otherwise be
   * returned. Defaults to the same value as `limit`.
   */
  readonly lookback?: number;

  /**
   * When `true`, an episode whose {@link name} or any event {@link payload}
   * contains the query text (case-insensitive substring match) is boosted in
   * recall scoring. Defaults to `false`.
   */
  readonly fullText?: boolean;
}

/**
 * An individual hit produced by {@link EpisodicRetriever.recall}.
 *
 * Wraps the matched episode together with a `score` in `[0, 1]` describing
 * how strongly the episode matches the recalled context. Higher scores
 * indicate stronger relevance.
 */
export interface EpisodeHit {
  /**
   * The recalled episode itself.
   */
  readonly episode: Episode;

  /**
   * Relevance score in `[0, 1]`. `1` indicates an exact signal match; `0`
   * indicates the episode was returned only as lookback filler.
   */
  readonly score: number;

  /**
   * Human-readable description of *why* the episode matched, useful for
   * debugging and for explaining retrieval decisions to users.
   */
  readonly reason: string;
}

/**
 * Result of a {@link EpisodicLifecycle.consolidate} operation.
 *
 * Consolidation merges several episodes into one and reports which ids were
 * absorbed and what became of them.
 */
export interface ConsolidationResult {
  /**
   * Identifier of the surviving, merged episode.
   */
  readonly targetId: EpisodeId;

  /**
   * Identifiers of the episodes that were absorbed into `targetId` and
   * subsequently removed from the store.
   */
  readonly mergedIds: readonly EpisodeId[];

  /**
   * Total number of events in the merged episode.
   */
  readonly events: number;

  /**
   * The merged episode itself, as persisted to the store.
   */
  readonly episode: Episode;
}

/**
 * Payload emitted by the episodic lifecycle event emitter.
 *
 * Each event carries enough context for observers to react without reaching
 * back into the store: the affected episode id (or ids), and the primary
 * value produced (episode, summary text, or consolidation result).
 */
export interface EpisodeLifecycleEvent {
  /**
   * Discriminator naming the lifecycle operation that fired: `'prune'`,
   * `'consolidate'`, `'summarize'`, or `'trim'`.
   */
  readonly type: 'prune' | 'consolidate' | 'summarize' | 'trim';

  /**
   * The episode id (or ids, for consolidate) involved in the operation.
   */
  readonly ids: readonly EpisodeId[];

  /**
   * Epoch-millisecond time at which the event was emitted.
   */
  readonly timestamp: Timestamp;

  /**
   * Operation-specific payload. For `'prune'` this is the number of episodes
   * removed; for `'consolidate'`, the {@link ConsolidationResult}; for
   * `'summarize'`, the summary string; for `'trim'`, the number of events
   * removed.
   */
  readonly detail: unknown;

  /**
   * The affected episode when available (not available for `'prune'`).
   */
  readonly episode?: Episode;
}

/**
 * Interface implemented by {@link EpisodicRuntimeAdapter} to present episodic
 * memory behind a uniform, semantic-memory-style surface.
 *
 * The adapter deliberately mirrors a key/value memory contract (set/get/
 * delete/has/keys/clear/stats) so that a semantic store, a working-memory
 * store and an episodic store can be swapped behind the same consumer.
 */
export interface RuntimeMemory {
  /**
   * Store a value under a key. Keys are episode ids when the value is an
   * {@link Episode} (via {@link EpisodicRuntimeAdapter.set}).
   */
  set(key: string, value: unknown, metadata?: EpisodeMetadata): Promise<void>;

  /**
   * Retrieve the value stored under a key, or `undefined` when absent.
   */
  get(key: string): Promise<unknown>;

  /**
   * Remove the value stored under a key. Returns `true` if a value existed.
   */
  delete(key: string): Promise<boolean>;

  /**
   * Whether a key currently holds a value.
   */
  has(key: string): Promise<boolean>;

  /**
   * All currently-stored keys.
   */
  keys(): Promise<string[]>;

  /**
   * Remove all values.
   */
  clear(): Promise<void>;

  /**
   * Aggregate statistics about the current contents.
   */
  stats(): Promise<EpisodeStats>;
}