/**
 * Microsoft AutoGen Target
 *
 * Compiles MAM AST to runnable Python using the classic `autogen` package
 * (pyautogen). Each MAM agent becomes a `ConversableAgent` with the module
 * context as its `system_message`; systems/teams/workflows become a
 * `GroupChat` driven by a `GroupChatManager`, and a `main()` that calls
 * `initiate_chat` is emitted under `if __name__ == "__main__"`.
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2WorkflowNode, V2TeamNode, V2SystemNode, V2MemoryNode, V2PolicyNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig, TargetHandlerOutput } from '../compiler.js';
import { generateModuleContext } from '../context.js';
import { optimizePrompt } from './optimize.js';

function pyStr(value: unknown): string {
  const s = String(value ?? '');
  return `'${s
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')}'`;
}

function ident(name: string): string {
  let s = name.toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/^_+|_+$/g, '');
  if (!s) s = 'module';
  if (/^[0-9]/.test(s)) s = '_' + s;
  return s;
}

function makeFn(name: string): string {
  return 'make_' + ident(name);
}

function chatFn(name: string): string {
  return makeFn(name) + '_chat';
}

export class AutoGenTarget implements CompileTargetHandler {
  name = 'autogen';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string | TargetHandlerOutput {
    if (config.optimizeTokens) {
      return this.compileOptimized(modules, config);
    }
    return this.compileDefault(modules, config);
  }

  private compileDefault(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];
    const indent = config.indent || 4;
    const pad = ' '.repeat(indent);

    lines.push('"""');
    lines.push('Generated by MAM Compiler');
    lines.push('Target: Microsoft AutoGen (pyautogen)');
    lines.push('"""');
    lines.push('');
    lines.push('import json');
    lines.push('import os');
    lines.push('');
    lines.push('from autogen import ConversableAgent, GroupChat, GroupChatManager');
    lines.push('');
    lines.push('MODEL = "gpt-4o"');
    lines.push('');
    lines.push('def _llm_config() -> dict:');
    lines.push(`${pad}"""Build an AutoGen LLM config from the environment."""`);
    lines.push(`${pad}return {`);
    lines.push(`${pad}${pad}"config_list": [`);
    lines.push(`${pad}${pad}${pad}{`);
    lines.push(`${pad}${pad}${pad}${pad}"model": MODEL,`);
    lines.push(`${pad}${pad}${pad}${pad}"api_key": os.environ.get("OPENAI_API_KEY"),`);
    lines.push(`${pad}${pad}${pad}},`);
    lines.push(`${pad}${pad}],`);
    lines.push(`${pad}}`);
    lines.push('');
    lines.push('def _make_agent(name: str, system_message: str) -> ConversableAgent:');
    lines.push(`${pad}"""Create a ConversableAgent with the given system message."""`);
    lines.push(`${pad}return ConversableAgent(`);
    lines.push(`${pad}${pad}name=name,`);
    lines.push(`${pad}${pad}system_message=system_message,`);
    lines.push(`${pad}${pad}llm_config=_llm_config(),`);
    lines.push(`${pad}${pad}human_input_mode="NEVER",`);
    lines.push(`${pad})`);
    lines.push('');
    lines.push('def _groupchat(agents: list[ConversableAgent]) -> GroupChatManager:');
    lines.push(`${pad}"""Build a GroupChatManager over the given agents."""`);
    lines.push(`${pad}groupchat = GroupChat(agents=agents, messages=[], max_round=12)`);
    lines.push(`${pad}return GroupChatManager(groupchat=groupchat, llm_config=_llm_config())`);
    lines.push('');

    let primary: string | null = null;
    for (const mod of modules) {
      lines.push(generateModuleContext(mod, 'autogen'));
      lines.push('');
      lines.push(...this.compileModule(mod, indent, config));
      lines.push('');
      if (
        primary === null &&
        (mod.moduleType === 'system' || mod.moduleType === 'workflow' || mod.moduleType === 'team' || mod.moduleType === 'agent')
      ) {
        primary = chatFn(mod.name);
      }
    }

    lines.push('def main() -> int:');
    if (primary) {
      lines.push(`${pad}api_key = os.environ.get("OPENAI_API_KEY")`);
      lines.push(`${pad}if not api_key:`);
      lines.push(`${pad}${pad}print("OPENAI_API_KEY is not set; skipping the live AutoGen chat.")`);
      lines.push(`${pad}${pad}return 1`);
      lines.push(`${pad}manager = ${primary}()`);
      lines.push(`${pad}result = manager.initiate_chat(`);
      lines.push(`${pad}${pad}manager,`);
      lines.push(`${pad}${pad}message="Execute the system and return the final result.",`);
      lines.push(`${pad}${pad}summary_method="last_msg",`);
      lines.push(`${pad})`);
      lines.push(`${pad}print(result.summary)`);
      lines.push(`${pad}return 0`);
    } else {
      lines.push(`${pad}print("No runnable module (system, workflow, team or agent) found in this MAM document.")`);
      lines.push(`${pad}return 0`);
    }
    lines.push('');
    lines.push('if __name__ == "__main__":');
    lines.push(`${pad}raise SystemExit(main())`);
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Emits the same program shape as the default path but with the prompt
   * content run through the token optimizer. The optimized text becomes a
   * module-level `SYSTEM_MESSAGE` used by every runnable module.
   */
  private compileOptimized(modules: V2ModuleNode[], config: CompilerConfig): TargetHandlerOutput {
    const { optimizedText, tokenOptimization } = optimizePrompt(modules, 'autogen');
    const lines: string[] = [];
    const indent = config.indent || 4;
    const pad = ' '.repeat(indent);

    lines.push('"""');
    lines.push('Generated by MAM Compiler');
    lines.push('Target: Microsoft AutoGen (pyautogen) [token-optimized]');
    lines.push('"""');
    lines.push('');
    lines.push('import json');
    lines.push('import os');
    lines.push('');
    lines.push('from autogen import ConversableAgent, GroupChat, GroupChatManager');
    lines.push('');
    lines.push('MODEL = "gpt-4o"');
    lines.push('');
    lines.push('def _llm_config() -> dict:');
    lines.push(`${pad}"""Build an AutoGen LLM config from the environment."""`);
    lines.push(`${pad}return {`);
    lines.push(`${pad}${pad}"config_list": [`);
    lines.push(`${pad}${pad}${pad}{`);
    lines.push(`${pad}${pad}${pad}${pad}"model": MODEL,`);
    lines.push(`${pad}${pad}${pad}${pad}"api_key": os.environ.get("OPENAI_API_KEY"),`);
    lines.push(`${pad}${pad}${pad}},`);
    lines.push(`${pad}${pad}],`);
    lines.push(`${pad}}`);
    lines.push('');
    lines.push('def _make_agent(name: str, system_message: str) -> ConversableAgent:');
    lines.push(`${pad}"""Create a ConversableAgent with the given system message."""`);
    lines.push(`${pad}return ConversableAgent(`);
    lines.push(`${pad}${pad}name=name,`);
    lines.push(`${pad}${pad}system_message=system_message,`);
    lines.push(`${pad}${pad}llm_config=_llm_config(),`);
    lines.push(`${pad}${pad}human_input_mode="NEVER",`);
    lines.push(`${pad})`);
    lines.push('');
    lines.push('def _groupchat(agents: list[ConversableAgent]) -> GroupChatManager:');
    lines.push(`${pad}"""Build a GroupChatManager over the given agents."""`);
    lines.push(`${pad}groupchat = GroupChat(agents=agents, messages=[], max_round=12)`);
    lines.push(`${pad}return GroupChatManager(groupchat=groupchat, llm_config=_llm_config())`);
    lines.push('');
    lines.push(`SYSTEM_MESSAGE = ${pyStr(optimizedText)}`);
    lines.push('');

    let primary: string | null = null;
    for (const mod of modules) {
      if (
        primary === null &&
        (mod.moduleType === 'system' || mod.moduleType === 'workflow' || mod.moduleType === 'team' || mod.moduleType === 'agent')
      ) {
        primary = chatFn(mod.name);
      }
      lines.push(...this.compileOptimizedModule(mod, indent, config));
      lines.push('');
    }

    lines.push('def main() -> int:');
    if (primary) {
      lines.push(`${pad}api_key = os.environ.get("OPENAI_API_KEY")`);
      lines.push(`${pad}if not api_key:`);
      lines.push(`${pad}${pad}print("OPENAI_API_KEY is not set; skipping the live AutoGen chat.")`);
      lines.push(`${pad}${pad}return 1`);
      lines.push(`${pad}manager = ${primary}()`);
      lines.push(`${pad}result = manager.initiate_chat(`);
      lines.push(`${pad}${pad}manager,`);
      lines.push(`${pad}${pad}message="Execute the system and return the final result.",`);
      lines.push(`${pad}${pad}summary_method="last_msg",`);
      lines.push(`${pad})`);
      lines.push(`${pad}print(result.summary)`);
      lines.push(`${pad}return 0`);
    } else {
      lines.push(`${pad}print("No runnable module (system, workflow, team or agent) found in this MAM document.")`);
      lines.push(`${pad}return 0`);
    }
    lines.push('');
    lines.push('if __name__ == "__main__":');
    lines.push(`${pad}raise SystemExit(main())`);
    lines.push('');

    return { output: lines.join('\n'), tokenOptimization };
  }

  private compileOptimizedModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    switch (mod.moduleType) {
      case 'tool':
        return this.compileTool(mod as unknown as V2ToolNode, indent, config);
      case 'memory':
        return this.compileMemory(mod as unknown as V2MemoryNode, indent, config);
      case 'policy':
        return this.compilePolicy(mod as unknown as V2PolicyNode, indent, config);
      default:
        return this.compileOptimizedRunnable(mod, indent);
    }
  }

  private compileOptimizedRunnable(mod: V2ModuleNode, indent: number): string[] {
    const pad = ' '.repeat(indent);
    const agentName = ident(mod.name);

    return [
      `def ${makeFn(mod.name)}() -> ConversableAgent:`,
      `${pad}"""Create the ${mod.name} ConversableAgent (token-optimized)."""`,
      `${pad}return _make_agent(${pyStr(agentName)}, SYSTEM_MESSAGE)`,
      '',
      `def ${chatFn(mod.name)}() -> GroupChatManager:`,
      `${pad}"""GroupChat with the ${mod.name} agent."""`,
      `${pad}return _groupchat([${makeFn(mod.name)}()])`,
      '',
    ];
  }

  private compileModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];
    const pad = ' '.repeat(indent);

    if (config.includeComments) {
      lines.push(`# Module: ${mod.name}`);
      lines.push(`# Type: ${mod.moduleType}`);
      if (mod.description) lines.push(`# ${mod.description}`);
      lines.push('');
    }

    switch (mod.moduleType) {
      case 'agent':
        lines.push(...this.compileAgent(mod as unknown as V2AgentNode, indent, config));
        break;
      case 'tool':
        lines.push(...this.compileTool(mod as unknown as V2ToolNode, indent, config));
        break;
      case 'workflow':
        lines.push(...this.compileWorkflow(mod as unknown as V2WorkflowNode, indent, config));
        break;
      case 'team':
        lines.push(...this.compileTeam(mod as unknown as V2TeamNode, indent, config));
        break;
      case 'system':
        lines.push(...this.compileSystem(mod as unknown as V2SystemNode, indent, config));
        break;
      case 'memory':
        lines.push(...this.compileMemory(mod as unknown as V2MemoryNode, indent, config));
        break;
      case 'policy':
        lines.push(...this.compilePolicy(mod as unknown as V2PolicyNode, indent, config));
        break;
      default:
        lines.push(...this.compileGeneric(mod, indent, config));
    }

    return lines;
  }

  private compileAgent(mod: V2AgentNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = makeFn(mod.name);
    const agentName = ident(mod.name);
    const lines: string[] = [];

    const parts: string[] = [`${mod.name} agent`];
    if (mod.role) parts.push(`Role: ${mod.role}`);
    if (mod.goal) parts.push(`Goal: ${mod.goal}`);

    lines.push(`def ${fn}() -> ConversableAgent:`);
    lines.push(`${pad}"""Create the ${mod.name} ConversableAgent."""`);
    lines.push(`${pad}parts = [${parts.map(pyStr).join(', ')}]`);
    if (mod.rules && mod.rules.length > 0) {
      lines.push(`${pad}rules = [${mod.rules.map(pyStr).join(', ')}]`);
      lines.push(`${pad}if rules:`);
      lines.push(`${pad}${pad}parts.append("Rules:\\n" + "\\n".join("- " + r for r in rules))`);
    }
    lines.push(`${pad}system_message = "\\n".join(p for p in parts if p)`);
    lines.push(`${pad}return _make_agent(${pyStr(agentName)}, system_message)`);
    lines.push('');
    lines.push(`def ${chatFn(mod.name)}() -> GroupChatManager:`);
    lines.push(`${pad}"""GroupChat with the ${mod.name} agent."""`);
    lines.push(`${pad}return _groupchat([${fn}()])`);
    lines.push('');

    return lines;
  }

  private compileTool(mod: V2ToolNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = ident(mod.name);
    const provider = mod.provider || 'unknown';

    return [
      `def ${fn}(**kwargs: object) -> str:`,
      `${pad}"""${mod.name} tool (provider: ${provider})."""`,
      `${pad}return json.dumps({"tool": ${pyStr(mod.name)}, "action": kwargs}, sort_keys=True)`,
      '',
    ];
  }

  private compileWorkflow(mod: V2WorkflowNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = chatFn(mod.name);
    const steps = (mod.steps || []).map(s => ident(s.name)).filter(Boolean);
    const lines: string[] = [];

    if (steps.length === 0) {
      return [
        `def ${fn}() -> GroupChatManager:`,
        `${pad}"""${mod.name} workflow has no parseable steps."""`,
        `${pad}raise ValueError("No steps declared for workflow ${pyStr(mod.name)}")`,
        '',
      ];
    }

    lines.push(`def ${fn}() -> GroupChatManager:`);
    lines.push(`${pad}"""GroupChat that runs the ${mod.name} workflow steps."""`);
    lines.push(`${pad}agents: list[ConversableAgent] = []`);
    for (const step of steps) {
      lines.push(`${pad}agents.append(_make_agent(${pyStr(step)}, ${pyStr(`Workflow step: ${step}`)}))`);
    }
    lines.push(`${pad}return _groupchat(agents)`);
    lines.push('');

    return lines;
  }

  private compileTeam(mod: V2TeamNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = chatFn(mod.name);
    const members = (mod.members || []).map(String);
    const lines: string[] = [];

    if (members.length === 0) {
      return [
        `def ${fn}() -> GroupChatManager:`,
        `${pad}"""${mod.name} team has no parseable members."""`,
        `${pad}raise ValueError("No members declared for team ${pyStr(mod.name)}")`,
        '',
      ];
    }

    lines.push(`def ${fn}() -> GroupChatManager:`);
    lines.push(`${pad}"""GroupChat that coordinates the ${mod.name} team."""`);
    lines.push(`${pad}agents: list[ConversableAgent] = []`);
    for (const member of members) {
      const agentName = ident(member) || `member_${members.indexOf(member) + 1}`;
      lines.push(`${pad}agents.append(_make_agent(${pyStr(agentName)}, ${pyStr(`Team member: ${member}`)}))`);
    }
    lines.push(`${pad}return _groupchat(agents)`);
    lines.push('');

    return lines;
  }

  private compileSystem(mod: V2SystemNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = chatFn(mod.name);
    const modules = (mod.modules || []).map(String);
    const lines: string[] = [];

    if (modules.length === 0) {
      return [
        `def ${fn}() -> GroupChatManager:`,
        `${pad}"""${mod.name} system has no parseable modules."""`,
        `${pad}raise ValueError("No modules declared for system ${pyStr(mod.name)}")`,
        '',
      ];
    }

    lines.push(`def ${fn}() -> GroupChatManager:`);
    lines.push(`${pad}"""GroupChat that runs the ${mod.name} system modules."""`);
    lines.push(`${pad}agents: list[ConversableAgent] = []`);
    modules.forEach((module, index) => {
      const agentName = ident(module) || `module_${index + 1}`;
      lines.push(`${pad}agents.append(_make_agent(${pyStr(agentName)}, ${pyStr(`System module: ${module}`)}))`);
    });
    lines.push(`${pad}return _groupchat(agents)`);
    lines.push('');

    return lines;
  }

  private compileMemory(mod: V2MemoryNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = ident(mod.name) + '_memory';

    return [
      `class ${className}:`,
      `${pad}"""In-memory store for the ${mod.name} memory module (${mod.format} / ${mod.backend})."""`,
      '',
      `${pad}def __init__(self):`,
      `${pad}${pad}self.format = ${pyStr(mod.format)}`,
      `${pad}${pad}self.backend = ${pyStr(mod.backend)}`,
      `${pad}${pad}self.scope = ${pyStr(mod.scope || 'module')}`,
      `${pad}${pad}self._store: dict = {}`,
      '',
      `${pad}def store(self, key: str, value: str) -> None:`,
      `${pad}${pad}"""Store a value under a key."""`,
      `${pad}${pad}self._store[key] = value`,
      '',
      `${pad}def retrieve(self, key: str) -> str:`,
      `${pad}${pad}"""Retrieve a value by key."""`,
      `${pad}${pad}return self._store.get(key, "")`,
      '',
    ];
  }

  private compilePolicy(mod: V2PolicyNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = ident(mod.name) + '_policy';

    return [
      `class ${className}:`,
      `${pad}"""Policy for ${mod.name}: allow/deny access checks."""`,
      '',
      `${pad}ALLOW = [${(mod.allow || []).map(pyStr).join(', ')}]`,
      `${pad}DENY = [${(mod.deny || []).map(pyStr).join(', ')}]`,
      '',
      `${pad}def check(self, action: str) -> bool:`,
      `${pad}${pad}"""Return True if the action is permitted."""`,
      `${pad}${pad}if action in self.DENY:`,
      `${pad}${pad}${pad}return False`,
      `${pad}${pad}if action in self.ALLOW:`,
      `${pad}${pad}${pad}return True`,
      `${pad}${pad}return False`,
      '',
    ];
  }

  private compileGeneric(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = chatFn(mod.name);

    return [
      `def ${fn}() -> GroupChatManager:`,
      `${pad}"""GroupChat for the ${mod.description || mod.name} module."""`,
      `${pad}return _groupchat([_make_agent(${pyStr(ident(mod.name))}, ${pyStr(mod.description || mod.name)})])`,
      '',
    ];
  }
}