/**
 * Microsoft AutoGen Target
 *
 * Compiles MAM AST to Python code using autogen-agentchat.
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2MemoryNode, V2WorkflowNode, V2TeamNode, V2PolicyNode, V2SystemNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';
import { generateModuleContext } from '../context.js';

export class AutoGenTarget implements CompileTargetHandler {
  name = 'autogen';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];
    const indent = config.indent || 4;

    lines.push('"""');
    lines.push('Generated by MAM Compiler');
    lines.push('Target: Microsoft AutoGen');
    lines.push('"""');
    lines.push('');
    lines.push('from autogen_agentchat.agents import AssistantAgent');
    lines.push('from autogen_agentchat.teams import RoundRobinGroupChat');
    lines.push('from autogen_agentchat.conditions import TextMentionTermination');
    lines.push('from autogen_core.models import ChatCompletionClient');
    lines.push('');

    for (const mod of modules) {
      lines.push(generateModuleContext(mod, 'autogen'));
      lines.push('');
      lines.push(...this.compileModule(mod, indent, config));
      lines.push('');
    }

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];
    const pad = ' '.repeat(indent);

    if (config.includeComments) {
      lines.push(`# Module: ${mod.name}`);
      lines.push(`# Type: ${mod.moduleType}`);
      if (mod.description) lines.push(`# ${mod.description}`);
      lines.push('');
    }

    switch (mod.moduleType) {
      case 'agent':
        lines.push(...this.compileAgent(mod as unknown as V2AgentNode, indent, config));
        break;
      case 'tool':
        lines.push(...this.compileTool(mod as unknown as V2ToolNode, indent, config));
        break;
      case 'memory':
        lines.push(...this.compileMemory(mod as unknown as V2MemoryNode, indent, config));
        break;
      case 'workflow':
        lines.push(...this.compileWorkflow(mod as unknown as V2WorkflowNode, indent, config));
        break;
      case 'team':
        lines.push(...this.compileTeam(mod as unknown as V2TeamNode, indent, config));
        break;
      case 'policy':
        lines.push(...this.compilePolicy(mod as unknown as V2PolicyNode, indent, config));
        break;
      case 'system':
        lines.push(...this.compileSystem(mod as unknown as V2SystemNode, indent, config));
        break;
      default:
        lines.push(...this.compileGeneric(mod, indent, config));
    }

    return lines;
  }

  private compileAgent(mod: V2AgentNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const varName = mod.name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();

    return [
      `async def create_${varName}_agent(model_client: ChatCompletionClient):`,
      `${pad}"""Create ${mod.name} agent: ${mod.goal || mod.role}"""`,
      `${pad}agent = AssistantAgent(`,
      `${pad}${pad}name="${mod.name}",`,
      `${pad}${pad}model_client=model_client,`,
      `${pad}${pad}system_message="${mod.role || ''}. Goal: ${mod.goal || ''}",`,
      `${pad})`,
      `${pad}return agent`,
      '',
    ];
  }

  private compileTool(mod: V2ToolNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const funcName = mod.name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();

    return [
      `class ${funcName}_tool:`,
      `${pad}"""AutoGen tool: ${mod.provider}"""`,
      '',
      `${pad}def __init__(self):`,
      `${pad}${pad}self.provider = "${mod.provider}"`,
      `${pad}${pad}self.capabilities = ${JSON.stringify(mod.capabilities || [])}`,
      '',
      `${pad}async def execute(self, action: str, **kwargs) -> str:`,
      `${pad}${pad}"""Execute a tool action."""`,
      `${pad}${pad}raise NotImplementedError`,
      '',
    ];
  }

  private compileMemory(mod: V2MemoryNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = mod.name.replace(/[^a-zA-Z0-9_]/g, '_');

    return [
      `class ${className}_memory:`,
      `${pad}"""AutoGen memory: ${mod.format} / ${mod.backend}"""`,
      '',
      `${pad}def __init__(self):`,
      `${pad}${pad}self.format = "${mod.format}"`,
      `${pad}${pad}self.backend = "${mod.backend}"`,
      `${pad}${pad}self.scope = "${mod.scope}"`,
      `${pad}${pad}self._store = {}`,
      '',
      `${pad}async def store(self, key: str, value: str):`,
      `${pad}${pad}self._store[key] = value`,
      '',
      `${pad}async def retrieve(self, key: str) -> str:`,
      `${pad}${pad}return self._store.get(key, "")`,
      '',
    ];
  }

  private compileWorkflow(mod: V2WorkflowNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const varName = mod.name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();

    return [
      `async def create_${varName}_workflow(agents: list):`,
      `${pad}"""Create ${mod.name} workflow"""`,
      `${pad}steps = ${JSON.stringify(mod.steps?.map(s => s.name) || [])}`,
      `${pad}edges = ${JSON.stringify(mod.edges?.map(e => [e.source, e.target]) || [])}`,
      `${pad}termination = TextMentionTermination("STOP")`,
      `${pad}team = RoundRobinGroupChat(agents, termination_condition=termination)`,
      `${pad}return team`,
      '',
    ];
  }

  private compileTeam(mod: V2TeamNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const varName = mod.name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();

    return [
      `async def create_${varName}_team(agents: dict):`,
      `${pad}"""Create ${mod.name} team"""`,
      `${pad}members = ${JSON.stringify(mod.members || [])}`,
      `${pad}team_agents = [agents[m] for m in members if m in agents]`,
      `${pad}termination = TextMentionTermination("STOP")`,
      `${pad}team = RoundRobinGroupChat(team_agents, termination_condition=termination)`,
      `${pad}return team`,
      '',
    ];
  }

  private compilePolicy(mod: V2PolicyNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = mod.name.replace(/[^a-zA-Z0-9_]/g, '_');

    return [
      `class ${className}_policy:`,
      `${pad}"""AutoGen policy"""`,
      '',
      `${pad}ALLOW = ${JSON.stringify(mod.allow || [])}`,
      `${pad}DENY = ${JSON.stringify(mod.deny || [])}`,
      '',
      `${pad}def check(self, action: str) -> bool:`,
      `${pad}${pad}if action in self.DENY: return False`,
      `${pad}${pad}if action in self.ALLOW: return True`,
      `${pad}${pad}return False`,
      '',
    ];
  }

  private compileSystem(mod: V2SystemNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const varName = mod.name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();

    return [
      `async def run_${varName}_system(agents: dict):`,
      `${pad}"""Run ${mod.name} system"""`,
      `${pad}agent_list = ${JSON.stringify(mod.agents || [])}`,
      `${pad}module_list = ${JSON.stringify(mod.modules || [])}`,
      `${pad}team_agents = [agents[a] for a in agent_list if a in agents]`,
      `${pad}if not team_agents:`,
      `${pad}${pad}raise ValueError("No agents found")`,
      `${pad}termination = TextMentionTermination("STOP")`,
      `${pad}team = RoundRobinGroupChat(team_agents, termination_condition=termination)`,
      `${pad}await team.run(task="System initialized")`,
      '',
    ];
  }

  private compileGeneric(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = mod.name.replace(/[^a-zA-Z0-9_]/g, '_');

    return [
      `class ${className}:`,
      `${pad}"""${mod.description || mod.name}"""`,
      '',
      `${pad}def __init__(self):`,
      `${pad}${pad}pass`,
      '',
    ];
  }
}
