/**
 * Claude SDK Target
 *
 * Compiles MAM AST to runnable Python using the `anthropic` package.
 * Each MAM agent becomes a real `Anthropic().messages.create` call with the
 * module context as the system prompt. A `main()` self-test guarded by
 * `if __name__ == "__main__"` is emitted at the end.
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2WorkflowNode, V2TeamNode, V2SystemNode, V2MemoryNode, V2PolicyNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig, TargetHandlerOutput } from '../compiler.js';
import { generateModuleContext } from '../context.js';
import { optimizePrompt } from './optimize.js';

function pyStr(value: unknown): string {
  const s = String(value ?? '');
  return `'${s
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')}'`;
}

function ident(name: string): string {
  let s = name.toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/^_+|_+$/g, '');
  if (!s) s = 'module';
  if (/^[0-9]/.test(s)) s = '_' + s;
  return s;
}

function runFn(name: string): string {
  return 'run_' + ident(name);
}

function claudeContext(mod: V2ModuleNode): string {
  const ctx = generateModuleContext(mod, 'claude');
  return ctx
    .split('\n')
    .map(line => {
      if (line.trim() === '') return '';
      if (line.startsWith('//')) return '#' + line.slice(2);
      if (line.startsWith('#')) return line;
      return '# ' + line;
    })
    .join('\n');
}

export class ClaudeTarget implements CompileTargetHandler {
  name = 'claude';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string | TargetHandlerOutput {
    if (config.optimizeTokens) {
      return this.compileOptimized(modules, config);
    }
    return this.compileDefault(modules, config);
  }

  private compileDefault(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];
    const indent = config.indent || 4;
    const pad = ' '.repeat(indent);

    lines.push('"""');
    lines.push('Generated by MAM Compiler');
    lines.push('Target: Claude SDK (anthropic messages API)');
    lines.push('"""');
    lines.push('');
    lines.push('import json');
    lines.push('import os');
    lines.push('');
    lines.push('import anthropic');
    lines.push('');
    lines.push('MODEL = "claude-3-5-sonnet-20241022"');
    lines.push('');
    lines.push('def _client(api_key: str | None = None) -> anthropic.Anthropic:');
    lines.push(`${pad}"""Create an Anthropic client from the environment or an explicit key."""`);
    lines.push(`${pad}if api_key is None:`);
    lines.push(`${pad}${pad}api_key = os.environ.get("ANTHROPIC_API_KEY")`);
    lines.push(`${pad}return anthropic.Anthropic(api_key=api_key)`);
    lines.push('');
    lines.push('def _complete(system: str, task: str, client: anthropic.Anthropic, model: str = MODEL) -> str:');
    lines.push(`${pad}"""Send a messages.create request and return the reply text."""`);
    lines.push(`${pad}message = client.messages.create(`);
    lines.push(`${pad}${pad}model=model,`);
    lines.push(`${pad}${pad}max_tokens=4096,`);
    lines.push(`${pad}${pad}system=system,`);
    lines.push(`${pad}${pad}messages=[{"role": "user", "content": task}],`);
    lines.push(`${pad})`);
    lines.push(`${pad}return message.content[0].text`);
    lines.push('');

    let primary: string | null = null;
    for (const mod of modules) {
      lines.push(claudeContext(mod));
      lines.push('');
      lines.push(...this.compileModule(mod, indent, config));
      lines.push('');
      if (primary === null && (mod.moduleType === 'system' || mod.moduleType === 'agent')) {
        primary = runFn(mod.name);
      }
    }

    lines.push('def main() -> int:');
    if (primary) {
      lines.push(`${pad}api_key = os.environ.get("ANTHROPIC_API_KEY")`);
      lines.push(`${pad}if not api_key:`);
      lines.push(`${pad}${pad}print("ANTHROPIC_API_KEY is not set; skipping the live Claude call.")`);
      lines.push(`${pad}${pad}return 1`);
      lines.push(`${pad}client = _client(api_key)`);
      lines.push(`${pad}task = "Execute the module and return the final result."`);
      lines.push(`${pad}result = ${primary}(task, api_key=api_key, client=client)`);
      lines.push(`${pad}print(result)`);
      lines.push(`${pad}return 0`);
    } else {
      lines.push(`${pad}print("No runnable module (system or agent) found in this MAM document.")`);
      lines.push(`${pad}return 0`);
    }
    lines.push('');
    lines.push('if __name__ == "__main__":');
    lines.push(`${pad}raise SystemExit(main())`);
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Emits the same program shape as the default path but with the prompt
   * content run through the token optimizer. The optimized text becomes a
   * module-level `SYSTEM_PROMPT` used by every runnable module.
   */
  private compileOptimized(modules: V2ModuleNode[], config: CompilerConfig): TargetHandlerOutput {
    const { optimizedText, tokenOptimization } = optimizePrompt(modules, 'claude');
    const lines: string[] = [];
    const indent = config.indent || 4;
    const pad = ' '.repeat(indent);

    lines.push('"""');
    lines.push('Generated by MAM Compiler');
    lines.push('Target: Claude SDK (anthropic messages API) [token-optimized]');
    lines.push('"""');
    lines.push('');
    lines.push('import json');
    lines.push('import os');
    lines.push('');
    lines.push('import anthropic');
    lines.push('');
    lines.push('MODEL = "claude-3-5-sonnet-20241022"');
    lines.push('');
    lines.push('def _client(api_key: str | None = None) -> anthropic.Anthropic:');
    lines.push(`${pad}"""Create an Anthropic client from the environment or an explicit key."""`);
    lines.push(`${pad}if api_key is None:`);
    lines.push(`${pad}${pad}api_key = os.environ.get("ANTHROPIC_API_KEY")`);
    lines.push(`${pad}return anthropic.Anthropic(api_key=api_key)`);
    lines.push('');
    lines.push('def _complete(system: str, task: str, client: anthropic.Anthropic, model: str = MODEL) -> str:');
    lines.push(`${pad}"""Send a messages.create request and return the reply text."""`);
    lines.push(`${pad}message = client.messages.create(`);
    lines.push(`${pad}${pad}model=model,`);
    lines.push(`${pad}${pad}max_tokens=4096,`);
    lines.push(`${pad}${pad}system=system,`);
    lines.push(`${pad}${pad}messages=[{"role": "user", "content": task}],`);
    lines.push(`${pad})`);
    lines.push(`${pad}return message.content[0].text`);
    lines.push('');
    lines.push(`SYSTEM_PROMPT = ${pyStr(optimizedText)}`);
    lines.push('');

    let primary: string | null = null;
    for (const mod of modules) {
      if (primary === null && (mod.moduleType === 'system' || mod.moduleType === 'agent')) {
        primary = runFn(mod.name);
      }
      lines.push(...this.compileOptimizedModule(mod, indent, config));
      lines.push('');
    }

    lines.push('def main() -> int:');
    if (primary) {
      lines.push(`${pad}api_key = os.environ.get("ANTHROPIC_API_KEY")`);
      lines.push(`${pad}if not api_key:`);
      lines.push(`${pad}${pad}print("ANTHROPIC_API_KEY is not set; skipping the live Claude call.")`);
      lines.push(`${pad}${pad}return 1`);
      lines.push(`${pad}client = _client(api_key)`);
      lines.push(`${pad}task = "Execute the module and return the final result."`);
      lines.push(`${pad}result = ${primary}(task, api_key=api_key, client=client)`);
      lines.push(`${pad}print(result)`);
      lines.push(`${pad}return 0`);
    } else {
      lines.push(`${pad}print("No runnable module (system or agent) found in this MAM document.")`);
      lines.push(`${pad}return 0`);
    }
    lines.push('');
    lines.push('if __name__ == "__main__":');
    lines.push(`${pad}raise SystemExit(main())`);
    lines.push('');

    return { output: lines.join('\n'), tokenOptimization };
  }

  private compileOptimizedModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    switch (mod.moduleType) {
      case 'tool':
        return this.compileTool(mod as unknown as V2ToolNode, indent, config);
      case 'memory':
        return this.compileMemory(mod as unknown as V2MemoryNode, indent, config);
      case 'policy':
        return this.compilePolicy(mod as unknown as V2PolicyNode, indent, config);
      default:
        return this.compileOptimizedRunnable(mod, indent);
    }
  }

  private compileOptimizedRunnable(mod: V2ModuleNode, indent: number): string[] {
    const pad = ' '.repeat(indent);
    const fn = runFn(mod.name);

    return [
      `def ${fn}(task: str, *, api_key: str | None = None, client: anthropic.Anthropic | None = None, model: str = MODEL) -> str:`,
      `${pad}"""${mod.description || mod.name} via the Claude messages API (token-optimized)."""`,
      `${pad}if client is None:`,
      `${pad}${pad}client = _client(api_key)`,
      `${pad}return _complete(SYSTEM_PROMPT, task, client, model=model)`,
      '',
    ];
  }

  private compileModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];

    switch (mod.moduleType) {
      case 'agent':
        lines.push(...this.compileAgent(mod as unknown as V2AgentNode, indent, config));
        break;
      case 'tool':
        lines.push(...this.compileTool(mod as unknown as V2ToolNode, indent, config));
        break;
      case 'workflow':
        lines.push(...this.compileWorkflow(mod as unknown as V2WorkflowNode, indent, config));
        break;
      case 'team':
        lines.push(...this.compileTeam(mod as unknown as V2TeamNode, indent, config));
        break;
      case 'system':
        lines.push(...this.compileSystem(mod as unknown as V2SystemNode, indent, config));
        break;
      case 'memory':
        lines.push(...this.compileMemory(mod as unknown as V2MemoryNode, indent, config));
        break;
      case 'policy':
        lines.push(...this.compilePolicy(mod as unknown as V2PolicyNode, indent, config));
        break;
      default:
        lines.push(...this.compileGeneric(mod, indent, config));
    }

    return lines;
  }

  private compileAgent(mod: V2AgentNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = runFn(mod.name);
    const lines: string[] = [];

    if (config.includeComments) {
      lines.push(`# Agent: ${mod.name}`);
      lines.push(`# Role: ${mod.role || 'N/A'}`);
      lines.push(`# Goal: ${mod.goal || 'N/A'}`);
      lines.push('');
    }

    const parts: string[] = [`${mod.name} agent`];
    if (mod.role) parts.push(`Role: ${mod.role}`);
    if (mod.goal) parts.push(`Goal: ${mod.goal}`);
    if (mod.handoff && mod.handoff.length > 0) parts.push(`Handoff: ${mod.handoff.join(', ')}`);

    lines.push(`def ${fn}(task: str, *, api_key: str | None = None, client: anthropic.Anthropic | None = None, model: str = MODEL) -> str:`);
    lines.push(`${pad}"""Run the ${mod.name} agent via the Claude messages API."""`);
    lines.push(`${pad}if client is None:`);
    lines.push(`${pad}${pad}client = _client(api_key)`);
    lines.push(`${pad}parts = [${parts.map(pyStr).join(', ')}]`);
    if (mod.rules && mod.rules.length > 0) {
      lines.push(`${pad}rules = [${mod.rules.map(pyStr).join(', ')}]`);
      lines.push(`${pad}if rules:`);
      lines.push(`${pad}${pad}parts.append("Rules:\\n" + "\\n".join("- " + r for r in rules))`);
    }
    lines.push(`${pad}system = "\\n".join(p for p in parts if p)`);
    lines.push(`${pad}return _complete(system, task, client, model=model)`);
    lines.push('');

    return lines;
  }

  private compileTool(mod: V2ToolNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = ident(mod.name);
    const provider = mod.provider || 'unknown';

    return [
      `def ${fn}(**kwargs: object) -> str:`,
      `${pad}"""${mod.name} tool (provider: ${provider})."""`,
      `${pad}return json.dumps({"tool": ${pyStr(mod.name)}, "action": kwargs}, sort_keys=True)`,
      '',
    ];
  }

  private compileWorkflow(mod: V2WorkflowNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = runFn(mod.name);
    const steps = (mod.steps || []).map(s => ident(s.name)).filter(Boolean);

    return [
      `def ${fn}(task: str, *, api_key: str | None = None, client: anthropic.Anthropic | None = None, model: str = MODEL) -> str:`,
      `${pad}"""Run the ${mod.name} workflow via the Claude messages API."""`,
      `${pad}if client is None:`,
      `${pad}${pad}client = _client(api_key)`,
      `${pad}steps = [${steps.map(pyStr).join(', ')}]`,
      `${pad}parts = [${pyStr(`${mod.name} workflow`)}]`,
      `${pad}if steps:`,
      `${pad}${pad}parts.append("Steps:\\n" + "\\n".join("- " + s for s in steps))`,
      `${pad}system = "\\n".join(p for p in parts if p)`,
      `${pad}return _complete(system, task, client, model=model)`,
      '',
    ];
  }

  private compileTeam(mod: V2TeamNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = runFn(mod.name);
    const members = (mod.members || []).map(String);

    return [
      `def ${fn}(task: str, *, api_key: str | None = None, client: anthropic.Anthropic | None = None, model: str = MODEL) -> str:`,
      `${pad}"""Coordinate the ${mod.name} team via the Claude messages API."""`,
      `${pad}if client is None:`,
      `${pad}${pad}client = _client(api_key)`,
      `${pad}members = [${members.map(pyStr).join(', ')}]`,
      `${pad}parts = [${pyStr(`${mod.name} team`)}]`,
      `${pad}if members:`,
      `${pad}${pad}parts.append("Members:\\n" + "\\n".join("- " + m for m in members))`,
      `${pad}system = "\\n".join(p for p in parts if p)`,
      `${pad}return _complete(system, task, client, model=model)`,
      '',
    ];
  }

  private compileSystem(mod: V2SystemNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = runFn(mod.name);
    const modules = (mod.modules || []).map(String);

    return [
      `def ${fn}(task: str, *, api_key: str | None = None, client: anthropic.Anthropic | None = None, model: str = MODEL) -> str:`,
      `${pad}"""Run the ${mod.name} system via the Claude messages API."""`,
      `${pad}if client is None:`,
      `${pad}${pad}client = _client(api_key)`,
      `${pad}modules = [${modules.map(pyStr).join(', ')}]`,
      `${pad}parts = [${pyStr(`${mod.name}: ${mod.description || 'System composition'}`)}]`,
      `${pad}if modules:`,
      `${pad}${pad}parts.append("Modules to orchestrate:\\n" + "\\n".join("- " + m for m in modules))`,
      `${pad}system = "\\n".join(p for p in parts if p)`,
      `${pad}return _complete(system, task, client, model=model)`,
      '',
    ];
  }

  private compileMemory(mod: V2MemoryNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = ident(mod.name) + '_memory';

    return [
      `class ${className}:`,
      `${pad}"""In-memory store for the ${mod.name} memory module (${mod.format} / ${mod.backend})."""`,
      '',
      `${pad}def __init__(self):`,
      `${pad}${pad}self.format = ${pyStr(mod.format)}`,
      `${pad}${pad}self.backend = ${pyStr(mod.backend)}`,
      `${pad}${pad}self.scope = ${pyStr(mod.scope || 'module')}`,
      `${pad}${pad}self._store: dict = {}`,
      '',
      `${pad}def store(self, key: str, value: str) -> None:`,
      `${pad}${pad}"""Store a value under a key."""`,
      `${pad}${pad}self._store[key] = value`,
      '',
      `${pad}def retrieve(self, key: str) -> str:`,
      `${pad}${pad}"""Retrieve a value by key."""`,
      `${pad}${pad}return self._store.get(key, "")`,
      '',
    ];
  }

  private compilePolicy(mod: V2PolicyNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = ident(mod.name) + '_policy';

    return [
      `class ${className}:`,
      `${pad}"""Policy for ${mod.name}: allow/deny access checks."""`,
      '',
      `${pad}ALLOW = [${(mod.allow || []).map(pyStr).join(', ')}]`,
      `${pad}DENY = [${(mod.deny || []).map(pyStr).join(', ')}]`,
      '',
      `${pad}def check(self, action: str) -> bool:`,
      `${pad}${pad}"""Return True if the action is permitted."""`,
      `${pad}${pad}if action in self.DENY:`,
      `${pad}${pad}${pad}return False`,
      `${pad}${pad}if action in self.ALLOW:`,
      `${pad}${pad}${pad}return True`,
      `${pad}${pad}return False`,
      '',
    ];
  }

  private compileGeneric(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = runFn(mod.name);

    return [
      `def ${fn}(task: str, *, api_key: str | None = None, client: anthropic.Anthropic | None = None, model: str = MODEL) -> str:`,
      `${pad}"""${mod.description || mod.name} via the Claude messages API."""`,
      `${pad}if client is None:`,
      `${pad}${pad}client = _client(api_key)`,
      `${pad}system = ${pyStr(mod.description || mod.name)}`,
      `${pad}return _complete(system, task, client, model=model)`,
      '',
    ];
  }
}