/**
 * Claude SDK Target
 * 
 * Compiles MAM AST to Claude SDK code.
 */

import { V2ModuleNode, V2AgentNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';

export class ClaudeTarget implements CompileTargetHandler {
  name = 'claude';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];

    lines.push('"""');
    lines.push('Generated by MAM Compiler');
    lines.push('Target: Claude SDK');
    lines.push('"""');
    lines.push('');
    lines.push('import anthropic');
    lines.push('');

    for (const mod of modules) {
      lines.push(...this.compileModule(mod, config));
      lines.push('');
    }

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode, config: CompilerConfig): string[] {
    const lines: string[] = [];
    const varName = mod.name.toLowerCase().replace(/[^a-z0-9_]/g, '_');

    if (mod.moduleType === 'agent') {
      lines.push(`# Agent: ${mod.name}`);
      lines.push(`${varName}_client = anthropic.Anthropic()`);
      lines.push('');
      lines.push(`async def run_${varName}(task: str) -> str:`);
      lines.push(`    """${mod.goal || mod.role || mod.name}"""`);
      lines.push(`    message = ${varName}_client.messages.create(`);
      lines.push(`        model="claude-3-opus-20240229",`);
      lines.push(`        max_tokens=4096,`);
      lines.push(`        messages=[{"role": "user", "content": task}]`);
      lines.push(`    )`);
      lines.push(`    return message.content[0].text`);
      lines.push('');
    }

    return lines;
  }
}