/**
 * CrewAI Target
 *
 * Compiles MAM AST to runnable Python using `crewai`.
 * Agents become `Agent(role=..., goal=..., backstory=...)`, workflows/teams/
 * systems become `Task` + `Crew(..., process=Process.sequential)` instances,
 * and a `main()` that `.kickoff()`s is emitted under `if __name__ == "__main__"`.
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2WorkflowNode, V2TeamNode, V2SystemNode, V2MemoryNode, V2PolicyNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig, TargetHandlerOutput } from '../compiler.js';
import { generateModuleContext } from '../context.js';
import { optimizePrompt } from './optimize.js';

function pyStr(value: unknown): string {
  const s = String(value ?? '');
  return `'${s
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')}'`;
}

function ident(name: string): string {
  let s = name.toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/^_+|_+$/g, '');
  if (!s) s = 'module';
  if (/^[0-9]/.test(s)) s = '_' + s;
  return s;
}

function makeFn(name: string): string {
  return 'make_' + ident(name);
}

function crewFn(name: string): string {
  return makeFn(name) + '_crew';
}

export class CrewAITarget implements CompileTargetHandler {
  name = 'crewai';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string | TargetHandlerOutput {
    if (config.optimizeTokens) {
      return this.compileOptimized(modules, config);
    }
    return this.compileDefault(modules, config);
  }

  private compileDefault(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];
    const indent = config.indent || 4;
    const pad = ' '.repeat(indent);

    lines.push('"""');
    lines.push('Generated by MAM Compiler');
    lines.push('Target: CrewAI');
    lines.push('"""');
    lines.push('');
    lines.push('import json');
    lines.push('import os');
    lines.push('');
    lines.push('from crewai import Agent, Crew, Process, Task');
    lines.push('from crewai_tools import BaseTool');
    lines.push('');
    lines.push('MODEL = "gpt-4o"');
    lines.push('');
    lines.push('def _make_agent(role: str, goal: str, backstory: str) -> Agent:');
    lines.push(`${pad}"""Create a CrewAI Agent with the configured LLM."""`);
    lines.push(`${pad}return Agent(`);
    lines.push(`${pad}${pad}role=role,`);
    lines.push(`${pad}${pad}goal=goal,`);
    lines.push(`${pad}${pad}backstory=backstory,`);
    lines.push(`${pad}${pad}verbose=True,`);
    lines.push(`${pad}${pad}allow_delegation=False,`);
    lines.push(`${pad}${pad}llm=MODEL,`);
    lines.push(`${pad})`);
    lines.push('');
    lines.push('def _make_task(description: str, agent: Agent) -> Task:');
    lines.push(`${pad}"""Create a CrewAI Task for an agent."""`);
    lines.push(`${pad}return Task(`);
    lines.push(`${pad}${pad}description=description,`);
    lines.push(`${pad}${pad}expected_output="A complete, well-formed result for the task.",`);
    lines.push(`${pad}${pad}agent=agent,`);
    lines.push(`${pad})`);
    lines.push('');

    let primary: string | null = null;
    for (const mod of modules) {
      lines.push(generateModuleContext(mod, 'crewai'));
      lines.push('');
      lines.push(...this.compileModule(mod, indent, config));
      lines.push('');
      if (
        primary === null &&
        (mod.moduleType === 'system' || mod.moduleType === 'workflow' || mod.moduleType === 'team' || mod.moduleType === 'agent')
      ) {
        primary = crewFn(mod.name);
      }
    }

    lines.push('def main() -> int:');
    if (primary) {
      lines.push(`${pad}api_key = os.environ.get("OPENAI_API_KEY")`);
      lines.push(`${pad}if not api_key:`);
      lines.push(`${pad}${pad}print("OPENAI_API_KEY is not set; skipping the live CrewAI kickoff.")`);
      lines.push(`${pad}${pad}return 1`);
      lines.push(`${pad}crew = ${primary}()`);
      lines.push(`${pad}result = crew.kickoff()`);
      lines.push(`${pad}print(result)`);
      lines.push(`${pad}return 0`);
    } else {
      lines.push(`${pad}print("No runnable module (system, workflow, team or agent) found in this MAM document.")`);
      lines.push(`${pad}return 0`);
    }
    lines.push('');
    lines.push('if __name__ == "__main__":');
    lines.push(`${pad}raise SystemExit(main())`);
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Emits the same program shape as the default path but with the prompt
   * content run through the token optimizer. The optimized text becomes a
   * module-level `SYSTEM_PROMPT` used as every agent's backstory.
   */
  private compileOptimized(modules: V2ModuleNode[], config: CompilerConfig): TargetHandlerOutput {
    const { optimizedText, tokenOptimization } = optimizePrompt(modules, 'crewai');
    const lines: string[] = [];
    const indent = config.indent || 4;
    const pad = ' '.repeat(indent);

    lines.push('"""');
    lines.push('Generated by MAM Compiler');
    lines.push('Target: CrewAI [token-optimized]');
    lines.push('"""');
    lines.push('');
    lines.push('import json');
    lines.push('import os');
    lines.push('');
    lines.push('from crewai import Agent, Crew, Process, Task');
    lines.push('from crewai_tools import BaseTool');
    lines.push('');
    lines.push('MODEL = "gpt-4o"');
    lines.push('');
    lines.push('def _make_agent(role: str, goal: str, backstory: str) -> Agent:');
    lines.push(`${pad}"""Create a CrewAI Agent with the configured LLM."""`);
    lines.push(`${pad}return Agent(`);
    lines.push(`${pad}${pad}role=role,`);
    lines.push(`${pad}${pad}goal=goal,`);
    lines.push(`${pad}${pad}backstory=backstory,`);
    lines.push(`${pad}${pad}verbose=True,`);
    lines.push(`${pad}${pad}allow_delegation=False,`);
    lines.push(`${pad}${pad}llm=MODEL,`);
    lines.push(`${pad})`);
    lines.push('');
    lines.push('def _make_task(description: str, agent: Agent) -> Task:');
    lines.push(`${pad}"""Create a CrewAI Task for an agent."""`);
    lines.push(`${pad}return Task(`);
    lines.push(`${pad}${pad}description=description,`);
    lines.push(`${pad}${pad}expected_output="A complete, well-formed result for the task.",`);
    lines.push(`${pad}${pad}agent=agent,`);
    lines.push(`${pad})`);
    lines.push('');
    lines.push(`SYSTEM_PROMPT = ${pyStr(optimizedText)}`);
    lines.push('');

    let primary: string | null = null;
    for (const mod of modules) {
      if (
        primary === null &&
        (mod.moduleType === 'system' || mod.moduleType === 'workflow' || mod.moduleType === 'team' || mod.moduleType === 'agent')
      ) {
        primary = crewFn(mod.name);
      }
      lines.push(...this.compileOptimizedModule(mod, indent, config));
      lines.push('');
    }

    lines.push('def main() -> int:');
    if (primary) {
      lines.push(`${pad}api_key = os.environ.get("OPENAI_API_KEY")`);
      lines.push(`${pad}if not api_key:`);
      lines.push(`${pad}${pad}print("OPENAI_API_KEY is not set; skipping the live CrewAI kickoff.")`);
      lines.push(`${pad}${pad}return 1`);
      lines.push(`${pad}crew = ${primary}()`);
      lines.push(`${pad}result = crew.kickoff()`);
      lines.push(`${pad}print(result)`);
      lines.push(`${pad}return 0`);
    } else {
      lines.push(`${pad}print("No runnable module (system, workflow, team or agent) found in this MAM document.")`);
      lines.push(`${pad}return 0`);
    }
    lines.push('');
    lines.push('if __name__ == "__main__":');
    lines.push(`${pad}raise SystemExit(main())`);
    lines.push('');

    return { output: lines.join('\n'), tokenOptimization };
  }

  private compileOptimizedModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    switch (mod.moduleType) {
      case 'tool':
        return this.compileTool(mod as unknown as V2ToolNode, indent, config);
      case 'memory':
        return this.compileMemory(mod as unknown as V2MemoryNode, indent, config);
      case 'policy':
        return this.compilePolicy(mod as unknown as V2PolicyNode, indent, config);
      default:
        return this.compileOptimizedRunnable(mod, indent);
    }
  }

  private compileOptimizedRunnable(mod: V2ModuleNode, indent: number): string[] {
    const pad = ' '.repeat(indent);
    const role = mod.role || mod.name;

    return [
      `def ${makeFn(mod.name)}() -> Agent:`,
      `${pad}"""Create the ${mod.name} agent (token-optimized)."""`,
      `${pad}return _make_agent(`,
      `${pad}${pad}role=${pyStr(role)},`,
      `${pad}${pad}goal=${pyStr(`Execute the ${mod.name} task.`)},`,
      `${pad}${pad}backstory=SYSTEM_PROMPT,`,
      `${pad})`,
      '',
      `def ${crewFn(mod.name)}() -> Crew:`,
      `${pad}"""Crew that runs the ${mod.name} agent directly."""`,
      `${pad}agent = ${makeFn(mod.name)}()`,
      `${pad}task = _make_task(${pyStr(`Execute the ${mod.name} task and report the result.`)}, agent)`,
      `${pad}return Crew(agents=[agent], tasks=[task], process=Process.sequential, verbose=True)`,
      '',
    ];
  }

  private compileModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];

    switch (mod.moduleType) {
      case 'agent':
        lines.push(...this.compileAgent(mod as unknown as V2AgentNode, indent, config));
        break;
      case 'tool':
        lines.push(...this.compileTool(mod as unknown as V2ToolNode, indent, config));
        break;
      case 'workflow':
        lines.push(...this.compileWorkflow(mod as unknown as V2WorkflowNode, indent, config));
        break;
      case 'team':
        lines.push(...this.compileTeam(mod as unknown as V2TeamNode, indent, config));
        break;
      case 'system':
        lines.push(...this.compileSystem(mod as unknown as V2SystemNode, indent, config));
        break;
      case 'memory':
        lines.push(...this.compileMemory(mod as unknown as V2MemoryNode, indent, config));
        break;
      case 'policy':
        lines.push(...this.compilePolicy(mod as unknown as V2PolicyNode, indent, config));
        break;
      default:
        lines.push(`# Module: ${mod.name} (${mod.moduleType})`);
    }

    return lines;
  }

  private compileAgent(mod: V2AgentNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = makeFn(mod.name);
    const lines: string[] = [];

    if (config.includeComments) {
      lines.push(`# Agent: ${mod.name}`);
      lines.push(`# Role: ${mod.role || 'N/A'}`);
      lines.push(`# Goal: ${mod.goal || 'N/A'}`);
      lines.push('');
    }

    const role = mod.role || mod.name;
    const backstory = `You are a ${role} agent${mod.goal ? ` whose goal is: ${mod.goal}` : ''}.`;

    lines.push(`def ${fn}() -> Agent:`);
    lines.push(`${pad}"""Create the ${mod.name} agent."""`);
    lines.push(`${pad}return _make_agent(`);
    lines.push(`${pad}${pad}role=${pyStr(role)},`);
    lines.push(`${pad}${pad}goal=${pyStr(mod.goal || `Execute the ${mod.name} task.`)},`);
    lines.push(`${pad}${pad}backstory=${pyStr(backstory)},`);
    lines.push(`${pad})`);
    lines.push('');
    lines.push(`def ${crewFn(mod.name)}() -> Crew:`);
    lines.push(`${pad}"""Crew that runs the ${mod.name} agent directly."""`);
    lines.push(`${pad}agent = ${fn}()`);
    lines.push(`${pad}task = _make_task(${pyStr(`Execute the ${mod.name} task and report the result.`)}, agent)`);
    lines.push(`${pad}return Crew(agents=[agent], tasks=[task], process=Process.sequential, verbose=True)`);
    lines.push('');

    return lines;
  }

  private compileTool(mod: V2ToolNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = mod.name.replace(/[^a-zA-Z0-9_]/g, '_') + 'Tool';
    const provider = mod.provider || 'unknown';

    return [
      `class ${className}(BaseTool):`,
      `${pad}"""${mod.name} tool (provider: ${provider})."""`,
      `${pad}name: str = ${pyStr(mod.name)}`,
      `${pad}description: str = ${pyStr(`${mod.name} tool (${provider})`)}`,
      '',
      `${pad}def _run(self, **kwargs: object) -> str:`,
      `${pad}${pad}"""Execute the tool and return a structured result."""`,
      `${pad}${pad}return json.dumps({"tool": ${pyStr(mod.name)}, "action": kwargs}, sort_keys=True)`,
      '',
      `${pad}def _arun(self, **kwargs: object) -> str:`,
      `${pad}${pad}"""Async execute the tool."""`,
      `${pad}${pad}return self._run(**kwargs)`,
      '',
    ];
  }

  private compileWorkflow(mod: V2WorkflowNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = crewFn(mod.name);
    const steps = (mod.steps || []).map(s => ident(s.name)).filter(Boolean);
    const lines: string[] = [];

    if (steps.length === 0) {
      return [
        `def ${fn}() -> Crew:`,
        `${pad}"""${mod.name} workflow has no parseable steps."""`,
        `${pad}raise ValueError("No steps declared for workflow ${pyStr(mod.name)}")`,
        '',
      ];
    }

    lines.push(`def ${fn}() -> Crew:`);
    lines.push(`${pad}"""Crew that executes the ${mod.name} workflow steps sequentially."""`);
    lines.push(`${pad}agents: list[Agent] = []`);
    lines.push(`${pad}tasks: list[Task] = []`);
    for (const step of steps) {
      const stepIdent = ident(step);
      lines.push(`${pad}agent_${stepIdent} = _make_agent(`);
      lines.push(`${pad}${pad}role=${pyStr(step)},`);
      lines.push(`${pad}${pad}goal=${pyStr(`Execute workflow step: ${step}`)},`);
      lines.push(`${pad}${pad}backstory=${pyStr(`Workflow step executor for the ${mod.name} workflow.`)},`);
      lines.push(`${pad})`);
      lines.push(`${pad}agents.append(agent_${stepIdent})`);
      lines.push(`${pad}tasks.append(_make_task(${pyStr(`Execute the workflow step: ${step}`)}, agent_${stepIdent}))`);
    }
    lines.push(`${pad}return Crew(agents=agents, tasks=tasks, process=Process.sequential, verbose=True)`);
    lines.push('');

    return lines;
  }

  private compileTeam(mod: V2TeamNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = crewFn(mod.name);
    const members = (mod.members || []).map(String);
    const lines: string[] = [];

    if (members.length === 0) {
      return [
        `def ${fn}() -> Crew:`,
        `${pad}"""${mod.name} team has no parseable members."""`,
        `${pad}raise ValueError("No members declared for team ${pyStr(mod.name)}")`,
        '',
      ];
    }

    lines.push(`def ${fn}() -> Crew:`);
    lines.push(`${pad}"""Crew that coordinates the ${mod.name} team members."""`);
    lines.push(`${pad}agents: list[Agent] = []`);
    lines.push(`${pad}tasks: list[Task] = []`);
    members.forEach((member, index) => {
      const memberIdent = ident(member) || `member_${index + 1}`;
      lines.push(`${pad}agent_${memberIdent} = _make_agent(`);
      lines.push(`${pad}${pad}role=${pyStr(member)},`);
      lines.push(`${pad}${pad}goal=${pyStr(`Contribute to the ${mod.name} team as ${member}.`)},`);
      lines.push(`${pad}${pad}backstory=${pyStr(`Member of the ${mod.name} team.`)},`);
      lines.push(`${pad})`);
      lines.push(`${pad}agents.append(agent_${memberIdent})`);
      lines.push(`${pad}tasks.append(_make_task(${pyStr(`Complete the work of team member: ${member}`)}, agent_${memberIdent}))`);
    });
    lines.push(`${pad}return Crew(agents=agents, tasks=tasks, process=Process.sequential, verbose=True)`);
    lines.push('');

    return lines;
  }

  private compileSystem(mod: V2SystemNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = crewFn(mod.name);
    const modules = (mod.modules || []).map(String);
    const lines: string[] = [];

    if (modules.length === 0) {
      return [
        `def ${fn}() -> Crew:`,
        `${pad}"""${mod.name} system has no parseable modules."""`,
        `${pad}raise ValueError("No modules declared for system ${pyStr(mod.name)}")`,
        '',
      ];
    }

    lines.push(`def ${fn}() -> Crew:`);
    lines.push(`${pad}"""Crew that runs the ${mod.name} system modules in order."""`);
    lines.push(`${pad}agents: list[Agent] = []`);
    lines.push(`${pad}tasks: list[Task] = []`);
    modules.forEach((module, index) => {
      const moduleIdent = ident(module) || `module_${index + 1}`;
      lines.push(`${pad}agent_${moduleIdent} = _make_agent(`);
      lines.push(`${pad}${pad}role=${pyStr(module)},`);
      lines.push(`${pad}${pad}goal=${pyStr(`Execute the ${mod.name} system module: ${module}`)},`);
      lines.push(`${pad}${pad}backstory=${pyStr(`System module executor for the ${mod.name} system.`)},`);
      lines.push(`${pad})`);
      lines.push(`${pad}agents.append(agent_${moduleIdent})`);
      lines.push(`${pad}tasks.append(_make_task(${pyStr(`Execute the system module: ${module}`)}, agent_${moduleIdent}))`);
    });
    lines.push(`${pad}return Crew(agents=agents, tasks=tasks, process=Process.sequential, verbose=True)`);
    lines.push('');

    return lines;
  }

  private compileMemory(mod: V2MemoryNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = ident(mod.name) + '_memory';

    return [
      `class ${className}:`,
      `${pad}"""In-memory store for the ${mod.name} memory module (${mod.format} / ${mod.backend})."""`,
      '',
      `${pad}def __init__(self):`,
      `${pad}${pad}self.format = ${pyStr(mod.format)}`,
      `${pad}${pad}self.backend = ${pyStr(mod.backend)}`,
      `${pad}${pad}self.scope = ${pyStr(mod.scope || 'module')}`,
      `${pad}${pad}self._store: dict = {}`,
      '',
      `${pad}def store(self, key: str, value: str) -> None:`,
      `${pad}${pad}"""Store a value under a key."""`,
      `${pad}${pad}self._store[key] = value`,
      '',
      `${pad}def retrieve(self, key: str) -> str:`,
      `${pad}${pad}"""Retrieve a value by key."""`,
      `${pad}${pad}return self._store.get(key, "")`,
      '',
    ];
  }

  private compilePolicy(mod: V2PolicyNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = ident(mod.name) + '_policy';

    return [
      `class ${className}:`,
      `${pad}"""Policy for ${mod.name}: allow/deny access checks."""`,
      '',
      `${pad}ALLOW = [${(mod.allow || []).map(pyStr).join(', ')}]`,
      `${pad}DENY = [${(mod.deny || []).map(pyStr).join(', ')}]`,
      '',
      `${pad}def check(self, action: str) -> bool:`,
      `${pad}${pad}"""Return True if the action is permitted."""`,
      `${pad}${pad}if action in self.DENY:`,
      `${pad}${pad}${pad}return False`,
      `${pad}${pad}if action in self.ALLOW:`,
      `${pad}${pad}${pad}return True`,
      `${pad}${pad}return False`,
      '',
    ];
  }
}