/**
 * CrewAI Target
 * 
 * Compiles MAM AST to CrewAI code.
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2TeamNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';

export class CrewAITarget implements CompileTargetHandler {
  name = 'crewai';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];
    const indent = config.indent || 4;

    lines.push('"""');
    lines.push('Generated by MAM Compiler');
    lines.push('Target: CrewAI');
    lines.push('"""');
    lines.push('');
    lines.push('from crewai import Agent, Task, Crew, Process');
    lines.push('from crewai_tools import BaseTool');
    lines.push('');

    for (const mod of modules) {
      lines.push(...this.compileModule(mod, indent, config));
      lines.push('');
    }

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];

    switch (mod.moduleType) {
      case 'agent':
        lines.push(...this.compileAgent(mod as unknown as V2AgentNode, indent, config));
        break;
      case 'tool':
        lines.push(...this.compileTool(mod as unknown as V2ToolNode, indent, config));
        break;
      case 'team':
        lines.push(...this.compileTeam(mod as unknown as V2TeamNode, indent, config));
        break;
      default:
        lines.push(`# Module: ${mod.name} (${mod.moduleType})`);
    }

    return lines;
  }

  private compileAgent(mod: V2AgentNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const varName = mod.name.toLowerCase().replace(/[^a-z0-9_]/g, '_');

    const lines: string[] = [];

    if (config.includeComments) {
      lines.push(`# Agent: ${mod.name}`);
      lines.push(`# Role: ${mod.role || 'N/A'}`);
      lines.push(`# Goal: ${mod.goal || 'N/A'}`);
      lines.push('');
    }

    lines.push(`${varName} = Agent(`);
    lines.push(`${pad}role="${mod.role || mod.name}",`);
    lines.push(`${pad}goal="""${mod.goal || ''}""",`);
    lines.push(`${pad}backstory="""You are a ${mod.role || mod.name} agent.""",`);

    if (mod.tools && mod.tools.length > 0) {
      lines.push(`${pad}tools=[${mod.tools.map(t => t.toLowerCase() + '_tool').join(', ')}],`);
    }

    lines.push(`${pad}verbose=True,`);
    lines.push(`${pad}allow_delegation=False,`);
    lines.push(`)`);
    lines.push('');

    return lines;
  }

  private compileTool(mod: V2ToolNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = mod.name.replace(/[^a-zA-Z0-9_]/g, '_') + 'Tool';
    const funcName = mod.name.toLowerCase().replace(/[^a-z0-9_]/g, '_') + '_tool';

    return [
      `class ${className}(BaseTool):`,
      `${pad}name: str = "${mod.name}"`,
      `${pad}description: str = "${mod.name} tool (${mod.provider})"`,
      '',
      `${pad}def _run(self) -> str:`,
      `${pad}${pad}"""Execute the tool."""`,
      `${pad}${pad}# TODO: Implement ${mod.name}`,
      `${pad}${pad}return ""`,
      '',
      `${pad}def _arun(self) -> str:`,
      `${pad}${pad}"""Async execute the tool."""`,
      `${pad}${pad}return self._run()`,
      '',
      '',
      `${funcName} = ${className}()`,
      '',
    ];
  }

  private compileTeam(mod: V2TeamNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const lines: string[] = [];

    lines.push(`# Team: ${mod.name}`);
    lines.push('');

    if (mod.members && mod.members.length > 0) {
      lines.push(`# Create tasks for team members`);
      lines.push('');

      for (const member of mod.members) {
        const taskVar = member.toLowerCase().replace(/[^a-z0-9_]/g, '_') + '_task';
        lines.push(`${taskVar} = Task(`);
        lines.push(`${pad}description="""Execute ${member} tasks""",`);
        lines.push(`${pad}agent=${member.toLowerCase().replace(/[^a-z0-9_]/g, '_')},`);
        lines.push(`${pad}expected_output="Task result",`);
        lines.push(`)`);
        lines.push('');
      }

      // Create crew
      const crewVar = mod.name.toLowerCase().replace(/[^a-z0-9_]/g, '_') + '_crew';
      lines.push(`${crewVar} = Crew(`);
      lines.push(`${pad}agents=[${mod.members.map(m => m.toLowerCase().replace(/[^a-z0-9_]/g, '_')).join(', ')}],`);
      lines.push(`${pad}tasks=[${mod.members.map(m => m.toLowerCase().replace(/[^a-z0-9_]/g, '_') + '_task').join(', ')}],`);
      lines.push(`${pad}process=Process.sequential,`);
      lines.push(`${pad}verbose=True,`);
      lines.push(`)`);
      lines.push('');
    }

    return lines;
  }
}