/**
 * C# Target
 *
 * Compiles MAM AST to C# (.NET) code.
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2MemoryNode, V2WorkflowNode, V2TeamNode, V2PolicyNode, V2SystemNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';
import { generateModuleContext } from '../context.js';

export class CSharpTarget implements CompileTargetHandler {
  name = 'csharp';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];
    const indent = config.indent || 4;

    lines.push('// Generated by MAM Compiler');
    lines.push('// Target: C#');
    lines.push('');
    lines.push('using System;');
    lines.push('using System.Collections.Generic;');
    lines.push('using System.Threading.Tasks;');
    lines.push('');

    for (const mod of modules) {
      lines.push(generateModuleContext(mod, 'csharp'));
      lines.push('');
      lines.push(...this.compileModule(mod, indent, config));
      lines.push('');
    }

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];
    const pad = ' '.repeat(indent);

    if (config.includeComments) {
      lines.push(`// Module: ${mod.name}`);
      lines.push(`// Type: ${mod.moduleType}`);
      if (mod.description) lines.push(`// ${mod.description}`);
      lines.push('');
    }

    switch (mod.moduleType) {
      case 'agent':
        lines.push(...this.compileAgent(mod as unknown as V2AgentNode, indent, config));
        break;
      case 'tool':
        lines.push(...this.compileTool(mod as unknown as V2ToolNode, indent, config));
        break;
      case 'memory':
        lines.push(...this.compileMemory(mod as unknown as V2MemoryNode, indent, config));
        break;
      case 'workflow':
        lines.push(...this.compileWorkflow(mod as unknown as V2WorkflowNode, indent, config));
        break;
      case 'team':
        lines.push(...this.compileTeam(mod as unknown as V2TeamNode, indent, config));
        break;
      case 'policy':
        lines.push(...this.compilePolicy(mod as unknown as V2PolicyNode, indent, config));
        break;
      case 'system':
        lines.push(...this.compileSystem(mod as unknown as V2SystemNode, indent, config));
        break;
      default:
        lines.push(...this.compileGeneric(mod, indent, config));
    }

    return lines;
  }

  private toPascalCase(name: string): string {
    return name.replace(/(^|[-_])(\w)/g, (_, __, c) => c.toUpperCase()).replace(/[^a-zA-Z0-9]/g, '');
  }

  private compileAgent(mod: V2AgentNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = this.toPascalCase(mod.name);

    return [
      `public class ${className}Agent`,
      `{`,
      `${pad}public string Role { get; set; } = "${mod.role || ''}";`,
      `${pad}public string Goal { get; set; } = "${mod.goal || ''}";`,
      `${pad}public List<string> Tools { get; set; } = new() { ${mod.tools?.map(t => `"${t}"`).join(', ') || ''} };`,
      `${pad}public List<string> Handoff { get; set; } = new() { ${mod.handoff?.map(h => `"${h}"`).join(', ') || ''} };`,
      '',
      `${pad}public async Task<string> ExecuteAsync(string task)`,
      `${pad}{`,
      `${pad}${pad}throw new NotImplementedException();`,
      `${pad}}`,
      `}`,
    ];
  }

  private compileTool(mod: V2ToolNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = this.toPascalCase(mod.name);

    return [
      `public class ${className}Tool`,
      `{`,
      `${pad}public string Provider { get; set; } = "${mod.provider}";`,
      `${pad}public List<string> Capabilities { get; set; } = new() { ${mod.capabilities?.map(c => `"${c}"`).join(', ') || ''} };`,
      '',
      `${pad}public async Task<string> ExecuteAsync(string action, Dictionary<string, object>? kwargs = null)`,
      `${pad}{`,
      `${pad}${pad}throw new NotImplementedException();`,
      `${pad}}`,
      `}`,
    ];
  }

  private compileMemory(mod: V2MemoryNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = this.toPascalCase(mod.name);

    return [
      `public class ${className}Memory`,
      `{`,
      `${pad}public string Format { get; set; } = "${mod.format}";`,
      `${pad}public string Backend { get; set; } = "${mod.backend}";`,
      `${pad}public string Scope { get; set; } = "${mod.scope}";`,
      '',
      `${pad}public async Task StoreAsync(string key, object value)`,
      `${pad}{`,
      `${pad}${pad}throw new NotImplementedException();`,
      `${pad}}`,
      '',
      `${pad}public async Task<object> RetrieveAsync(string key)`,
      `${pad}{`,
      `${pad}${pad}throw new NotImplementedException();`,
      `${pad}}`,
      `}`,
    ];
  }

  private compileWorkflow(mod: V2WorkflowNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = this.toPascalCase(mod.name);

    return [
      `public class ${className}Workflow`,
      `{`,
      `${pad}public List<string> Steps { get; } = new() { ${mod.steps?.map(s => `"${s.name}"`).join(', ') || ''} };`,
      `${pad}public List<(string Source, string Target)> Edges { get; } = new() { ${mod.edges?.map(e => `("${e.source}", "${e.target}")`).join(', ') || ''} };`,
      '',
      `${pad}public async Task ExecuteAsync()`,
      `${pad}{`,
      `${pad}${pad}foreach (var step in Steps)`,
      `${pad}${pad}{`,
      `${pad}${pad}${pad}Console.WriteLine($"Executing step: {step}");`,
      `${pad}${pad}}`,
      `${pad}}`,
      `}`,
    ];
  }

  private compileTeam(mod: V2TeamNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = this.toPascalCase(mod.name);

    return [
      `public class ${className}Team`,
      `{`,
      `${pad}public List<string> Members { get; } = new() { ${mod.members?.map(m => `"${m}"`).join(', ') || ''} };`,
      '',
      `${pad}public async Task CoordinateAsync()`,
      `${pad}{`,
      `${pad}${pad}throw new NotImplementedException();`,
      `${pad}}`,
      `}`,
    ];
  }

  private compilePolicy(mod: V2PolicyNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = this.toPascalCase(mod.name);

    return [
      `public class ${className}Policy`,
      `{`,
      `${pad}public List<string> Allow { get; } = new() { ${mod.allow?.map(a => `"${a}"`).join(', ') || ''} };`,
      `${pad}public List<string> Deny { get; } = new() { ${mod.deny?.map(d => `"${d}"`).join(', ') || ''} };`,
      '',
      `${pad}public bool Check(string action)`,
      `${pad}{`,
      `${pad}${pad}if (Deny.Contains(action)) return false;`,
      `${pad}${pad}if (Allow.Contains(action)) return true;`,
      `${pad}${pad}return false;`,
      `${pad}}`,
      `}`,
    ];
  }

  private compileSystem(mod: V2SystemNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = this.toPascalCase(mod.name);

    return [
      `public class ${className}System`,
      `{`,
      `${pad}public List<string> Agents { get; } = new() { ${mod.agents?.map(a => `"${a}"`).join(', ') || ''} };`,
      `${pad}public List<string> Modules { get; } = new() { ${mod.modules?.map(m => `"${m}"`).join(', ') || ''} };`,
      `${pad}public List<(string Source, string Target)> Edges { get; } = new() { ${mod.edges?.map(e => `("${e.source}", "${e.target}")`).join(', ') || ''} };`,
      '',
      `${pad}public async Task RunAsync()`,
      `${pad}{`,
      `${pad}${pad}throw new NotImplementedException();`,
      `${pad}}`,
      `}`,
    ];
  }

  private compileGeneric(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = this.toPascalCase(mod.name);

    return [
      `public class ${className}Module`,
      `{`,
      `${pad}// ${mod.description || mod.name}`,
      `}`,
    ];
  }
}
