/**
 * C# Target
 *
 * Compiles MAM AST to C# (.NET) code.
 * Emits a complete, runnable program: shared result/port types, one class per
 * module with concrete behaviour, and a `Program.Main` that instantiates and
 * runs every module.
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2MemoryNode, V2WorkflowNode, V2TeamNode, V2PolicyNode, V2SystemNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';
import { generateModuleContext } from '../context.js';

export class CSharpTarget implements CompileTargetHandler {
  name = 'csharp';

  private demoCounter = 0;

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];
    const indent = config.indent || 4;
    const pad = ' '.repeat(indent);
    this.demoCounter = 0;

    lines.push('// Generated by MAM Compiler');
    lines.push('// Target: C#');
    lines.push('//');
    lines.push('// Compile: csc /out:MamGenerated.exe out.cs && MamGenerated.exe');
    lines.push('//');
    lines.push('using System;');
    lines.push('using System.Collections.Generic;');
    lines.push('using System.Linq;');
    lines.push('#nullable enable');
    lines.push('');
    lines.push('namespace MamGenerated');
    lines.push('{');

    lines.push(...this.helperTypes(indent));
    lines.push('');

    const demos: string[] = [];

    for (const mod of modules) {
      const ctx = generateModuleContext(mod, 'csharp')
        .split('\n')
        .map(l => (l === '' ? '' : pad + (l.startsWith('///') ? l : `/// ${l}`)));
      lines.push(...ctx);
      lines.push('');
      const result = this.compileModule(mod, indent, config);
      lines.push(...result.code);
      lines.push('');
      demos.push(...result.demo);
    }

    lines.push(pad + 'public static class Registry');
    lines.push(pad + '{');
    lines.push(pad + pad + 'public static readonly List<string> Modules = new()');
    lines.push(pad + pad + '{');
    for (const m of modules) lines.push(pad + pad + pad + `"${this.esc(`${m.name} (${m.moduleType})`)}",`);
    lines.push(pad + pad + '};');
    lines.push(pad + '}');
    lines.push('');

    lines.push(pad + 'public static class Program');
    lines.push(pad + '{');
    lines.push(pad + pad + 'public static void Main()');
    lines.push(pad + pad + '{');
    const stmtPad = pad + pad + pad;
    lines.push(stmtPad + 'Console.WriteLine("Registry: " + string.Join(", ", Registry.Modules));');
    for (const d of demos) lines.push(stmtPad + d);
    lines.push(pad + pad + '}');
    lines.push(pad + '}');
    lines.push('}');

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const lines: string[] = [];

    if (config.includeComments) {
      lines.push(`// Module: ${mod.name}`);
      lines.push(`// Type: ${mod.moduleType}`);
      if (mod.description) {
        for (const dl of mod.description.split('\n')) lines.push(`// ${dl}`);
      }
      lines.push('');
    }

    let code: string[];
    let demo: string[];

    switch (mod.moduleType) {
      case 'agent':
        ({ code, demo } = this.compileAgent(mod as unknown as V2AgentNode, indent, config));
        break;
      case 'tool':
        ({ code, demo } = this.compileTool(mod as unknown as V2ToolNode, indent, config));
        break;
      case 'memory':
        ({ code, demo } = this.compileMemory(mod as unknown as V2MemoryNode, indent, config));
        break;
      case 'workflow':
        ({ code, demo } = this.compileWorkflow(mod as unknown as V2WorkflowNode, indent, config));
        break;
      case 'team':
        ({ code, demo } = this.compileTeam(mod as unknown as V2TeamNode, indent, config));
        break;
      case 'policy':
        ({ code, demo } = this.compilePolicy(mod as unknown as V2PolicyNode, indent, config));
        break;
      case 'system':
        ({ code, demo } = this.compileSystem(mod as unknown as V2SystemNode, indent, config));
        break;
      default:
        ({ code, demo } = this.compileGeneric(mod, indent, config));
    }

    lines.push(...code);
    return { code: lines, demo };
  }

  private toPascalCase(name: string): string {
    const cleaned = name.replace(/[^a-zA-Z0-9]+/g, ' ').trim();
    if (!cleaned) return 'MamModule';
    let result = cleaned
      .split(/\s+/)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join('');
    if (/^[0-9]/.test(result)) result = `_${result}`;
    return result;
  }

  private className(name: string, suffix: string): string {
    const base = this.toPascalCase(name);
    return base.endsWith(suffix) ? base : `${base}${suffix}`;
  }

  private esc(s: string): string {
    return s
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\r/g, '')
      .replace(/\n/g, '\\n');
  }

  private newVar(): string {
    return `mod${++this.demoCounter}`;
  }

  private helperTypes(indent: number): string[] {
    const pad = ' '.repeat(indent);
    return [
      '// ===== Shared result, port and edge types =====',
      pad + 'public sealed class Port',
      pad + '{',
      pad + pad + 'public string Name { get; }',
      pad + pad + 'public string Type { get; }',
      pad + pad + 'public bool Required { get; }',
      pad + pad + 'public Port(string name, string type, bool required = false) { Name = name; Type = type; Required = required; }',
      pad + '}',
      '',
      pad + 'public sealed class Edge',
      pad + '{',
      pad + pad + 'public string Source { get; }',
      pad + pad + 'public string Target { get; }',
      pad + pad + 'public Edge(string source, string target) { Source = source; Target = target; }',
      pad + pad + 'public override string ToString() => Source + " -> " + Target;',
      pad + '}',
      '',
      pad + 'public sealed class ModuleResult',
      pad + '{',
      pad + pad + 'public bool Success { get; set; }',
      pad + pad + 'public Dictionary<string, object?> Outputs { get; set; } = new();',
      pad + pad + 'public string? Error { get; set; }',
      pad + pad + 'public static ModuleResult Ok(Dictionary<string, object?> outputs) => new ModuleResult { Success = true, Outputs = outputs };',
      pad + pad + 'public static ModuleResult Fail(string error) => new ModuleResult { Success = false, Error = error };',
      pad + pad + 'public override string ToString() => Success ? "OK: " + string.Join(", ", Outputs.Select(kv => kv.Key + "=" + (kv.Value ?? "<null>"))) : "ERROR: " + Error;',
      pad + '}',
      '',
      pad + 'public sealed class AgentResult',
      pad + '{',
      pad + pad + 'public string Task { get; set; } = "";',
      pad + pad + 'public string Result { get; set; } = "";',
      pad + pad + 'public string? Tool { get; set; }',
      pad + pad + 'public bool Success { get; set; }',
      pad + pad + 'public override string ToString() => "[" + (Success ? "ok" : "fail") + "] " + Task + " -> " + Result + (Tool == null ? "" : " (tool: " + Tool + ")");',
      pad + '}',
      '',
      pad + 'public sealed class ToolResult',
      pad + '{',
      pad + pad + 'public bool Success { get; set; }',
      pad + pad + 'public string Action { get; set; } = "";',
      pad + pad + 'public string Result { get; set; } = "";',
      pad + pad + 'public override string ToString() => Success ? "OK: " + Action + " -> " + Result : "FAIL: " + Action + " -> " + Result;',
      pad + '}',
      '',
      pad + 'public sealed class MemberResult',
      pad + '{',
      pad + pad + 'public string Member { get; set; } = "";',
      pad + pad + 'public bool Success { get; set; }',
      pad + pad + 'public string Result { get; set; } = "";',
      pad + pad + 'public override string ToString() => "[" + (Success ? "ok" : "fail") + "] " + Member + ": " + Result;',
      pad + '}',
      '',
      pad + 'public sealed class TeamResult',
      pad + '{',
      pad + pad + 'public string Task { get; set; } = "";',
      pad + pad + 'public List<MemberResult> Members { get; set; } = new();',
      pad + pad + 'public override string ToString() => "Team [" + Task + "]: " + string.Join(" | ", Members.Select(m => m.ToString()));',
      pad + '}',
      '',
      pad + 'public sealed class WorkflowResult',
      pad + '{',
      pad + pad + 'public bool Success { get; set; }',
      pad + pad + 'public List<string> Order { get; set; } = new();',
      pad + pad + 'public string? Error { get; set; }',
      pad + pad + 'public override string ToString() => Success ? "Workflow: " + string.Join(" -> ", Order) : "Workflow error: " + Error;',
      pad + '}',
      '',
      pad + 'public sealed class SystemResult',
      pad + '{',
      pad + pad + 'public bool Success { get; set; }',
      pad + pad + 'public List<string> Order { get; set; } = new();',
      pad + pad + 'public string? Error { get; set; }',
      pad + pad + 'public Dictionary<string, object?> Results { get; set; } = new();',
      pad + pad + 'public override string ToString() => Success ? "System run: " + string.Join(" -> ", Order) : "System error: " + Error;',
      pad + '}',
    ];
  }

  private compileAgent(mod: V2AgentNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const cls = this.className(mod.name, 'Agent');
    const demoVar = this.newVar();
    const memName = mod.memory?.name || mod.memory?.type || '';
    const memProp = memName ? `${pad}public string Memory { get; } = "${this.esc(memName)}";` : null;
    const memFrag = memName ? ` + " | logged to memory: " + Memory` : '';

    const code = [
      `public sealed class ${cls}`,
      `{`,
      `${pad}public string Name { get; } = "${this.esc(mod.name)}";`,
      `${pad}public string Role { get; } = "${this.esc(mod.role || '')}";`,
      `${pad}public string Goal { get; } = "${this.esc(mod.goal || '')}";`,
      `${pad}public List<string> Tools { get; } = new() { ${mod.tools?.map(t => `"${this.esc(t)}"`).join(', ') || ''} };`,
      `${pad}public List<string> Handoff { get; } = new() { ${mod.handoff?.map(h => `"${this.esc(h)}"`).join(', ') || ''} };`,
      ...(memProp ? [memProp] : []),
      '',
      `${pad}public AgentResult Execute(string task)`,
      `${pad}{`,
      `${pad}${pad}return new AgentResult`,
      `${pad}${pad}{`,
      `${pad}${pad}${pad}Success = true,`,
      `${pad}${pad}${pad}Task = task,`,
      `${pad}${pad}${pad}Result = "[" + Role + "] completed '" + task + "' toward goal: " + Goal${memFrag},`,
      `${pad}${pad}${pad}Tool = Tools.Count > 0 ? Tools[0] : null,`,
      `${pad}${pad}};`,
      `${pad}}`,
      `}`,
    ];

    const demo = [
      `var ${demoVar} = new ${cls}();`,
      `Console.WriteLine(${demoVar}.Execute("demo task").ToString());`,
    ];

    return { code, demo };
  }

  private compileTool(mod: V2ToolNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const cls = this.className(mod.name, 'Tool');
    const demoVar = this.newVar();
    const caps = mod.capabilities?.map(c => `"${this.esc(c)}"`).join(', ') || '';
    const firstCap = mod.capabilities && mod.capabilities.length > 0 ? mod.capabilities[0] : 'invoke';

    const code = [
      `public sealed class ${cls}`,
      `{`,
      `${pad}public string Name { get; } = "${this.esc(mod.name)}";`,
      `${pad}public string Provider { get; } = "${this.esc(mod.provider || '')}";`,
      `${pad}public List<string> Capabilities { get; } = new() { ${caps} };`,
      '',
      `${pad}public ToolResult Invoke(string action, Dictionary<string, object?>? parameters = null)`,
      `${pad}{`,
      `${pad}${pad}if (!Capabilities.Contains(action))`,
      `${pad}${pad}{`,
      `${pad}${pad}${pad}return new ToolResult`,
      `${pad}${pad}${pad}{`,
      `${pad}${pad}${pad}${pad}Success = false,`,
      `${pad}${pad}${pad}${pad}Action = action,`,
      `${pad}${pad}${pad}${pad}Result = "Action '" + action + "' is not a capability. Available: " + string.Join(", ", Capabilities),`,
      `${pad}${pad}${pad}};`,
      `${pad}${pad}}`,
      `${pad}${pad}return new ToolResult`,
      `${pad}${pad}{`,
      `${pad}${pad}${pad}Success = true,`,
      `${pad}${pad}${pad}Action = action,`,
      `${pad}${pad}${pad}Result = "[" + Provider + "] invoked '" + action + "' with " + (parameters == null ? 0 : parameters.Count) + " parameter(s)",`,
      `${pad}${pad}};`,
      `${pad}}`,
      `}`,
    ];

    const demo = [
      `var ${demoVar} = new ${cls}();`,
      `Console.WriteLine(${demoVar}.Invoke("${this.esc(firstCap)}", null).ToString());`,
      `Console.WriteLine(${demoVar}.Invoke("not-a-capability", null).ToString());`,
    ];

    return { code, demo };
  }

  private compileMemory(mod: V2MemoryNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const cls = this.className(mod.name, 'Memory');
    const demoVar = this.newVar();

    const code = [
      `public sealed class ${cls}`,
      `{`,
      `${pad}public string Name { get; } = "${this.esc(mod.name)}";`,
      `${pad}public string Format { get; } = "${this.esc(mod.format || 'key-value')}";`,
      `${pad}public string Backend { get; } = "${this.esc(mod.backend || 'local')}";`,
      `${pad}public string Scope { get; } = "${this.esc(mod.scope || 'module')}";`,
      `${pad}private readonly Dictionary<string, object?> _store = new();`,
      '',
      `${pad}public void Store(string key, object? value) { _store[key] = value; }`,
      `${pad}public object? Retrieve(string key) { return _store.TryGetValue(key, out var v) ? v : null; }`,
      `${pad}public bool Delete(string key) { return _store.Remove(key); }`,
      `${pad}public List<string> Search(string term) { return _store.Keys.Where(k => k.IndexOf(term, StringComparison.OrdinalIgnoreCase) >= 0).ToList(); }`,
      `${pad}public int Count => _store.Count;`,
      `}`,
    ];

    const demo = [
      `var ${demoVar} = new ${cls}();`,
      `${demoVar}.Store("topic", "MAM compiler");`,
      `${demoVar}.Store("lang", "C#");`,
      `Console.WriteLine(${demoVar}.Count + " entr" + (${demoVar}.Count == 1 ? "y" : "ies") + " stored");`,
      `Console.WriteLine("retrieve(topic) = " + ${demoVar}.Retrieve("topic"));`,
      `Console.WriteLine("search(compiler) -> " + ${demoVar}.Search("compiler").Count + " match(es)");`,
      `Console.WriteLine("delete(lang) = " + ${demoVar}.Delete("lang"));`,
    ];

    return { code, demo };
  }

  private compileWorkflow(mod: V2WorkflowNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const cls = this.className(mod.name, 'Workflow');
    const demoVar = this.newVar();
    const steps = mod.steps?.map(s => `"${this.esc(s.name)}"`).join(', ') || '';
    const edges = mod.edges?.map(e => `new Edge("${this.esc(e.source)}", "${this.esc(e.target)}")`).join(', ') || '';

    const code = [
      `public sealed class ${cls}`,
      `{`,
      `${pad}public List<string> Steps { get; } = new() { ${steps} };`,
      `${pad}public List<Edge> Edges { get; } = new() { ${edges} };`,
      '',
      `${pad}public WorkflowResult Run(Dictionary<string, object?>? inputs = null)`,
      `${pad}{`,
      `${pad}${pad}var indegree = new Dictionary<string, int>();`,
      `${pad}${pad}var adj = new Dictionary<string, List<string>>();`,
      `${pad}${pad}foreach (var s in Steps) { indegree[s] = 0; adj[s] = new List<string>(); }`,
      `${pad}${pad}foreach (var e in Edges)`,
      `${pad}${pad}{`,
      `${pad}${pad}${pad}if (!adj.ContainsKey(e.Source) || !indegree.ContainsKey(e.Target)) continue;`,
      `${pad}${pad}${pad}adj[e.Source].Add(e.Target);`,
      `${pad}${pad}${pad}indegree[e.Target] = indegree[e.Target] + 1;`,
      `${pad}${pad}}`,
      `${pad}${pad}var queue = new Queue<string>(Steps.Where(s => indegree[s] == 0));`,
      `${pad}${pad}var order = new List<string>();`,
      `${pad}${pad}while (queue.Count > 0)`,
      `${pad}${pad}{`,
      `${pad}${pad}${pad}var u = queue.Dequeue();`,
      `${pad}${pad}${pad}order.Add(u);`,
      `${pad}${pad}${pad}foreach (var v in adj[u]) { indegree[v] = indegree[v] - 1; if (indegree[v] == 0) queue.Enqueue(v); }`,
      `${pad}${pad}}`,
      `${pad}${pad}if (order.Count != Steps.Count)`,
      `${pad}${pad}${pad}return new WorkflowResult { Success = false, Error = "Cycle detected in workflow edges" };`,
      `${pad}${pad}return new WorkflowResult { Success = true, Order = order };`,
      `${pad}}`,
      `}`,
    ];

    const demo = [
      `var ${demoVar} = new ${cls}();`,
      `Console.WriteLine(${demoVar}.Run(null).ToString());`,
    ];

    return { code, demo };
  }

  private compileTeam(mod: V2TeamNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const cls = this.className(mod.name, 'Team');
    const demoVar = this.newVar();
    const members = mod.members?.map(m => `"${this.esc(m)}"`).join(', ') || '';

    const code = [
      `public sealed class ${cls}`,
      `{`,
      `${pad}public List<string> Members { get; } = new() { ${members} };`,
      '',
      `${pad}public TeamResult Coordinate(string task)`,
      `${pad}{`,
      `${pad}${pad}var members = new List<MemberResult>();`,
      `${pad}${pad}foreach (var m in Members)`,
      `${pad}${pad}${pad}members.Add(new MemberResult { Member = m, Success = true, Result = "completed '" + task + "'" });`,
      `${pad}${pad}return new TeamResult { Task = task, Members = members };`,
      `${pad}}`,
      `}`,
    ];

    const demo = [
      `var ${demoVar} = new ${cls}();`,
      `Console.WriteLine(${demoVar}.Coordinate("demo task").ToString());`,
    ];

    return { code, demo };
  }

  private compilePolicy(mod: V2PolicyNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const cls = this.className(mod.name, 'Policy');
    const demoVar = this.newVar();
    const allow = mod.allow?.map(a => `"${this.esc(a)}"`).join(', ') || '';
    const deny = mod.deny?.map(d => `"${this.esc(d)}"`).join(', ') || '';
    const allowSample = mod.allow && mod.allow.length > 0 ? mod.allow[0] : 'read';
    const denySample = mod.deny && mod.deny.length > 0 ? mod.deny[0] : 'blocked';

    const code = [
      `public sealed class ${cls}`,
      `{`,
      `${pad}public List<string> Allow { get; } = new() { ${allow} };`,
      `${pad}public List<string> Deny { get; } = new() { ${deny} };`,
      '',
      `${pad}public bool Check(string action)`,
      `${pad}{`,
      `${pad}${pad}if (Deny.Contains(action)) return false;`,
      `${pad}${pad}if (Allow.Contains(action)) return true;`,
      `${pad}${pad}return false;`,
      `${pad}}`,
      `}`,
    ];

    const demo = [
      `var ${demoVar} = new ${cls}();`,
      `Console.WriteLine("check('${this.esc(allowSample)}') = " + ${demoVar}.Check("${this.esc(allowSample)}"));`,
      `Console.WriteLine("check('${this.esc(denySample)}') = " + ${demoVar}.Check("${this.esc(denySample)}"));`,
      `Console.WriteLine("check('anything') = " + ${demoVar}.Check("anything"));`,
    ];

    return { code, demo };
  }

  private compileSystem(mod: V2SystemNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const cls = this.className(mod.name, 'System');
    const demoVar = this.newVar();
    const agents = mod.agents?.map(a => `"${this.esc(a)}"`).join(', ') || '';
    const modules = mod.modules?.map(m => `"${this.esc(m)}"`).join(', ') || '';
    const edges = mod.edges?.map(e => `new Edge("${this.esc(e.source)}", "${this.esc(e.target)}")`).join(', ') || '';

    const code = [
      `public sealed class ${cls}`,
      `{`,
      `${pad}public List<string> Agents { get; } = new() { ${agents} };`,
      `${pad}public List<string> Modules { get; } = new() { ${modules} };`,
      `${pad}public List<Edge> Edges { get; } = new() { ${edges} };`,
      '',
      `${pad}public SystemResult Run()`,
      `${pad}{`,
      `${pad}${pad}var nodes = Agents.Concat(Modules).ToList();`,
      `${pad}${pad}var indegree = new Dictionary<string, int>();`,
      `${pad}${pad}var adj = new Dictionary<string, List<string>>();`,
      `${pad}${pad}foreach (var n in nodes) { indegree[n] = 0; adj[n] = new List<string>(); }`,
      `${pad}${pad}foreach (var e in Edges)`,
      `${pad}${pad}{`,
      `${pad}${pad}${pad}if (!adj.ContainsKey(e.Source) || !indegree.ContainsKey(e.Target)) continue;`,
      `${pad}${pad}${pad}adj[e.Source].Add(e.Target);`,
      `${pad}${pad}${pad}indegree[e.Target] = indegree[e.Target] + 1;`,
      `${pad}${pad}}`,
      `${pad}${pad}var queue = new Queue<string>(nodes.Where(n => indegree[n] == 0));`,
      `${pad}${pad}var order = new List<string>();`,
      `${pad}${pad}while (queue.Count > 0)`,
      `${pad}${pad}{`,
      `${pad}${pad}${pad}var u = queue.Dequeue();`,
      `${pad}${pad}${pad}order.Add(u);`,
      `${pad}${pad}${pad}foreach (var v in adj[u]) { indegree[v] = indegree[v] - 1; if (indegree[v] == 0) queue.Enqueue(v); }`,
      `${pad}${pad}}`,
      `${pad}${pad}var results = new Dictionary<string, object?>();`,
      `${pad}${pad}foreach (var n in order) results[n] = "[" + n + "] executed";`,
      `${pad}${pad}if (order.Count != nodes.Count)`,
      `${pad}${pad}${pad}return new SystemResult { Success = false, Error = "Cycle detected in system graph", Results = results };`,
      `${pad}${pad}return new SystemResult { Success = true, Order = order, Results = results };`,
      `${pad}}`,
      `}`,
    ];

    const demo = [
      `var ${demoVar} = new ${cls}();`,
      `Console.WriteLine(${demoVar}.Run().ToString());`,
    ];

    return { code, demo };
  }

  private compileGeneric(mod: V2ModuleNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const cls = this.className(mod.name, 'Module');
    const demoVar = this.newVar();
    const inputs = mod.inputs?.map(i => `new Port("${this.esc(i.name)}", "${this.esc(i.type || 'unknown')}", ${i.required ? 'true' : 'false'})`).join(', ') || '';
    const outputs = mod.outputs?.map(o => `new Port("${this.esc(o.name)}", "${this.esc(o.type || 'unknown')}")`).join(', ') || '';
    const caps = mod.capabilities?.map(c => `"${this.esc(c)}"`).join(', ') || '';
    const required = mod.inputs?.filter(i => i.required) || [];

    const code = [
      `public sealed class ${cls}`,
      `{`,
      `${pad}public string Name { get; } = "${this.esc(mod.name)}";`,
      `${pad}public string Description { get; } = "${this.esc(mod.description || '')}";`,
      `${pad}public List<Port> Inputs { get; } = new() { ${inputs} };`,
      `${pad}public List<Port> Outputs { get; } = new() { ${outputs} };`,
      `${pad}public List<string> Capabilities { get; } = new() { ${caps} };`,
      '',
      `${pad}public ModuleResult Run(Dictionary<string, object?> inputs)`,
      `${pad}{`,
      `${pad}${pad}var missing = Inputs.Where(i => i.Required && !inputs.ContainsKey(i.Name)).Select(i => i.Name).ToList();`,
      `${pad}${pad}if (missing.Count > 0) return ModuleResult.Fail("Missing required inputs: " + string.Join(", ", missing));`,
      `${pad}${pad}var outputs = new Dictionary<string, object?>();`,
      `${pad}${pad}foreach (var o in Outputs) outputs[o.Name] = null;`,
      `${pad}${pad}foreach (var kv in inputs) { if (!outputs.ContainsKey(kv.Key)) outputs[kv.Key] = kv.Value; }`,
      `${pad}${pad}return ModuleResult.Ok(outputs);`,
      `${pad}}`,
      `}`,
    ];

    const entries = required.map(i => `{ "${this.esc(i.name)}", "demo" }`).join(', ');
    const demo = [
      `var ${demoVar} = new ${cls}();`,
      `var ${demoVar}_inputs = new Dictionary<string, object?> { ${entries} };`,
      `Console.WriteLine(${demoVar}.Run(${demoVar}_inputs).ToString());`,
    ];

    return { code, demo };
  }
}