/**
 * Docker Target
 * 
 * Compiles MAM AST to Dockerfile and docker-compose.yml.
 */

import { V2ModuleNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';

export class DockerTarget implements CompileTargetHandler {
  name = 'docker';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];

    lines.push('# Generated by MAM Compiler');
    lines.push('# Target: Docker');
    lines.push('');
    lines.push('FROM python:3.11-slim');
    lines.push('');
    lines.push('WORKDIR /app');
    lines.push('');

    // Collect dependencies
    const dependencies = new Set<string>();
    for (const mod of modules) {
      if (mod.requires) {
        for (const req of mod.requires) {
          dependencies.add(req);
        }
      }
    }

    if (dependencies.size > 0) {
      lines.push('# Dependencies');
      lines.push('COPY requirements.txt .');
      lines.push('RUN pip install -r requirements.txt');
      lines.push('');
    }

    lines.push('COPY . .');
    lines.push('');

    // Add ports if network permissions
    for (const mod of modules) {
      if (mod.permissions?.network === 'internet') {
        lines.push('EXPOSE 8080');
        break;
      }
    }

    lines.push('CMD ["python", "main.py"]');

    return lines.join('\n');
  }
}