/**
 * Google Gemini SDK Target
 *
 * Compiles MAM AST to Python code using google.generativeai.
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2MemoryNode, V2WorkflowNode, V2TeamNode, V2PolicyNode, V2SystemNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';

export class GeminiTarget implements CompileTargetHandler {
  name = 'gemini';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];
    const indent = config.indent || 4;

    lines.push('"""');
    lines.push('Generated by MAM Compiler');
    lines.push('Target: Google Gemini SDK');
    lines.push('"""');
    lines.push('');
    lines.push('import google.generativeai as genai');
    lines.push('');

    for (const mod of modules) {
      lines.push(...this.compileModule(mod, indent, config));
      lines.push('');
    }

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];
    const pad = ' '.repeat(indent);

    if (config.includeComments) {
      lines.push(`# Module: ${mod.name}`);
      lines.push(`# Type: ${mod.moduleType}`);
      if (mod.description) lines.push(`# ${mod.description}`);
      lines.push('');
    }

    switch (mod.moduleType) {
      case 'agent':
        lines.push(...this.compileAgent(mod as unknown as V2AgentNode, indent, config));
        break;
      case 'tool':
        lines.push(...this.compileTool(mod as unknown as V2ToolNode, indent, config));
        break;
      case 'memory':
        lines.push(...this.compileMemory(mod as unknown as V2MemoryNode, indent, config));
        break;
      case 'workflow':
        lines.push(...this.compileWorkflow(mod as unknown as V2WorkflowNode, indent, config));
        break;
      case 'team':
        lines.push(...this.compileTeam(mod as unknown as V2TeamNode, indent, config));
        break;
      case 'policy':
        lines.push(...this.compilePolicy(mod as unknown as V2PolicyNode, indent, config));
        break;
      case 'system':
        lines.push(...this.compileSystem(mod as unknown as V2SystemNode, indent, config));
        break;
      default:
        lines.push(...this.compileGeneric(mod, indent, config));
    }

    return lines;
  }

  private compileAgent(mod: V2AgentNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = mod.name.replace(/[^a-zA-Z0-9_]/g, '_');

    return [
      `class ${className}:`,
      `${pad}"""Gemini agent: ${mod.goal || mod.role || mod.name}"""`,
      '',
      `${pad}def __init__(self, api_key: str):`,
      `${pad}${pad}genai.configure(api_key=api_key)`,
      `${pad}${pad}self.model = genai.GenerativeModel('gemini-pro')`,
      `${pad}${pad}self.chat = self.model.start_chat(history=[])`,
      `${pad}${pad}self.role = "${mod.role || ''}"`,
      `${pad}${pad}self.goal = "${mod.goal || ''}"`,
      `${pad}${pad}self.tools = ${JSON.stringify(mod.tools || [])}`,
      `${pad}${pad}self.handoff = ${JSON.stringify(mod.handoff || [])}`,
      '',
      `${pad}def execute(self, task: str) -> str:`,
      `${pad}${pad}"""Execute the agent's task using Gemini."""`,
      `${pad}${pad}response = self.chat.send_message(task)`,
      `${pad}${pad}return response.text`,
      '',
    ];
  }

  private compileTool(mod: V2ToolNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = mod.name.replace(/[^a-zA-Z0-9_]/g, '_');

    return [
      `class ${className}:`,
      `${pad}"""Gemini tool: ${mod.provider}"""`,
      '',
      `${pad}def __init__(self, api_key: str):`,
      `${pad}${pad}genai.configure(api_key=api_key)`,
      `${pad}${pad}self.provider = "${mod.provider}"`,
      `${pad}${pad}self.capabilities = ${JSON.stringify(mod.capabilities || [])}`,
      '',
      `${pad}def execute(self, action: str, **kwargs) -> str:`,
      `${pad}${pad}"""Execute a tool action via Gemini function calling."""`,
      `${pad}${pad}raise NotImplementedError`,
      '',
    ];
  }

  private compileMemory(mod: V2MemoryNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = mod.name.replace(/[^a-zA-Z0-9_]/g, '_');

    return [
      `class ${className}:`,
      `${pad}"""Gemini memory: ${mod.format} / ${mod.backend}"""`,
      '',
      `${pad}def __init__(self):`,
      `${pad}${pad}self.format = "${mod.format}"`,
      `${pad}${pad}self.backend = "${mod.backend}"`,
      `${pad}${pad}self.scope = "${mod.scope}"`,
      `${pad}${pad}self._store = {}`,
      '',
      `${pad}def store(self, key: str, value: str):`,
      `${pad}${pad}self._store[key] = value`,
      '',
      `${pad}def retrieve(self, key: str) -> str:`,
      `${pad}${pad}return self._store.get(key, "")`,
      '',
    ];
  }

  private compileWorkflow(mod: V2WorkflowNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = mod.name.replace(/[^a-zA-Z0-9_]/g, '_');

    return [
      `class ${className}:`,
      `${pad}"""Gemini workflow"""`,
      '',
      `${pad}STEPS = ${JSON.stringify(mod.steps?.map(s => s.name) || [])}`,
      `${pad}EDGES = ${JSON.stringify(mod.edges?.map(e => [e.source, e.target]) || [])}`,
      '',
      `${pad}def execute(self):`,
      `${pad}${pad}for step in self.STEPS:`,
      `${pad}${pad}${pad}print(f"Executing step: {step}")`,
      '',
    ];
  }

  private compileTeam(mod: V2TeamNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = mod.name.replace(/[^a-zA-Z0-9_]/g, '_');

    return [
      `class ${className}:`,
      `${pad}"""Gemini team"""`,
      '',
      `${pad}MEMBERS = ${JSON.stringify(mod.members || [])}`,
      '',
      `${pad}def coordinate(self):`,
      `${pad}${pad}raise NotImplementedError`,
      '',
    ];
  }

  private compilePolicy(mod: V2PolicyNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = mod.name.replace(/[^a-zA-Z0-9_]/g, '_');

    return [
      `class ${className}:`,
      `${pad}"""Gemini policy"""`,
      '',
      `${pad}ALLOW = ${JSON.stringify(mod.allow || [])}`,
      `${pad}DENY = ${JSON.stringify(mod.deny || [])}`,
      '',
      `${pad}def check(self, action: str) -> bool:`,
      `${pad}${pad}if action in self.DENY: return False`,
      `${pad}${pad}if action in self.ALLOW: return True`,
      `${pad}${pad}return False`,
      '',
    ];
  }

  private compileSystem(mod: V2SystemNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = mod.name.replace(/[^a-zA-Z0-9_]/g, '_');

    return [
      `class ${className}:`,
      `${pad}"""Gemini system"""`,
      '',
      `${pad}AGENTS = ${JSON.stringify(mod.agents || [])}`,
      `${pad}MODULES = ${JSON.stringify(mod.modules || [])}`,
      `${pad}EDGES = ${JSON.stringify(mod.edges?.map(e => [e.source, e.target]) || [])}`,
      '',
      `${pad}def run(self):`,
      `${pad}${pad}raise NotImplementedError`,
      '',
    ];
  }

  private compileGeneric(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = mod.name.replace(/[^a-zA-Z0-9_]/g, '_');

    return [
      `class ${className}:`,
      `${pad}"""${mod.description || mod.name}"""`,
      '',
      `${pad}def __init__(self):`,
      `${pad}${pad}pass`,
      '',
    ];
  }
}
