/**
 * Go Target
 * 
 * Compiles MAM AST to Go code.
 */

import { V2ModuleNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';

export class GoTarget implements CompileTargetHandler {
  name = 'go';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];

    lines.push('// Generated by MAM Compiler');
    lines.push('// Target: Go');
    lines.push('');
    lines.push('package main');
    lines.push('');
    lines.push('import (');
    lines.push('\t"fmt"');
    lines.push(')');
    lines.push('');

    for (const mod of modules) {
      lines.push(...this.compileModule(mod, config));
      lines.push('');
    }

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode, config: CompilerConfig): string[] {
    const lines: string[] = [];
    const structName = this.toPascalCase(mod.name);

    lines.push(`// ${structName} represents a ${mod.moduleType} module`);
    lines.push(`type ${structName} struct {`);

    if (mod.role) lines.push(`\tRole string`);
    if (mod.goal) lines.push(`\tGoal string`);
    if (mod.tools) lines.push(`\tTools []string`);
    if (mod.handoff) lines.push(`\tHandoff []string`);
    if (mod.members) lines.push(`\tMembers []string`);
    if (mod.steps) lines.push(`\tSteps []string`);
    if (mod.allow) lines.push(`\tAllow []string`);
    if (mod.deny) lines.push(`\tDeny []string`);

    lines.push(`}`);
    lines.push('');

    lines.push(`// New${structName} creates a new ${structName}`);
    lines.push(`func New${structName}() *${structName} {`);
    lines.push(`\treturn &${structName}{`);

    if (mod.role) lines.push(`\t\tRole: "${mod.role}",`);
    if (mod.goal) lines.push(`\t\tGoal: "${mod.goal}",`);
    if (mod.tools) lines.push(`\t\tTools: ${JSON.stringify(mod.tools)},`);
    if (mod.handoff) lines.push(`\t\tHandoff: ${JSON.stringify(mod.handoff)},`);

    lines.push(`\t}`);
    lines.push(`}`);
    lines.push('');

    lines.push(`// Execute runs the module`);
    lines.push(`func (m *${structName}) Execute(task string) error {`);
    lines.push(`\treturn fmt.Errorf("not implemented")`);
    lines.push(`}`);

    return lines;
  }

  private toPascalCase(str: string): string {
    return str
      .replace(/[^a-zA-Z0-9\s]/g, '')
      .split(/\s+/)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
  }
}