/**
 * Java Target
 *
 * Compiles MAM AST to Java code.
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2MemoryNode, V2WorkflowNode, V2TeamNode, V2PolicyNode, V2SystemNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';
import { generateModuleContext } from '../context.js';

export class JavaTarget implements CompileTargetHandler {
  name = 'java';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];
    const indent = config.indent || 4;

    lines.push('// Generated by MAM Compiler');
    lines.push('// Target: Java');
    lines.push('');
    lines.push('import java.util.*;');
    lines.push('');

    for (const mod of modules) {
      lines.push(generateModuleContext(mod, 'java'));
      lines.push('');
      lines.push(...this.compileModule(mod, indent, config));
      lines.push('');
    }

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];
    const pad = ' '.repeat(indent);

    if (config.includeComments) {
      lines.push(`// Module: ${mod.name}`);
      lines.push(`// Type: ${mod.moduleType}`);
      if (mod.description) lines.push(`// ${mod.description}`);
      lines.push('');
    }

    switch (mod.moduleType) {
      case 'agent':
        lines.push(...this.compileAgent(mod as unknown as V2AgentNode, indent, config));
        break;
      case 'tool':
        lines.push(...this.compileTool(mod as unknown as V2ToolNode, indent, config));
        break;
      case 'memory':
        lines.push(...this.compileMemory(mod as unknown as V2MemoryNode, indent, config));
        break;
      case 'workflow':
        lines.push(...this.compileWorkflow(mod as unknown as V2WorkflowNode, indent, config));
        break;
      case 'team':
        lines.push(...this.compileTeam(mod as unknown as V2TeamNode, indent, config));
        break;
      case 'policy':
        lines.push(...this.compilePolicy(mod as unknown as V2PolicyNode, indent, config));
        break;
      case 'system':
        lines.push(...this.compileSystem(mod as unknown as V2SystemNode, indent, config));
        break;
      default:
        lines.push(...this.compileGeneric(mod, indent, config));
    }

    return lines;
  }

  private toPascalCase(name: string): string {
    return name.replace(/(^|[-_])(\w)/g, (_, __, c) => c.toUpperCase()).replace(/[^a-zA-Z0-9]/g, '');
  }

  private compileAgent(mod: V2AgentNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = this.toPascalCase(mod.name);

    return [
      `public class ${className}Agent {`,
      `${pad}private String role = "${mod.role || ''}";`,
      `${pad}private String goal = "${mod.goal || ''}";`,
      `${pad}private List<String> tools = Arrays.asList(${mod.tools?.map(t => `"${t}"`).join(', ') || ''});`,
      `${pad}private List<String> handoff = Arrays.asList(${mod.handoff?.map(h => `"${h}"`).join(', ') || ''});`,
      '',
      `${pad}public String execute(String task) throws Exception {`,
      `${pad}${pad}throw new Exception("Not implemented");`,
      `${pad}}`,
      `}`,
    ];
  }

  private compileTool(mod: V2ToolNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = this.toPascalCase(mod.name);

    return [
      `public class ${className}Tool {`,
      `${pad}private String provider = "${mod.provider}";`,
      `${pad}private List<String> capabilities = Arrays.asList(${mod.capabilities?.map(c => `"${c}"`).join(', ') || ''});`,
      '',
      `${pad}public String execute(String action, Map<String, Object> kwargs) throws Exception {`,
      `${pad}${pad}throw new Exception("Not implemented");`,
      `${pad}}`,
      `}`,
    ];
  }

  private compileMemory(mod: V2MemoryNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = this.toPascalCase(mod.name);

    return [
      `public class ${className}Memory {`,
      `${pad}private String format = "${mod.format}";`,
      `${pad}private String backend = "${mod.backend}";`,
      `${pad}private String scope = "${mod.scope}";`,
      '',
      `${pad}public void store(String key, Object value) throws Exception {`,
      `${pad}${pad}throw new Exception("Not implemented");`,
      `${pad}}`,
      '',
      `${pad}public Object retrieve(String key) throws Exception {`,
      `${pad}${pad}throw new Exception("Not implemented");`,
      `${pad}}`,
      `}`,
    ];
  }

  private compileWorkflow(mod: V2WorkflowNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = this.toPascalCase(mod.name);

    return [
      `public class ${className}Workflow {`,
      `${pad}private List<String> steps = Arrays.asList(${mod.steps?.map(s => `"${s.name}"`).join(', ') || ''});`,
      `${pad}private List<String[]> edges = Arrays.asList(${mod.edges?.map(e => `new String[]{"${e.source}", "${e.target}"}`).join(', ') || ''});`,
      '',
      `${pad}public void execute() {`,
      `${pad}${pad}for (String step : steps) {`,
      `${pad}${pad}${pad}System.out.println("Executing step: " + step);`,
      `${pad}${pad}}`,
      `${pad}}`,
      `}`,
    ];
  }

  private compileTeam(mod: V2TeamNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = this.toPascalCase(mod.name);

    return [
      `public class ${className}Team {`,
      `${pad}private List<String> members = Arrays.asList(${mod.members?.map(m => `"${m}"`).join(', ') || ''});`,
      '',
      `${pad}public void coordinate() throws Exception {`,
      `${pad}${pad}throw new Exception("Not implemented");`,
      `${pad}}`,
      `}`,
    ];
  }

  private compilePolicy(mod: V2PolicyNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = this.toPascalCase(mod.name);

    return [
      `public class ${className}Policy {`,
      `${pad}private List<String> allow = Arrays.asList(${mod.allow?.map(a => `"${a}"`).join(', ') || ''});`,
      `${pad}private List<String> deny = Arrays.asList(${mod.deny?.map(d => `"${d}"`).join(', ') || ''});`,
      '',
      `${pad}public boolean check(String action) {`,
      `${pad}${pad}if (deny.contains(action)) return false;`,
      `${pad}${pad}if (allow.contains(action)) return true;`,
      `${pad}${pad}return false;`,
      `${pad}}`,
      `}`,
    ];
  }

  private compileSystem(mod: V2SystemNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = this.toPascalCase(mod.name);

    return [
      `public class ${className}System {`,
      `${pad}private List<String> agents = Arrays.asList(${mod.agents?.map(a => `"${a}"`).join(', ') || ''});`,
      `${pad}private List<String> modules = Arrays.asList(${mod.modules?.map(m => `"${m}"`).join(', ') || ''});`,
      `${pad}private List<String[]> edges = Arrays.asList(${mod.edges?.map(e => `new String[]{"${e.source}", "${e.target}"}`).join(', ') || ''});`,
      '',
      `${pad}public void run() throws Exception {`,
      `${pad}${pad}throw new Exception("Not implemented");`,
      `${pad}}`,
      `}`,
    ];
  }

  private compileGeneric(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = this.toPascalCase(mod.name);

    return [
      `public class ${className}Module {`,
      `${pad}// ${mod.description || mod.name}`,
      `}`,
    ];
  }
}
