/**
 * Java Target
 *
 * Compiles MAM AST to Java code.
 * Emits a single, runnable file: `package mam.generated;` with a public
 * `MAMMain` class containing a `main`, shared result types, and one public
 * static class per module with concrete behaviour.
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2MemoryNode, V2WorkflowNode, V2TeamNode, V2PolicyNode, V2SystemNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';
import { generateModuleContext } from '../context.js';

export class JavaTarget implements CompileTargetHandler {
  name = 'java';

  private demoCounter = 0;

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];
    const indent = config.indent || 4;
    const pad = ' '.repeat(indent);
    this.demoCounter = 0;

    lines.push('// Generated by MAM Compiler');
    lines.push('// Target: Java');
    lines.push('//');
    lines.push('// Compile: javac -d out MAMMain.java && java -cp out com.mam.generated.MAMMain');
    lines.push('');
    lines.push('package com.mam.generated;');
    lines.push('');
    lines.push('import java.util.*;');
    lines.push('');
    lines.push('public class MAMMain {');

    // --- main ---
    lines.push(pad + 'public static void main(String[] args) {');
    const stmtPad = pad + pad;
    const demos: string[] = [];
    for (const mod of modules) {
      const result = this.compileModule(mod, indent, config);
      demos.push(...result.demo);
    }
    lines.push(stmtPad + 'System.out.println("Registry: " + String.join(", ", Registry.modules));');
    for (const d of demos) lines.push(stmtPad + d);
    lines.push(pad + '}');
    lines.push('');

    // --- helper result types (public static, shared) ---
    lines.push(...this.helperTypes(indent));
    lines.push('');

    // --- module classes ---
    for (const mod of modules) {
      const ctx = generateModuleContext(mod, 'java')
        .split('\n')
        .map(l => (l === '' ? '' : pad + (l.startsWith('//') ? l : `// ${l}`)));
      lines.push(...ctx);
      lines.push('');
      const result = this.compileModule(mod, indent, config);
      lines.push(...result.code);
      lines.push('');
    }

    // --- registry ---
    lines.push(pad + 'public static class Registry {');
    lines.push(pad + pad + 'public static final List<String> modules = Arrays.asList(');
    const registryPad = pad + pad + pad;
    lines.push(modules.map(m => `${registryPad}"${this.esc(`${m.name} (${m.moduleType})`)}"`).join(',\n'));
    lines.push(pad + pad + ');');
    lines.push(pad + '}');

    lines.push('}');

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const lines: string[] = [];

    if (config.includeComments) {
      lines.push(`// Module: ${mod.name}`);
      lines.push(`// Type: ${mod.moduleType}`);
      if (mod.description) {
        for (const dl of mod.description.split('\n')) lines.push(`// ${dl}`);
      }
      lines.push('');
    }

    let code: string[];
    let demo: string[];

    switch (mod.moduleType) {
      case 'agent':
        ({ code, demo } = this.compileAgent(mod as unknown as V2AgentNode, indent, config));
        break;
      case 'tool':
        ({ code, demo } = this.compileTool(mod as unknown as V2ToolNode, indent, config));
        break;
      case 'memory':
        ({ code, demo } = this.compileMemory(mod as unknown as V2MemoryNode, indent, config));
        break;
      case 'workflow':
        ({ code, demo } = this.compileWorkflow(mod as unknown as V2WorkflowNode, indent, config));
        break;
      case 'team':
        ({ code, demo } = this.compileTeam(mod as unknown as V2TeamNode, indent, config));
        break;
      case 'policy':
        ({ code, demo } = this.compilePolicy(mod as unknown as V2PolicyNode, indent, config));
        break;
      case 'system':
        ({ code, demo } = this.compileSystem(mod as unknown as V2SystemNode, indent, config));
        break;
      default:
        ({ code, demo } = this.compileGeneric(mod, indent, config));
    }

    lines.push(...code);
    return { code: lines, demo };
  }

  private toPascalCase(name: string): string {
    const cleaned = name.replace(/[^a-zA-Z0-9]+/g, ' ').trim();
    if (!cleaned) return 'MamModule';
    let result = cleaned
      .split(/\s+/)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join('');
    if (/^[0-9]/.test(result)) result = `_${result}`;
    return result;
  }

  private className(name: string, suffix: string): string {
    const base = this.toPascalCase(name);
    return base.endsWith(suffix) ? base : `${base}${suffix}`;
  }

  private esc(s: string): string {
    return s
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\r/g, '')
      .replace(/\n/g, '\\n');
  }

  private newVar(): string {
    return `mod${++this.demoCounter}`;
  }

  private helperTypes(indent: number): string[] {
    const pad = ' '.repeat(indent);
    const m = pad + pad;
    return [
      pad + '// ===== Shared result, port and edge types =====',
      pad + 'public static class Port {',
      m + 'public final String name;',
      m + 'public final String type;',
      m + 'public final boolean required;',
      m + 'public Port(String name, String type, boolean required) { this.name = name; this.type = type; this.required = required; }',
      pad + '}',
      '',
      pad + 'public static class Edge {',
      m + 'public final String source;',
      m + 'public final String target;',
      m + 'public Edge(String source, String target) { this.source = source; this.target = target; }',
      m + 'public String toString() { return source + " -> " + target; }',
      pad + '}',
      '',
      pad + 'public static class ModuleResult {',
      m + 'public final boolean success;',
      m + 'public final String error;',
      m + 'public final Map<String, Object> outputs;',
      m + 'public ModuleResult(boolean success, String error, Map<String, Object> outputs) { this.success = success; this.error = error; this.outputs = outputs; }',
      m + 'public static ModuleResult ok(Map<String, Object> outputs) { return new ModuleResult(true, null, outputs); }',
      m + 'public static ModuleResult fail(String error) { return new ModuleResult(false, error, new LinkedHashMap<>()); }',
      m + 'public String toString() {',
      m + m + 'if (!success) return "ERROR: " + error;',
      m + m + 'StringBuilder sb = new StringBuilder("OK: ");',
      m + m + 'for (Map.Entry<String, Object> e : outputs.entrySet()) { if (sb.length() > 4) sb.append(", "); sb.append(e.getKey()).append("=").append(e.getValue()); }',
      m + m + 'return sb.toString();',
      m + '}',
      pad + '}',
      '',
      pad + 'public static class AgentResult {',
      m + 'public final boolean success;',
      m + 'public final String task;',
      m + 'public final String result;',
      m + 'public final String tool;',
      m + 'public AgentResult(boolean success, String task, String result, String tool) { this.success = success; this.task = task; this.result = result; this.tool = tool; }',
      m + 'public String toString() { return "[" + (success ? "ok" : "fail") + "] " + task + " -> " + result + (tool == null ? "" : " (tool: " + tool + ")"); }',
      pad + '}',
      '',
      pad + 'public static class ToolResult {',
      m + 'public final boolean success;',
      m + 'public final String action;',
      m + 'public final String result;',
      m + 'public ToolResult(boolean success, String action, String result) { this.success = success; this.action = action; this.result = result; }',
      m + 'public String toString() { return (success ? "OK: " : "FAIL: ") + action + " -> " + result; }',
      pad + '}',
      '',
      pad + 'public static class MemberResult {',
      m + 'public final String member;',
      m + 'public final boolean success;',
      m + 'public final String result;',
      m + 'public MemberResult(String member, boolean success, String result) { this.member = member; this.success = success; this.result = result; }',
      m + 'public String toString() { return "[" + (success ? "ok" : "fail") + "] " + member + ": " + result; }',
      pad + '}',
      '',
      pad + 'public static class TeamResult {',
      m + 'public final String task;',
      m + 'public final List<MemberResult> members;',
      m + 'public TeamResult(String task, List<MemberResult> members) { this.task = task; this.members = members; }',
      m + 'public String toString() {',
      m + m + 'StringBuilder sb = new StringBuilder("Team [" + task + "]: ");',
      m + m + 'for (int i = 0; i < members.size(); i++) { if (i > 0) sb.append(" | "); sb.append(members.get(i)); }',
      m + m + 'return sb.toString();',
      m + '}',
      pad + '}',
      '',
      pad + 'public static class WorkflowResult {',
      m + 'public final boolean success;',
      m + 'public final String error;',
      m + 'public final List<String> order;',
      m + 'public WorkflowResult(boolean success, String error, List<String> order) { this.success = success; this.error = error; this.order = order; }',
      m + 'public String toString() { return success ? "Workflow: " + String.join(" -> ", order) : "Workflow error: " + error; }',
      pad + '}',
      '',
      pad + 'public static class SystemResult {',
      m + 'public final boolean success;',
      m + 'public final String error;',
      m + 'public final List<String> order;',
      m + 'public final Map<String, Object> results;',
      m + 'public SystemResult(boolean success, String error, List<String> order, Map<String, Object> results) { this.success = success; this.error = error; this.order = order; this.results = results; }',
      m + 'public String toString() { return success ? "System run: " + String.join(" -> ", order) : "System error: " + error; }',
      pad + '}',
    ];
  }

  private compileAgent(mod: V2AgentNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const m = pad + pad;
    const cls = this.className(mod.name, 'Agent');
    const demoVar = this.newVar();
    const tools = mod.tools?.map(t => `"${this.esc(t)}"`).join(', ') || '';
    const handoff = mod.handoff?.map(h => `"${this.esc(h)}"`).join(', ') || '';
    const memName = mod.memory?.name || mod.memory?.type || '';
    const memField = memName ? `${m}public final String memory = "${this.esc(memName)}";` : null;
    const memFrag = memName ? ` + " | logged to memory: " + memory` : '';

    const code = [
      pad + `public static class ${cls} {`,
      m + `public final String name = "${this.esc(mod.name)}";`,
      m + `public final String role = "${this.esc(mod.role || '')}";`,
      m + `public final String goal = "${this.esc(mod.goal || '')}";`,
      m + `public final List<String> tools = Arrays.asList(${tools});`,
      m + `public final List<String> handoff = Arrays.asList(${handoff});`,
      ...(memField ? [memField] : []),
      '',
      m + 'public AgentResult execute(String task) {',
      m + m + 'String tool = tools.isEmpty() ? null : tools.get(0);',
      m + m + 'return new AgentResult(true, task, "[" + role + "] completed \'" + task + "\' toward goal: " + goal' + memFrag + ', tool);',
      m + '}',
      pad + '}',
    ];

    const demo = [
      `${cls} ${demoVar} = new ${cls}();`,
      `System.out.println(${demoVar}.execute("demo task"));`,
    ];

    return { code, demo };
  }

  private compileTool(mod: V2ToolNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const m = pad + pad;
    const cls = this.className(mod.name, 'Tool');
    const demoVar = this.newVar();
    const caps = mod.capabilities?.map(c => `"${this.esc(c)}"`).join(', ') || '';
    const firstCap = mod.capabilities && mod.capabilities.length > 0 ? mod.capabilities[0] : 'invoke';

    const code = [
      pad + `public static class ${cls} {`,
      m + `public final String name = "${this.esc(mod.name)}";`,
      m + `public final String provider = "${this.esc(mod.provider || '')}";`,
      m + `public final List<String> capabilities = Arrays.asList(${caps});`,
      '',
      m + 'public ToolResult invoke(String action, Map<String, Object> kwargs) {',
      m + m + 'if (!capabilities.contains(action)) {',
      m + m + m + 'return new ToolResult(false, action, "Action \'" + action + "\' is not a capability. Available: " + String.join(", ", capabilities));',
      m + m + '}',
      m + m + 'int count = kwargs == null ? 0 : kwargs.size();',
      m + m + 'return new ToolResult(true, action, "[" + provider + "] invoked \'" + action + "\' with " + count + " parameter(s)");',
      m + '}',
      pad + '}',
    ];

    const demo = [
      `${cls} ${demoVar} = new ${cls}();`,
      `System.out.println(${demoVar}.invoke("${this.esc(firstCap)}", null));`,
      `System.out.println(${demoVar}.invoke("not-a-capability", null));`,
    ];

    return { code, demo };
  }

  private compileMemory(mod: V2MemoryNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const m = pad + pad;
    const cls = this.className(mod.name, 'Memory');
    const demoVar = this.newVar();

    const code = [
      pad + `public static class ${cls} {`,
      m + `public final String name = "${this.esc(mod.name)}";`,
      m + `public final String format = "${this.esc(mod.format || 'key-value')}";`,
      m + `public final String backend = "${this.esc(mod.backend || 'local')}";`,
      m + `public final String scope = "${this.esc(mod.scope || 'module')}";`,
      m + 'private final Map<String, Object> store = new HashMap<>();',
      '',
      m + 'public void store(String key, Object value) { store.put(key, value); }',
      m + 'public Object retrieve(String key) { return store.get(key); }',
      m + 'public boolean delete(String key) { return store.remove(key) != null; }',
      m + 'public List<String> search(String term) {',
      m + m + 'List<String> hits = new ArrayList<>();',
      m + m + 'for (String k : store.keySet()) { if (k.toLowerCase().contains(term.toLowerCase())) hits.add(k); }',
      m + m + 'return hits;',
      m + '}',
      m + 'public int count() { return store.size(); }',
      pad + '}',
    ];

    const demo = [
      `${cls} ${demoVar} = new ${cls}();`,
      `${demoVar}.store("topic", "MAM compiler");`,
      `${demoVar}.store("lang", "Java");`,
      `System.out.println(${demoVar}.count() + " entr" + (${demoVar}.count() == 1 ? "y" : "ies") + " stored");`,
      `System.out.println("retrieve(topic) = " + ${demoVar}.retrieve("topic"));`,
      `System.out.println("search(compiler) -> " + ${demoVar}.search("compiler").size() + " match(es)");`,
      `System.out.println("delete(lang) = " + ${demoVar}.delete("lang"));`,
    ];

    return { code, demo };
  }

  private compileWorkflow(mod: V2WorkflowNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const m = pad + pad;
    const cls = this.className(mod.name, 'Workflow');
    const demoVar = this.newVar();
    const steps = mod.steps?.map(s => `"${this.esc(s.name)}"`).join(', ') || '';
    const edges = mod.edges?.map(e => `new Edge("${this.esc(e.source)}", "${this.esc(e.target)}")`).join(', ') || '';

    const code = [
      pad + `public static class ${cls} {`,
      m + `public final List<String> steps = Arrays.asList(${steps});`,
      m + `public final List<Edge> edges = Arrays.asList(${edges});`,
      '',
      m + 'public WorkflowResult run(Map<String, Object> inputs) {',
      m + m + 'Map<String, Integer> indegree = new HashMap<>();',
      m + m + 'Map<String, List<String>> adj = new HashMap<>();',
      m + m + 'for (String s : steps) { indegree.put(s, 0); adj.put(s, new ArrayList<>()); }',
      m + m + 'for (Edge e : edges) {',
      m + m + m + 'if (!adj.containsKey(e.source) || !indegree.containsKey(e.target)) continue;',
      m + m + m + 'adj.get(e.source).add(e.target);',
      m + m + m + 'indegree.put(e.target, indegree.get(e.target) + 1);',
      m + m + '}',
      m + m + 'Deque<String> queue = new ArrayDeque<>();',
      m + m + 'for (String s : steps) { if (indegree.get(s) == 0) queue.add(s); }',
      m + m + 'List<String> order = new ArrayList<>();',
      m + m + 'while (!queue.isEmpty()) {',
      m + m + m + 'String u = queue.poll();',
      m + m + m + 'order.add(u);',
      m + m + m + 'for (String v : adj.get(u)) { indegree.put(v, indegree.get(v) - 1); if (indegree.get(v) == 0) queue.add(v); }',
      m + m + '}',
      m + m + 'if (order.size() != steps.size()) return new WorkflowResult(false, "Cycle detected in workflow edges", order);',
      m + m + 'return new WorkflowResult(true, null, order);',
      m + '}',
      pad + '}',
    ];

    const demo = [
      `${cls} ${demoVar} = new ${cls}();`,
      `System.out.println(${demoVar}.run(new LinkedHashMap<>()));`,
    ];

    return { code, demo };
  }

  private compileTeam(mod: V2TeamNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const m = pad + pad;
    const cls = this.className(mod.name, 'Team');
    const demoVar = this.newVar();
    const members = mod.members?.map(mem => `"${this.esc(mem)}"`).join(', ') || '';

    const code = [
      pad + `public static class ${cls} {`,
      m + `public final List<String> members = Arrays.asList(${members});`,
      '',
      m + 'public TeamResult coordinate(String task) {',
      m + m + 'List<MemberResult> results = new ArrayList<>();',
      m + m + 'for (String member : members) results.add(new MemberResult(member, true, "completed \'" + task + "\'"));',
      m + m + 'return new TeamResult(task, results);',
      m + '}',
      pad + '}',
    ];

    const demo = [
      `${cls} ${demoVar} = new ${cls}();`,
      `System.out.println(${demoVar}.coordinate("demo task"));`,
    ];

    return { code, demo };
  }

  private compilePolicy(mod: V2PolicyNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const m = pad + pad;
    const cls = this.className(mod.name, 'Policy');
    const demoVar = this.newVar();
    const allow = mod.allow?.map(a => `"${this.esc(a)}"`).join(', ') || '';
    const deny = mod.deny?.map(d => `"${this.esc(d)}"`).join(', ') || '';
    const allowSample = mod.allow && mod.allow.length > 0 ? mod.allow[0] : 'read';
    const denySample = mod.deny && mod.deny.length > 0 ? mod.deny[0] : 'blocked';

    const code = [
      pad + `public static class ${cls}Policy {`,
      m + `public final List<String> allow = Arrays.asList(${allow});`,
      m + `public final List<String> deny = Arrays.asList(${deny});`,
      '',
      m + 'public boolean check(String action) {',
      m + m + 'if (deny.contains(action)) return false;',
      m + m + 'if (allow.contains(action)) return true;',
      m + m + 'return false;',
      m + '}',
      pad + '}',
    ];

    const demo = [
      `${cls}Policy ${demoVar} = new ${cls}Policy();`,
      `System.out.println("check(\'${this.esc(allowSample)}\') = " + ${demoVar}.check("${this.esc(allowSample)}"));`,
      `System.out.println("check(\'${this.esc(denySample)}\') = " + ${demoVar}.check("${this.esc(denySample)}"));`,
      `System.out.println("check(\'anything\') = " + ${demoVar}.check("anything"));`,
    ];

    return { code, demo };
  }

  private compileSystem(mod: V2SystemNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const m = pad + pad;
    const cls = this.className(mod.name, 'System');
    const demoVar = this.newVar();
    const agents = mod.agents?.map(a => `"${this.esc(a)}"`).join(', ') || '';
    const modules = mod.modules?.map(mm => `"${this.esc(mm)}"`).join(', ') || '';
    const edges = mod.edges?.map(e => `new Edge("${this.esc(e.source)}", "${this.esc(e.target)}")`).join(', ') || '';

    const code = [
      pad + `public static class ${cls}System {`,
      m + `public final List<String> agents = Arrays.asList(${agents});`,
      m + `public final List<String> modules = Arrays.asList(${modules});`,
      m + `public final List<Edge> edges = Arrays.asList(${edges});`,
      '',
      m + 'public SystemResult run() {',
      m + m + 'List<String> nodes = new ArrayList<>(agents);',
      m + m + 'nodes.addAll(modules);',
      m + m + 'Map<String, Integer> indegree = new HashMap<>();',
      m + m + 'Map<String, List<String>> adj = new HashMap<>();',
      m + m + 'for (String n : nodes) { indegree.put(n, 0); adj.put(n, new ArrayList<>()); }',
      m + m + 'for (Edge e : edges) {',
      m + m + m + 'if (!adj.containsKey(e.source) || !indegree.containsKey(e.target)) continue;',
      m + m + m + 'adj.get(e.source).add(e.target);',
      m + m + m + 'indegree.put(e.target, indegree.get(e.target) + 1);',
      m + m + '}',
      m + m + 'Deque<String> queue = new ArrayDeque<>();',
      m + m + 'for (String n : nodes) { if (indegree.get(n) == 0) queue.add(n); }',
      m + m + 'List<String> order = new ArrayList<>();',
      m + m + 'while (!queue.isEmpty()) {',
      m + m + m + 'String u = queue.poll();',
      m + m + m + 'order.add(u);',
      m + m + m + 'for (String v : adj.get(u)) { indegree.put(v, indegree.get(v) - 1); if (indegree.get(v) == 0) queue.add(v); }',
      m + m + '}',
      m + m + 'Map<String, Object> results = new LinkedHashMap<>();',
      m + m + 'for (String n : order) results.put(n, "[" + n + "] executed");',
      m + m + 'if (order.size() != nodes.size()) return new SystemResult(false, "Cycle detected in system graph", order, results);',
      m + m + 'return new SystemResult(true, null, order, results);',
      m + '}',
      pad + '}',
    ];

    const demo = [
      `${cls}System ${demoVar} = new ${cls}System();`,
      `System.out.println(${demoVar}.run());`,
    ];

    return { code, demo };
  }

  private compileGeneric(mod: V2ModuleNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const m = pad + pad;
    const cls = this.className(mod.name, 'Module');
    const demoVar = this.newVar();
    const inputs = mod.inputs?.map(i => `new Port("${this.esc(i.name)}", "${this.esc(i.type || 'unknown')}", ${i.required ? 'true' : 'false'})`).join(', ') || '';
    const outputs = mod.outputs?.map(o => `new Port("${this.esc(o.name)}", "${this.esc(o.type || 'unknown')}", false)`).join(', ') || '';
    const caps = mod.capabilities?.map(c => `"${this.esc(c)}"`).join(', ') || '';
    const required = mod.inputs?.filter(i => i.required) || [];

    const code = [
      pad + `public static class ${cls}Module {`,
      m + `public final String name = "${this.esc(mod.name)}";`,
      m + `public final String description = "${this.esc(mod.description || '')}";`,
      m + `public final List<Port> inputs = Arrays.asList(${inputs});`,
      m + `public final List<Port> outputs = Arrays.asList(${outputs});`,
      m + `public final List<String> capabilities = Arrays.asList(${caps});`,
      '',
      m + 'public ModuleResult run(Map<String, Object> inputs) {',
      m + m + 'List<String> missing = new ArrayList<>();',
      m + m + 'for (Port p : this.inputs) { if (p.required && !inputs.containsKey(p.name)) missing.add(p.name); }',
      m + m + 'if (!missing.isEmpty()) return ModuleResult.fail("Missing required inputs: " + String.join(", ", missing));',
      m + m + 'Map<String, Object> outputs = new LinkedHashMap<>();',
      m + m + 'for (Port o : this.outputs) outputs.put(o.name, null);',
      m + m + 'for (Map.Entry<String, Object> e : inputs.entrySet()) { if (!outputs.containsKey(e.getKey())) outputs.put(e.getKey(), e.getValue()); }',
      m + m + 'return ModuleResult.ok(outputs);',
      m + '}',
      pad + '}',
    ];

    const demo = [
      `${cls}Module ${demoVar} = new ${cls}Module();`,
      `Map<String, Object> ${demoVar}_inputs = new LinkedHashMap<>();`,
      ...required.map(i => `${demoVar}_inputs.put("${this.esc(i.name)}", "demo");`),
      `System.out.println(${demoVar}.run(${demoVar}_inputs));`,
    ];

    return { code, demo };
  }
}