/**
 * JavaScript Target
 * 
 * Compiles MAM AST to JavaScript code.
 */

import { V2ModuleNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';

export class JavaScriptTarget implements CompileTargetHandler {
  name = 'javascript';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];

    lines.push('/**');
    lines.push(' * Generated by MAM Compiler');
    lines.push(' * Target: JavaScript');
    lines.push(' */');
    lines.push('');
    lines.push('"use strict";');
    lines.push('');

    for (const mod of modules) {
      lines.push(...this.compileModule(mod, config));
      lines.push('');
    }

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode, config: CompilerConfig): string[] {
    const lines: string[] = [];
    const className = mod.name.replace(/[^a-zA-Z0-9_]/g, '_');

    lines.push(`class ${className} {`);
    lines.push(`  constructor() {`);

    if (mod.role) lines.push(`    this.role = "${mod.role}";`);
    if (mod.goal) lines.push(`    this.goal = "${mod.goal}";`);
    if (mod.tools) lines.push(`    this.tools = ${JSON.stringify(mod.tools)};`);
    if (mod.handoff) lines.push(`    this.handoff = ${JSON.stringify(mod.handoff)};`);
    if (mod.members) lines.push(`    this.members = ${JSON.stringify(mod.members)};`);
    if (mod.steps) lines.push(`    this.steps = ${JSON.stringify(mod.steps.map(s => s.name))};`);
    if (mod.edges) lines.push(`    this.edges = ${JSON.stringify(mod.edges.map(e => ({ source: e.source, target: e.target })))};`);
    if (mod.allow) lines.push(`    this.allow = ${JSON.stringify(mod.allow)};`);
    if (mod.deny) lines.push(`    this.deny = ${JSON.stringify(mod.deny)};`);

    lines.push(`  }`);
    lines.push('');

    lines.push(`  async execute(task) {`);
    lines.push(`    throw new Error("Not implemented");`);
    lines.push(`  }`);

    if (mod.moduleType === 'policy') {
      lines.push('');
      lines.push(`  check(action) {`);
      lines.push(`    if (this.deny.includes(action)) return false;`);
      lines.push(`    if (this.allow.includes(action)) return true;`);
      lines.push(`    return false;`);
      lines.push(`  }`);
    }

    lines.push(`}`);
    lines.push('');
    lines.push(`module.exports = { ${className} };`);

    return lines;
  }
}