/**
 * Kubernetes Target
 *
 * Compiles MAM AST to deployable Kubernetes manifests (YAML).
 * Emits a single multi-document YAML stream containing, per module:
 *   - a ConfigMap holding the module metadata / context
 *   - a Deployment (image mam/<module>:latest, ports derived from
 *     permissions, env derived from module metadata)
 *   - a Service routing to the deployment
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2MemoryNode, V2WorkflowNode, V2TeamNode, V2PolicyNode, V2SystemNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';
import { generateModuleContext } from '../context.js';

export class KubernetesTarget implements CompileTargetHandler {
  name = 'kubernetes';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const docs: string[] = ['# Generated by MAM Compiler', '# Target: Kubernetes'];
    for (const mod of modules) {
      docs.push(...this.compileModuleDocs(mod));
    }
    return docs.join('\n---\n') + '\n';
  }

  private compileModuleDocs(mod: V2ModuleNode): string[] {
    // The context block is emitted as its own `---`-separated document so that
    // multi-line metadata can never corrupt the YAML manifests that follow.
    return [generateModuleContext(mod, 'kubernetes'), this.configMapYaml(mod), this.deploymentYaml(mod), this.serviceYaml(mod)];
  }

  // ==========================================================================
  // Helpers
  // ==========================================================================

  private toK8sName(name: string): string {
    const k = name.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
    return k || 'module';
  }

  private labels(mod: V2ModuleNode): Record<string, string> {
    return { app: this.toK8sName(mod.name), 'mam-type': mod.moduleType, 'managed-by': 'mam-compiler' };
  }

  private scalar(v: unknown): string {
    const s = String(v);
    if (s === '') return '""';
    return JSON.stringify(s);
  }

  private runtimeOf(mod: V2ModuleNode): string {
    const meta = mod.metadata as Record<string, unknown> | undefined;
    const rt = (meta?.runtime as Record<string, unknown>) || {};
    return String(rt.language || 'python').toLowerCase().trim() || 'python';
  }

  private moduleContextText(mod: V2ModuleNode): string {
    const meta = mod.metadata as Record<string, unknown> | undefined;
    const lines: string[] = [
      `name: ${mod.name}`,
      `type: ${mod.moduleType}`,
      `version: ${(meta?.version as string) || '1.0.0'}`,
      `author: ${(meta?.author as string) || 'MAM User'}`,
      `license: ${(meta?.license as string) || 'MIT'}`,
    ];
    if (mod.description) lines.push(`description: ${mod.description}`);
    if (mod.role) lines.push(`role: ${mod.role}`);
    if (mod.goal) lines.push(`goal: ${mod.goal}`);
    if (mod.provider) lines.push(`provider: ${mod.provider}`);
    if (mod.requires?.length) lines.push(`dependencies: ${mod.requires.join(', ')}`);
    if (mod.permissions?.network) lines.push(`network: ${mod.permissions.network}`);
    if (mod.permissions?.filesystem) lines.push(`filesystem: ${mod.permissions.filesystem}`);
    return lines.join('\n');
  }

  private moduleEnv(mod: V2ModuleNode): Record<string, string> {
    const env: Record<string, string> = {
      MAM_MODULE: mod.name,
      MAM_TYPE: mod.moduleType,
    };
    switch (mod.moduleType) {
      case 'agent': {
        const a = mod as unknown as V2AgentNode;
        env.AGENT_ROLE = a.role || '';
        env.AGENT_GOAL = a.goal || '';
        if (a.tools?.length) env.AGENT_TOOLS = a.tools.join(',');
        if (a.handoff?.length) env.AGENT_HANDOFF = a.handoff.join(',');
        break;
      }
      case 'tool': {
        const t = mod as unknown as V2ToolNode;
        env.TOOL_PROVIDER = t.provider || '';
        if (t.capabilities?.length) env.TOOL_CAPABILITIES = t.capabilities.join(',');
        break;
      }
      case 'memory': {
        const m = mod as unknown as V2MemoryNode;
        env.MEMORY_FORMAT = m.format || '';
        env.MEMORY_BACKEND = m.backend || '';
        env.MEMORY_SCOPE = m.scope || '';
        break;
      }
      case 'workflow': {
        const w = mod as unknown as V2WorkflowNode;
        if (w.steps?.length) env.WORKFLOW_STEPS = w.steps.map(s => s.name).join(',');
        break;
      }
      case 'team': {
        const t = mod as unknown as V2TeamNode;
        if (t.members?.length) env.TEAM_MEMBERS = t.members.join(',');
        break;
      }
      case 'policy': {
        const p = mod as unknown as V2PolicyNode;
        if (p.allow?.length) env.POLICY_ALLOW = p.allow.join(',');
        if (p.deny?.length) env.POLICY_DENY = p.deny.join(',');
        break;
      }
      case 'system': {
        const s = mod as unknown as V2SystemNode;
        if (s.agents?.length) env.SYSTEM_AGENTS = s.agents.join(',');
        if (s.modules?.length) env.SYSTEM_MODULES = s.modules.join(',');
        break;
      }
      default:
        break;
    }
    return env;
  }

  private modulePort(mod: V2ModuleNode): number | null {
    const network = mod.permissions?.network;
    if (network !== 'internet' && network !== 'internal') return null;
    const raw = mod.permissions?.custom?.port;
    const parsed = raw ? parseInt(String(raw), 10) : NaN;
    return Number.isFinite(parsed) && parsed > 0 && parsed <= 65535 ? parsed : 8080;
  }

  // ==========================================================================
  // Manifests
  // ==========================================================================

  private configMapYaml(mod: V2ModuleNode): string {
    const k = this.toK8sName(mod.name);
    const labels = this.labels(mod);
    const meta = mod.metadata as Record<string, unknown> | undefined;

    const data: Array<[string, string]> = [
      ['module-name', mod.name],
      ['module-type', mod.moduleType],
      ['version', (meta?.version as string) || '1.0.0'],
      ['author', (meta?.author as string) || 'MAM User'],
      ['license', (meta?.license as string) || 'MIT'],
      ['runtime', this.runtimeOf(mod)],
    ];
    if (mod.description) data.push(['description', mod.description]);
    if (mod.requires?.length) data.push(['dependencies', mod.requires.join(',')]);
    if (mod.capabilities?.length) data.push(['capabilities', mod.capabilities.join(',')]);
    if (mod.permissions) {
      data.push(['permissions-network', mod.permissions.network || 'none']);
      data.push(['permissions-filesystem', mod.permissions.filesystem || 'none']);
    }

    const lines: string[] = [];
    lines.push('apiVersion: v1');
    lines.push('kind: ConfigMap');
    lines.push('metadata:');
    lines.push(`  name: ${k}-config`);
    lines.push('  labels:');
    for (const [lk, lv] of Object.entries(labels)) lines.push(`    ${lk}: ${lv}`);
    lines.push('data:');
    for (const [dk, dv] of data) lines.push(`  ${dk}: ${this.scalar(dv)}`);
    lines.push('  context: |-');
    for (const cl of this.moduleContextText(mod).split('\n')) lines.push(`    ${cl}`);
    return lines.join('\n');
  }

  private deploymentYaml(mod: V2ModuleNode): string {
    const k = this.toK8sName(mod.name);
    const labels = this.labels(mod);
    const env = this.moduleEnv(mod);
    const port = this.modulePort(mod);

    const lines: string[] = [];
    lines.push('apiVersion: apps/v1');
    lines.push('kind: Deployment');
    lines.push('metadata:');
    lines.push(`  name: ${k}`);
    lines.push('  labels:');
    for (const [lk, lv] of Object.entries(labels)) lines.push(`    ${lk}: ${lv}`);
    lines.push('spec:');
    lines.push('  replicas: 1');
    lines.push('  selector:');
    lines.push('    matchLabels:');
    lines.push(`      app: ${k}`);
    lines.push('  template:');
    lines.push('    metadata:');
    lines.push('      labels:');
    for (const [lk, lv] of Object.entries(labels)) lines.push(`        ${lk}: ${lv}`);
    lines.push('    spec:');
    lines.push('      containers:');
    lines.push(`      - name: ${k}`);
    lines.push(`        image: mam/${k}:latest`);
    lines.push('        imagePullPolicy: IfNotPresent');
    if (Object.keys(env).length > 0) {
      lines.push('        env:');
      for (const [ek, ev] of Object.entries(env)) {
        lines.push(`        - name: ${ek}`);
        lines.push(`          value: ${this.scalar(ev)}`);
      }
    }
    if (port) {
      lines.push('        ports:');
      lines.push(`        - containerPort: ${port}`);
      lines.push('          protocol: TCP');
    }
    lines.push('        resources:');
    lines.push('          requests:');
    lines.push('            cpu: 100m');
    lines.push('            memory: 128Mi');
    lines.push('          limits:');
    lines.push('            cpu: 500m');
    lines.push('            memory: 256Mi');
    return lines.join('\n');
  }

  private serviceYaml(mod: V2ModuleNode): string {
    const k = this.toK8sName(mod.name);
    const port = this.modulePort(mod);

    const lines: string[] = [];
    lines.push('apiVersion: v1');
    lines.push('kind: Service');
    lines.push('metadata:');
    lines.push(`  name: ${k}-svc`);
    lines.push('  labels:');
    lines.push(`    app: ${k}`);
    lines.push(`    mam-type: ${mod.moduleType}`);
    lines.push('spec:');
    lines.push('  type: ClusterIP');
    if (port) {
      lines.push('  selector:');
      lines.push(`    app: ${k}`);
      lines.push('  ports:');
      lines.push('  - port: 80');
      lines.push(`    targetPort: ${port}`);
      lines.push('    protocol: TCP');
    } else {
      lines.push('  clusterIP: None');
      lines.push('  selector:');
      lines.push(`    app: ${k}`);
    }
    return lines.join('\n');
  }
}