/**
 * Kubernetes Target
 *
 * Compiles MAM AST to Kubernetes Deployment manifests (YAML).
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2MemoryNode, V2WorkflowNode, V2TeamNode, V2PolicyNode, V2SystemNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';

export class KubernetesTarget implements CompileTargetHandler {
  name = 'kubernetes';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];

    lines.push('# Generated by MAM Compiler');
    lines.push('# Target: Kubernetes');
    lines.push('---');

    for (const mod of modules) {
      const parts = this.compileModule(mod, config);
      if (parts.length > 0) {
        lines.push(...parts);
        lines.push('---');
      }
    }

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode, config: CompilerConfig): string[] {
    const comments: string[] = [];
    if (config.includeComments) {
      comments.push(`# Module: ${mod.name}`);
      comments.push(`# Type: ${mod.moduleType}`);
      if (mod.description) comments.push(`# ${mod.description}`);
      comments.push('');
    }

    let result: string[];
    switch (mod.moduleType) {
      case 'agent':
        result = this.compileAgent(mod as unknown as V2AgentNode, config);
        break;
      case 'tool':
        result = this.compileTool(mod as unknown as V2ToolNode, config);
        break;
      case 'memory':
        result = this.compileMemory(mod as unknown as V2MemoryNode, config);
        break;
      case 'workflow':
        result = this.compileWorkflow(mod as unknown as V2WorkflowNode, config);
        break;
      case 'team':
        result = this.compileTeam(mod as unknown as V2TeamNode, config);
        break;
      case 'policy':
        result = this.compilePolicy(mod as unknown as V2PolicyNode, config);
        break;
      case 'system':
        result = this.compileSystem(mod as unknown as V2SystemNode, config);
        break;
      default:
        result = this.compileGeneric(mod, config);
    }

    return [...comments, ...result];
  }

  private toK8sName(name: string): string {
    return name.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
  }

  private deploymentYaml(name: string, image: string, labels: Record<string, string>, env: Record<string, string>): string {
    const k8sName = this.toK8sName(name);
    const labelEntries = Object.entries(labels).map(([k, v]) => `    ${k}: ${v}`).join('\n');
    const envEntries = Object.entries(env).map(([k, v]) => `    - name: ${k}\n      value: "${v}"`).join('\n');

    return [
      `apiVersion: apps/v1`,
      `kind: Deployment`,
      `metadata:`,
      `  name: ${k8sName}`,
      `  labels:`,
      labelEntries,
      `spec:`,
      `  replicas: 1`,
      `  selector:`,
      `    matchLabels:`,
      labelEntries,
      `  template:`,
      `    metadata:`,
      `      labels:`,
      labelEntries,
      `    spec:`,
      `      containers:`,
      `      - name: ${k8sName}`,
      `        image: ${image}`,
      envEntries.length > 0 ? `        env:\n${envEntries}` : '',
    ].filter(l => l !== '').join('\n');
  }

  private compileAgent(mod: V2AgentNode, config: CompilerConfig): string[] {
    const labels = { app: this.toK8sName(mod.name), 'mam-type': 'agent' };
    const env = { AGENT_ROLE: mod.role || '', AGENT_GOAL: mod.goal || '' };
    return this.deploymentYaml(mod.name, 'mam/agent:latest', labels, env).split('\n');
  }

  private compileTool(mod: V2ToolNode, config: CompilerConfig): string[] {
    const labels = { app: this.toK8sName(mod.name), 'mam-type': 'tool' };
    const env = { TOOL_PROVIDER: mod.provider };
    return this.deploymentYaml(mod.name, 'mam/tool:latest', labels, env).split('\n');
  }

  private compileMemory(mod: V2MemoryNode, config: CompilerConfig): string[] {
    const labels = { app: this.toK8sName(mod.name), 'mam-type': 'memory' };
    const env = { MEMORY_FORMAT: mod.format, MEMORY_BACKEND: mod.backend, MEMORY_SCOPE: mod.scope };
    return this.deploymentYaml(mod.name, 'mam/memory:latest', labels, env).split('\n');
  }

  private compileWorkflow(mod: V2WorkflowNode, config: CompilerConfig): string[] {
    const labels = { app: this.toK8sName(mod.name), 'mam-type': 'workflow' };
    const stepNames = mod.steps?.map(s => s.name).join(',') || '';
    const env = { WORKFLOW_STEPS: stepNames };
    return this.deploymentYaml(mod.name, 'mam/workflow:latest', labels, env).split('\n');
  }

  private compileTeam(mod: V2TeamNode, config: CompilerConfig): string[] {
    const labels = { app: this.toK8sName(mod.name), 'mam-type': 'team' };
    const env = { TEAM_MEMBERS: mod.members?.join(',') || '' };
    return this.deploymentYaml(mod.name, 'mam/team:latest', labels, env).split('\n');
  }

  private compilePolicy(mod: V2PolicyNode, config: CompilerConfig): string[] {
    const labels = { app: this.toK8sName(mod.name), 'mam-type': 'policy' };
    const env = {
      POLICY_ALLOW: mod.allow?.join(',') || '',
      POLICY_DENY: mod.deny?.join(',') || '',
    };
    return this.deploymentYaml(mod.name, 'mam/policy:latest', labels, env).split('\n');
  }

  private compileSystem(mod: V2SystemNode, config: CompilerConfig): string[] {
    const labels = { app: this.toK8sName(mod.name), 'mam-type': 'system' };
    const env = {
      SYSTEM_AGENTS: mod.agents?.join(',') || '',
      SYSTEM_MODULES: mod.modules?.join(',') || '',
    };
    return this.deploymentYaml(mod.name, 'mam/system:latest', labels, env).split('\n');
  }

  private compileGeneric(mod: V2ModuleNode, config: CompilerConfig): string[] {
    const labels = { app: this.toK8sName(mod.name), 'mam-type': 'module' };
    const env = {};
    return this.deploymentYaml(mod.name, 'mam/module:latest', labels, env).split('\n');
  }
}
