/**
 * LangGraph Target
 *
 * Compiles MAM AST to runnable Python using `langgraph` + `langchain`.
 * Workflow `steps` become graph nodes and workflow `edges` (or agent handoffs)
 * become graph edges; the graph is compiled with `StateGraph` and invoked from
 * a `main()` guarded by `if __name__ == "__main__"`.
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2WorkflowNode, V2TeamNode, V2SystemNode, V2MemoryNode, V2PolicyNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';
import { generateModuleContext } from '../context.js';

function pyStr(value: unknown): string {
  const s = String(value ?? '');
  return `'${s
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')}'`;
}

function ident(name: string): string {
  let s = name.toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/^_+|_+$/g, '');
  if (!s) s = 'module';
  if (/^[0-9]/.test(s)) s = '_' + s;
  return s;
}

function nodeFn(name: string): string {
  return 'node_' + ident(name);
}

function buildFn(name: string): string {
  return 'build_' + ident(name);
}

export class LangGraphTarget implements CompileTargetHandler {
  name = 'langgraph';

  private agentNodes: Set<string> = new Set();

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];
    const indent = config.indent || 4;
    const pad = ' '.repeat(indent);

    this.agentNodes = new Set(
      modules.filter(m => m.moduleType === 'agent').map(m => nodeFn(m.name)),
    );

    lines.push('"""');
    lines.push('Generated by MAM Compiler');
    lines.push('Target: LangGraph (langgraph + langchain)');
    lines.push('"""');
    lines.push('');
    lines.push('import json');
    lines.push('import os');
    lines.push('');
    lines.push('from typing import Annotated, TypedDict');
    lines.push('');
    lines.push('from langchain_openai import ChatOpenAI');
    lines.push('from langgraph.graph import END, START, StateGraph');
    lines.push('from langgraph.graph.message import add_messages');
    lines.push('');
    lines.push('MODEL = "gpt-4o"');
    lines.push('');
    lines.push('class MAMState(TypedDict):');
    lines.push(`${pad}messages: Annotated[list, add_messages]`);
    lines.push('');
    lines.push('def _system_prompt(*parts: str) -> str:');
    lines.push(`${pad}"""Join non-empty prompt parts with a blank line."""`);
    lines.push(`${pad}return "\\n\\n".join(p for p in parts if p)`);
    lines.push('');
    lines.push('def _chat(system: str, task: str) -> str:');
    lines.push(`${pad}"""Run a chat model for a LangGraph node."""`);
    lines.push(`${pad}model = ChatOpenAI(model=MODEL, temperature=0)`);
    lines.push(`${pad}response = model.invoke([`);
    lines.push(`${pad}${pad}{"role": "system", "content": system},`);
    lines.push(`${pad}${pad}{"role": "user", "content": task},`);
    lines.push(`${pad}])`);
    lines.push(`${pad}return str(response.content)`);
    lines.push('');

    let primary: string | null = null;
    for (const mod of modules) {
      lines.push(generateModuleContext(mod, 'langgraph'));
      lines.push('');
      lines.push(...this.compileModule(mod, indent, config));
      lines.push('');
      if (
        primary === null &&
        (mod.moduleType === 'workflow' || mod.moduleType === 'system' || mod.moduleType === 'team' || mod.moduleType === 'agent')
      ) {
        primary = buildFn(mod.name);
      }
    }

    lines.push('def main() -> int:');
    if (primary) {
      lines.push(`${pad}api_key = os.environ.get("OPENAI_API_KEY")`);
      lines.push(`${pad}if not api_key:`);
      lines.push(`${pad}${pad}print("OPENAI_API_KEY is not set; skipping the live LangGraph run.")`);
      lines.push(`${pad}${pad}return 1`);
      lines.push(`${pad}graph = ${primary}()`);
      lines.push(`${pad}result = graph.invoke({"messages": [{"role": "user", "content": "Run the workflow and produce the final result."}]})`);
      lines.push(`${pad}last = result.get("messages")`);
      lines.push(`${pad}if last:`);
      lines.push(`${pad}${pad}print(last[-1].content)`);
      lines.push(`${pad}return 0`);
    } else {
      lines.push(`${pad}print("No graphable module (workflow, system, team or agent) found in this MAM document.")`);
      lines.push(`${pad}return 0`);
    }
    lines.push('');
    lines.push('if __name__ == "__main__":');
    lines.push(`${pad}raise SystemExit(main())`);
    lines.push('');

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];

    switch (mod.moduleType) {
      case 'agent':
        lines.push(...this.compileAgent(mod as unknown as V2AgentNode, indent, config));
        break;
      case 'tool':
        lines.push(...this.compileTool(mod as unknown as V2ToolNode, indent, config));
        break;
      case 'workflow':
        lines.push(...this.compileWorkflow(mod as unknown as V2WorkflowNode, indent, config));
        break;
      case 'team':
        lines.push(...this.compileTeam(mod as unknown as V2TeamNode, indent, config));
        break;
      case 'system':
        lines.push(...this.compileSystem(mod as unknown as V2SystemNode, indent, config));
        break;
      case 'memory':
        lines.push(...this.compileMemory(mod as unknown as V2MemoryNode, indent, config));
        break;
      case 'policy':
        lines.push(...this.compilePolicy(mod as unknown as V2PolicyNode, indent, config));
        break;
      default:
        lines.push(`# Module: ${mod.name} (${mod.moduleType})`);
    }

    return lines;
  }

  private compileAgent(mod: V2AgentNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const node = nodeFn(mod.name);
    const build = buildFn(mod.name);
    const lines: string[] = [];

    const parts: string[] = [`${mod.name} agent`];
    if (mod.role) parts.push(`Role: ${mod.role}`);
    if (mod.goal) parts.push(`Goal: ${mod.goal}`);

    lines.push(`def ${node}(state: MAMState) -> dict:`);
    lines.push(`${pad}"""Agent node: ${mod.name}${mod.role ? ` (${mod.role})` : ''}."""`);
    lines.push(`${pad}last = state["messages"][-1]`);
    lines.push(`${pad}parts = [${parts.map(pyStr).join(', ')}]`);
    if (mod.rules && mod.rules.length > 0) {
      lines.push(`${pad}rules = [${mod.rules.map(pyStr).join(', ')}]`);
      lines.push(`${pad}if rules:`);
      lines.push(`${pad}${pad}parts.append("Rules:\\n" + "\\n".join("- " + r for r in rules))`);
    }
    lines.push(`${pad}system = _system_prompt(*parts)`);
    lines.push(`${pad}reply = _chat(system, str(last.content))`);
    lines.push(`${pad}return {"messages": [{"role": "assistant", "content": reply}]}`);
    lines.push('');
    lines.push(`def ${build}():`);
    lines.push(`${pad}"""Build the ${mod.name} LangGraph."""`);
    lines.push(`${pad}graph = StateGraph(MAMState)`);
    lines.push(`${pad}graph.add_node(${pyStr(ident(mod.name))}, ${node})`);
    lines.push(`${pad}graph.add_edge(START, ${pyStr(ident(mod.name))})`);
    const handoffs = (mod.handoff || []).filter(h => this.agentNodes.has(nodeFn(h)));
    for (const target of handoffs) {
      lines.push(`${pad}graph.add_edge(${pyStr(ident(mod.name))}, ${pyStr(nodeFn(target))})`);
    }
    lines.push(`${pad}graph.add_edge(${pyStr(ident(mod.name))}, END)`);
    lines.push(`${pad}return graph.compile()`);
    lines.push('');

    return lines;
  }

  private compileTool(mod: V2ToolNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = ident(mod.name);
    const provider = mod.provider || 'unknown';

    return [
      `def ${fn}(**kwargs: object) -> str:`,
      `${pad}"""${mod.name} tool (provider: ${provider})."""`,
      `${pad}return json.dumps({"tool": ${pyStr(mod.name)}, "action": kwargs}, sort_keys=True)`,
      '',
    ];
  }

  private compileWorkflow(mod: V2WorkflowNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const build = buildFn(mod.name);
    const lines: string[] = [];

    const steps = (mod.steps || []).map(s => ident(s.name)).filter(Boolean);
    const stepSet = new Set(steps);
    const edges = (mod.edges || [])
      .filter(e => stepSet.has(ident(e.source)) && stepSet.has(ident(e.target)))
      .map(e => [ident(e.source), ident(e.target)] as [string, string]);

    if (steps.length === 0) {
      return [
        `def ${build}():`,
        `${pad}"""${mod.name} workflow has no parseable steps."""`,
        `${pad}raise ValueError("No steps declared for workflow ${pyStr(mod.name)}")`,
        '',
      ];
    }

    for (const step of steps) {
      lines.push(`def ${nodeFn(step)}(state: MAMState) -> dict:`);
      lines.push(`${pad}"""Step node: ${step}."""`);
      lines.push(`${pad}last = state["messages"][-1]`);
      lines.push(`${pad}system = _system_prompt(${pyStr(`${mod.name} workflow`)}, ${pyStr(`Step: ${step}`)})`);
      lines.push(`${pad}reply = _chat(system, str(last.content))`);
      lines.push(`${pad}return {"messages": [{"role": "assistant", "content": reply}]}`);
      lines.push('');
    }

    lines.push(`def ${build}():`);
    lines.push(`${pad}"""Build the ${mod.name} workflow graph."""`);
    lines.push(`${pad}graph = StateGraph(MAMState)`);
    for (const step of steps) {
      lines.push(`${pad}graph.add_node(${pyStr(step)}, ${nodeFn(step)})`);
    }
    lines.push(`${pad}graph.add_edge(START, ${pyStr(steps[0])})`);
    const sources = new Set(edges.map(([source]) => source));
    for (const [source, target] of edges) {
      lines.push(`${pad}graph.add_edge(${pyStr(source)}, ${pyStr(target)})`);
    }
    const terminals = steps.filter(step => !sources.has(step));
    for (const step of terminals) {
      lines.push(`${pad}graph.add_edge(${pyStr(step)}, END)`);
    }
    lines.push(`${pad}return graph.compile()`);
    lines.push('');

    return lines;
  }

  private compileTeam(mod: V2TeamNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const build = buildFn(mod.name);
    const members = (mod.members || []).map(m => ident(m)).filter(Boolean);
    const lines: string[] = [];

    if (members.length === 0) {
      return [
        `def ${build}():`,
        `${pad}"""${mod.name} team has no parseable members."""`,
        `${pad}raise ValueError("No members declared for team ${pyStr(mod.name)}")`,
        '',
      ];
    }

    for (const member of members) {
      lines.push(`def ${nodeFn(member)}(state: MAMState) -> dict:`);
      lines.push(`${pad}"""Member node: ${member}."""`);
      lines.push(`${pad}last = state["messages"][-1]`);
      lines.push(`${pad}system = _system_prompt(${pyStr(`${mod.name} team`)}, ${pyStr(`Member: ${member}`)})`);
      lines.push(`${pad}reply = _chat(system, str(last.content))`);
      lines.push(`${pad}return {"messages": [{"role": "assistant", "content": reply}]}`);
      lines.push('');
    }

    lines.push(`def ${build}():`);
    lines.push(`${pad}"""Build the ${mod.name} team graph."""`);
    lines.push(`${pad}graph = StateGraph(MAMState)`);
    for (const member of members) {
      lines.push(`${pad}graph.add_node(${pyStr(member)}, ${nodeFn(member)})`);
    }
    lines.push(`${pad}graph.add_edge(START, ${pyStr(members[0])})`);
    for (let i = 0; i < members.length - 1; i++) {
      lines.push(`${pad}graph.add_edge(${pyStr(members[i])}, ${pyStr(members[i + 1])})`);
    }
    lines.push(`${pad}graph.add_edge(${pyStr(members[members.length - 1])}, END)`);
    lines.push(`${pad}return graph.compile()`);
    lines.push('');

    return lines;
  }

  private compileSystem(mod: V2SystemNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const build = buildFn(mod.name);
    const modules = (mod.modules || []).map(String);
    const lines: string[] = [];

    if (modules.length === 0) {
      return [
        `def ${build}():`,
        `${pad}"""${mod.name} system has no parseable modules."""`,
        `${pad}raise ValueError("No modules declared for system ${pyStr(mod.name)}")`,
        '',
      ];
    }

    const keys: string[] = [];
    modules.forEach((module, index) => {
      keys.push(ident(module) || `module_${index + 1}`);
    });
    // Ensure uniqueness of node keys
    const seen = new Set<string>();
    const uniqueKeys = keys.map(k => {
      let candidate = k;
      let suffix = 1;
      while (seen.has(candidate)) {
        suffix += 1;
        candidate = `${k}_${suffix}`;
      }
      seen.add(candidate);
      return candidate;
    });

    for (let i = 0; i < modules.length; i++) {
      const key = uniqueKeys[i];
      lines.push(`def ${nodeFn(key)}(state: MAMState) -> dict:`);
      lines.push(`${pad}"""System node: ${modules[i]}."""`);
      lines.push(`${pad}last = state["messages"][-1]`);
      lines.push(`${pad}system = _system_prompt(${pyStr(mod.name)}, ${pyStr(`Module: ${modules[i]}`)})`);
      lines.push(`${pad}reply = _chat(system, str(last.content))`);
      lines.push(`${pad}return {"messages": [{"role": "assistant", "content": reply}]}`);
      lines.push('');
    }

    lines.push(`def ${build}():`);
    lines.push(`${pad}"""Build the ${mod.name} system graph."""`);
    lines.push(`${pad}graph = StateGraph(MAMState)`);
    for (let i = 0; i < uniqueKeys.length; i++) {
      lines.push(`${pad}graph.add_node(${pyStr(uniqueKeys[i])}, ${nodeFn(uniqueKeys[i])})`);
    }
    lines.push(`${pad}graph.add_edge(START, ${pyStr(uniqueKeys[0])})`);
    for (let i = 0; i < uniqueKeys.length - 1; i++) {
      lines.push(`${pad}graph.add_edge(${pyStr(uniqueKeys[i])}, ${pyStr(uniqueKeys[i + 1])})`);
    }
    lines.push(`${pad}graph.add_edge(${pyStr(uniqueKeys[uniqueKeys.length - 1])}, END)`);
    lines.push(`${pad}return graph.compile()`);
    lines.push('');

    return lines;
  }

  private compileMemory(mod: V2MemoryNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = ident(mod.name) + '_memory';

    return [
      `class ${className}:`,
      `${pad}"""In-memory store for the ${mod.name} memory module (${mod.format} / ${mod.backend})."""`,
      '',
      `${pad}def __init__(self):`,
      `${pad}${pad}self.format = ${pyStr(mod.format)}`,
      `${pad}${pad}self.backend = ${pyStr(mod.backend)}`,
      `${pad}${pad}self.scope = ${pyStr(mod.scope || 'module')}`,
      `${pad}${pad}self._store: dict = {}`,
      '',
      `${pad}def store(self, key: str, value: str) -> None:`,
      `${pad}${pad}"""Store a value under a key."""`,
      `${pad}${pad}self._store[key] = value`,
      '',
      `${pad}def retrieve(self, key: str) -> str:`,
      `${pad}${pad}"""Retrieve a value by key."""`,
      `${pad}${pad}return self._store.get(key, "")`,
      '',
    ];
  }

  private compilePolicy(mod: V2PolicyNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = ident(mod.name) + '_policy';

    return [
      `class ${className}:`,
      `${pad}"""Policy for ${mod.name}: allow/deny access checks."""`,
      '',
      `${pad}ALLOW = [${(mod.allow || []).map(pyStr).join(', ')}]`,
      `${pad}DENY = [${(mod.deny || []).map(pyStr).join(', ')}]`,
      '',
      `${pad}def check(self, action: str) -> bool:`,
      `${pad}${pad}"""Return True if the action is permitted."""`,
      `${pad}${pad}if action in self.DENY:`,
      `${pad}${pad}${pad}return False`,
      `${pad}${pad}if action in self.ALLOW:`,
      `${pad}${pad}${pad}return True`,
      `${pad}${pad}return False`,
      '',
    ];
  }
}