/**
 * LangGraph Target
 * 
 * Compiles MAM AST to LangGraph code.
 */

import { V2ModuleNode, V2AgentNode, V2WorkflowNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';
import { generateModuleContext } from '../context.js';

export class LangGraphTarget implements CompileTargetHandler {
  name = 'langgraph';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];
    const indent = config.indent || 4;

    lines.push('"""');
    lines.push('Generated by MAM Compiler');
    lines.push('Target: LangGraph');
    lines.push('"""');
    lines.push('');
    lines.push('from typing import TypedDict, Annotated');
    lines.push('from langgraph.graph import StateGraph, END');
    lines.push('from langgraph.graph.message import add_messages');
    lines.push('');

    for (const mod of modules) {
      lines.push(generateModuleContext(mod, 'langgraph'));
      lines.push('');
      lines.push(...this.compileModule(mod, indent, config));
      lines.push('');
    }

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];

    switch (mod.moduleType) {
      case 'agent':
        lines.push(...this.compileAgent(mod as unknown as V2AgentNode, indent, config));
        break;
      case 'workflow':
        lines.push(...this.compileWorkflow(mod as unknown as V2WorkflowNode, indent, config));
        break;
      case 'system':
        lines.push(...this.compileSystem(mod, indent, config));
        break;
      default:
        lines.push(`# Module: ${mod.name} (${mod.moduleType})`);
    }

    return lines;
  }

  private compileAgent(mod: V2AgentNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const funcName = mod.name.toLowerCase().replace(/[^a-z0-9_]/g, '_');

    return [
      `class ${mod.name}State(TypedDict):`,
      `${pad}messages: Annotated[list, add_messages]`,
      `${pad}next: str`,
      '',
      `async def ${funcName}(state: ${mod.name}State) -> ${mod.name}State:`,
      `${pad}"""${mod.goal || mod.role || mod.name}"""`,
      `${pad}# TODO: Implement ${mod.name}`,
      `${pad}return {"messages": [], "next": "end"}`,
      '',
    ];
  }

  private compileWorkflow(mod: V2WorkflowNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const graphName = mod.name.replace(/[^a-zA-Z0-9_]/g, '_');
    const lines: string[] = [];

    lines.push(`def build_${graphName.toLowerCase()}():`);
    lines.push(`${pad}"""Build the ${mod.name} workflow graph."""`);
    lines.push(`${pad}workflow = StateGraph(dict)`);
    lines.push('');

    // Add nodes
    if (mod.steps) {
      for (const step of mod.steps) {
        const nodeFunc = step.name.toLowerCase().replace(/[^a-z0-9_]/g, '_');
        lines.push(`${pad}workflow.add_node("${step.name}", ${nodeFunc})`);
      }
    }

    lines.push('');

    // Add edges
    if (mod.edges) {
      for (const edge of mod.edges) {
        lines.push(`${pad}workflow.add_edge("${edge.source}", "${edge.target}")`);
      }
    }

    lines.push('');

    // Set entry and exit
    if (mod.steps && mod.steps.length > 0) {
      lines.push(`${pad}workflow.set_entry_point("${mod.steps[0].name}")`);
      lines.push(`${pad}workflow.add_edge("${mod.steps[mod.steps.length - 1].name}", END)`);
    }

    lines.push('');
    lines.push(`${pad}return workflow.compile()`);
    lines.push('');

    return lines;
  }

  private compileSystem(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const lines: string[] = [];

    lines.push(`# System: ${mod.name}`);
    lines.push('');

    if (mod.agents && mod.agents.length > 0) {
      lines.push(`# Agents:`);
      for (const agent of mod.agents) {
        lines.push(`#   - ${agent}`);
      }
    }

    lines.push('');

    return lines;
  }
}