/**
 * OpenAI SDK Target
 * 
 * Compiles MAM AST to OpenAI Agents SDK code.
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';

export class OpenAITarget implements CompileTargetHandler {
  name = 'openai';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];
    const indent = config.indent || 4;

    lines.push('"""');
    lines.push('Generated by MAM Compiler');
    lines.push('Target: OpenAI Agents SDK');
    lines.push('"""');
    lines.push('');
    lines.push('from agents import Agent, Tool, function_tool');
    lines.push('from agents.run import Runner');
    lines.push('');

    for (const mod of modules) {
      lines.push(...this.compileModule(mod, indent, config));
      lines.push('');
    }

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];

    switch (mod.moduleType) {
      case 'agent':
        lines.push(...this.compileAgent(mod as V2AgentNode, indent, config));
        break;
      case 'tool':
        lines.push(...this.compileTool(mod as V2ToolNode, indent, config));
        break;
      case 'system':
        lines.push(...this.compileSystem(mod, indent, config));
        break;
      default:
        lines.push(...this.compileGeneric(mod, indent, config));
    }

    return lines;
  }

  private compileAgent(mod: V2AgentNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const varName = mod.name.toLowerCase().replace(/[^a-z0-9_]/g, '_');

    const lines: string[] = [];

    if (config.includeComments) {
      lines.push(`# Agent: ${mod.name}`);
      lines.push(`# Role: ${mod.role || 'N/A'}`);
      lines.push(`# Goal: ${mod.goal || 'N/A'}`);
      lines.push('');
    }

    // Tools
    if (mod.tools && mod.tools.length > 0) {
      for (const tool of mod.tools) {
        lines.push(`@function_tool`);
        lines.push(`def ${tool.toLowerCase()}() -> str:`);
        lines.push(`${pad}"""${tool} tool"""`);
        lines.push(`${pad}# TODO: Implement ${tool}`);
        lines.push(`${pad}return ""`);
        lines.push('');
      }
    }

    // Agent definition
    lines.push(`${varName} = Agent(`);
    lines.push(`${pad}name="${mod.name}",`);
    lines.push(`${pad}instructions="""${mod.goal || mod.role || ''}""",`);

    if (mod.tools && mod.tools.length > 0) {
      lines.push(`${pad}tools=[${mod.tools.map(t => t.toLowerCase()).join(', ')}],`);
    }

    lines.push(`)`);
    lines.push('');

    // Runner
    lines.push(`async def run_${varName}(task: str):`);
    lines.push(`${pad}"""Run the ${mod.name} agent."""`);
    lines.push(`${pad}result = await Runner.run(${varName}, task)`);
    lines.push(`${pad}return result`);
    lines.push('');

    return lines;
  }

  private compileTool(mod: V2ToolNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const funcName = mod.name.toLowerCase().replace(/[^a-z0-9_]/g, '_');

    return [
      `@function_tool`,
      `def ${funcName}() -> str:`,
      `${pad}"""${mod.name} tool (${mod.provider})"""`,
      `${pad}# TODO: Implement ${mod.name}`,
      `${pad}return ""`,
      '',
    ];
  }

  private compileSystem(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const lines: string[] = [];

    lines.push(`# System: ${mod.name}`);
    lines.push('');

    if (mod.agents && mod.agents.length > 0) {
      lines.push(`# Agents in system:`);
      for (const agent of mod.agents) {
        lines.push(`#   - ${agent}`);
      }
      lines.push('');
    }

    if (mod.edges && mod.edges.length > 0) {
      lines.push(`# Workflow edges:`);
      for (const edge of mod.edges) {
        lines.push(`#   ${edge.source} -> ${edge.target}`);
      }
      lines.push('');
    }

    lines.push(`async def run_${mod.name.toLowerCase().replace(/[^a-z0-9_]/g, '_')}():`);
    lines.push(`${pad}"""Run the ${mod.name} system."""`);
    lines.push(`${pad}# TODO: Implement system orchestration`);
    lines.push(`${pad}pass`);
    lines.push('');

    return lines;
  }

  private compileGeneric(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);

    return [
      `# Module: ${mod.name} (${mod.moduleType})`,
      '',
    ];
  }
}