/**
 * OpenAI SDK Target
 *
 * Compiles MAM AST to runnable Python using the `openai` package (v1+).
 * Each MAM agent becomes a real `OpenAI.chat.completions.create` call that
 * sends the module context (purpose + rules) as the system prompt. Tools are
 * registered as OpenAI function tools. A `main()` self-test guarded by
 * `if __name__ == "__main__"` is emitted at the end.
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2WorkflowNode, V2TeamNode, V2SystemNode, V2MemoryNode, V2PolicyNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig, TargetHandlerOutput } from '../compiler.js';
import { generateModuleContext } from '../context.js';
import { optimizePrompt } from './optimize.js';

function pyStr(value: unknown): string {
  const s = String(value ?? '');
  return `'${s
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')}'`;
}

function ident(name: string): string {
  let s = name.toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/^_+|_+$/g, '');
  if (!s) s = 'module';
  if (/^[0-9]/.test(s)) s = '_' + s;
  return s;
}

function runFn(name: string): string {
  return 'run_' + ident(name);
}

export class OpenAITarget implements CompileTargetHandler {
  name = 'openai';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string | TargetHandlerOutput {
    if (config.optimizeTokens) {
      return this.compileOptimized(modules, config);
    }
    return this.compileDefault(modules, config);
  }

  private compileDefault(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];
    const indent = config.indent || 4;
    const pad = ' '.repeat(indent);

    lines.push('"""');
    lines.push('Generated by MAM Compiler');
    lines.push('Target: OpenAI SDK (openai v1+)');
    lines.push('"""');
    lines.push('');
    lines.push('import json');
    lines.push('import os');
    lines.push('');
    lines.push('from openai import OpenAI');
    lines.push('');
    lines.push('MODEL = "gpt-4o"');
    lines.push('');
    lines.push('def _system_prompt(*parts: str) -> str:');
    lines.push(`${pad}"""Join non-empty prompt parts with a blank line."""`);
    lines.push(`${pad}return "\\n\\n".join(p for p in parts if p)`);
    lines.push('');

    let primary: string | null = null;
    for (const mod of modules) {
      lines.push(generateModuleContext(mod, 'openai'));
      lines.push('');
      lines.push(...this.compileModule(mod, indent, config));
      lines.push('');
      if (primary === null && (mod.moduleType === 'system' || mod.moduleType === 'agent')) {
        primary = runFn(mod.name);
      }
    }

    lines.push('def main() -> int:');
    if (primary) {
      lines.push(`${pad}api_key = os.environ.get("OPENAI_API_KEY")`);
      lines.push(`${pad}if not api_key:`);
      lines.push(`${pad}${pad}print("OPENAI_API_KEY is not set; skipping the live API call.")`);
      lines.push(`${pad}${pad}return 1`);
      lines.push(`${pad}client = OpenAI(api_key=api_key)`);
      lines.push(`${pad}task = "Execute the module and return the final result."`);
      lines.push(`${pad}result = ${primary}(task, client=client)`);
      lines.push(`${pad}print(result)`);
      lines.push(`${pad}return 0`);
    } else {
      lines.push(`${pad}print("No runnable module (system or agent) found in this MAM document.")`);
      lines.push(`${pad}return 0`);
    }
    lines.push('');
    lines.push('if __name__ == "__main__":');
    lines.push(`${pad}raise SystemExit(main())`);
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Emits the same program shape as the default path but with the prompt
   * content run through the token optimizer. The optimized text becomes a
   * module-level `SYSTEM_PROMPT` used by every runnable module.
   */
  private compileOptimized(modules: V2ModuleNode[], config: CompilerConfig): TargetHandlerOutput {
    const { optimizedText, tokenOptimization } = optimizePrompt(modules, 'openai');
    const lines: string[] = [];
    const indent = config.indent || 4;
    const pad = ' '.repeat(indent);

    lines.push('"""');
    lines.push('Generated by MAM Compiler');
    lines.push('Target: OpenAI SDK (openai v1+) [token-optimized]');
    lines.push('"""');
    lines.push('');
    lines.push('import json');
    lines.push('import os');
    lines.push('');
    lines.push('from openai import OpenAI');
    lines.push('');
    lines.push('MODEL = "gpt-4o"');
    lines.push('');
    lines.push('def _system_prompt(*parts: str) -> str:');
    lines.push(`${pad}"""Join non-empty prompt parts with a blank line."""`);
    lines.push(`${pad}return "\\n\\n".join(p for p in parts if p)`);
    lines.push('');
    lines.push(`SYSTEM_PROMPT = ${pyStr(optimizedText)}`);
    lines.push('');

    let primary: string | null = null;
    for (const mod of modules) {
      if (primary === null && (mod.moduleType === 'system' || mod.moduleType === 'agent')) {
        primary = runFn(mod.name);
      }
      lines.push(...this.compileOptimizedModule(mod, indent, config));
      lines.push('');
    }

    lines.push('def main() -> int:');
    if (primary) {
      lines.push(`${pad}api_key = os.environ.get("OPENAI_API_KEY")`);
      lines.push(`${pad}if not api_key:`);
      lines.push(`${pad}${pad}print("OPENAI_API_KEY is not set; skipping the live API call.")`);
      lines.push(`${pad}${pad}return 1`);
      lines.push(`${pad}client = OpenAI(api_key=api_key)`);
      lines.push(`${pad}task = "Execute the module and return the final result."`);
      lines.push(`${pad}result = ${primary}(task, client=client)`);
      lines.push(`${pad}print(result)`);
      lines.push(`${pad}return 0`);
    } else {
      lines.push(`${pad}print("No runnable module (system or agent) found in this MAM document.")`);
      lines.push(`${pad}return 0`);
    }
    lines.push('');
    lines.push('if __name__ == "__main__":');
    lines.push(`${pad}raise SystemExit(main())`);
    lines.push('');

    return { output: lines.join('\n'), tokenOptimization };
  }

  private compileOptimizedModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    switch (mod.moduleType) {
      case 'tool':
        return this.compileTool(mod as unknown as V2ToolNode, indent, config);
      case 'memory':
        return this.compileMemory(mod as unknown as V2MemoryNode, indent, config);
      case 'policy':
        return this.compilePolicy(mod as unknown as V2PolicyNode, indent, config);
      default:
        return this.compileOptimizedRunnable(mod, indent);
    }
  }

  private compileOptimizedRunnable(mod: V2ModuleNode, indent: number): string[] {
    const pad = ' '.repeat(indent);
    const fn = runFn(mod.name);

    return [
      `def ${fn}(task: str, *, client: OpenAI | None = None, model: str = MODEL) -> str:`,
      `${pad}"""${mod.description || mod.name} via the OpenAI SDK (token-optimized)."""`,
      `${pad}if client is None:`,
      `${pad}${pad}client = OpenAI()`,
      `${pad}prompt = _system_prompt(SYSTEM_PROMPT)`,
      `${pad}messages = [`,
      `${pad}${pad}{"role": "system", "content": prompt},`,
      `${pad}${pad}{"role": "user", "content": task},`,
      `${pad}]`,
      `${pad}kwargs: dict = {"model": model, "messages": messages}`,
      `${pad}response = client.chat.completions.create(**kwargs)`,
      `${pad}return response.choices[0].message.content or ""`,
      '',
    ];
  }

  private compileModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];

    switch (mod.moduleType) {
      case 'agent':
        lines.push(...this.compileAgent(mod as unknown as V2AgentNode, indent, config));
        break;
      case 'tool':
        lines.push(...this.compileTool(mod as unknown as V2ToolNode, indent, config));
        break;
      case 'workflow':
        lines.push(...this.compileWorkflow(mod as unknown as V2WorkflowNode, indent, config));
        break;
      case 'team':
        lines.push(...this.compileTeam(mod as unknown as V2TeamNode, indent, config));
        break;
      case 'system':
        lines.push(...this.compileSystem(mod as unknown as V2SystemNode, indent, config));
        break;
      case 'memory':
        lines.push(...this.compileMemory(mod as unknown as V2MemoryNode, indent, config));
        break;
      case 'policy':
        lines.push(...this.compilePolicy(mod as unknown as V2PolicyNode, indent, config));
        break;
      default:
        lines.push(...this.compileGeneric(mod, indent, config));
    }

    return lines;
  }

  private compileAgent(mod: V2AgentNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = runFn(mod.name);
    const lines: string[] = [];

    if (config.includeComments) {
      lines.push(`# Agent: ${mod.name}`);
      lines.push(`# Role: ${mod.role || 'N/A'}`);
      lines.push(`# Goal: ${mod.goal || 'N/A'}`);
      lines.push('');
    }

    const parts: string[] = [`${mod.name} agent`];
    if (mod.role) parts.push(`Role: ${mod.role}`);
    if (mod.goal) parts.push(`Goal: ${mod.goal}`);
    if (mod.handoff && mod.handoff.length > 0) parts.push(`Handoff: ${mod.handoff.join(', ')}`);

    lines.push(`def ${fn}(task: str, *, client: OpenAI | None = None, model: str = MODEL) -> str:`);
    lines.push(`${pad}"""${mod.name} agent via the OpenAI SDK."""`);
    lines.push(`${pad}if client is None:`);
    lines.push(`${pad}${pad}client = OpenAI()`);
    lines.push(`${pad}parts = [${parts.map(pyStr).join(', ')}]`);
    if (mod.rules && mod.rules.length > 0) {
      lines.push(`${pad}rules = [${mod.rules.map(pyStr).join(', ')}]`);
      lines.push(`${pad}if rules:`);
      lines.push(`${pad}${pad}parts.append("Rules:\\n" + "\\n".join("- " + r for r in rules))`);
    }
    lines.push(`${pad}prompt = _system_prompt(*parts)`);
    lines.push(`${pad}messages = [`);
    lines.push(`${pad}${pad}{"role": "system", "content": prompt},`);
    lines.push(`${pad}${pad}{"role": "user", "content": task},`);
    lines.push(`${pad}]`);
    lines.push(`${pad}kwargs: dict = {"model": model, "messages": messages}`);
    if (mod.tools && mod.tools.length > 0) {
      const schemas = mod.tools.map(t =>
        `{"type": "function", "function": {"name": ${pyStr(ident(t))}, "description": ${pyStr(`${t} tool`)}, "parameters": {"type": "object", "properties": {}}}}`,
      );
      lines.push(`${pad}tools = [${schemas.join(', ')}]`);
      lines.push(`${pad}if tools:`);
      lines.push(`${pad}${pad}kwargs["tools"] = tools`);
    }
    lines.push(`${pad}response = client.chat.completions.create(**kwargs)`);
    lines.push(`${pad}return response.choices[0].message.content or ""`);
    lines.push('');

    return lines;
  }

  private compileTool(mod: V2ToolNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = ident(mod.name);
    const provider = mod.provider || 'unknown';

    return [
      `def ${fn}(**kwargs: object) -> str:`,
      `${pad}"""${mod.name} tool (provider: ${provider})."""`,
      `${pad}return json.dumps({"tool": ${pyStr(mod.name)}, "action": kwargs}, sort_keys=True)`,
      '',
      `def ${fn}_schema() -> dict:`,
      `${pad}"""OpenAI function schema for ${mod.name}."""`,
      `${pad}return {`,
      `${pad}${pad}"type": "function",`,
      `${pad}${pad}"function": {`,
      `${pad}${pad}${pad}"name": ${pyStr(fn)},`,
      `${pad}${pad}${pad}"description": ${pyStr(`${mod.name} tool (${provider})`)},`,
      `${pad}${pad}${pad}"parameters": {"type": "object", "properties": {}},`,
      `${pad}${pad}},`,
      `${pad}}`,
      '',
    ];
  }

  private compileWorkflow(mod: V2WorkflowNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = runFn(mod.name);
    const steps = (mod.steps || []).map(s => ident(s.name)).filter(Boolean);

    return [
      `def ${fn}(task: str, *, client: OpenAI | None = None, model: str = MODEL) -> str:`,
      `${pad}"""${mod.name} workflow orchestrated via the OpenAI SDK."""`,
      `${pad}if client is None:`,
      `${pad}${pad}client = OpenAI()`,
      `${pad}steps = [${steps.map(pyStr).join(', ')}]`,
      `${pad}parts = [${pyStr(`${mod.name} workflow`)}]`,
      `${pad}if steps:`,
      `${pad}${pad}parts.append("Steps:\\n" + "\\n".join("- " + s for s in steps))`,
      `${pad}prompt = _system_prompt(*parts)`,
      `${pad}response = client.chat.completions.create(`,
      `${pad}${pad}model=model,`,
      `${pad}${pad}messages=[`,
      `${pad}${pad}${pad}{"role": "system", "content": prompt},`,
      `${pad}${pad}${pad}{"role": "user", "content": task},`,
      `${pad}${pad}],`,
      `${pad})`,
      `${pad}return response.choices[0].message.content or ""`,
      '',
    ];
  }

  private compileTeam(mod: V2TeamNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = runFn(mod.name);
    const members = (mod.members || []).map(String);

    return [
      `def ${fn}(task: str, *, client: OpenAI | None = None, model: str = MODEL) -> str:`,
      `${pad}"""${mod.name} team coordinated via the OpenAI SDK."""`,
      `${pad}if client is None:`,
      `${pad}${pad}client = OpenAI()`,
      `${pad}members = [${members.map(pyStr).join(', ')}]`,
      `${pad}parts = [${pyStr(`${mod.name} team`)}]`,
      `${pad}if members:`,
      `${pad}${pad}parts.append("Members:\\n" + "\\n".join("- " + m for m in members))`,
      `${pad}prompt = _system_prompt(*parts)`,
      `${pad}response = client.chat.completions.create(`,
      `${pad}${pad}model=model,`,
      `${pad}${pad}messages=[`,
      `${pad}${pad}${pad}{"role": "system", "content": prompt},`,
      `${pad}${pad}${pad}{"role": "user", "content": task},`,
      `${pad}${pad}],`,
      `${pad})`,
      `${pad}return response.choices[0].message.content or ""`,
      '',
    ];
  }

  private compileSystem(mod: V2SystemNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = runFn(mod.name);
    const modules = (mod.modules || []).map(String);

    return [
      `def ${fn}(task: str, *, client: OpenAI | None = None, model: str = MODEL) -> str:`,
      `${pad}"""${mod.name} system orchestrator via the OpenAI SDK."""`,
      `${pad}if client is None:`,
      `${pad}${pad}client = OpenAI()`,
      `${pad}modules = [${modules.map(pyStr).join(', ')}]`,
      `${pad}parts = [${pyStr(`${mod.name}: ${mod.description || 'System composition'}`)}]`,
      `${pad}if modules:`,
      `${pad}${pad}parts.append("Modules to orchestrate:\\n" + "\\n".join("- " + m for m in modules))`,
      `${pad}prompt = _system_prompt(*parts)`,
      `${pad}response = client.chat.completions.create(`,
      `${pad}${pad}model=model,`,
      `${pad}${pad}messages=[`,
      `${pad}${pad}${pad}{"role": "system", "content": prompt},`,
      `${pad}${pad}${pad}{"role": "user", "content": task},`,
      `${pad}${pad}],`,
      `${pad})`,
      `${pad}return response.choices[0].message.content or ""`,
      '',
    ];
  }

  private compileMemory(mod: V2MemoryNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = ident(mod.name) + '_memory';

    return [
      `class ${className}:`,
      `${pad}"""In-memory store for the ${mod.name} memory module (${mod.format} / ${mod.backend})."""`,
      '',
      `${pad}def __init__(self):`,
      `${pad}${pad}self.format = ${pyStr(mod.format)}`,
      `${pad}${pad}self.backend = ${pyStr(mod.backend)}`,
      `${pad}${pad}self.scope = ${pyStr(mod.scope || 'module')}`,
      `${pad}${pad}self._store: dict = {}`,
      '',
      `${pad}def store(self, key: str, value: str) -> None:`,
      `${pad}${pad}"""Store a value under a key."""`,
      `${pad}${pad}self._store[key] = value`,
      '',
      `${pad}def retrieve(self, key: str) -> str:`,
      `${pad}${pad}"""Retrieve a value by key."""`,
      `${pad}${pad}return self._store.get(key, "")`,
      '',
    ];
  }

  private compilePolicy(mod: V2PolicyNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const className = ident(mod.name) + '_policy';

    return [
      `class ${className}:`,
      `${pad}"""Policy for ${mod.name}: allow/deny access checks."""`,
      '',
      `${pad}ALLOW = [${(mod.allow || []).map(pyStr).join(', ')}]`,
      `${pad}DENY = [${(mod.deny || []).map(pyStr).join(', ')}]`,
      '',
      `${pad}def check(self, action: str) -> bool:`,
      `${pad}${pad}"""Return True if the action is permitted."""`,
      `${pad}${pad}if action in self.DENY:`,
      `${pad}${pad}${pad}return False`,
      `${pad}${pad}if action in self.ALLOW:`,
      `${pad}${pad}${pad}return True`,
      `${pad}${pad}return False`,
      '',
    ];
  }

  private compileGeneric(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const fn = runFn(mod.name);

    return [
      `def ${fn}(task: str, *, client: OpenAI | None = None, model: str = MODEL) -> str:`,
      `${pad}"""${mod.description || mod.name} via the OpenAI SDK."""`,
      `${pad}if client is None:`,
      `${pad}${pad}client = OpenAI()`,
      `${pad}parts = [${pyStr(mod.description || mod.name)}]`,
      `${pad}prompt = _system_prompt(*parts)`,
      `${pad}response = client.chat.completions.create(`,
      `${pad}${pad}model=model,`,
      `${pad}${pad}messages=[`,
      `${pad}${pad}${pad}{"role": "system", "content": prompt},`,
      `${pad}${pad}${pad}{"role": "user", "content": task},`,
      `${pad}${pad}],`,
      `${pad})`,
      `${pad}return response.choices[0].message.content or ""`,
      '',
    ];
  }
}