/**
 * Rust Target
 * 
 * Compiles MAM AST to Rust code.
 * Production-grade implementation with full type system, error handling, and async support.
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2MemoryNode, V2WorkflowNode, V2TeamNode, V2PolicyNode, V2SystemNode, V2StepNode, V2EdgeNode, V2PortDefinition, V2PermissionSet } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';

// ============================================================================
// Rust Target
// ============================================================================

export class RustTarget implements CompileTargetHandler {
  name = 'rust';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];
    const indent = config.indent || 4;

    lines.push('//! Generated by MAM Compiler');
    lines.push('//! Target: Rust');
    lines.push('//!');
    lines.push('//! This crate implements the MAM module system in Rust.');
    lines.push('');
    lines.push('use std::collections::HashMap;');
    lines.push('use std::error::Error;');
    lines.push('use std::fmt;');
    lines.push('');

    // Generate error enum
    lines.push(...this.generateErrorEnum(indent));
    lines.push('');

    // Generate modules
    for (const mod of modules) {
      lines.push(...this.compileModule(mod, indent, config));
      lines.push('');
    }

    // Generate traits
    lines.push(...this.generateTraits(indent));
    lines.push('');

    // Generate main function if system
    const system = modules.find(m => m.moduleType === 'system');
    if (system) {
      lines.push(...this.generateMain(system as unknown as V2SystemNode, indent));
    }

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];
    const pad = ' '.repeat(indent);
    const structName = this.toPascalCase(mod.name);

    switch (mod.moduleType) {
      case 'agent':
        lines.push(...this.compileAgent(mod as unknown as V2AgentNode, indent, config));
        break;
      case 'tool':
        lines.push(...this.compileTool(mod as unknown as V2ToolNode, indent, config));
        break;
      case 'memory':
        lines.push(...this.compileMemory(mod as unknown as V2MemoryNode, indent, config));
        break;
      case 'workflow':
        lines.push(...this.compileWorkflow(mod as unknown as V2WorkflowNode, indent, config));
        break;
      case 'team':
        lines.push(...this.compileTeam(mod as unknown as V2TeamNode, indent, config));
        break;
      case 'policy':
        lines.push(...this.compilePolicy(mod as unknown as V2PolicyNode, indent, config));
        break;
      case 'system':
        lines.push(...this.compileSystem(mod as unknown as V2SystemNode, indent, config));
        break;
      default:
        lines.push(...this.compileGeneric(mod, indent, config));
    }

    return lines;
  }

  private compileAgent(mod: V2AgentNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const structName = this.toPascalCase(mod.name);
    const lines: string[] = [];

    if (config.includeComments) {
      lines.push(`/// Agent: ${mod.name}`);
      lines.push(`/// Role: ${mod.role || 'N/A'}`);
      lines.push(`/// Goal: ${mod.goal || 'N/A'}`);
      lines.push('');
    }

    // Struct definition
    lines.push(`#[derive(Debug, Clone)]`);
    lines.push(`pub struct ${structName} {`);
    lines.push(`${pad}pub role: String,`);
    lines.push(`${pad}pub goal: String,`);
    if (mod.tools && mod.tools.length > 0) {
      lines.push(`${pad}pub tools: Vec<String>,`);
    }
    if (mod.handoff && mod.handoff.length > 0) {
      lines.push(`${pad}pub handoff: Vec<String>,`);
    }
    lines.push(`${pad}pub memory: Option<String>,`);
    lines.push(`}`);
    lines.push('');

    // Implementation
    lines.push(`impl ${structName} {`);
    lines.push(`${pad}/// Create a new ${structName}`);
    lines.push(`${pad}pub fn new(role: &str, goal: &str) -> Self {`);
    lines.push(`${pad}${pad}Self {`);
    lines.push(`${pad}${pad}${pad}role: role.to_string(),`);
    lines.push(`${pad}${pad}${pad}goal: goal.to_string(),`);
    if (mod.tools && mod.tools.length > 0) {
      lines.push(`${pad}${pad}${pad}tools: vec![${mod.tools.map(t => `"${t}"`.toString()).join(', ')}],`);
    }
    if (mod.handoff && mod.handoff.length > 0) {
      lines.push(`${pad}${pad}${pad}handoff: vec![${mod.handoff.map(t => `"${t}"`.toString()).join(', ')}],`);
    }
    lines.push(`${pad}${pad}${pad}memory: None,`);
    lines.push(`${pad}${pad}}`);
    lines.push(`${pad}}`);
    lines.push('');

    // Execute method
    lines.push(`${pad}/// Execute a task`);
    lines.push(`${pad}pub async fn execute(&self, task: &str) -> Result<String, MAMError> {`);
    lines.push(`${pad}${pad}log::info!("Executing task: {}", task);`);
    lines.push(`${pad}${pad}Err(MAMError::NotImplemented("execute".to_string()))`);
    lines.push(`${pad}}`);
    lines.push('');

    // Handoff method
    if (mod.handoff && mod.handoff.length > 0) {
      lines.push(`${pad}/// Handoff to another agent`);
      lines.push(`${pad}pub fn handoff_to(&self, target: &str) -> bool {`);
      lines.push(`${pad}${pad}self.handoff.contains(&target.to_string())`);
      lines.push(`${pad}}`);
      lines.push('');
    }

    // Getters
    lines.push(`${pad}/// Get agent role`);
    lines.push(`${pad}pub fn role(&self) -> &str { &self.role }`);
    lines.push('');
    lines.push(`${pad}/// Get agent goal`);
    lines.push(`${pad}pub fn goal(&self) -> &str { &self.goal }`);
    lines.push('');

    lines.push(`}`);
    lines.push('');

    // Implement Display
    lines.push(`impl fmt::Display for ${structName} {`);
    lines.push(`${pad}fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {`);
    lines.push(`${pad}${pad}write!(f, "${structName} {{ role: {}, goal: {} }}", self.role, self.goal)`);
    lines.push(`${pad}}`);
    lines.push(`}`);
    lines.push('');

    // Implement FromStr
    lines.push(`impl std::str::FromStr for ${structName} {`);
    lines.push(`${pad}type Err = MAMError;`);
    lines.push('');
    lines.push(`${pad}fn from_str(s: &str) -> Result<Self, Self::Err> {`);
    lines.push(`${pad}${pad}let parts: Vec<&str> = s.split(',').collect();`);
    lines.push(`${pad}${pad}if parts.len() < 2 {`);
    lines.push(`${pad}${pad}${pad}return Err(MAMError::ParseError("Invalid format".to_string()));`);
    lines.push(`${pad}${pad}}`);
    lines.push(`${pad}${pad}Ok(Self::new(parts[0].trim(), parts[1].trim()))`);
    lines.push(`${pad}}`);
    lines.push(`}`);

    return lines;
  }

  private compileTool(mod: V2ToolNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const structName = this.toPascalCase(mod.name) + 'Tool';
    const lines: string[] = [];

    lines.push(`/// Tool: ${mod.name}`);
    lines.push(`#[derive(Debug, Clone)]`);
    lines.push(`pub struct ${structName} {`);
    lines.push(`${pad}pub provider: String,`);
    if (mod.capabilities && mod.capabilities.length > 0) {
      lines.push(`${pad}pub capabilities: Vec<String>,`);
    }
    lines.push(`${pad}pub permissions: HashMap<String, String>,`);
    lines.push(`}`);
    lines.push('');

    lines.push(`impl ${structName} {`);
    lines.push(`${pad}pub fn new(provider: &str) -> Self {`);
    lines.push(`${pad}${pad}let mut permissions = HashMap::new();`);
    if (mod.permissions) {
      if (mod.permissions.network) lines.push(`${pad}${pad}permissions.insert("network".to_string(), "${mod.permissions.network}".to_string());`);
      if (mod.permissions.filesystem) lines.push(`${pad}${pad}permissions.insert("filesystem".to_string(), "${mod.permissions.filesystem}".to_string());`);
    }
    lines.push(`${pad}${pad}Self {`);
    lines.push(`${pad}${pad}${pad}provider: provider.to_string(),`);
    if (mod.capabilities && mod.capabilities.length > 0) {
      lines.push(`${pad}${pad}${pad}capabilities: vec![${mod.capabilities.map(c => `"${c}"`.toString()).join(', ')}],`);
    }
    lines.push(`${pad}${pad}${pad}permissions,`);
    lines.push(`${pad}${pad}}`);
    lines.push(`${pad}}`);
    lines.push('');
    lines.push(`${pad}pub fn execute(&self, action: &str) -> Result<String, MAMError> {`);
    lines.push(`${pad}${pad}Err(MAMError::NotImplemented("execute".to_string()))`);
    lines.push(`${pad}}`);
    lines.push(`}`);

    return lines;
  }

  private compileMemory(mod: V2MemoryNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const structName = this.toPascalCase(mod.name) + 'Memory';
    const lines: string[] = [];

    lines.push(`/// Memory: ${mod.name}`);
    lines.push(`#[derive(Debug, Clone)]`);
    lines.push(`pub struct ${structName} {`);
    lines.push(`${pad}pub format: String,`);
    lines.push(`${pad}pub backend: String,`);
    lines.push(`${pad}pub scope: String,`);
    lines.push(`${pad}pub store: HashMap<String, serde_json::Value>,`);
    lines.push(`}`);
    lines.push('');

    lines.push(`impl ${structName} {`);
    lines.push(`${pad}pub fn new(format: &str, backend: &str, scope: &str) -> Self {`);
    lines.push(`${pad}${pad}Self {`);
    lines.push(`${pad}${pad}${pad}format: format.to_string(),`);
    lines.push(`${pad}${pad}${pad}backend: backend.to_string(),`);
    lines.push(`${pad}${pad}${pad}scope: scope.to_string(),`);
    lines.push(`${pad}${pad}${pad}store: HashMap::new(),`);
    lines.push(`${pad}${pad}}`);
    lines.push(`${pad}}`);
    lines.push('');
    lines.push(`${pad}pub fn store(&mut self, key: &str, value: serde_json::Value) {`);
    lines.push(`${pad}${pad}self.store.insert(key.to_string(), value);`);
    lines.push(`${pad}}`);
    lines.push('');
    lines.push(`${pad}pub fn retrieve(&self, key: &str) -> Option<&serde_json::Value> {`);
    lines.push(`${pad}${pad}self.store.get(key)`);
    lines.push(`${pad}}`);
    lines.push(`}`);

    return lines;
  }

  private compileWorkflow(mod: V2WorkflowNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const structName = this.toPascalCase(mod.name) + 'Workflow';
    const lines: string[] = [];

    lines.push(`/// Workflow: ${mod.name}`);
    lines.push(`#[derive(Debug, Clone)]`);
    lines.push(`pub struct ${structName} {`);
    lines.push(`${pad}pub steps: Vec<String>,`);
    lines.push(`${pad}pub edges: Vec<(String, String)>,`);
    lines.push(`}`);
    lines.push('');

    lines.push(`impl ${structName} {`);
    lines.push(`${pad}pub fn new() -> Self {`);
    lines.push(`${pad}${pad}Self {`);
    lines.push(`${pad}${pad}${pad}steps: vec![${mod.steps?.map(s => `"${s.name}"`.toString()).join(', ') || ""}],`);
    lines.push(`${pad}${pad}${pad}edges: vec![${mod.edges?.map(e => `("${e.source}", "${e.target}")`.toString()).join(', ') || ""}],`);
    lines.push(`${pad}${pad}}`);
    lines.push(`${pad}}`);
    lines.push('');
    lines.push(`${pad}pub async fn execute(&self) -> Result<(), MAMError> {`);
    lines.push(`${pad}${pad}for step in &self.steps {`);
    lines.push(`${pad}${pad}${pad}log::info!("Executing step: {}", step);`);
    lines.push(`${pad}${pad}}`);
    lines.push(`${pad}${pad}Ok(())`);
    lines.push(`${pad}}`);
    lines.push(`}`);

    return lines;
  }

  private compileTeam(mod: V2TeamNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const structName = this.toPascalCase(mod.name) + 'Team';
    const lines: string[] = [];

    lines.push(`/// Team: ${mod.name}`);
    lines.push(`#[derive(Debug, Clone)]`);
    lines.push(`pub struct ${structName} {`);
    lines.push(`${pad}pub members: Vec<String>,`);
    if (mod.policy) lines.push(`${pad}pub policy: Option<String>,`);
    lines.push(`}`);
    lines.push('');

    lines.push(`impl ${structName} {`);
    lines.push(`${pad}pub fn new(members: Vec<&str>) -> Self {`);
    lines.push(`${pad}${pad}Self {`);
    lines.push(`${pad}${pad}${pad}members: members.into_iter().map(String::from).collect(),`);
    lines.push(`${pad}${pad}${pad}policy: None,`);
    lines.push(`${pad}${pad}}`);
    lines.push(`${pad}}`);
    lines.push('');
    lines.push(`${pad}pub fn coordinate(&self) -> Result<(), MAMError> {`);
    lines.push(`${pad}${pad}for member in &self.members {`);
    lines.push(`${pad}${pad}${pad}log::info!("Coordinating: {}", member);`);
    lines.push(`${pad}${pad}}`);
    lines.push(`${pad}${pad}Ok(())`);
    lines.push(`${pad}}`);
    lines.push(`}`);

    return lines;
  }

  private compilePolicy(mod: V2PolicyNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const structName = this.toPascalCase(mod.name) + 'Policy';
    const lines: string[] = [];

    lines.push(`/// Policy: ${mod.name}`);
    lines.push(`#[derive(Debug, Clone)]`);
    lines.push(`pub struct ${structName} {`);
    lines.push(`${pad}pub allow: Vec<String>,`);
    lines.push(`${pad}pub deny: Vec<String>,`);
    lines.push(`}`);
    lines.push('');

    lines.push(`impl ${structName} {`);
    lines.push(`${pad}pub fn new(allow: Vec<&str>, deny: Vec<&str>) -> Self {`);
    lines.push(`${pad}${pad}Self {`);
    lines.push(`${pad}${pad}${pad}allow: allow.into_iter().map(String::from).collect(),`);
    lines.push(`${pad}${pad}${pad}deny: deny.into_iter().map(String::from).collect(),`);
    lines.push(`${pad}${pad}}`);
    lines.push(`${pad}}`);
    lines.push('');
    lines.push(`${pad}pub fn check(&self, action: &str) -> bool {`);
    lines.push(`${pad}${pad}if self.deny.contains(&action.to_string()) {`);
    lines.push(`${pad}${pad}${pad}return false;`);
    lines.push(`${pad}${pad}}`);
    lines.push(`${pad}${pad}self.allow.contains(&action.to_string())`);
    lines.push(`${pad}}`);
    lines.push(`}`);

    return lines;
  }

  private compileSystem(mod: V2SystemNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const structName = this.toPascalCase(mod.name) + 'System';
    const lines: string[] = [];

    lines.push(`/// System: ${mod.name}`);
    lines.push(`#[derive(Debug, Clone)]`);
    lines.push(`pub struct ${structName} {`);
    lines.push(`${pad}pub agents: Vec<String>,`);
    lines.push(`${pad}pub modules: Vec<String>,`);
    lines.push(`${pad}pub edges: Vec<(String, String)>,`);
    lines.push(`}`);
    lines.push('');

    lines.push(`impl ${structName} {`);
    lines.push(`${pad}pub fn new() -> Self {`);
    lines.push(`${pad}${pad}Self {`);
    lines.push(`${pad}${pad}${pad}agents: vec![${mod.agents?.map(a => `"${a}"`.toString()).join(', ') || ""}],`);
    lines.push(`${pad}${pad}${pad}modules: vec![${mod.modules?.map(m => `"${m}"`.toString()).join(', ') || ""}],`);
    lines.push(`${pad}${pad}${pad}edges: vec![${mod.edges?.map(e => `("${e.source}", "${e.target}")`.toString()).join(', ') || ""}],`);
    lines.push(`${pad}${pad}}`);
    lines.push(`${pad}}`);
    lines.push('');
    lines.push(`${pad}pub async fn run(&self) -> Result<(), MAMError> {`);
    lines.push(`${pad}${pad}log::info!("Running system: {}", stringify!(${structName}));`);
    lines.push(`${pad}${pad}Ok(())`);
    lines.push(`${pad}}`);
    lines.push(`}`);

    return lines;
  }

  private compileGeneric(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const structName = this.toPascalCase(mod.name);

    return [
      `/// Module: ${mod.name}`,
      `#[derive(Debug, Clone)]`,
      `pub struct ${structName} {`,
      `${pad}pub name: String,`,
      `}`,
      '',
      `impl ${structName} {`,
      `${pad}pub fn new(name: &str) -> Self {`,
      `${pad}${pad}Self { name: name.to_string() }`,
      `${pad}}`,
      `}`,
    ];
  }

  private generateErrorEnum(indent: number): string[] {
    const pad = ' '.repeat(indent);
    return [
      '/// MAM Error types',
      '#[derive(Debug, Clone)]',
      'pub enum MAMError {',
      `${pad}ParseError(String),`,
      `${pad}ValidationError(String),`,
      `${pad}CompilationError(String),`,
      `${pad}RuntimeError(String),`,
      `${pad}NotImplemented(String),`,
      `${pad}IoError(std::io::Error),`,
      `${pad}JsonError(serde_json::Error),`,
      '}',
      '',
      'impl fmt::Display for MAMError {',
      `${pad}fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {`,
      `${pad}${pad}match self {`,
      `${pad}${pad}${pad}MAMError::ParseError(e) => write!(f, "Parse error: {}", e),`,
      `${pad}${pad}${pad}MAMError::ValidationError(e) => write!(f, "Validation error: {}", e),`,
      `${pad}${pad}${pad}MAMError::CompilationError(e) => write!(f, "Compilation error: {}", e),`,
      `${pad}${pad}${pad}MAMError::RuntimeError(e) => write!(f, "Runtime error: {}", e),`,
      `${pad}${pad}${pad}MAMError::NotImplemented(e) => write!(f, "Not implemented: {}", e),`,
      `${pad}${pad}${pad}MAMError::IoError(e) => write!(f, "IO error: {}", e),`,
      `${pad}${pad}${pad}MAMError::JsonError(e) => write!(f, "JSON error: {}", e),`,
      `${pad}${pad}}`,
      `${pad}}`,
      '}',
      '',
      'impl Error for MAMError {}',
      '',
      'impl From<std::io::Error> for MAMError {',
      `${pad}fn from(e: std::io::Error) -> Self {`,
      `${pad}${pad}MAMError::IoError(e)`,
      `${pad}}`,
      '}',
      '',
      'impl From<serde_json::Error> for MAMError {',
      `${pad}fn from(e: serde_json::Error) -> Self {`,
      `${pad}${pad}MAMError::JsonError(e)`,
      `${pad}}`,
      '}',
    ];
  }

  private generateTraits(indent: number): string[] {
    const pad = ' '.repeat(indent);
    return [
      '/// Trait for executable modules',
      '#[async_trait::async_trait]',
      'pub trait Executable {',
      `${pad}async fn execute(&self, input: &str) -> Result<String, MAMError>;`,
      '}',
      '',
      '/// Trait for modules with memory',
      'pub trait HasMemory {',
      `${pad}fn store(&mut self, key: &str, value: serde_json::Value);`,
      `${pad}fn retrieve(&self, key: &str) -> Option<&serde_json::Value>;`,
      '}',
      '',
      '/// Trait for modules with permissions',
      'pub trait HasPermissions {',
      `${pad}fn check_permission(&self, action: &str) -> bool;`,
      `${pad}fn get_allowed(&self) -> &[String];`,
      `${pad}fn get_denied(&self) -> &[String];`,
      '}',
    ];
  }

  private generateMain(system: V2SystemNode, indent: number): string[] {
    const pad = ' '.repeat(indent);
    const structName = this.toPascalCase(system.name) + 'System';

    return [
      '#[tokio::main]',
      'async fn main() -> Result<(), Box<dyn std::error::Error>> {',
      `${pad}env_logger::init();`,
      `${pad}log::info!("Starting ${system.name} system");`,
      '',
      `${pad}let system = ${structName}::new();`,
      `${pad}system.run().await?;`,
      '',
      `${pad}Ok(())`,
      '}',
    ];
  }

  private toPascalCase(str: string): string {
    return str
      .replace(/[^a-zA-Z0-9\s]/g, '')
      .split(/\s+/)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
  }
}