/**
 * Rust Target
 *
 * Compiles MAM AST to Rust code.
 * Emits a complete, runnable crate using only the standard library: an error
 * type, shared result/port types, one struct per module with concrete
 * behaviour, and a `fn main()` that instantiates and runs every module.
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2MemoryNode, V2WorkflowNode, V2TeamNode, V2PolicyNode, V2SystemNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';
import { generateModuleContext } from '../context.js';

export class RustTarget implements CompileTargetHandler {
  name = 'rust';

  private demoCounter = 0;

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];
    const indent = config.indent || 4;
    this.demoCounter = 0;

    lines.push('//! Generated by MAM Compiler');
    lines.push('//! Target: Rust');
    lines.push('//!');
    lines.push('//! This crate implements the MAM module system in Rust using only std.');
    lines.push('//!');
    lines.push('//! Compile: rustc out.rs && out.exe');
    lines.push('');
    lines.push('use std::collections::{HashMap, VecDeque};');
    lines.push('use std::fmt;');
    lines.push('');

    // Error type
    lines.push(...this.generateError(indent));
    lines.push('');

    // Shared types
    lines.push(...this.generateSharedTypes(indent));
    lines.push('');

    // Module structs
    for (const mod of modules) {
      const ctx = generateModuleContext(mod, 'rust')
        .split('\n')
        .map(l => l.replace(/^\/\/!/, '//'))
        .map(l => (l === '' ? '' : (l.startsWith('//') ? l : `// ${l}`)));
      lines.push(...ctx);
      lines.push('');
      lines.push(...this.compileModule(mod, indent, config).code);
      lines.push('');
    }

    // Registry
    lines.push(...this.generateRegistry(modules, indent));

    // main
    lines.push(...this.generateMain(modules, indent));

    return lines.join('\n');
  }

  private generateRegistry(modules: V2ModuleNode[], indent: number): string[] {
    const pad = ' '.repeat(indent);
    return [
      '// ===== Registry =====',
      '/// Lists every compiled module by name and type.',
      `fn registry() -> Vec<&'static str> {`,
      `${pad}vec![`,
      ...modules.map(m => `${pad}${pad}"${this.esc(`${m.name} (${m.moduleType})`)}",`),
      `${pad}]`,
      '}',
      '',
    ];
  }

  private compileModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const lines: string[] = [];

    if (config.includeComments) {
      lines.push(`// Module: ${mod.name}`);
      lines.push(`// Type: ${mod.moduleType}`);
      if (mod.description) {
        for (const dl of mod.description.split('\n')) lines.push(`// ${dl}`);
      }
      lines.push('');
    }

    let code: string[];
    let demo: string[];

    switch (mod.moduleType) {
      case 'agent':
        ({ code, demo } = this.compileAgent(mod as unknown as V2AgentNode, indent, config));
        break;
      case 'tool':
        ({ code, demo } = this.compileTool(mod as unknown as V2ToolNode, indent, config));
        break;
      case 'memory':
        ({ code, demo } = this.compileMemory(mod as unknown as V2MemoryNode, indent, config));
        break;
      case 'workflow':
        ({ code, demo } = this.compileWorkflow(mod as unknown as V2WorkflowNode, indent, config));
        break;
      case 'team':
        ({ code, demo } = this.compileTeam(mod as unknown as V2TeamNode, indent, config));
        break;
      case 'policy':
        ({ code, demo } = this.compilePolicy(mod as unknown as V2PolicyNode, indent, config));
        break;
      case 'system':
        ({ code, demo } = this.compileSystem(mod as unknown as V2SystemNode, indent, config));
        break;
      default:
        ({ code, demo } = this.compileGeneric(mod, indent, config));
    }

    lines.push(...code);
    return { code: lines, demo };
  }

  private toPascalCase(str: string): string {
    const cleaned = str.replace(/[^a-zA-Z0-9]+/g, ' ').trim();
    if (!cleaned) return 'MamModule';
    let result = cleaned
      .split(/\s+/)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join('');
    if (/^[0-9]/.test(result)) result = `_${result}`;
    return result;
  }

  private className(name: string, suffix: string): string {
    const base = this.toPascalCase(name);
    return base.endsWith(suffix) ? base : `${base}${suffix}`;
  }

  private esc(s: string): string {
    return s
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\r/g, '')
      .replace(/\n/g, '\\n');
  }

  private newVar(): string {
    return `mod${++this.demoCounter}`;
  }

  private generateError(indent: number): string[] {
    const pad = ' '.repeat(indent);
    return [
      '/// MAM error types.',
      '#[derive(Debug, Clone)]',
      'pub enum MAMError {',
      `${pad}Validation(String),`,
      `${pad}Runtime(String),`,
      '}',
      '',
      'impl fmt::Display for MAMError {',
      `${pad}fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {`,
      `${pad}${pad}match self {`,
      `${pad}${pad}${pad}MAMError::Validation(e) => write!(f, "Validation error: {}", e),`,
      `${pad}${pad}${pad}MAMError::Runtime(e) => write!(f, "Runtime error: {}", e),`,
      `${pad}${pad}}`,
      `${pad}}`,
      '}',
      '',
      'impl std::error::Error for MAMError {}',
    ];
  }

  private generateSharedTypes(indent: number): string[] {
    const pad = ' '.repeat(indent);
    return [
      '// ===== Shared result, port and edge types =====',
      '#[derive(Debug, Clone)]',
      'pub struct Port {',
      `${pad}pub name: String,`,
      `${pad}pub typ: String,`,
      `${pad}pub required: bool,`,
      '}',
      '',
      'impl Port {',
      `${pad}pub fn new(name: &str, typ: &str, required: bool) -> Self {`,
      `${pad}${pad}Self { name: name.to_string(), typ: typ.to_string(), required }`,
      `${pad}}`,
      '}',
      '',
      '#[derive(Debug, Clone)]',
      'pub struct Edge {',
      `${pad}pub source: String,`,
      `${pad}pub target: String,`,
      '}',
      '',
      'impl Edge {',
      `${pad}pub fn new(source: &str, target: &str) -> Self {`,
      `${pad}${pad}Self { source: source.to_string(), target: target.to_string() }`,
      `${pad}}`,
      '}',
      '',
      '#[derive(Debug, Clone)]',
      'pub struct ModuleResult {',
      `${pad}pub success: bool,`,
      `${pad}pub error: Option<String>,`,
      `${pad}pub outputs: HashMap<String, String>,`,
      '}',
      '',
      'impl fmt::Display for ModuleResult {',
      `${pad}fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {`,
      `${pad}${pad}if !self.success {`,
      `${pad}${pad}${pad}return write!(f, "ERROR: {}", self.error.as_deref().unwrap_or("unknown"));`,
      `${pad}${pad}}`,
      `${pad}${pad}let mut parts: Vec<String> = Vec::new();`,
      `${pad}${pad}for (k, v) in &self.outputs { parts.push(format!("{}={}", k, v)); }`,
      `${pad}${pad}write!(f, "OK: {}", parts.join(", "))`,
      `${pad}}`,
      '}',
      '',
      '#[derive(Debug, Clone)]',
      'pub struct AgentResult {',
      `${pad}pub success: bool,`,
      `${pad}pub task: String,`,
      `${pad}pub result: String,`,
      `${pad}pub tool: Option<String>,`,
      '}',
      '',
      'impl fmt::Display for AgentResult {',
      `${pad}fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {`,
      `${pad}${pad}let tag = if self.success { "ok" } else { "fail" };`,
      `${pad}${pad}match &self.tool {`,
      `${pad}${pad}${pad}Some(t) => write!(f, "[{}] {} -> {} (tool: {})", tag, self.task, self.result, t),`,
      `${pad}${pad}${pad}None => write!(f, "[{}] {} -> {}", tag, self.task, self.result),`,
      `${pad}${pad}}`,
      `${pad}}`,
      '}',
      '',
      '#[derive(Debug, Clone)]',
      'pub struct ToolResult {',
      `${pad}pub success: bool,`,
      `${pad}pub action: String,`,
      `${pad}pub result: String,`,
      '}',
      '',
      'impl fmt::Display for ToolResult {',
      `${pad}fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {`,
      `${pad}${pad}let tag = if self.success { "OK" } else { "FAIL" };`,
      `${pad}${pad}write!(f, "{}: {} -> {}", tag, self.action, self.result)`,
      `${pad}}`,
      '}',
      '',
      '#[derive(Debug, Clone)]',
      'pub struct MemberResult {',
      `${pad}pub member: String,`,
      `${pad}pub success: bool,`,
      `${pad}pub result: String,`,
      '}',
      '',
      'impl fmt::Display for MemberResult {',
      `${pad}fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {`,
      `${pad}${pad}let tag = if self.success { "ok" } else { "fail" };`,
      `${pad}${pad}write!(f, "[{}] {}: {}", tag, self.member, self.result)`,
      `${pad}}`,
      '}',
      '',
      '#[derive(Debug, Clone)]',
      'pub struct TeamResult {',
      `${pad}pub task: String,`,
      `${pad}pub members: Vec<MemberResult>,`,
      '}',
      '',
      'impl fmt::Display for TeamResult {',
      `${pad}fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {`,
      `${pad}${pad}let joined: Vec<String> = self.members.iter().map(|m| m.to_string()).collect();`,
      `${pad}${pad}write!(f, "Team [{}]: {}", self.task, joined.join(" | "))`,
      `${pad}}`,
      '}',
      '',
      '#[derive(Debug, Clone)]',
      'pub struct WorkflowResult {',
      `${pad}pub success: bool,`,
      `${pad}pub error: Option<String>,`,
      `${pad}pub order: Vec<String>,`,
      '}',
      '',
      'impl fmt::Display for WorkflowResult {',
      `${pad}fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {`,
      `${pad}${pad}if !self.success {`,
      `${pad}${pad}${pad}return write!(f, "Workflow error: {}", self.error.as_deref().unwrap_or("unknown"));`,
      `${pad}${pad}}`,
      `${pad}${pad}write!(f, "Workflow: {}", self.order.join(" -> "))`,
      `${pad}}`,
      '}',
      '',
      '#[derive(Debug, Clone)]',
      'pub struct SystemResult {',
      `${pad}pub success: bool,`,
      `${pad}pub error: Option<String>,`,
      `${pad}pub order: Vec<String>,`,
      `${pad}pub results: HashMap<String, String>,`,
      '}',
      '',
      'impl fmt::Display for SystemResult {',
      `${pad}fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {`,
      `${pad}${pad}if !self.success {`,
      `${pad}${pad}${pad}return write!(f, "System error: {}", self.error.as_deref().unwrap_or("unknown"));`,
      `${pad}${pad}}`,
      `${pad}${pad}write!(f, "System run: {}", self.order.join(" -> "))`,
      `${pad}}`,
      '}',
    ];
  }

  private topoSort(indent: number): string[] {
    const pad = ' '.repeat(indent);
    return [
      '/// Kahn topological sort. Returns (order, has_cycle).',
      'fn topo_sort(nodes: &[String], edges: &[Edge]) -> (Vec<String>, bool) {',
      `${pad}let mut indegree: HashMap<String, usize> = HashMap::new();`,
      `${pad}let mut adj: HashMap<String, Vec<String>> = HashMap::new();`,
      `${pad}for n in nodes {`,
      `${pad}${pad}indegree.insert(n.clone(), 0);`,
      `${pad}${pad}adj.insert(n.clone(), Vec::new());`,
      `${pad}}`,
      `${pad}for e in edges {`,
      `${pad}${pad}if !adj.contains_key(&e.source) || !indegree.contains_key(&e.target) {`,
      `${pad}${pad}${pad}continue;`,
      `${pad}${pad}}`,
      `${pad}${pad}adj.get_mut(&e.source).unwrap().push(e.target.clone());`,
      `${pad}${pad}*indegree.get_mut(&e.target).unwrap() += 1;`,
      `${pad}}`,
      `${pad}let mut queue: VecDeque<String> = VecDeque::new();`,
      `${pad}for n in nodes {`,
      `${pad}${pad}if *indegree.get(n).unwrap() == 0 { queue.push_back(n.clone()); }`,
      `${pad}}`,
      `${pad}let mut order = Vec::new();`,
      `${pad}while let Some(u) = queue.pop_front() {`,
      `${pad}${pad}order.push(u.clone());`,
      `${pad}${pad}for v in adj.get(&u).cloned().unwrap_or_default() {`,
      `${pad}${pad}${pad}let d = indegree.get_mut(&v).unwrap();`,
      `${pad}${pad}${pad}*d -= 1;`,
      `${pad}${pad}${pad}if *d == 0 { queue.push_back(v); }`,
      `${pad}${pad}}`,
      `${pad}}`,
      `${pad}(order, order.len() != nodes.len())`,
      '}',
    ];
  }

  private compileAgent(mod: V2AgentNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const cls = this.className(mod.name, 'Agent');
    const demoVar = this.newVar();
    const tools = mod.tools?.map(t => `"${this.esc(t)}".to_string()`).join(', ') || '';
    const handoff = mod.handoff?.map(h => `"${this.esc(h)}".to_string()`).join(', ') || '';
    const memName = mod.memory?.name || mod.memory?.type || '';
    const memInit = memName
      ? `${pad}${pad}${pad}memory: Some("${this.esc(memName)}".to_string()),`
      : `${pad}${pad}${pad}memory: None,`;
    const executeBlock = memName
      ? [
          `${pad}pub fn execute(&self, task: &str) -> AgentResult {`,
          `${pad}${pad}let mut result = format!("[{}] completed '{}' toward goal: {}", self.role, task, self.goal);`,
          `${pad}${pad}if let Some(m) = &self.memory {`,
          `${pad}${pad}${pad}result.push_str(&format!(" | logged to memory: {}", m));`,
          `${pad}${pad}}`,
          `${pad}${pad}AgentResult {`,
          `${pad}${pad}${pad}success: true,`,
          `${pad}${pad}${pad}task: task.to_string(),`,
          `${pad}${pad}${pad}result,`,
          `${pad}${pad}${pad}tool: self.tools.first().cloned(),`,
          `${pad}${pad}}`,
          `${pad}}`,
        ]
      : [
          `${pad}pub fn execute(&self, task: &str) -> AgentResult {`,
          `${pad}${pad}AgentResult {`,
          `${pad}${pad}${pad}success: true,`,
          `${pad}${pad}${pad}task: task.to_string(),`,
          `${pad}${pad}${pad}result: format!("[{}] completed '{}' toward goal: {}", self.role, task, self.goal),`,
          `${pad}${pad}${pad}tool: self.tools.first().cloned(),`,
          `${pad}${pad}}`,
          `${pad}}`,
        ];

    const code = [
      `#[derive(Debug, Clone)]`,
      `pub struct ${cls}Agent {`,
      `${pad}pub name: String,`,
      `${pad}pub role: String,`,
      `${pad}pub goal: String,`,
      `${pad}pub tools: Vec<String>,`,
      `${pad}pub handoff: Vec<String>,`,
      `${pad}pub memory: Option<String>,`,
      '}',
      '',
      `impl ${cls}Agent {`,
      `${pad}pub fn new() -> Self {`,
      `${pad}${pad}Self {`,
      `${pad}${pad}${pad}name: "${this.esc(mod.name)}".to_string(),`,
      `${pad}${pad}${pad}role: "${this.esc(mod.role || '')}".to_string(),`,
      `${pad}${pad}${pad}goal: "${this.esc(mod.goal || '')}".to_string(),`,
      `${pad}${pad}${pad}tools: vec![${tools}],`,
      `${pad}${pad}${pad}handoff: vec![${handoff}],`,
      memInit,
      `${pad}${pad}}`,
      `${pad}}`,
      '',
      ...executeBlock,
      '',
      `${pad}pub fn role(&self) -> &str { &self.role }`,
      `${pad}pub fn goal(&self) -> &str { &self.goal }`,
      '}',
      '',
      'impl Default for ' + cls + 'Agent {',
      `${pad}fn default() -> Self { Self::new() }`,
      '}',
    ];

    const demo = [
      `let ${demoVar} = ${cls}Agent::new();`,
      `println!("{}", ${demoVar}.execute("demo task"));`,
    ];

    return { code, demo };
  }

  private compileTool(mod: V2ToolNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const cls = this.className(mod.name, 'Tool');
    const demoVar = this.newVar();
    const caps = mod.capabilities?.map(c => `"${this.esc(c)}".to_string()`).join(', ') || '';
    const firstCap = mod.capabilities && mod.capabilities.length > 0 ? mod.capabilities[0] : 'invoke';

    const code = [
      `#[derive(Debug, Clone)]`,
      `pub struct ${cls}Tool {`,
      `${pad}pub name: String,`,
      `${pad}pub provider: String,`,
      `${pad}pub capabilities: Vec<String>,`,
      '}',
      '',
      `impl ${cls}Tool {`,
      `${pad}pub fn new() -> Self {`,
      `${pad}${pad}Self {`,
      `${pad}${pad}${pad}name: "${this.esc(mod.name)}".to_string(),`,
      `${pad}${pad}${pad}provider: "${this.esc(mod.provider || '')}".to_string(),`,
      `${pad}${pad}${pad}capabilities: vec![${caps}],`,
      `${pad}${pad}}`,
      `${pad}}`,
      '',
      `${pad}pub fn invoke(&self, action: &str, kwargs: &HashMap<String, String>) -> ToolResult {`,
      `${pad}${pad}if !self.capabilities.contains(&action.to_string()) {`,
      `${pad}${pad}${pad}return ToolResult {`,
      `${pad}${pad}${pad}${pad}success: false,`,
      `${pad}${pad}${pad}${pad}action: action.to_string(),`,
      `${pad}${pad}${pad}${pad}result: format!("Action '{}' is not a capability. Available: {}", action, self.capabilities.join(", ")),`,
      `${pad}${pad}${pad}};`,
      `${pad}${pad}}`,
      `${pad}${pad}ToolResult {`,
      `${pad}${pad}${pad}success: true,`,
      `${pad}${pad}${pad}action: action.to_string(),`,
      `${pad}${pad}${pad}result: format!("[{}] invoked '{}' with {} parameter(s)", self.provider, action, kwargs.len()),`,
      `${pad}${pad}}`,
      `${pad}}`,
      '}',
      '',
      'impl Default for ' + cls + 'Tool {',
      `${pad}fn default() -> Self { Self::new() }`,
      '}',
    ];

    const demo = [
      `let ${demoVar} = ${cls}Tool::new();`,
      `println!("{}", ${demoVar}.invoke("${this.esc(firstCap)}", &HashMap::new()));`,
      `println!("{}", ${demoVar}.invoke("not-a-capability", &HashMap::new()));`,
    ];

    return { code, demo };
  }

  private compileMemory(mod: V2MemoryNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const cls = this.className(mod.name, 'Memory');
    const demoVar = this.newVar();

    const code = [
      `#[derive(Debug, Clone)]`,
      `pub struct ${cls}Memory {`,
      `${pad}pub name: String,`,
      `${pad}pub format: String,`,
      `${pad}pub backend: String,`,
      `${pad}pub scope: String,`,
      `${pad}store: HashMap<String, String>,`,
      '}',
      '',
      `impl ${cls}Memory {`,
      `${pad}pub fn new() -> Self {`,
      `${pad}${pad}Self {`,
      `${pad}${pad}${pad}name: "${this.esc(mod.name)}".to_string(),`,
      `${pad}${pad}${pad}format: "${this.esc(mod.format || 'key-value')}".to_string(),`,
      `${pad}${pad}${pad}backend: "${this.esc(mod.backend || 'local')}".to_string(),`,
      `${pad}${pad}${pad}scope: "${this.esc(mod.scope || 'module')}".to_string(),`,
      `${pad}${pad}${pad}store: HashMap::new(),`,
      `${pad}${pad}}`,
      `${pad}}`,
      '',
      `${pad}pub fn store(&mut self, key: &str, value: &str) {`,
      `${pad}${pad}self.store.insert(key.to_string(), value.to_string());`,
      `${pad}}`,
      '',
      `${pad}pub fn retrieve(&self, key: &str) -> Option<&String> {`,
      `${pad}${pad}self.store.get(key)`,
      `${pad}}`,
      '',
      `${pad}pub fn delete(&mut self, key: &str) -> bool {`,
      `${pad}${pad}self.store.remove(key).is_some()`,
      `${pad}}`,
      '',
      `${pad}pub fn search(&self, term: &str) -> Vec<String> {`,
      `${pad}${pad}let needle = term.to_lowercase();`,
      `${pad}${pad}self.store.keys().filter(|k| k.to_lowercase().contains(&needle)).cloned().collect()`,
      `${pad}}`,
      '',
      `${pad}pub fn count(&self) -> usize { self.store.len() }`,
      '}',
      '',
      'impl Default for ' + cls + 'Memory {',
      `${pad}fn default() -> Self { Self::new() }`,
      '}',
    ];

    const demo = [
      `let mut ${demoVar} = ${cls}Memory::new();`,
      `${demoVar}.store("topic", "MAM compiler");`,
      `${demoVar}.store("lang", "Rust");`,
      `println!("{} entr{} stored", ${demoVar}.count(), if ${demoVar}.count() == 1 { "y" } else { "ies" });`,
      `println!("retrieve(topic) = {:?}", ${demoVar}.retrieve("topic"));`,
      `println!("search(compiler) -> {} match(es)", ${demoVar}.search("compiler").len());`,
      `println!("delete(lang) = {}", ${demoVar}.delete("lang"));`,
    ];

    return { code, demo };
  }

  private compileWorkflow(mod: V2WorkflowNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const cls = this.className(mod.name, 'Workflow');
    const demoVar = this.newVar();
    const steps = mod.steps?.map(s => `"${this.esc(s.name)}".to_string()`).join(', ') || '';
    const edges = mod.edges?.map(e => `Edge::new("${this.esc(e.source)}", "${this.esc(e.target)}")`).join(', ') || '';

    const code = [
      `#[derive(Debug, Clone)]`,
      `pub struct ${cls}Workflow {`,
      `${pad}pub name: String,`,
      `${pad}pub steps: Vec<String>,`,
      `${pad}pub edges: Vec<Edge>,`,
      '}',
      '',
      `impl ${cls}Workflow {`,
      `${pad}pub fn new() -> Self {`,
      `${pad}${pad}Self {`,
      `${pad}${pad}${pad}name: "${this.esc(mod.name)}".to_string(),`,
      `${pad}${pad}${pad}steps: vec![${steps}],`,
      `${pad}${pad}${pad}edges: vec![${edges}],`,
      `${pad}${pad}}`,
      `${pad}}`,
      '',
      `${pad}pub fn run(&self) -> Result<WorkflowResult, MAMError> {`,
      `${pad}${pad}let (order, has_cycle) = topo_sort(&self.steps, &self.edges);`,
      `${pad}${pad}if has_cycle {`,
      `${pad}${pad}${pad}return Ok(WorkflowResult { success: false, error: Some("Cycle detected in workflow edges".to_string()), order });`,
      `${pad}${pad}}`,
      `${pad}${pad}Ok(WorkflowResult { success: true, error: None, order })`,
      `${pad}}`,
      '}',
      '',
      'impl Default for ' + cls + 'Workflow {',
      `${pad}fn default() -> Self { Self::new() }`,
      '}',
    ];

    const demo = [
      `let ${demoVar} = ${cls}Workflow::new();`,
      `println!("{}", ${demoVar}.run()?);`,
    ];

    return { code, demo };
  }

  private compileTeam(mod: V2TeamNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const cls = this.className(mod.name, 'Team');
    const demoVar = this.newVar();
    const members = mod.members?.map(m => `"${this.esc(m)}".to_string()`).join(', ') || '';

    const code = [
      `#[derive(Debug, Clone)]`,
      `pub struct ${cls}Team {`,
      `${pad}pub name: String,`,
      `${pad}pub members: Vec<String>,`,
      '}',
      '',
      `impl ${cls}Team {`,
      `${pad}pub fn new() -> Self {`,
      `${pad}${pad}Self {`,
      `${pad}${pad}${pad}name: "${this.esc(mod.name)}".to_string(),`,
      `${pad}${pad}${pad}members: vec![${members}],`,
      `${pad}${pad}}`,
      `${pad}}`,
      '',
      `${pad}pub fn coordinate(&self, task: &str) -> TeamResult {`,
      `${pad}${pad}let results: Vec<MemberResult> = self`,
      `${pad}${pad}${pad}.members`,
      `${pad}${pad}${pad}.iter()`,
      `${pad}${pad}${pad}.map(|member| MemberResult {`,
      `${pad}${pad}${pad}${pad}member: member.clone(),`,
      `${pad}${pad}${pad}${pad}success: true,`,
      `${pad}${pad}${pad}${pad}result: format!("completed '{}'", task),`,
      `${pad}${pad}${pad}})`,
      `${pad}${pad}${pad}.collect();`,
      `${pad}${pad}TeamResult { task: task.to_string(), members: results }`,
      `${pad}}`,
      '}',
      '',
      'impl Default for ' + cls + 'Team {',
      `${pad}fn default() -> Self { Self::new() }`,
      '}',
    ];

    const demo = [
      `let ${demoVar} = ${cls}Team::new();`,
      `println!("{}", ${demoVar}.coordinate("demo task"));`,
    ];

    return { code, demo };
  }

  private compilePolicy(mod: V2PolicyNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const cls = this.className(mod.name, 'Policy');
    const demoVar = this.newVar();
    const allow = mod.allow?.map(a => `"${this.esc(a)}".to_string()`).join(', ') || '';
    const deny = mod.deny?.map(d => `"${this.esc(d)}".to_string()`).join(', ') || '';
    const allowSample = mod.allow && mod.allow.length > 0 ? mod.allow[0] : 'read';
    const denySample = mod.deny && mod.deny.length > 0 ? mod.deny[0] : 'blocked';

    const code = [
      `#[derive(Debug, Clone)]`,
      `pub struct ${cls}Policy {`,
      `${pad}pub name: String,`,
      `${pad}pub allow: Vec<String>,`,
      `${pad}pub deny: Vec<String>,`,
      '}',
      '',
      `impl ${cls}Policy {`,
      `${pad}pub fn new() -> Self {`,
      `${pad}${pad}Self {`,
      `${pad}${pad}${pad}name: "${this.esc(mod.name)}".to_string(),`,
      `${pad}${pad}${pad}allow: vec![${allow}],`,
      `${pad}${pad}${pad}deny: vec![${deny}],`,
      `${pad}${pad}}`,
      `${pad}}`,
      '',
      `${pad}pub fn check(&self, action: &str) -> bool {`,
      `${pad}${pad}if self.deny.contains(&action.to_string()) { return false; }`,
      `${pad}${pad}self.allow.contains(&action.to_string())`,
      `${pad}}`,
      '}',
      '',
      'impl Default for ' + cls + 'Policy {',
      `${pad}fn default() -> Self { Self::new() }`,
      '}',
    ];

    const demo = [
      `let ${demoVar} = ${cls}Policy::new();`,
      `println!("check('${this.esc(allowSample)}') = {}", ${demoVar}.check("${this.esc(allowSample)}"));`,
      `println!("check('${this.esc(denySample)}') = {}", ${demoVar}.check("${this.esc(denySample)}"));`,
      `println!("check('anything') = {}", ${demoVar}.check("anything"));`,
    ];

    return { code, demo };
  }

  private compileSystem(mod: V2SystemNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const cls = this.className(mod.name, 'System');
    const demoVar = this.newVar();
    const agents = mod.agents?.map(a => `"${this.esc(a)}".to_string()`).join(', ') || '';
    const modules = mod.modules?.map(m => `"${this.esc(m)}".to_string()`).join(', ') || '';
    const edges = mod.edges?.map(e => `Edge::new("${this.esc(e.source)}", "${this.esc(e.target)}")`).join(', ') || '';

    const code = [
      `#[derive(Debug, Clone)]`,
      `pub struct ${cls}System {`,
      `${pad}pub name: String,`,
      `${pad}pub agents: Vec<String>,`,
      `${pad}pub modules: Vec<String>,`,
      `${pad}pub edges: Vec<Edge>,`,
      '}',
      '',
      `impl ${cls}System {`,
      `${pad}pub fn new() -> Self {`,
      `${pad}${pad}Self {`,
      `${pad}${pad}${pad}name: "${this.esc(mod.name)}".to_string(),`,
      `${pad}${pad}${pad}agents: vec![${agents}],`,
      `${pad}${pad}${pad}modules: vec![${modules}],`,
      `${pad}${pad}${pad}edges: vec![${edges}],`,
      `${pad}${pad}}`,
      `${pad}}`,
      '',
      `${pad}pub fn run(&self) -> Result<SystemResult, MAMError> {`,
      `${pad}${pad}let mut nodes = self.agents.clone();`,
      `${pad}${pad}nodes.extend(self.modules.clone());`,
      `${pad}${pad}let (order, has_cycle) = topo_sort(&nodes, &self.edges);`,
      `${pad}${pad}let mut results: HashMap<String, String> = HashMap::new();`,
      `${pad}${pad}for n in &order { results.insert(n.clone(), format!("[{}] executed", n)); }`,
      `${pad}${pad}if has_cycle {`,
      `${pad}${pad}${pad}return Ok(SystemResult { success: false, error: Some("Cycle detected in system graph".to_string()), order, results });`,
      `${pad}${pad}}`,
      `${pad}${pad}Ok(SystemResult { success: true, error: None, order, results })`,
      `${pad}}`,
      '}',
      '',
      'impl Default for ' + cls + 'System {',
      `${pad}fn default() -> Self { Self::new() }`,
      '}',
    ];

    const demo = [
      `let ${demoVar} = ${cls}System::new();`,
      `println!("{}", ${demoVar}.run()?);`,
    ];

    return { code, demo };
  }

  private compileGeneric(mod: V2ModuleNode, indent: number, config: CompilerConfig): { code: string[]; demo: string[] } {
    const pad = ' '.repeat(indent);
    const cls = this.className(mod.name, 'Module');
    const demoVar = this.newVar();
    const inputs = mod.inputs?.map(i => `Port::new("${this.esc(i.name)}", "${this.esc(i.type || 'unknown')}", ${i.required ? 'true' : 'false'})`).join(', ') || '';
    const outputs = mod.outputs?.map(o => `Port::new("${this.esc(o.name)}", "${this.esc(o.type || 'unknown')}", false)`).join(', ') || '';
    const caps = mod.capabilities?.map(c => `"${this.esc(c)}".to_string()`).join(', ') || '';
    const required = mod.inputs?.filter(i => i.required) || [];

    const code = [
      `#[derive(Debug, Clone)]`,
      `pub struct ${cls}Module {`,
      `${pad}pub name: String,`,
      `${pad}pub description: String,`,
      `${pad}pub inputs: Vec<Port>,`,
      `${pad}pub outputs: Vec<Port>,`,
      `${pad}pub capabilities: Vec<String>,`,
      '}',
      '',
      `impl ${cls}Module {`,
      `${pad}pub fn new() -> Self {`,
      `${pad}${pad}Self {`,
      `${pad}${pad}${pad}name: "${this.esc(mod.name)}".to_string(),`,
      `${pad}${pad}${pad}description: "${this.esc(mod.description || '')}".to_string(),`,
      `${pad}${pad}${pad}inputs: vec![${inputs}],`,
      `${pad}${pad}${pad}outputs: vec![${outputs}],`,
      `${pad}${pad}${pad}capabilities: vec![${caps}],`,
      `${pad}${pad}}`,
      `${pad}}`,
      '',
      `${pad}pub fn run(&self, inputs: &HashMap<String, String>) -> ModuleResult {`,
      `${pad}${pad}let missing: Vec<String> = self`,
      `${pad}${pad}${pad}.inputs`,
      `${pad}${pad}${pad}.iter()`,
      `${pad}${pad}${pad}.filter(|p| p.required && !inputs.contains_key(&p.name))`,
      `${pad}${pad}${pad}.map(|p| p.name.clone())`,
      `${pad}${pad}${pad}.collect();`,
      `${pad}${pad}if !missing.is_empty() {`,
      `${pad}${pad}${pad}return ModuleResult { success: false, error: Some(format!("Missing required inputs: {}", missing.join(", "))), outputs: HashMap::new() };`,
      `${pad}${pad}}`,
      `${pad}${pad}let mut outputs: HashMap<String, String> = HashMap::new();`,
      `${pad}${pad}for o in &self.outputs { outputs.insert(o.name.clone(), String::new()); }`,
      `${pad}${pad}for (k, v) in inputs {`,
      `${pad}${pad}${pad}outputs.entry(k.clone()).or_insert_with(|| v.clone());`,
      `${pad}${pad}}`,
      `${pad}${pad}ModuleResult { success: true, error: None, outputs }`,
      `${pad}}`,
      '}',
      '',
      'impl Default for ' + cls + 'Module {',
      `${pad}fn default() -> Self { Self::new() }`,
      '}',
    ];

    const demo: string[] = [
      `let ${demoVar} = ${cls}Module::new();`,
      `let mut ${demoVar}_inputs: HashMap<String, String> = HashMap::new();`,
      ...required.map(i => `${demoVar}_inputs.insert("${this.esc(i.name)}".to_string(), "demo".to_string());`),
      `println!("{}", ${demoVar}.run(&${demoVar}_inputs));`,
    ];

    return { code, demo };
  }

  private generateMain(modules: V2ModuleNode[], indent: number): string[] {
    const pad = ' '.repeat(indent);
    const demos: string[] = [];

    for (const mod of modules) {
      demos.push(...this.compileModule(mod, indent, { target: 'rust' } as CompilerConfig).demo);
    }

    return [
      '',
      ...this.topoSort(indent),
      '',
      'fn main() -> Result<(), MAMError> {',
      `${pad}println!("Registry: {}", registry().join(", "));`,
      ...demos.map(d => pad + d),
      `${pad}Ok(())`,
      '}',
    ];
  }
}