/**
 * Terraform Target
 *
 * Compiles MAM AST to Terraform (.tf) resource blocks.
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2MemoryNode, V2WorkflowNode, V2TeamNode, V2PolicyNode, V2SystemNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';

export class TerraformTarget implements CompileTargetHandler {
  name = 'terraform';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];
    const indent = config.indent || 2;

    lines.push('# Generated by MAM Compiler');
    lines.push('# Target: Terraform');
    lines.push('');

    for (const mod of modules) {
      lines.push(...this.compileModule(mod, indent, config));
      lines.push('');
    }

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];

    if (config.includeComments) {
      lines.push(`# Module: ${mod.name}`);
      lines.push(`# Type: ${mod.moduleType}`);
      if (mod.description) lines.push(`# ${mod.description}`);
      lines.push('');
    }

    switch (mod.moduleType) {
      case 'agent':
        lines.push(...this.compileAgent(mod as unknown as V2AgentNode, indent, config));
        break;
      case 'tool':
        lines.push(...this.compileTool(mod as unknown as V2ToolNode, indent, config));
        break;
      case 'memory':
        lines.push(...this.compileMemory(mod as unknown as V2MemoryNode, indent, config));
        break;
      case 'workflow':
        lines.push(...this.compileWorkflow(mod as unknown as V2WorkflowNode, indent, config));
        break;
      case 'team':
        lines.push(...this.compileTeam(mod as unknown as V2TeamNode, indent, config));
        break;
      case 'policy':
        lines.push(...this.compilePolicy(mod as unknown as V2PolicyNode, indent, config));
        break;
      case 'system':
        lines.push(...this.compileSystem(mod as unknown as V2SystemNode, indent, config));
        break;
      default:
        lines.push(...this.compileGeneric(mod, indent, config));
    }

    return lines;
  }

  private toTerraformName(name: string): string {
    return name.toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '');
  }

  private compileAgent(mod: V2AgentNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const resName = this.toTerraformName(mod.name);

    return [
      `resource "mam_agent" "${resName}" {`,
      `${pad}name = "${mod.name}"`,
      `${pad}role = "${mod.role || ''}"`,
      `${pad}goal = "${mod.goal || ''}"`,
      '',
      `${pad}tools = [${mod.tools?.map(t => `"${t}"`).join(', ') || ''}]`,
      `${pad}handoff = [${mod.handoff?.map(h => `"${h}"`).join(', ') || ''}]`,
      '',
      `${pad}exec_command {`,
      `${pad}${pad}command = ["python", "execute.py"]`,
      `${pad}}`,
      '}',
    ];
  }

  private compileTool(mod: V2ToolNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const resName = this.toTerraformName(mod.name);

    return [
      `resource "mam_tool" "${resName}" {`,
      `${pad}name = "${mod.name}"`,
      `${pad}provider = "${mod.provider}"`,
      '',
      `${pad}capabilities = [${mod.capabilities?.map(c => `"${c}"`).join(', ') || ''}]`,
      '',
      `${pad}exec_command {`,
      `${pad}${pad}command = ["python", "tool.py"]`,
      `${pad}}`,
      '}',
    ];
  }

  private compileMemory(mod: V2MemoryNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const resName = this.toTerraformName(mod.name);

    return [
      `resource "mam_memory" "${resName}" {`,
      `${pad}name = "${mod.name}"`,
      `${pad}format = "${mod.format}"`,
      `${pad}backend = "${mod.backend}"`,
      `${pad}scope = "${mod.scope}"`,
      mod.ttl ? `${pad}ttl = "${mod.ttl}"` : '',
      '',
      `${pad}connection {`,
      `${pad}${pad}type = "${mod.backend}"`,
      `${pad}}`,
      '}',
    ].filter(l => l !== '');
  }

  private compileWorkflow(mod: V2WorkflowNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const resName = this.toTerraformName(mod.name);
    const lines: string[] = [];

    lines.push(`resource "mam_workflow" "${resName}" {`);
    lines.push(`${pad}name = "${mod.name}"`);
    lines.push('');

    if (mod.steps?.length) {
      for (const step of mod.steps) {
        lines.push(`${pad}step {`);
        lines.push(`${pad}${pad}name = "${step.name}"`);
        if (step.agent) lines.push(`${pad}${pad}agent = "${step.agent}"`);
        if (step.tool) lines.push(`${pad}${pad}tool = "${step.tool}"`);
        lines.push(`${pad}}`);
        lines.push('');
      }
    }

    if (mod.edges?.length) {
      for (const edge of mod.edges) {
        lines.push(`${pad}edge {`);
        lines.push(`${pad}${pad}source = "${edge.source}"`);
        lines.push(`${pad}${pad}target = "${edge.target}"`);
        lines.push(`${pad}}`);
      }
    }

    lines.push('}');
    return lines;
  }

  private compileTeam(mod: V2TeamNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const resName = this.toTerraformName(mod.name);

    return [
      `resource "mam_team" "${resName}" {`,
      `${pad}name = "${mod.name}"`,
      '',
      `${pad}members = [${mod.members?.map(m => `"${m}"`).join(', ') || ''}]`,
      mod.policy ? `${pad}policy = "${mod.policy}"` : '',
      '}',
    ].filter(l => l !== '');
  }

  private compilePolicy(mod: V2PolicyNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const resName = this.toTerraformName(mod.name);
    const lines: string[] = [];

    lines.push(`resource "mam_policy" "${resName}" {`);
    lines.push(`${pad}name = "${mod.name}"`);
    lines.push('');

    for (const action of mod.allow || []) {
      lines.push(`${pad}allow = "${action}"`);
    }
    for (const action of mod.deny || []) {
      lines.push(`${pad}deny = "${action}"`);
    }

    lines.push('}');
    return lines;
  }

  private compileSystem(mod: V2SystemNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const resName = this.toTerraformName(mod.name);
    const lines: string[] = [];

    lines.push(`resource "mam_system" "${resName}" {`);
    lines.push(`${pad}name = "${mod.name}"`);
    lines.push('');

    if (mod.agents?.length) {
      lines.push(`${pad}agents = [${mod.agents.map(a => `"${a}"`).join(', ')}]`);
    }
    if (mod.modules?.length) {
      lines.push(`${pad}modules = [${mod.modules.map(m => `"${m}"`).join(', ')}]`);
    }

    lines.push('');
    if (mod.edges?.length) {
      for (const edge of mod.edges) {
        lines.push(`${pad}edge {`);
        lines.push(`${pad}${pad}source = "${edge.source}"`);
        lines.push(`${pad}${pad}target = "${edge.target}"`);
        lines.push(`${pad}}`);
      }
    }

    lines.push('}');
    return lines;
  }

  private compileGeneric(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const resName = this.toTerraformName(mod.name);

    return [
      `resource "mam_module" "${resName}" {`,
      `${pad}name = "${mod.name}"`,
      `${pad}description = "${mod.description || mod.name}"`,
      '}',
    ];
  }
}
