/**
 * Terraform Target
 *
 * Compiles MAM AST to real, deployable Terraform HCL2.
 * Emits a valid `.tf` file with:
 *   - a `terraform {}` block declaring the kubernetes + local providers
 *   - provider blocks
 *   - a `namespace` variable and a per-module image variable
 *   - one `kubernetes_deployment_v1` resource per module (metadata, spec,
 *     template, labels, env, ports) and one `local_file` carrying the module
 *     context
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2MemoryNode, V2WorkflowNode, V2TeamNode, V2PolicyNode, V2SystemNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';
import { generateModuleContext } from '../context.js';

export class TerraformTarget implements CompileTargetHandler {
  name = 'terraform';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];

    lines.push('# Generated by MAM Compiler');
    lines.push('# Target: Terraform');
    lines.push('');
    lines.push('terraform {');
    lines.push('  required_version = ">= 1.0"');
    lines.push('  required_providers {');
    lines.push('    kubernetes = {');
    lines.push('      source  = "hashicorp/kubernetes"');
    lines.push('      version = "~> 2.23"');
    lines.push('    }');
    lines.push('    local = {');
    lines.push('      source  = "hashicorp/local"');
    lines.push('      version = "~> 2.4"');
    lines.push('    }');
    lines.push('  }');
    lines.push('}');
    lines.push('');
    lines.push('provider "kubernetes" {');
    lines.push('  # Cluster access is configured via KUBECONFIG or cloud provider credentials.');
    lines.push('}');
    lines.push('');
    lines.push('provider "local" {}');
    lines.push('');
    lines.push('variable "namespace" {');
    lines.push('  description = "Kubernetes namespace where MAM modules are deployed"');
    lines.push('  type        = string');
    lines.push('  default     = "default"');
    lines.push('}');
    lines.push('');

    for (const mod of modules) {
      lines.push(this.commentSafe(generateModuleContext(mod, 'terraform')));
      lines.push('');
      lines.push(...this.compileModule(mod));
      lines.push('');
    }

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode): string[] {
    const res = this.toTerraformName(mod.name);
    const k8s = this.toK8sName(mod.name);
    const env = this.moduleEnv(mod);
    const port = this.modulePort(mod);
    const lines: string[] = [];

    lines.push(`variable "${res}_image" {`);
    lines.push(`  description = ${this.hcl(`Container image for MAM module ${mod.name}`)}`);
    lines.push('  type        = string');
    lines.push(`  default     = ${this.hcl(`mam/${k8s}:latest`)}`);
    lines.push('}');
    lines.push('');

    lines.push(`resource "kubernetes_deployment_v1" "${res}" {`);
    lines.push('  metadata {');
    lines.push(`    name      = ${this.hcl(k8s)}`);
    lines.push('    namespace = var.namespace');
    lines.push('    labels = {');
    lines.push(`      app        = ${this.hcl(k8s)}`);
    lines.push(`      mam-type   = ${this.hcl(mod.moduleType)}`);
    lines.push('    }');
    lines.push('  }');
    lines.push('');
    lines.push('  spec {');
    lines.push('    replicas = 1');
    lines.push('    selector {');
    lines.push('      match_labels = {');
    lines.push(`        app = ${this.hcl(k8s)}`);
    lines.push('      }');
    lines.push('    }');
    lines.push('    template {');
    lines.push('      metadata {');
    lines.push('        labels = {');
    lines.push(`          app = ${this.hcl(k8s)}`);
    lines.push('        }');
    lines.push('      }');
    lines.push('      spec {');
    lines.push('        container {');
    lines.push(`          name  = ${this.hcl(k8s)}`);
    lines.push(`          image = var.${res}_image`);
    lines.push('          env {');
    lines.push(`            name  = ${this.hcl('MAM_MODULE')}`);
    lines.push(`            value = ${this.hcl(mod.name)}`);
    lines.push('          }');
    for (const [ek, ev] of Object.entries(env)) {
      if (ek === 'MAM_MODULE') continue;
      lines.push('          env {');
      lines.push(`            name  = ${this.hcl(ek)}`);
      lines.push(`            value = ${this.hcl(ev)}`);
      lines.push('          }');
    }
    if (port) {
      lines.push('          port {');
      lines.push(`            container_port = ${port}`);
      lines.push('          }');
    }
    lines.push('        }');
    lines.push('      }');
    lines.push('    }');
    lines.push('  }');
    lines.push('}');
    lines.push('');

    lines.push(`resource "local_file" "${res}_context" {`);
    lines.push(`  filename = ${this.hcl(`\${path.module}/context/${k8s}.txt`)}`);
    lines.push('  content  = <<EOT');
    lines.push(...generateModuleContext(mod, 'terraform').split('\n'));
    lines.push('EOT');
    lines.push('}');

    return lines;
  }

  // ==========================================================================
  // Helpers
  // ==========================================================================

  private commentSafe(text: string): string {
    return text
      .split('\n')
      .map(l => {
        const t = l.trim();
        if (t === '') return '#';
        if (l.startsWith('#')) return l;
        return `# ${l}`;
      })
      .join('\n');
  }

  private hcl(v: unknown): string {
    return `"${String(v).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
  }

  private toTerraformName(name: string): string {
    let res = name.toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '');
    if (res === '') res = 'module';
    if (/^[0-9]/.test(res)) res = 'mam_' + res;
    return res;
  }

  private toK8sName(name: string): string {
    const k = name.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
    return k || 'module';
  }

  private moduleEnv(mod: V2ModuleNode): Record<string, string> {
    const env: Record<string, string> = {
      MAM_MODULE: mod.name,
      MAM_TYPE: mod.moduleType,
    };
    switch (mod.moduleType) {
      case 'agent': {
        const a = mod as unknown as V2AgentNode;
        env.AGENT_ROLE = a.role || '';
        env.AGENT_GOAL = a.goal || '';
        if (a.tools?.length) env.AGENT_TOOLS = a.tools.join(',');
        if (a.handoff?.length) env.AGENT_HANDOFF = a.handoff.join(',');
        break;
      }
      case 'tool': {
        const t = mod as unknown as V2ToolNode;
        env.TOOL_PROVIDER = t.provider || '';
        if (t.capabilities?.length) env.TOOL_CAPABILITIES = t.capabilities.join(',');
        break;
      }
      case 'memory': {
        const m = mod as unknown as V2MemoryNode;
        env.MEMORY_FORMAT = m.format || '';
        env.MEMORY_BACKEND = m.backend || '';
        env.MEMORY_SCOPE = m.scope || '';
        break;
      }
      case 'workflow': {
        const w = mod as unknown as V2WorkflowNode;
        if (w.steps?.length) env.WORKFLOW_STEPS = w.steps.map(s => s.name).join(',');
        break;
      }
      case 'team': {
        const t = mod as unknown as V2TeamNode;
        if (t.members?.length) env.TEAM_MEMBERS = t.members.join(',');
        break;
      }
      case 'policy': {
        const p = mod as unknown as V2PolicyNode;
        if (p.allow?.length) env.POLICY_ALLOW = p.allow.join(',');
        if (p.deny?.length) env.POLICY_DENY = p.deny.join(',');
        break;
      }
      case 'system': {
        const s = mod as unknown as V2SystemNode;
        if (s.agents?.length) env.SYSTEM_AGENTS = s.agents.join(',');
        if (s.modules?.length) env.SYSTEM_MODULES = s.modules.join(',');
        break;
      }
      default:
        break;
    }
    return env;
  }

  private modulePort(mod: V2ModuleNode): number | null {
    const network = mod.permissions?.network;
    if (network !== 'internet' && network !== 'internal') return null;
    const raw = mod.permissions?.custom?.port;
    const parsed = raw ? parseInt(String(raw), 10) : NaN;
    return Number.isFinite(parsed) && parsed > 0 && parsed <= 65535 ? parsed : 8080;
  }
}