/**
 * WebAssembly Target
 *
 * Compiles MAM AST to a single, concrete WebAssembly Text (.wat) module.
 *
 * The emitted module is self-contained (no imports) and exports one or more
 * functions per MAM module:
 *
 *   agent_<name>_*      execute / role / goal / tool metadata
 *   tool_<name>_*       invoke (validates capability) / provider / capabilities
 *   memory_<name>_*     store / retrieve / delete / search / count
 *                       (real in-memory store in linear memory)
 *   workflow_<name>_*   run / step / edge metadata
 *   team_<name>_*       coordinate / member metadata
 *   policy_<name>_*     check (deny wins, then allow, else 0)
 *   system_<name>_*     run / node metadata
 *   module_<name>_*     run (validates required inputs) / capability metadata
 *
 * Strings live in a compact string table; string `i` is fetched with
 * `(call $s_off i)` / `(call $s_len i)`. Memory values are copied into a bump
 * heap and referenced by (offset, length) pairs.
 *
 * Verify: wat2wasm out.wat -o out.wasm   (or `wabt`'s parseWat in JS).
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2MemoryNode, V2WorkflowNode, V2TeamNode, V2PolicyNode, V2SystemNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';
import { generateModuleContext } from '../context.js';

interface WModule {
  mod: V2ModuleNode;
  prefix: string;
  indices: Record<string, number>;
  lists: Record<string, { base: number; count: number; indices: number[] }>;
  memBase?: number;
}

const RECORD_COUNT = 64;
const RECORD_STRIDE = 16;
const HEAP_SIZE = 8192;
const SEARCH_CAP = 64;

export class WasmTarget implements CompileTargetHandler {
  name = 'wasm';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const indent = config.indent || 2;
    const pad = ' '.repeat(indent);

    const lines: string[] = [];
    lines.push(';; Generated by MAM Compiler');
    lines.push(';; Target: WebAssembly (WAT)');
    lines.push(';;');
    lines.push(';; Self-contained module: no imports required.');
    lines.push(';; All strings live in a string table; memory ops use a bump heap.');
    lines.push('');

    // ------------------------------------------------------------------
    // 1. Register strings (string table)
    // ------------------------------------------------------------------
    const strings: string[] = [];
    const strIndices = new Map<string, number>();
    let dataLen = 0;

    const addStr = (s: string): number => {
      const key = s;
      const existing = strIndices.get(key);
      if (existing !== undefined) return existing;
      const idx = strings.length;
      strings.push(s);
      strIndices.set(key, idx);
      dataLen += this.byteLength(s);
      return idx;
    };

    const descriptors: WModule[] = [];

    for (const mod of modules) {
      const desc: WModule = {
        mod,
        prefix: this.sanitize(mod.name),
        indices: {},
        lists: {},
      };
      desc.indices.name = addStr(mod.name);
      desc.indices.type = addStr(mod.moduleType);
      if (mod.description) desc.indices.description = addStr(mod.description);

      switch (mod.moduleType) {
        case 'agent': {
          const a = mod as unknown as V2AgentNode;
          desc.indices.role = addStr(a.role || '');
          desc.indices.goal = addStr(a.goal || '');
          break;
        }
        case 'tool': {
          const t = mod as unknown as V2ToolNode;
          desc.indices.provider = addStr(t.provider || '');
          break;
        }
        case 'memory': {
          const mem = mod as unknown as V2MemoryNode;
          desc.indices.format = addStr(mem.format || 'key-value');
          desc.indices.backend = addStr(mem.backend || 'local');
          desc.indices.scope = addStr(mem.scope || 'module');
          break;
        }
        case 'workflow': {
          const w = mod as unknown as V2WorkflowNode;
          break;
        }
        case 'team': {
          const tm = mod as unknown as V2TeamNode;
          break;
        }
        case 'policy': {
          const p = mod as unknown as V2PolicyNode;
          break;
        }
        case 'system': {
          const s = mod as unknown as V2SystemNode;
          break;
        }
        default: {
          break;
        }
      }

      descriptors.push(desc);
    }

    // ------------------------------------------------------------------
    // 2. Register list strings (so every string is known before the
    //    string data + index table are built)
    // ------------------------------------------------------------------
    const indicesOf = (items: string[] | undefined): number[] =>
      (items || []).map(it => addStr(it));

    for (const desc of descriptors) {
      const mod = desc.mod;
      switch (mod.moduleType) {
        case 'agent': {
          const a = mod as unknown as V2AgentNode;
          desc.lists.tools = { base: 0, count: 0, indices: indicesOf(a.tools) };
          desc.lists.handoff = { base: 0, count: 0, indices: indicesOf(a.handoff) };
          break;
        }
        case 'tool': {
          const t = mod as unknown as V2ToolNode;
          desc.lists.capabilities = { base: 0, count: 0, indices: indicesOf(t.capabilities) };
          break;
        }
        case 'workflow': {
          const w = mod as unknown as V2WorkflowNode;
          desc.lists.steps = { base: 0, count: 0, indices: (w.steps || []).map(s => addStr(s.name)) };
          desc.lists.edgesSource = { base: 0, count: 0, indices: (w.edges || []).map(e => addStr(e.source)) };
          desc.lists.edgesTarget = { base: 0, count: 0, indices: (w.edges || []).map(e => addStr(e.target)) };
          break;
        }
        case 'team': {
          const tm = mod as unknown as V2TeamNode;
          desc.lists.members = { base: 0, count: 0, indices: indicesOf(tm.members) };
          break;
        }
        case 'policy': {
          const p = mod as unknown as V2PolicyNode;
          desc.lists.allow = { base: 0, count: 0, indices: indicesOf(p.allow) };
          desc.lists.deny = { base: 0, count: 0, indices: indicesOf(p.deny) };
          break;
        }
        case 'system': {
          const s = mod as unknown as V2SystemNode;
          desc.lists.agents = { base: 0, count: 0, indices: indicesOf(s.agents) };
          desc.lists.modules = { base: 0, count: 0, indices: indicesOf(s.modules) };
          desc.lists.edgesSource = { base: 0, count: 0, indices: (s.edges || []).map(e => addStr(e.source)) };
          desc.lists.edgesTarget = { base: 0, count: 0, indices: (s.edges || []).map(e => addStr(e.target)) };
          break;
        }
        case 'memory': {
          // Memory modules carry no port/capability lists; do not fall through
          // to the generic-module default below.
          break;
        }
        default: {
          desc.lists.capabilities = { base: 0, count: 0, indices: indicesOf(mod.capabilities) };
          desc.lists.inputs = { base: 0, count: 0, indices: (mod.inputs || []).map(i => addStr(i.name)) };
          desc.lists.outputs = { base: 0, count: 0, indices: (mod.outputs || []).map(o => addStr(o.name)) };
          desc.lists.required = { base: 0, count: 0, indices: (mod.inputs || []).filter(i => i.required).map(i => addStr(i.name)) };
          break;
        }
      }
    }

    // ------------------------------------------------------------------
    // 3. Build string data bytes + index table
    // ------------------------------------------------------------------
    const stringData: number[] = [];
    const offsets: number[] = [];
    let cursor = 0;
    for (const s of strings) {
      offsets.push(cursor);
      for (const b of this.utf8Bytes(s)) stringData.push(b);
      cursor += this.byteLength(s);
    }
    dataLen = cursor;

    const idxBase = this.align4(dataLen);
    const table: number[] = [];
    for (let i = 0; i < strings.length; i++) {
      table.push(...this.le32(offsets[i]), ...this.le32(strings[i].length));
    }

    // ------------------------------------------------------------------
    // 4. Place list arrays after the index table
    // ------------------------------------------------------------------
    const listSegments: { base: number; bytes: number[] }[] = [];
    let listsCursor = idxBase + table.length;
    const place = (list: { base: number; count: number; indices: number[] }): { base: number; count: number; indices: number[] } => {
      const bytes = this.le32Bytes(list.indices);
      const base = listsCursor;
      listsCursor += bytes.length;
      listSegments.push({ base, bytes });
      return { base, count: list.indices.length, indices: list.indices };
    };

    for (const desc of descriptors) {
      for (const key of Object.keys(desc.lists)) {
        desc.lists[key] = place(desc.lists[key]);
      }
    }

    // ------------------------------------------------------------------
    // 4b. Registry lists (one entry per module: name + type)
    // ------------------------------------------------------------------
    const registryNames = place({ base: 0, count: 0, indices: descriptors.map(d => d.indices.name) });
    const registryTypes = place({ base: 0, count: 0, indices: descriptors.map(d => d.indices.type) });

    // ------------------------------------------------------------------
    // 4. Compute memory layout
    // ------------------------------------------------------------------
    const heapBase = this.align4(listsCursor);
    const memoryModules = descriptors.filter(d => d.mod.moduleType === 'memory');
    memoryModules.forEach((d, i) => {
      d.memBase = heapBase + HEAP_SIZE + i * RECORD_COUNT * RECORD_STRIDE;
    });
    const searchBase =
      heapBase + HEAP_SIZE + memoryModules.length * RECORD_COUNT * RECORD_STRIDE;
    const totalEnd = searchBase + SEARCH_CAP * 8;
    const pages = Math.max(1, Math.ceil(totalEnd / 65536));

    // ------------------------------------------------------------------
    // 5. Emit module
    // ------------------------------------------------------------------
    lines.push('(module');
    lines.push(`${pad}(memory (export "memory") ${pages})`);

    lines.push(`${pad};; ===== Runtime helpers =====`);
    lines.push(`${pad}(global $heap_ptr (mut i32) (i32.const ${heapBase}))`);
    lines.push(`${pad}(global $search_base i32 (i32.const ${searchBase}))`);
    lines.push('');
    lines.push(...this.emitHelpers(pad, idxBase));
    lines.push('');

    const usedExports = new Set<string>();
    for (const desc of descriptors) {
      const ctx = generateModuleContext(desc.mod, 'wasm')
        .split('\n')
        .map(l => (l === '' ? '' : pad + (l.startsWith(';;') ? l : `;; ${l}`)));
      lines.push(...ctx);
      lines.push('');
      lines.push(...this.emitModule(desc, pad, usedExports));
      lines.push('');
    }

    // Registry (all modules)
    lines.push(`${pad};; ===== Registry =====`);
    lines.push(`${pad};; Lists every compiled module by name and type.`);
    lines.push(`${pad}(func (export "${this.uniqueExport('module_count', usedExports)}") (result i32) (i32.const ${descriptors.length}))`);
    lines.push(`${pad}(func (export "${this.uniqueExport('module_name', usedExports)}") (param $i i32) (result i32 i32)`);
    lines.push(`${pad}${pad}(call $str_at (i32.const ${registryNames.base}) (i32.const ${registryNames.count}) (local.get $i)))`);
    lines.push(`${pad}(func (export "${this.uniqueExport('module_type', usedExports)}") (param $i i32) (result i32 i32)`);
    lines.push(`${pad}${pad}(call $str_at (i32.const ${registryTypes.base}) (i32.const ${registryTypes.count}) (local.get $i)))`);
    lines.push('');

    // Data segments
    lines.push(`${pad};; ===== Data =====`);
    lines.push(`${pad}(data (i32.const 0) ${this.watBytes(stringData)})`);
    lines.push(`${pad}(data (i32.const ${idxBase}) ${this.watBytes(table)})`);
    for (const seg of listSegments) {
      lines.push(`${pad}(data (i32.const ${seg.base}) ${this.watBytes(seg.bytes)})`);
    }
    lines.push(')');

    return lines.join('\n');
  }

  // ==========================================================================
  // Runtime helpers (once per module)
  // ==========================================================================

  private emitHelpers(pad: string, idxBase: number): string[] {
    return [
      `${pad}(func $s_off (param $i i32) (result i32)`,
      `${pad}${pad}(i32.load (i32.add (i32.const ${idxBase}) (i32.mul (local.get $i) (i32.const 8)))))`,
      `${pad}(func $s_len (param $i i32) (result i32)`,
      `${pad}${pad}(i32.load (i32.add (i32.add (i32.const ${idxBase}) (i32.mul (local.get $i) (i32.const 8))) (i32.const 4))))`,
      '',
      `${pad}(func $memcmp (param $a i32) (param $b i32) (param $n i32) (result i32)`,
      `${pad}${pad}(local $i i32)`,
      `${pad}${pad}(block $done`,
      `${pad}${pad}${pad}(loop $again`,
      `${pad}${pad}${pad}${pad}(br_if $done (i32.ge_u (local.get $i) (local.get $n)))`,
      `${pad}${pad}${pad}${pad}(if (i32.ne (i32.load8_u (i32.add (local.get $a) (local.get $i))) (i32.load8_u (i32.add (local.get $b) (local.get $i))))`,
      `${pad}${pad}${pad}${pad}${pad}(then (return (i32.const 0))))`,
      `${pad}${pad}${pad}${pad}(local.set $i (i32.add (local.get $i) (i32.const 1)))`,
      `${pad}${pad}${pad}${pad}(br $again)))`,
      `${pad}${pad}(i32.const 1))`,
      '',
      `${pad}(func $eq_str (param $a i32) (param $al i32) (param $b i32) (param $bl i32) (result i32)`,
      `${pad}${pad}(i32.and (i32.eq (local.get $al) (local.get $bl)) (call $memcmp (local.get $a) (local.get $b) (local.get $al))))`,
      '',
      `${pad}(func $contains (param $hay i32) (param $hay_len i32) (param $needle i32) (param $needle_len i32) (result i32)`,
      `${pad}${pad}(local $i i32)`,
      `${pad}${pad}(if (i32.eqz (local.get $needle_len)) (then (return (i32.const 1))))`,
      `${pad}${pad}(block $done`,
      `${pad}${pad}${pad}(loop $again`,
      `${pad}${pad}${pad}${pad}(br_if $done (i32.gt_u (i32.add (local.get $i) (local.get $needle_len)) (local.get $hay_len)))`,
      `${pad}${pad}${pad}${pad}(if (call $memcmp (i32.add (local.get $hay) (local.get $i)) (local.get $needle) (local.get $needle_len))`,
      `${pad}${pad}${pad}${pad}${pad}(then (return (i32.const 1))))`,
      `${pad}${pad}${pad}${pad}(local.set $i (i32.add (local.get $i) (i32.const 1)))`,
      `${pad}${pad}${pad}${pad}(br $again)))`,
      `${pad}${pad}(i32.const 0))`,
      '',
      `${pad}(func $memcpy (param $dst i32) (param $src i32) (param $n i32)`,
      `${pad}${pad}(local $i i32)`,
      `${pad}${pad}(block $done`,
      `${pad}${pad}${pad}(loop $again`,
      `${pad}${pad}${pad}${pad}(br_if $done (i32.ge_u (local.get $i) (local.get $n)))`,
      `${pad}${pad}${pad}${pad}(i32.store8 (i32.add (local.get $dst) (local.get $i)) (i32.load8_u (i32.add (local.get $src) (local.get $i))))`,
      `${pad}${pad}${pad}${pad}(local.set $i (i32.add (local.get $i) (i32.const 1)))`,
      `${pad}${pad}${pad}${pad}(br $again))))`,
      '',
      `${pad}(func $alloc (param $len i32) (result i32)`,
      `${pad}${pad}(local $p i32)`,
      `${pad}${pad}(local.set $p (global.get $heap_ptr))`,
      `${pad}${pad}(global.set $heap_ptr (i32.add (global.get $heap_ptr) (local.get $len)))`,
      `${pad}${pad}(local.get $p))`,
      '',
      `${pad}(func $list_idx (param $base i32) (param $i i32) (result i32)`,
      `${pad}${pad}(i32.load (i32.add (local.get $base) (i32.mul (local.get $i) (i32.const 4)))))`,
      '',
      `${pad}(func $str_at (param $base i32) (param $count i32) (param $i i32) (result i32 i32)`,
      `${pad}${pad}(local $idx i32)`,
      `${pad}${pad}(if (i32.ge_u (local.get $i) (local.get $count)) (then (return (i32.const 0) (i32.const 0))))`,
      `${pad}${pad}(local.set $idx (call $list_idx (local.get $base) (local.get $i)))`,
      `${pad}${pad}(call $s_off (local.get $idx))`,
      `${pad}${pad}(call $s_len (local.get $idx)))`,
    ];
  }

  // ==========================================================================
  // Per-module functions
  // ==========================================================================

  private emitModule(desc: WModule, pad: string, usedExports: Set<string>): string[] {
    const lines: string[] = [];
    const name = desc.prefix;
    const uniq = (base: string): string => this.uniqueExport(base, usedExports);

    switch (desc.mod.moduleType) {
      case 'agent':
        lines.push(...this.emitAgent(desc, pad, uniq));
        break;
      case 'tool':
        lines.push(...this.emitTool(desc, pad, uniq));
        break;
      case 'memory':
        lines.push(...this.emitMemory(desc, pad, uniq));
        break;
      case 'workflow':
        lines.push(...this.emitWorkflow(desc, pad, uniq));
        break;
      case 'team':
        lines.push(...this.emitTeam(desc, pad, uniq));
        break;
      case 'policy':
        lines.push(...this.emitPolicy(desc, pad, uniq));
        break;
      case 'system':
        lines.push(...this.emitSystem(desc, pad, uniq));
        break;
      default:
        lines.push(...this.emitGeneric(desc, pad, uniq));
    }

    return lines;
  }

  private emitAgent(desc: WModule, pad: string, uniq: (b: string) => string): string[] {
    const n = desc.prefix;
    const s = desc.indices;
    const tools = desc.lists.tools;
    const handoff = desc.lists.handoff;
    const lines: string[] = [];

    lines.push(`${pad};; ==== Agent: ${this.displayName(desc)} ====`);
    lines.push(`${pad}(func (export "${uniq(`${n}_execute`)}") (param $task_off i32) (param $task_len i32) (result i32)`);
    lines.push(`${pad}${pad}(i32.const 1))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_role`)}") (result i32 i32)`);
    lines.push(`${pad}${pad}(call $s_off (i32.const ${s.role})) (call $s_len (i32.const ${s.role})))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_goal`)}") (result i32 i32)`);
    lines.push(`${pad}${pad}(call $s_off (i32.const ${s.goal})) (call $s_len (i32.const ${s.goal})))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_tool_count`)}") (result i32) (i32.const ${tools.count}))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_tool`)}") (param $i i32) (result i32 i32)`);
    lines.push(`${pad}${pad}(call $str_at (i32.const ${tools.base}) (i32.const ${tools.count}) (local.get $i)))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_handoff_count`)}") (result i32) (i32.const ${handoff.count}))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_handoff`)}") (param $i i32) (result i32 i32)`);
    lines.push(`${pad}${pad}(call $str_at (i32.const ${handoff.base}) (i32.const ${handoff.count}) (local.get $i)))`);

    return lines;
  }

  private emitTool(desc: WModule, pad: string, uniq: (b: string) => string): string[] {
    const n = desc.prefix;
    const s = desc.indices;
    const caps = desc.lists.capabilities;
    const lines: string[] = [];

    lines.push(`${pad};; ==== Tool: ${this.displayName(desc)} ====`);
    lines.push(`${pad}(func (export "${uniq(`${n}_invoke`)}") (param $a_off i32) (param $a_len i32) (result i32)`);
    for (let i = 0; i < caps.count; i++) {
      lines.push(`${pad}${pad}(if (call $eq_str (local.get $a_off) (local.get $a_len) (call $s_off (call $list_idx (i32.const ${caps.base}) (i32.const ${i}))) (call $s_len (call $list_idx (i32.const ${caps.base}) (i32.const ${i}))))`);
      lines.push(`${pad}${pad}${pad}(then (return (i32.const 1))))`);
    }
    lines.push(`${pad}${pad}(i32.const 0))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_provider`)}") (result i32 i32)`);
    lines.push(`${pad}${pad}(call $s_off (i32.const ${s.provider})) (call $s_len (i32.const ${s.provider})))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_capability_count`)}") (result i32) (i32.const ${caps.count}))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_capability`)}") (param $i i32) (result i32 i32)`);
    lines.push(`${pad}${pad}(call $str_at (i32.const ${caps.base}) (i32.const ${caps.count}) (local.get $i)))`);

    return lines;
  }

  private emitMemory(desc: WModule, pad: string, uniq: (b: string) => string): string[] {
    const n = desc.prefix;
    const s = desc.indices;
    const base = desc.memBase as number;
    const lines: string[] = [];
    const rec = `(i32.add (i32.const ${base}) (i32.mul (local.get $i) (i32.const ${RECORD_STRIDE})))`;

    lines.push(`${pad};; ==== Memory: ${this.displayName(desc)} ====`);
    lines.push(`${pad};; record layout: key_off, key_len, val_off, val_len (16 bytes)`);
    lines.push(`${pad}(func (export "${uniq(`${n}_store`)}") (param $k_off i32) (param $k_len i32) (param $v_off i32) (param $v_len i32) (result i32)`);
    lines.push(`${pad}${pad}(local $i i32)`);
    lines.push(`${pad}${pad}(local $slot i32)`);
    lines.push(`${pad}${pad}(local $k_ptr i32)`);
    lines.push(`${pad}${pad}(local $v_ptr i32)`);
    lines.push(`${pad}${pad}(local.set $slot (i32.const -1))`);
    lines.push(`${pad}${pad}(block $find`);
    lines.push(`${pad}${pad}${pad}(loop $again`);
    lines.push(`${pad}${pad}${pad}${pad}(br_if $find (i32.ge_u (local.get $i) (i32.const ${RECORD_COUNT})))`);
    lines.push(`${pad}${pad}${pad}${pad}(if (i32.eqz (i32.load (i32.add ${rec} (i32.const 4))))`);
    lines.push(`${pad}${pad}${pad}${pad}${pad}(then (local.set $slot (local.get $i)) (br $find)))`);
    lines.push(`${pad}${pad}${pad}${pad}(local.set $i (i32.add (local.get $i) (i32.const 1)))`);
    lines.push(`${pad}${pad}${pad}${pad}(br $again)))`);
    lines.push(`${pad}${pad}(if (i32.lt_s (local.get $slot) (i32.const 0)) (then (return (i32.const 0))))`);
    lines.push(`${pad}${pad}(local.set $i (local.get $slot))`);
    lines.push(`${pad}${pad}(local.set $k_ptr (call $alloc (local.get $k_len)))`);
    lines.push(`${pad}${pad}(call $memcpy (local.get $k_ptr) (local.get $k_off) (local.get $k_len))`);
    lines.push(`${pad}${pad}(local.set $v_ptr (call $alloc (local.get $v_len)))`);
    lines.push(`${pad}${pad}(call $memcpy (local.get $v_ptr) (local.get $v_off) (local.get $v_len))`);
    lines.push(`${pad}${pad}(i32.store ${rec} (local.get $k_ptr))`);
    lines.push(`${pad}${pad}(i32.store (i32.add ${rec} (i32.const 4)) (local.get $k_len))`);
    lines.push(`${pad}${pad}(i32.store (i32.add ${rec} (i32.const 8)) (local.get $v_ptr))`);
    lines.push(`${pad}${pad}(i32.store (i32.add ${rec} (i32.const 12)) (local.get $v_len))`);
    lines.push(`${pad}${pad}(i32.const 1))`);
    lines.push('');

    lines.push(`${pad}(func (export "${uniq(`${n}_retrieve`)}") (param $k_off i32) (param $k_len i32) (result i32 i32)`);
    lines.push(`${pad}${pad}(local $i i32)`);
    lines.push(`${pad}${pad}(block $find`);
    lines.push(`${pad}${pad}${pad}(loop $again`);
    lines.push(`${pad}${pad}${pad}${pad}(br_if $find (i32.ge_u (local.get $i) (i32.const ${RECORD_COUNT})))`);
    lines.push(`${pad}${pad}${pad}${pad}(if (i32.and (i32.eq (i32.load (i32.add ${rec} (i32.const 4))) (local.get $k_len)) (call $memcmp (i32.load ${rec}) (local.get $k_off) (local.get $k_len)))`);
    lines.push(`${pad}${pad}${pad}${pad}${pad}(then (return (i32.load (i32.add ${rec} (i32.const 8))) (i32.load (i32.add ${rec} (i32.const 12))))))`);
    lines.push(`${pad}${pad}${pad}${pad}(local.set $i (i32.add (local.get $i) (i32.const 1)))`);
    lines.push(`${pad}${pad}${pad}${pad}(br $again)))`);
    lines.push(`${pad}${pad}(i32.const 0) (i32.const 0))`);
    lines.push('');

    lines.push(`${pad}(func (export "${uniq(`${n}_delete`)}") (param $k_off i32) (param $k_len i32) (result i32)`);
    lines.push(`${pad}${pad}(local $i i32)`);
    lines.push(`${pad}${pad}(block $find`);
    lines.push(`${pad}${pad}${pad}(loop $again`);
    lines.push(`${pad}${pad}${pad}${pad}(br_if $find (i32.ge_u (local.get $i) (i32.const ${RECORD_COUNT})))`);
    lines.push(`${pad}${pad}${pad}${pad}(if (i32.and (i32.eq (i32.load (i32.add ${rec} (i32.const 4))) (local.get $k_len)) (call $memcmp (i32.load ${rec}) (local.get $k_off) (local.get $k_len)))`);
    lines.push(`${pad}${pad}${pad}${pad}${pad}(then (i32.store (i32.add ${rec} (i32.const 4)) (i32.const 0)) (return (i32.const 1))))`);
    lines.push(`${pad}${pad}${pad}${pad}(local.set $i (i32.add (local.get $i) (i32.const 1)))`);
    lines.push(`${pad}${pad}${pad}${pad}(br $again)))`);
    lines.push(`${pad}${pad}(i32.const 0))`);
    lines.push('');

    lines.push(`${pad}(func (export "${uniq(`${n}_search`)}") (param $q_off i32) (param $q_len i32) (result i32)`);
    lines.push(`${pad}${pad}(local $i i32)`);
    lines.push(`${pad}${pad}(local $count i32)`);
    lines.push(`${pad}${pad}(local.set $count (i32.const 0))`);
    lines.push(`${pad}${pad}(block $done`);
    lines.push(`${pad}${pad}${pad}(loop $again`);
    lines.push(`${pad}${pad}${pad}${pad}(br_if $done (i32.ge_u (local.get $i) (i32.const ${RECORD_COUNT})))`);
    lines.push(`${pad}${pad}${pad}${pad}(if (i32.and (i32.gt_u (i32.load (i32.add ${rec} (i32.const 4))) (i32.const 0)) (call $contains (i32.load ${rec}) (i32.load (i32.add ${rec} (i32.const 4))) (local.get $q_off) (local.get $q_len)))`);
    lines.push(`${pad}${pad}${pad}${pad}${pad}(then`);
    lines.push(`${pad}${pad}${pad}${pad}${pad}${pad}(i32.store (i32.add (global.get $search_base) (i32.mul (local.get $count) (i32.const 8))) (i32.load ${rec}))`);
    lines.push(`${pad}${pad}${pad}${pad}${pad}${pad}(i32.store (i32.add (i32.add (global.get $search_base) (i32.mul (local.get $count) (i32.const 8))) (i32.const 4)) (i32.load (i32.add ${rec} (i32.const 4))))`);
    lines.push(`${pad}${pad}${pad}${pad}${pad}${pad}(local.set $count (i32.add (local.get $count) (i32.const 1)))))`);
    lines.push(`${pad}${pad}${pad}${pad}(local.set $i (i32.add (local.get $i) (i32.const 1)))`);
    lines.push(`${pad}${pad}${pad}${pad}(br $again)))`);
    lines.push(`${pad}${pad}(local.get $count))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_search_key`)}") (param $i i32) (result i32 i32)`);
    lines.push(`${pad}${pad}(i32.load (i32.add (global.get $search_base) (i32.mul (local.get $i) (i32.const 8))))`);
    lines.push(`${pad}${pad}(i32.load (i32.add (i32.add (global.get $search_base) (i32.mul (local.get $i) (i32.const 8))) (i32.const 4))))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_count`)}") (result i32)`);
    lines.push(`${pad}${pad}(local $i i32)`);
    lines.push(`${pad}${pad}(local $n i32)`);
    lines.push(`${pad}${pad}(block $done`);
    lines.push(`${pad}${pad}${pad}(loop $again`);
    lines.push(`${pad}${pad}${pad}${pad}(br_if $done (i32.ge_u (local.get $i) (i32.const ${RECORD_COUNT})))`);
    lines.push(`${pad}${pad}${pad}${pad}(if (i32.gt_u (i32.load (i32.add ${rec} (i32.const 4))) (i32.const 0)) (then (local.set $n (i32.add (local.get $n) (i32.const 1)))))`);
    lines.push(`${pad}${pad}${pad}${pad}(local.set $i (i32.add (local.get $i) (i32.const 1)))`);
    lines.push(`${pad}${pad}${pad}${pad}(br $again)))`);
    lines.push(`${pad}${pad}(local.get $n))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_format`)}") (result i32 i32) (call $s_off (i32.const ${s.format})) (call $s_len (i32.const ${s.format})))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_backend`)}") (result i32 i32) (call $s_off (i32.const ${s.backend})) (call $s_len (i32.const ${s.backend})))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_scope`)}") (result i32 i32) (call $s_off (i32.const ${s.scope})) (call $s_len (i32.const ${s.scope})))`);

    return lines;
  }

  private emitWorkflow(desc: WModule, pad: string, uniq: (b: string) => string): string[] {
    const n = desc.prefix;
    const steps = desc.lists.steps;
    const src = desc.lists.edgesSource;
    const tgt = desc.lists.edgesTarget;
    const lines: string[] = [];

    lines.push(`${pad};; ==== Workflow: ${this.displayName(desc)} ====`);
    lines.push(`${pad};; run() returns the number of steps schedulable (host drives execution).`);
    lines.push(`${pad}(func (export "${uniq(`${n}_run`)}") (result i32) (i32.const ${steps.count}))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_step_count`)}") (result i32) (i32.const ${steps.count}))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_step`)}") (param $i i32) (result i32 i32)`);
    lines.push(`${pad}${pad}(call $str_at (i32.const ${steps.base}) (i32.const ${steps.count}) (local.get $i)))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_edge_count`)}") (result i32) (i32.const ${src.count}))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_edge_source`)}") (param $i i32) (result i32 i32)`);
    lines.push(`${pad}${pad}(call $str_at (i32.const ${src.base}) (i32.const ${src.count}) (local.get $i)))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_edge_target`)}") (param $i i32) (result i32 i32)`);
    lines.push(`${pad}${pad}(call $str_at (i32.const ${tgt.base}) (i32.const ${tgt.count}) (local.get $i)))`);

    return lines;
  }

  private emitTeam(desc: WModule, pad: string, uniq: (b: string) => string): string[] {
    const n = desc.prefix;
    const members = desc.lists.members;
    const lines: string[] = [];

    lines.push(`${pad};; ==== Team: ${this.displayName(desc)} ====`);
    lines.push(`${pad}(func (export "${uniq(`${n}_coordinate`)}") (result i32) (i32.const ${members.count}))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_member_count`)}") (result i32) (i32.const ${members.count}))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_member`)}") (param $i i32) (result i32 i32)`);
    lines.push(`${pad}${pad}(call $str_at (i32.const ${members.base}) (i32.const ${members.count}) (local.get $i)))`);

    return lines;
  }

  private emitPolicy(desc: WModule, pad: string, uniq: (b: string) => string): string[] {
    const n = desc.prefix;
    const allow = desc.lists.allow;
    const deny = desc.lists.deny;
    const lines: string[] = [];

    lines.push(`${pad};; ==== Policy: ${this.displayName(desc)} ====`);
    lines.push(`${pad}(func (export "${uniq(`${n}_check`)}") (param $a_off i32) (param $a_len i32) (result i32)`);
    for (let i = 0; i < deny.count; i++) {
      lines.push(`${pad}${pad}(if (call $eq_str (local.get $a_off) (local.get $a_len) (call $s_off (call $list_idx (i32.const ${deny.base}) (i32.const ${i}))) (call $s_len (call $list_idx (i32.const ${deny.base}) (i32.const ${i}))))`);
      lines.push(`${pad}${pad}${pad}(then (return (i32.const 0))))`);
    }
    for (let i = 0; i < allow.count; i++) {
      lines.push(`${pad}${pad}(if (call $eq_str (local.get $a_off) (local.get $a_len) (call $s_off (call $list_idx (i32.const ${allow.base}) (i32.const ${i}))) (call $s_len (call $list_idx (i32.const ${allow.base}) (i32.const ${i}))))`);
      lines.push(`${pad}${pad}${pad}(then (return (i32.const 1))))`);
    }
    lines.push(`${pad}${pad}(i32.const 0))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_allow_count`)}") (result i32) (i32.const ${allow.count}))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_deny_count`)}") (result i32) (i32.const ${deny.count}))`);

    return lines;
  }

  private emitSystem(desc: WModule, pad: string, uniq: (b: string) => string): string[] {
    const n = desc.prefix;
    const agents = desc.lists.agents;
    const modules = desc.lists.modules;
    const src = desc.lists.edgesSource;
    const tgt = desc.lists.edgesTarget;
    const nodeCount = agents.count + modules.count;
    const lines: string[] = [];

    lines.push(`${pad};; ==== System: ${this.displayName(desc)} ====`);
    lines.push(`${pad};; run() returns the number of nodes (agents + modules) to execute.`);
    lines.push(`${pad}(func (export "${uniq(`${n}_run`)}") (result i32) (i32.const ${nodeCount}))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_agent_count`)}") (result i32) (i32.const ${agents.count}))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_module_count`)}") (result i32) (i32.const ${modules.count}))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_node_count`)}") (result i32) (i32.const ${nodeCount}))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_agent`)}") (param $i i32) (result i32 i32)`);
    lines.push(`${pad}${pad}(call $str_at (i32.const ${agents.base}) (i32.const ${agents.count}) (local.get $i)))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_module`)}") (param $i i32) (result i32 i32)`);
    lines.push(`${pad}${pad}(call $str_at (i32.const ${modules.base}) (i32.const ${modules.count}) (local.get $i)))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_edge_count`)}") (result i32) (i32.const ${src.count}))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_edge_source`)}") (param $i i32) (result i32 i32)`);
    lines.push(`${pad}${pad}(call $str_at (i32.const ${src.base}) (i32.const ${src.count}) (local.get $i)))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_edge_target`)}") (param $i i32) (result i32 i32)`);
    lines.push(`${pad}${pad}(call $str_at (i32.const ${tgt.base}) (i32.const ${tgt.count}) (local.get $i)))`);

    return lines;
  }

  private emitGeneric(desc: WModule, pad: string, uniq: (b: string) => string): string[] {
    const n = desc.prefix;
    const s = desc.indices;
    const caps = desc.lists.capabilities;
    const inputs = desc.lists.inputs;
    const outputs = desc.lists.outputs;
    const required = desc.lists.required;
    const lines: string[] = [];

    lines.push(`${pad};; ==== Module: ${this.displayName(desc)} ====`);
    lines.push(`${pad};; run() returns the number of required inputs present in the input string.`);
    lines.push(`${pad}(func (export "${uniq(`${n}_run`)}") (param $in_off i32) (param $in_len i32) (result i32)`);
    if (required.count === 0) {
      lines.push(`${pad}${pad}(i32.const 1))`);
    } else {
      let expr = `(call $contains (local.get $in_off) (local.get $in_len) (call $s_off (call $list_idx (i32.const ${required.base}) (i32.const 0))) (call $s_len (call $list_idx (i32.const ${required.base}) (i32.const 0))))`;
      for (let i = 1; i < required.count; i++) {
        const term = `(call $contains (local.get $in_off) (local.get $in_len) (call $s_off (call $list_idx (i32.const ${required.base}) (i32.const ${i}))) (call $s_len (call $list_idx (i32.const ${required.base}) (i32.const ${i}))))`;
        expr = `(i32.add ${expr} ${term})`;
      }
      lines.push(`${pad}${pad}${expr})`);
    }
    lines.push(`${pad}(func (export "${uniq(`${n}_description`)}") (result i32 i32)`);
    lines.push(`${pad}${pad}(call $s_off (i32.const ${s.description ?? s.name})) (call $s_len (i32.const ${s.description ?? s.name})))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_capability_count`)}") (result i32) (i32.const ${caps.count}))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_capability`)}") (param $i i32) (result i32 i32)`);
    lines.push(`${pad}${pad}(call $str_at (i32.const ${caps.base}) (i32.const ${caps.count}) (local.get $i)))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_input_count`)}") (result i32) (i32.const ${inputs.count}))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_input`)}") (param $i i32) (result i32 i32)`);
    lines.push(`${pad}${pad}(call $str_at (i32.const ${inputs.base}) (i32.const ${inputs.count}) (local.get $i)))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_output_count`)}") (result i32) (i32.const ${outputs.count}))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_output`)}") (param $i i32) (result i32 i32)`);
    lines.push(`${pad}${pad}(call $str_at (i32.const ${outputs.base}) (i32.const ${outputs.count}) (local.get $i)))`);
    lines.push(`${pad}(func (export "${uniq(`${n}_required_count`)}") (result i32) (i32.const ${required.count}))`);

    return lines;
  }

  // ==========================================================================
  // Encoding helpers
  // ==========================================================================

  private uniqueExport(base: string, usedExports: Set<string>): string {
    let out = base;
    let i = 2;
    while (usedExports.has(out)) out = `${base}_${i++}`;
    usedExports.add(out);
    return out;
  }

  private displayName(desc: WModule): string {
    return desc.mod.name.replace(/\r?\n/g, ' ');
  }

  private sanitize(name: string): string {
    const cleaned = name.replace(/[^a-zA-Z0-9]+/g, '_').toLowerCase().replace(/^_+|_+$/g, '');
    return cleaned || 'module';
  }

  private byteLength(s: string): number {
    return new TextEncoder().encode(s).length;
  }

  private utf8Bytes(s: string): number[] {
    return Array.from(new TextEncoder().encode(s));
  }

  private align4(n: number): number {
    return Math.ceil(n / 4) * 4;
  }

  private le32(v: number): number[] {
    return [v & 0xff, (v >>> 8) & 0xff, (v >>> 16) & 0xff, (v >>> 24) & 0xff];
  }

  private le32Bytes(indices: number[]): number[] {
    const out: number[] = [];
    for (const i of indices) out.push(...this.le32(i));
    return out;
  }

  private watBytes(bytes: number[]): string {
    let out = '"';
    for (const b of bytes) {
      if (b >= 0x20 && b <= 0x7e && b !== 0x22 && b !== 0x5c) {
        out += String.fromCharCode(b);
      } else {
        out += `\\${b.toString(16).padStart(2, '0')}`;
      }
    }
    return out + '"';
  }
}