/**
 * WebAssembly Target
 *
 * Compiles MAM AST to WAT (WebAssembly Text) format.
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2MemoryNode, V2WorkflowNode, V2TeamNode, V2PolicyNode, V2SystemNode } from '@mam/ast';
import { CompileTargetHandler, CompilerConfig } from '../compiler.js';
import { generateModuleContext } from '../context.js';

export class WasmTarget implements CompileTargetHandler {
  name = 'wasm';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];
    const indent = config.indent || 2;

    lines.push(';; Generated by MAM Compiler');
    lines.push(';; Target: WebAssembly (WAT)');
    lines.push('');

    for (const mod of modules) {
      lines.push(generateModuleContext(mod, 'wasm'));
      lines.push('');
      lines.push(...this.compileModule(mod, indent, config));
      lines.push('');
    }

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const lines: string[] = [];

    if (config.includeComments) {
      lines.push(`;; Module: ${mod.name}`);
      lines.push(`;; Type: ${mod.moduleType}`);
      if (mod.description) lines.push(`;; ${mod.description}`);
      lines.push('');
    }

    switch (mod.moduleType) {
      case 'agent':
        lines.push(...this.compileAgent(mod as unknown as V2AgentNode, indent, config));
        break;
      case 'tool':
        lines.push(...this.compileTool(mod as unknown as V2ToolNode, indent, config));
        break;
      case 'memory':
        lines.push(...this.compileMemory(mod as unknown as V2MemoryNode, indent, config));
        break;
      case 'workflow':
        lines.push(...this.compileWorkflow(mod as unknown as V2WorkflowNode, indent, config));
        break;
      case 'team':
        lines.push(...this.compileTeam(mod as unknown as V2TeamNode, indent, config));
        break;
      case 'policy':
        lines.push(...this.compilePolicy(mod as unknown as V2PolicyNode, indent, config));
        break;
      case 'system':
        lines.push(...this.compileSystem(mod as unknown as V2SystemNode, indent, config));
        break;
      default:
        lines.push(...this.compileGeneric(mod, indent, config));
    }

    return lines;
  }

  private compileAgent(mod: V2AgentNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const funcName = mod.name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();

    return [
      `(module`,
      `${pad};; Agent: ${mod.name}`,
      `${pad};; Role: ${mod.role || 'N/A'}`,
      `${pad};; Goal: ${mod.goal || 'N/A'}`,
      '',
      `${pad}(memory (export "memory") 1)`,
      '',
      `${pad}(func (export "${funcName}_execute") (param i32 i32) (result i32)`,
      `${pad}${pad};; Execute the agent's task`,
      `${pad}${pad}local.get 0`,
      `${pad}${pad}local.get 1`,
      `${pad}${pad}i32.add`,
      `${pad})`,
      '',
      `${pad}(func (export "${funcName}_get_role") (result i32 i32)`,
      `${pad}${pad};; Return role string pointer and length`,
      `${pad}${pad}i32.const 0`,
      `${pad}${pad}i32.const 0`,
      `${pad})`,
      ')',
    ];
  }

  private compileTool(mod: V2ToolNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const funcName = mod.name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();

    return [
      `(module`,
      `${pad};; Tool: ${mod.name}`,
      `${pad};; Provider: ${mod.provider}`,
      '',
      `${pad}(memory (export "memory") 1)`,
      '',
      `${pad}(func (export "${funcName}_execute") (param i32 i32) (result i32)`,
      `${pad}${pad};; Execute a tool action`,
      `${pad}${pad}local.get 0`,
      `${pad}${pad}local.get 1`,
      `${pad}${pad}i32.add`,
      `${pad})`,
      '',
      `${pad}(func (export "${funcName}_get_provider") (result i32 i32)`,
      `${pad}${pad}i32.const 0`,
      `${pad}${pad}i32.const 0`,
      `${pad})`,
      ')',
    ];
  }

  private compileMemory(mod: V2MemoryNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const funcName = mod.name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();

    return [
      `(module`,
      `${pad};; Memory: ${mod.name}`,
      `${pad};; Format: ${mod.format}, Backend: ${mod.backend}, Scope: ${mod.scope}`,
      '',
      `${pad}(memory (export "memory") 1)`,
      '',
      `${pad}(func (export "${funcName}_store") (param i32 i32 i32 i32)`,
      `${pad}${pad};; Store key-value pair`,
      `${pad}${pad}nop`,
      `${pad})`,
      '',
      `${pad}(func (export "${funcName}_retrieve") (param i32 i32) (result i32 i32)`,
      `${pad}${pad};; Retrieve value by key`,
      `${pad}${pad}i32.const 0`,
      `${pad}${pad}i32.const 0`,
      `${pad})`,
      ')',
    ];
  }

  private compileWorkflow(mod: V2WorkflowNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const funcName = mod.name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();
    const stepCount = mod.steps?.length || 0;
    const edgeCount = mod.edges?.length || 0;

    return [
      `(module`,
      `${pad};; Workflow: ${mod.name}`,
      `${pad};; Steps: ${stepCount}, Edges: ${edgeCount}`,
      '',
      `${pad}(memory (export "memory") 1)`,
      `${pad}(global (mutual i32) (i32.const 0))`,
      '',
      `${pad}(func (export "${funcName}_execute")`,
      `${pad}${pad};; Execute workflow steps`,
      `${pad}${pad}nop`,
      `${pad})`,
      '',
      `${pad}(func (export "${funcName}_get_step_count") (result i32)`,
      `${pad}${pad}i32.const ${stepCount}`,
      `${pad})`,
      ')',
    ];
  }

  private compileTeam(mod: V2TeamNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const funcName = mod.name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();
    const memberCount = mod.members?.length || 0;

    return [
      `(module`,
      `${pad};; Team: ${mod.name}`,
      `${pad};; Members: ${memberCount}`,
      '',
      `${pad}(memory (export "memory") 1)`,
      '',
      `${pad}(func (export "${funcName}_coordinate")`,
      `${pad}${pad};; Coordinate team members`,
      `${pad}${pad}nop`,
      `${pad})`,
      '',
      `${pad}(func (export "${funcName}_get_member_count") (result i32)`,
      `${pad}${pad}i32.const ${memberCount}`,
      `${pad})`,
      ')',
    ];
  }

  private compilePolicy(mod: V2PolicyNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const funcName = mod.name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();

    return [
      `(module`,
      `${pad};; Policy: ${mod.name}`,
      `${pad};; Allow: ${mod.allow?.length || 0} rules, Deny: ${mod.deny?.length || 0} rules`,
      '',
      `${pad}(memory (export "memory") 1)`,
      '',
      `${pad}(func (export "${funcName}_check") (param i32 i32) (result i32)`,
      `${pad}${pad};; Check if action is allowed (1=allow, 0=deny)`,
      `${pad}${pad}i32.const 1`,
      `${pad})`,
      ')',
    ];
  }

  private compileSystem(mod: V2SystemNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const funcName = mod.name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();

    return [
      `(module`,
      `${pad};; System: ${mod.name}`,
      `${pad};; Agents: ${mod.agents?.length || 0}, Modules: ${mod.modules?.length || 0}`,
      '',
      `${pad}(memory (export "memory") 1)`,
      '',
      `${pad}(func (export "${funcName}_run")`,
      `${pad}${pad};; Run the system`,
      `${pad}${pad}nop`,
      `${pad})`,
      ')',
    ];
  }

  private compileGeneric(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const pad = ' '.repeat(indent);
    const funcName = mod.name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();

    return [
      `(module`,
      `${pad};; Module: ${mod.name}`,
      `${pad};; ${mod.description || mod.name}`,
      '',
      `${pad}(memory (export "memory") 1)`,
      '',
      `${pad}(func (export "${funcName}_init")`,
      `${pad}${pad}nop`,
      `${pad})`,
      ')',
    ];
  }
}
