# Auto-generated by MAM Compiler | Target: terraform | Source: C:\Users\USER\LifeJiggy\Prompt_AI-Support\MAM\examples\advanced\knowledge-graph.mam.md

terraform {
    required_version = ">= 1.0"
    required_providers {
        aws = { source = "hashicorp/aws", version = "~> 5.0" }
    }
}

variable "region" { description = "AWS region"; type = string; default = "us-east-1" }

resource "aws_ecs_cluster" "knowledge-graph_mam" {
    name = "knowledge-graph_mam-cluster"
    setting { name = "containerInsights"; value = "enabled" }
}

resource "aws_ecs_task_definition" "knowledge-graph_mam" {
    family = "knowledge-graph_mam-task"
    network_mode = "awsvpc"
    requires_compatibilities = ["FARGATE"]
    cpu = 256; memory = 512
    container_definitions = jsonencode([{name="knowledge-graph_mam",image="mam/knowledge-graph_mam:latest",portMappings=[{containerPort=8080}],essential=true}])
}

resource "aws_ecs_service" "knowledge-graph_mam" {
    name = "knowledge-graph_mam-svc"
    cluster = aws_ecs_cluster.knowledge-graph_mam.id
    task_definition = aws_ecs_task_definition.knowledge-graph_mam.arn
    desired_count = 1; launch_type = "FARGATE"
    network_configuration { subnets = ["subnet-xxx"]; security_groups = ["sg-xxx"] }
}

output "cluster_arn" { value = aws_ecs_cluster.knowledge-graph_mam.arn }
