/**
 * MAM Compiler
 * 
 * Transpiles MAM AST to target languages.
 * MAM never executes. MAM compiles.
 */

import { V2ModuleNode, V2AgentNode, V2ToolNode, V2MemoryNode, V2WorkflowNode, V2TeamNode, V2PolicyNode, V2SystemNode } from '@mam/ast';
import { generateModuleContext } from './context.js';

// ============================================================================
// Types
// ============================================================================

export type CompileTarget = 'python' | 'javascript' | 'go' | 'rust' | 'typescript' | 'json' | 'yaml' | 'openai' | 'langgraph' | 'crewai';

export interface CompilerConfig {
  target: CompileTarget;
  indent?: number;
  includeComments?: boolean;
  includeMetadata?: boolean;
  optimize?: boolean;
}

export interface CompileResult {
  success: boolean;
  output: string;
  target: CompileTarget;
  warnings: string[];
  errors: string[];
  stats: CompileStats;
}

export interface CompileStats {
  modulesCompiled: number;
  linesGenerated: number;
  timeMs: number;
}

// ============================================================================
// Target Interface
// ============================================================================

export interface CompileTargetHandler {
  name: string;
  compile(modules: V2ModuleNode[], config: CompilerConfig): string;
}

// ============================================================================
// Compiler
// ============================================================================

export class MAMCompiler {
  private targets: Map<string, CompileTargetHandler> = new Map();
  private startTime: number = 0;

  constructor() {
    // Register built-in targets
    this.targets.set('python', new PythonTargetHandler());
    this.targets.set('javascript', new JavaScriptTargetHandler());
    this.targets.set('json', new JSONTargetHandler());
  }

  /**
   * Register a custom target
   */
  registerTarget(name: string, handler: CompileTargetHandler): void {
    this.targets.set(name, handler);
  }

  /**
   * Compile modules to target
   */
  compile(modules: V2ModuleNode[], config: CompilerConfig): CompileResult {
    this.startTime = performance.now();
    const warnings: string[] = [];
    const errors: string[] = [];

    const handler = this.targets.get(config.target);
    if (!handler) {
      return {
        success: false,
        output: '',
        target: config.target,
        warnings,
        errors: [`Unknown target: ${config.target}`],
        stats: { modulesCompiled: 0, linesGenerated: 0, timeMs: 0 },
      };
    }

    try {
      // Validate modules
      for (const mod of modules) {
        if (!mod.name) {
          warnings.push(`Module at line ${mod.location.start.line} has no name`);
        }
      }

      // Compile
      const output = handler.compile(modules, config);

      const lines = output.split('\n').length;

      return {
        success: true,
        output,
        target: config.target,
        warnings,
        errors,
        stats: {
          modulesCompiled: modules.length,
          linesGenerated: lines,
          timeMs: performance.now() - this.startTime,
        },
      };
    } catch (error) {
      return {
        success: false,
        output: '',
        target: config.target,
        warnings,
        errors: [(error as Error).message],
        stats: { modulesCompiled: 0, linesGenerated: 0, timeMs: performance.now() - this.startTime },
      };
    }
  }

  /**
   * Get available targets
   */
  getTargets(): string[] {
    return Array.from(this.targets.keys());
  }
}

// ============================================================================
// Python Target
// ============================================================================

class PythonTargetHandler implements CompileTargetHandler {
  name = 'python';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];
    const indent = config.indent || 4;

    lines.push('"""');
    lines.push('Generated by MAM Compiler');
    lines.push('Target: Python');
    lines.push('"""');
    lines.push('');

    for (const mod of modules) {
      lines.push(generateModuleContext(mod, 'python'));
      lines.push('');
      lines.push(...this.compileModule(mod, indent, config));
      lines.push('');
    }

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];
    const pad = ' '.repeat(indent);

    if (config.includeComments) {
      lines.push(`# Module: ${mod.name}`);
      lines.push(`# Type: ${mod.moduleType}`);
      if (mod.description) lines.push(`# ${mod.description}`);
      lines.push('');
    }

    switch (mod.moduleType) {
      case 'agent':
        lines.push(...this.compileAgent(mod as unknown as V2AgentNode, indent, config));
        break;
      case 'tool':
        lines.push(...this.compileTool(mod as unknown as V2ToolNode, indent, config));
        break;
      case 'memory':
        lines.push(...this.compileMemory(mod as unknown as V2MemoryNode, indent, config));
        break;
      case 'workflow':
        lines.push(...this.compileWorkflow(mod as unknown as V2WorkflowNode, indent, config));
        break;
      case 'team':
        lines.push(...this.compileTeam(mod as unknown as V2TeamNode, indent, config));
        break;
      case 'policy':
        lines.push(...this.compilePolicy(mod as unknown as V2PolicyNode, indent, config));
        break;
      case 'system':
        lines.push(...this.compileSystem(mod as unknown as V2SystemNode, indent, config));
        break;
      default:
        lines.push(...this.compileGenericModule(mod, indent, config));
    }

    return lines;
  }

  private compileAgent(mod: V2AgentNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];
    const pad = ' '.repeat(indent);

    lines.push(`class ${mod.name.replace(/[^a-zA-Z0-9_]/g, '_')}:`);
    lines.push(`${pad}"""${mod.goal || mod.role || mod.name}"""`);
    lines.push('');
    lines.push(`${pad}def __init__(self):`);
    lines.push(`${pad}${pad}self.role = "${mod.role || ''}"`);
    lines.push(`${pad}${pad}self.goal = "${mod.goal || ''}"`);
    lines.push(`${pad}${pad}self.tools = ${JSON.stringify(mod.tools || [])}`);
    lines.push(`${pad}${pad}self.handoff = ${JSON.stringify(mod.handoff || [])}`);
    lines.push('');

    if (mod.memory) {
      lines.push(`${pad}def get_memory(self):`);
      lines.push(`${pad}${pad}return None  # Memory: ${mod.memory.type || 'local'}`);
      lines.push('');
    }

    lines.push(`${pad}def execute(self, task):`);
    lines.push(`${pad}${pad}"""Execute the agent's task."""`);
    lines.push(`${pad}${pad}raise NotImplementedError`);
    lines.push('');

    return lines;
  }

  private compileTool(mod: V2ToolNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];
    const pad = ' '.repeat(indent);

    lines.push(`class ${mod.name.replace(/[^a-zA-Z0-9_]/g, '_')}:`);
    lines.push(`${pad}"""Tool: ${mod.provider}"""`);
    lines.push('');
    lines.push(`${pad}def __init__(self):`);
    lines.push(`${pad}${pad}self.provider = "${mod.provider}"`);
    lines.push(`${pad}${pad}self.capabilities = ${JSON.stringify(mod.capabilities || [])}`);
    lines.push('');

    lines.push(`${pad}def execute(self, action, **kwargs):`);
    lines.push(`${pad}${pad}"""Execute a tool action."""`);
    lines.push(`${pad}${pad}raise NotImplementedError`);
    lines.push('');

    return lines;
  }

  private compileMemory(mod: V2MemoryNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];
    const pad = ' '.repeat(indent);

    lines.push(`class ${mod.name.replace(/[^a-zA-Z0-9_]/g, '_')}:`);
    lines.push(`${pad}"""Memory: ${mod.format} / ${mod.backend}"""`);
    lines.push('');
    lines.push(`${pad}def __init__(self):`);
    lines.push(`${pad}${pad}self.format = "${mod.format}"`);
    lines.push(`${pad}${pad}self.backend = "${mod.backend}"`);
    lines.push(`${pad}${pad}self.scope = "${mod.scope}"`);
    lines.push('');

    lines.push(`${pad}def store(self, key, value):`);
    lines.push(`${pad}${pad}"""Store data in memory."""`);
    lines.push(`${pad}${pad}raise NotImplementedError`);
    lines.push('');

    lines.push(`${pad}def retrieve(self, key):`);
    lines.push(`${pad}${pad}"""Retrieve data from memory."""`);
    lines.push(`${pad}${pad}raise NotImplementedError`);
    lines.push('');

    return lines;
  }

  private compileWorkflow(mod: V2WorkflowNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];
    const pad = ' '.repeat(indent);

    lines.push(`class ${mod.name.replace(/[^a-zA-Z0-9_]/g, '_')}:`);
    lines.push(`${pad}"""Workflow"""`);
    lines.push('');
    lines.push(`${pad}STEPS = ${JSON.stringify(mod.steps?.map((s: { name: string }) => s.name) || [])}`);
    lines.push(`${pad}EDGES = ${JSON.stringify(mod.edges?.map((e: { source: string; target: string }) => [e.source, e.target]) || [])}`);
    lines.push('');

    lines.push(`${pad}def execute(self):`);
    lines.push(`${pad}${pad}"""Execute the workflow."""`);
    lines.push(`${pad}${pad}for step in self.STEPS:`);
    lines.push(`${pad}${pad}${pad}print(f"Executing step: {step}")`);
    lines.push('');

    return lines;
  }

  private compileTeam(mod: V2TeamNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];
    const pad = ' '.repeat(indent);

    lines.push(`class ${mod.name.replace(/[^a-zA-Z0-9_]/g, '_')}:`);
    lines.push(`${pad}"""Team"""`);
    lines.push('');
    lines.push(`${pad}MEMBERS = ${JSON.stringify(mod.members || [])}`);
    lines.push('');

    lines.push(`${pad}def coordinate(self):`);
    lines.push(`${pad}${pad}"""Coordinate team members."""`);
    lines.push(`${pad}${pad}raise NotImplementedError`);
    lines.push('');

    return lines;
  }

  private compilePolicy(mod: V2PolicyNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];
    const pad = ' '.repeat(indent);

    lines.push(`class ${mod.name.replace(/[^a-zA-Z0-9_]/g, '_')}:`);
    lines.push(`${pad}"""Policy"""`);
    lines.push('');
    lines.push(`${pad}ALLOW = ${JSON.stringify(mod.allow || [])}`);
    lines.push(`${pad}DENY = ${JSON.stringify(mod.deny || [])}`);
    lines.push('');

    lines.push(`${pad}def check(self, action):`);
    lines.push(`${pad}${pad}"""Check if action is allowed."""`);
    lines.push(`${pad}${pad}if action in self.DENY:`);
    lines.push(`${pad}${pad}${pad}return False`);
    lines.push(`${pad}${pad}if action in self.ALLOW:`);
    lines.push(`${pad}${pad}${pad}return True`);
    lines.push(`${pad}${pad}return False`);
    lines.push('');

    return lines;
  }

  private compileSystem(mod: V2SystemNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];
    const pad = ' '.repeat(indent);

    lines.push(`class ${mod.name.replace(/[^a-zA-Z0-9_]/g, '_')}:`);
    lines.push(`${pad}"""System"""`);
    lines.push('');
    lines.push(`${pad}AGENTS = ${JSON.stringify(mod.agents || [])}`);
    lines.push(`${pad}MODULES = ${JSON.stringify(mod.modules || [])}`);
    lines.push(`${pad}EDGES = ${JSON.stringify(mod.edges?.map((e: { source: string; target: string }) => [e.source, e.target]) || [])}`);
    lines.push('');

    lines.push(`${pad}def run(self):`);
    lines.push(`${pad}${pad}"""Run the system."""`);
    lines.push(`${pad}${pad}raise NotImplementedError`);
    lines.push('');

    return lines;
  }

  private compileGenericModule(mod: V2ModuleNode, indent: number, config: CompilerConfig): string[] {
    const lines: string[] = [];
    const pad = ' '.repeat(indent);

    lines.push(`class ${mod.name.replace(/[^a-zA-Z0-9_]/g, '_')}:`);
    lines.push(`${pad}"""${mod.description || mod.name}"""`);
    lines.push('');
    lines.push(`${pad}def __init__(self):`);
    lines.push(`${pad}${pad}pass`);
    lines.push('');

    return lines;
  }
}

// ============================================================================
// JavaScript Target
// ============================================================================

class JavaScriptTargetHandler implements CompileTargetHandler {
  name = 'javascript';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    const lines: string[] = [];

    lines.push('/**');
    lines.push(' * Generated by MAM Compiler');
    lines.push(' * Target: JavaScript');
    lines.push(' */');
    lines.push('');

    for (const mod of modules) {
      lines.push(generateModuleContext(mod, 'javascript'));
      lines.push('');
      lines.push(...this.compileModule(mod, config));
      lines.push('');
    }

    return lines.join('\n');
  }

  private compileModule(mod: V2ModuleNode, config: CompilerConfig): string[] {
    const lines: string[] = [];
    const className = mod.name.replace(/[^a-zA-Z0-9_]/g, '_');

    lines.push(`class ${className} {`);
    lines.push(`  constructor() {`);

    if (mod.role) lines.push(`    this.role = "${mod.role}";`);
    if (mod.goal) lines.push(`    this.goal = "${mod.goal}";`);
    if (mod.tools) lines.push(`    this.tools = ${JSON.stringify(mod.tools)};`);
    if (mod.handoff) lines.push(`    this.handoff = ${JSON.stringify(mod.handoff)};`);
    if (mod.members) lines.push(`    this.members = ${JSON.stringify(mod.members)};`);

    lines.push(`  }`);
    lines.push('');

    lines.push(`  async execute(task) {`);
    lines.push(`    throw new Error("Not implemented");`);
    lines.push(`  }`);

    lines.push(`}`);
    lines.push('');
    lines.push(`module.exports = { ${className} };`);

    return lines;
  }
}

// ============================================================================
// JSON Target
// ============================================================================

class JSONTargetHandler implements CompileTargetHandler {
  name = 'json';

  compile(modules: V2ModuleNode[], config: CompilerConfig): string {
    if (modules.length === 1) {
      return generateModuleContext(modules[0], 'json');
    }
    return JSON.stringify(modules.map(m => JSON.parse(generateModuleContext(m, 'json'))), null, config.indent || 2);
  }
}