/**
 * MAM Code Emission Helpers
 *
 * Shared utilities for target generators: an indented line buffer
 * (CodeWriter), standard file headers, and text/identifier helpers.
 */

// ============================================================================
// CodeWriter
// ============================================================================

export interface CodeWriterOptions {
  /** Number of spaces per indent level (default 4). */
  indent?: number;
}

export class CodeWriter {
  private lines: string[] = [];
  private level = 0;
  private readonly unit: string;

  constructor(options: CodeWriterOptions = {}) {
    this.unit = ' '.repeat(options.indent ?? 4);
  }

  /** Write a single line at the current indent level. */
  write(line: string): this {
    if (line === '') {
      this.lines.push('');
    } else {
      this.lines.push(this.unit.repeat(this.level) + line);
    }
    return this;
  }

  /** Write one line built from concatenated parts (no args emits a blank line). */
  line(...parts: Array<string | number | boolean>): this {
    if (parts.length === 0) return this.write('');
    return this.write(parts.map(String).join(''));
  }

  /** Emit an empty line. */
  blank(): this {
    return this.write('');
  }

  /** Increase the current indent level. */
  indent(): this {
    this.level += 1;
    return this;
  }

  /** Decrease the current indent level (never below zero). */
  dedent(): this {
    if (this.level > 0) this.level -= 1;
    return this;
  }

  /** Run fn with one extra indent level, then restore the previous level. */
  withIndent<T>(fn: () => T): T {
    this.indent();
    try {
      return fn();
    } finally {
      this.dedent();
    }
  }

  toString(): string {
    return this.lines.join('\n');
  }

  getLines(): string[] {
    return [...this.lines];
  }
}

// ============================================================================
// Header Emission
// ============================================================================

/**
 * Standard generated-file header comment.
 * Python targets get a `"""` docstring; everything else uses `//` line comments.
 */
export function emitHeader(target: string, source: string): string {
  const title = 'Auto-generated by MAM Compiler';
  if (target === 'python') {
    return [
      '"""',
      title,
      `Target: ${target}`,
      `Source: ${source}`,
      '"""',
    ].join('\n');
  }
  return [
    `// ${title}`,
    `// Target: ${target}`,
    `// Source: ${source}`,
  ].join('\n');
}

// ============================================================================
// Text Helpers
// ============================================================================

/** Indent every non-empty line of `text` by `spaces` spaces. */
export function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(Math.max(0, spaces));
  return text
    .split('\n')
    .map(l => (l === '' ? '' : pad + l))
    .join('\n');
}

/** Join an array of lines into a single string. */
export function joinLines(lines: string[]): string {
  return lines.join('\n');
}

/** Replace characters that are invalid in most identifiers, and guard leading digits. */
export function sanitizeIdentifier(name: string): string {
  let result = name.replace(/[^a-zA-Z0-9_]/g, '_');
  if (/^[0-9]/.test(result)) result = `_${result}`;
  if (result === '') result = '_';
  return result;
}