import { parseString } from './parser.js';

/** Starter template identifiers. */
export type StarterKind = 'module' | 'agent' | 'tool';

/** Returns supported starter kinds. */
export function listStarterKinds(): StarterKind[] {
  return ['module', 'agent', 'tool'];
}

/** Resolves a starter alias. */
export function resolveStarterKind(kind: string): StarterKind {
  const value = kind.trim().toLowerCase();
  if (value === 'mod' || value === 'module') return 'module';
  if (value === 'bot' || value === 'assistant' || value === 'agent') return 'agent';
  if (value === 'utility' || value === 'cli' || value === 'tool') return 'tool';
  throw new Error(`unknown starter kind: ${kind}`);
}

/** Returns a starter template with placeholders. */
export function getStarterTemplate(kind: string): string {
  const resolved = resolveStarterKind(kind);
  const names: Record<StarterKind, string> = { module: 'Module', agent: 'Agent', tool: 'Tool' };
  return `---\nschema_version: "1"\nname: "{{name}}"\nversion: "0.1.0"\ndescription: "{{description}}"\nauthors:\n  - "{{author}}"\ntags:\n  - {{kind}}\nlicense: MIT\n---\n\n## Metadata\n\n${names[resolved]} generated by MAM TypeScript SDK.\n\n## Purpose\n\n{{purpose}}\n\n## Workflow\n\n1. Receive input.\n2. Produce output.\n\n## Outputs\n\n- result\n`;
}

/** Returns placeholder names in first-seen order. */
export function starterVariables(template: string): string[] {
  const result: string[] = [];
  for (const match of template.matchAll(/\{\{\s*([A-Za-z_][\w-]*)\s*\}\}/g)) if (!result.includes(match[1])) result.push(match[1]);
  return result;
}

/** Replaces placeholders case-insensitively and leaves unknown ones visible. */
export function renderStarter(template: string, values: Record<string, string>): string {
  return template.replace(/\{\{\s*([A-Za-z_][\w-]*)\s*\}\}/g, (whole, key: string) => {
    const wanted = key.toLowerCase();
    const found = Object.entries(values).find(([name]) => name.toLowerCase() === wanted);
    return found?.[1] ?? whole;
  });
}

/** Returns a validated starter name. */
export function validateStarterName(name: string): boolean {
  return /^[A-Za-z0-9][A-Za-z0-9 _-]{0,63}$/.test(name.trim());
}

/** Returns a safe file name for a starter. */
export function starterFileName(name: string): string {
  if (!validateStarterName(name)) throw new Error(`invalid starter name: ${name}`);
  return `${name.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-')}.mam.md`;
}

/** Creates a rendered starter and verifies it parses. */
export function newModuleStarter(name: string, kind = 'module', values: Record<string, string> = {}): string {
  if (!validateStarterName(name)) throw new Error(`invalid starter name: ${name}`);
  const output = renderStarter(getStarterTemplate(kind), { name, description: `${name} module`, author: 'MAM Team', purpose: `Define the ${name} capability.`, kind: resolveStarterKind(kind), ...values });
  parseString(output, { filePath: starterFileName(name) });
  return output;
}

/** Returns a slug suitable for identifiers. */
export function slugify(name: string): string {
  return name.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

/** Returns all starter templates keyed by kind. */
export function allStarterTemplates(): Record<StarterKind, string> {
  return { module: getStarterTemplate('module'), agent: getStarterTemplate('agent'), tool: getStarterTemplate('tool') };
}

/** Returns a safe default variable set. */
export function defaultStarterVariables(name: string, kind: string): Record<string, string> {
  return { name, description: `${name} module`, author: 'MAM Team', purpose: `Define the ${name} capability.`, kind };
}

/** Returns whether a template contains a named variable. */
export function hasStarterVariable(template: string, name: string): boolean {
  return starterVariables(template).includes(name);
}

/** Returns the number of placeholders in a template. */
export function countStarterVariables(template: string): number {
  return starterVariables(template).length;
}

/** Reports whether a starter is a valid module by parsing it. */
export function isValidStarter(template: string): boolean {
  try { return Boolean(parseString(template, { filePath: '<starter>' }).frontmatter); } catch { return false; }
}

/** Returns a starter kind description. */
export function describeStarterKind(kind: string): string {
  const resolved = resolveStarterKind(kind);
  return resolved === 'agent' ? 'An agent-oriented module with a purpose and workflow.' : resolved === 'tool' ? 'A focused tool module with explicit inputs and outputs.' : 'A general-purpose MAM module starter.';
}

/** Returns a rendered template without parsing. */
export function renderNamedStarter(name: string, kind: string, values: Record<string, string> = {}): string {
  return renderStarter(getStarterTemplate(kind), { ...defaultStarterVariables(name, resolveStarterKind(kind)), ...values });
}

/** Returns the filename extension used by MAM modules. */
export function starterExtension(): string {
  return '.mam.md';
}

/** Returns a starter with a canonical trailing newline. */
export function normalizeStarter(template: string): string {
  return `${template.trimEnd()}\n`;
}

/** Returns starter variables after rendering. */
export function remainingStarterVariables(template: string): string[] {
  return starterVariables(template);
}

void hasStarterVariable;
void countStarterVariables;

/** Returns a starter kind list as display text. */
export function starterKindList(): string {
  return listStarterKinds().join(', ');
}

/** Returns a safe starter name with a fallback. */
export function safeStarterName(name: string | undefined): string {
  return name && validateStarterName(name) ? name.trim() : 'module';
}

/** Returns a default template for a kind. */
export function defaultStarter(kind: string): string {
  return normalizeStarter(getStarterTemplate(kind));
}

/** Returns a rendered template with a title-safe name. */
export function renderedStarter(name: string, kind = 'module'): string {
  return newModuleStarter(name, kind, defaultStarterVariables(name, resolveStarterKind(kind)));
}

/** Returns whether a template contains no placeholders. */
export function templateIsRendered(template: string): boolean {
  return starterVariables(template).length === 0;
}

/** Returns the first variable in a template. */
export function firstStarterVariable(template: string): string | undefined {
  return starterVariables(template)[0];
}

/** Returns a template rendered with deterministic defaults. */
export function renderDefaultStarter(name: string, kind = 'module'): string {
  return renderStarter(defaultStarter(kind), defaultStarterVariables(name, resolveStarterKind(kind)));
}

/** Returns a safe file basename without an extension. */
export function starterBaseName(name: string): string {
  return starterFileName(name).slice(0, -'.mam.md'.length);
}

/** Returns all variables from a rendered module. */
export function starterVariablesFor(name: string, kind: string): string[] {
  return starterVariables(renderDefaultStarter(name, kind));
}

/** Returns a concise starter description. */
export function starterDescription(kind: string): string {
  return describeStarterKind(kind);
}

/** Returns a template with placeholders replaced by safe values. */
export function renderSafeStarter(template: string, values: Record<string, string>): string {
  return normalizeStarter(renderStarter(template, Object.fromEntries(starterVariables(template).map((key) => [key, values[key] ?? '']))));
}

/** Returns a list of starter aliases. */
export function starterAliases(kind: StarterKind): string[] {
  return kind === 'module' ? ['module', 'mod'] : kind === 'agent' ? ['agent', 'bot', 'assistant'] : ['tool', 'utility', 'cli'];
}

/** Reports whether a kind has an alias. */
export function isStarterAlias(value: string): boolean {
  return ['mod', 'bot', 'assistant', 'utility', 'cli'].includes(value.toLowerCase());
}

/** Returns a placeholder-preserving renderer result count. */
export function unresolvedVariableCount(template: string): number {
  return starterVariables(template).length;
}

/** Returns a rendered starter with a predictable newline. */
export function starterText(name: string, kind = 'module'): string {
  return normalizeStarter(renderedStarter(name, kind));
}

/** Returns the section title of a generated starter. */
export function starterPrimarySection(): string {
  return 'Purpose';
}

/** Returns a starter filename with a custom suffix. */
export function starterFileNameWithSuffix(name: string, suffix: string): string {
  if (!suffix.trim()) return starterFileName(name);
  return `${starterBaseName(name)}${suffix.startsWith('.') ? suffix : `.${suffix}`}`;
}

/** Returns whether a string contains MAM frontmatter. */
export function containsStarterFrontmatter(template: string): boolean {
  return /^---\n/.test(normalizeStarter(template));
}

/** Returns a starter name from a file path. */
export function starterNameFromPath(path: string): string {
  return path.replace(/\.mam\.md$/i, '').split(/[\\/]/).pop() ?? 'module';
}

/** Returns a simple template title. */
export function starterTitle(kind: string): string {
  const resolved = resolveStarterKind(kind);
  return resolved.charAt(0).toUpperCase() + resolved.slice(1);
}

/** Returns a starter template with a custom author. */
export function starterForAuthor(name: string, author: string, kind = 'module'): string {
  return newModuleStarter(name, kind, { ...defaultStarterVariables(name, resolveStarterKind(kind)), author });
}

/** Returns the number of known starter variables for a kind. */
export function standardVariableCount(kind = 'module'): number {
  return starterVariables(getStarterTemplate(kind)).length;
}

/** Returns a starter name with punctuation removed. */
export function cleanStarterName(name: string): string {
  return name.trim().replace(/[^A-Za-z0-9 _-]+/g, '').trim();
}

/** Reports whether a rendered starter is complete. */
export function starterIsComplete(rendered: string): boolean {
  return !templateIsRendered(rendered) && containsStarterFrontmatter(rendered);
}

/** Returns a default rendered starter for a name. */
export function completeStarter(name: string, kind = 'module'): string {
  return normalizeStarter(renderNamedStarter(safeStarterName(name), kind));
}

/** Returns a template's placeholders with their positions. */
export function variablePositions(template: string): Array<[string, number]> {
  return [...template.matchAll(/\{\{\s*([A-Za-z_][\w-]*)\s*\}\}/g)].map((match) => [match[1], match.index ?? 0]);
}

/** Returns a stable list of aliases. */
export function allStarterAliases(): string[] {
  return listStarterKinds().flatMap(starterAliases);
}

/** Returns a starter filename from a slug. */
export function fileNameForSlug(slug: string): string {
  if (!slug.trim()) throw new Error('starter slug must not be empty');
  return `${slug.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-')}.mam.md`;
}

/** Reports whether a template has a purpose section. */
export function hasPurposeSection(template: string): boolean {
  return /^##\s+Purpose\s*$/m.test(normalizeStarter(template));
}

/** Returns the first standard section in a template. */
export function firstSectionInTemplate(template: string): string | undefined {
  return normalizeStarter(template).match(/^##\s+(.+)$/m)?.[1];
}

/** Returns a starter description with a name. */
export function namedStarterDescription(name: string, kind: string): string {
  return `${safeStarterName(name)}: ${starterDescription(kind)}`;
}

/** Returns whether a starter name is safe for a file. */
export function starterNameIsFileSafe(name: string): boolean {
  return validateStarterName(name) && !/[\\/:*?"<>|]/.test(name);
}

/** Returns a stable template fingerprint. */
export function templateFingerprint(template: string): string {
  return starterVariables(template).sort().join('|');
}

/** Returns a display list of template variables. */
export function variableList(template: string): string {
  return starterVariables(template).join(', ') || 'none';
}

/** Returns a starter kind label. */
export function kindLabel(kind: string): string {
  return starterTitle(kind);
}

/** Returns a default template and its kind. */
export function templateWithKind(kind: string): { kind: StarterKind; template: string } {
  const resolved = resolveStarterKind(kind);
  return { kind: resolved, template: defaultStarter(resolved) };
}

/** Reports whether a name is a valid starter. */
export function validStarterName(name: string): boolean {
  return validateStarterName(name);
}
