# Auto-generated by MAM Compiler | Target: docker | Source: C:\Users\USER\LifeJiggy\Prompt_AI-Support\MAM\examples\advanced\agent.mam.md

FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .
RUN npm run build 2>/dev/null || true

FROM node:20-alpine AS production
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
ENV MAM_MODULE=agent-mam

RUN addgroup -g 1001 -S mamgroup && adduser -S mamuser -u 1001 -G mamgroup
WORKDIR /app
COPY --from=builder --chown=mamuser:mamgroup /app/node_modules ./node_modules
COPY --from=builder --chown=mamuser:mamgroup /app/package*.json ./
COPY --from=builder --chown=mamuser:mamgroup /app/dist ./dist
USER mamuser
EXPOSE 8080
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 CMD wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1
CMD ["node", "dist/index.js"]
