/**
 * Target Handler Tests
 */

import { describe, it, expect } from 'vitest';
import { PythonTarget } from '../src/targets/python.js';
import { JavaScriptTarget } from '../src/targets/javascript.js';
import { GoTarget } from '../src/targets/go.js';
import { OpenAITarget } from '../src/targets/openai.js';
import { LangGraphTarget } from '../src/targets/langgraph.js';
import { CrewAITarget } from '../src/targets/crewai.js';
import { type V2ModuleNode, type CompilerConfig } from '@mam/ast';

const loc = { start: { line: 1, column: 0 }, end: { line: 5, column: 0 } };

function makeModule(overrides: Partial<V2ModuleNode> & { name: string }): V2ModuleNode {
  return {
    type: 'ModuleNode',
    moduleType: 'agent',
    name: 'test-module',
    role: 'Test agent',
    goal: 'Test goal',
    location: loc,
    ...overrides,
  };
}

const agentModules: V2ModuleNode[] = [
  makeModule({
    name: 'researcher',
    moduleType: 'agent',
    role: 'Researcher',
    goal: 'Research topics',
    tools: ['web-search'],
    handoff: ['writer'],
  }),
];

const toolModules: V2ModuleNode[] = [
  makeModule({
    name: 'web-search',
    moduleType: 'tool',
    provider: 'google',
    capabilities: ['search'],
  }),
];

const workflowModules: V2ModuleNode[] = [
  makeModule({
    name: 'pipeline',
    moduleType: 'workflow',
    steps: [
      { type: 'StepNode', name: 'step-1', location: loc },
      { type: 'StepNode', name: 'step-2', location: loc },
    ],
    edges: [
      { type: 'EdgeNode', source: 'step-1', target: 'step-2', location: loc },
    ],
  }),
];

const teamModules: V2ModuleNode[] = [
  makeModule({
    name: 'dream-team',
    moduleType: 'team',
    members: ['researcher', 'writer'],
  }),
];

const config: CompilerConfig = { target: 'python', includeComments: true };

describe('PythonTargetHandler', () => {
  it('should generate Python code with class and def execute', () => {
    const target = new PythonTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('class');
    expect(output).toContain('def execute');
    expect(output).toContain('"""');
    expect(output).toContain('Generated by MAM Compiler');
    expect(output).toContain('Target: Python');
  });

  it('should generate tool class with provider', () => {
    const target = new PythonTarget();
    const output = target.compile(toolModules, config);

    expect(output).toContain('class');
    expect(output).toContain('google');
    expect(output).toContain('def execute');
  });

  it('should generate workflow with STEPS and EDGES', () => {
    const target = new PythonTarget();
    const output = target.compile(workflowModules, config);

    expect(output).toContain('class');
    expect(output).toContain('STEPS');
    expect(output).toContain('EDGES');
    expect(output).toContain('step-1');
    expect(output).toContain('step-2');
  });

  it('should generate team with MEMBERS', () => {
    const target = new PythonTarget();
    const output = target.compile(teamModules, config);

    expect(output).toContain('class');
    expect(output).toContain('MEMBERS');
  });
});

describe('JavaScriptTargetHandler', () => {
  it('should generate JS code with class and module.exports', () => {
    const target = new JavaScriptTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('class');
    expect(output).toContain('module.exports');
    expect(output).toContain('constructor');
    expect(output).toContain('execute');
    expect(output).toContain('Generated by MAM Compiler');
    expect(output).toContain('Target: JavaScript');
    expect(output).toContain('"use strict"');
  });

  it('should include role and goal in constructor', () => {
    const target = new JavaScriptTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('this.role');
    expect(output).toContain('this.goal');
    expect(output).toContain('Researcher');
    expect(output).toContain('Research topics');
  });

  it('should generate policy with check method', () => {
    const policyModules: V2ModuleNode[] = [
      makeModule({
        name: 'access-policy',
        moduleType: 'policy',
        allow: ['read', 'write'],
        deny: ['delete'],
      }),
    ];

    const target = new JavaScriptTarget();
    const output = target.compile(policyModules, config);

    expect(output).toContain('check');
    expect(output).toContain('this.deny');
    expect(output).toContain('this.allow');
  });
});

describe('GoTargetHandler', () => {
  it('should generate Go code with func and struct', () => {
    const target = new GoTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('struct');
    expect(output).toContain('func');
    expect(output).toContain('package main');
    expect(output).toContain('Generated by MAM Compiler');
    expect(output).toContain('Target: Go');
  });

  it('should generate PascalCase struct name', () => {
    const target = new GoTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('Researcher');
    expect(output).toContain('New');
  });

  it('should include Role and Goal fields', () => {
    const target = new GoTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('Role string');
    expect(output).toContain('Goal string');
    expect(output).toContain('Tools []string');
  });
});

describe('OpenAITargetHandler', () => {
  it('should generate OpenAI SDK code with Agent and Runner', () => {
    const target = new OpenAITarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('Agent(');
    expect(output).toContain('Runner');
    expect(output).toContain('from agents import');
    expect(output).toContain('Generated by MAM Compiler');
    expect(output).toContain('Target: OpenAI Agents SDK');
  });

  it('should generate function_tool decorators for tools', () => {
    const target = new OpenAITarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('@function_tool');
    expect(output).toContain('async def');
  });

  it('should generate tool function with return type', () => {
    const target = new OpenAITarget();
    const output = target.compile(toolModules, config);

    expect(output).toContain('@function_tool');
    expect(output).toContain('def');
    expect(output).toContain('-> str');
  });
});

describe('LangGraphTargetHandler', () => {
  it('should generate LangGraph code with StateGraph', () => {
    const target = new LangGraphTarget();
    const output = target.compile(workflowModules, config);

    expect(output).toContain('StateGraph');
    expect(output).toContain('build_');
    expect(output).toContain('workflow.add_node');
    expect(output).toContain('Generated by MAM Compiler');
    expect(output).toContain('Target: LangGraph');
  });

  it('should generate TypedDict for agents', () => {
    const target = new LangGraphTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('TypedDict');
    expect(output).toContain('add_messages');
  });

  it('should include entry point and END edge', () => {
    const target = new LangGraphTarget();
    const output = target.compile(workflowModules, config);

    expect(output).toContain('set_entry_point');
    expect(output).toContain('END');
  });
});

describe('CrewAITargetHandler', () => {
  it('should generate CrewAI code with Agent and Task', () => {
    const target = new CrewAITarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('Agent(');
    expect(output).toContain('role=');
    expect(output).toContain('goal=');
    expect(output).toContain('from crewai import');
    expect(output).toContain('Generated by MAM Compiler');
    expect(output).toContain('Target: CrewAI');
  });

  it('should generate tool class extending BaseTool', () => {
    const target = new CrewAITarget();
    const output = target.compile(toolModules, config);

    expect(output).toContain('class');
    expect(output).toContain('BaseTool');
    expect(output).toContain('_run');
    expect(output).toContain('_arun');
  });

  it('should generate team with tasks and crew', () => {
    const target = new CrewAITarget();
    const output = target.compile(teamModules, config);

    expect(output).toContain('Task(');
    expect(output).toContain('Crew(');
    expect(output).toContain('Process.sequential');
    expect(output).toContain('researcher');
    expect(output).toContain('writer');
  });
});
