/**
 * Target Handler Tests
 */

import { describe, it, expect } from 'vitest';
import { PythonTarget } from '../src/targets/python.js';
import { JavaScriptTarget } from '../src/targets/javascript.js';
import { GoTarget } from '../src/targets/go.js';
import { OpenAITarget } from '../src/targets/openai.js';
import { LangGraphTarget } from '../src/targets/langgraph.js';
import { CrewAITarget } from '../src/targets/crewai.js';
import { CSharpTarget } from '../src/targets/csharp.js';
import { JavaTarget } from '../src/targets/java.js';
import { WasmTarget } from '../src/targets/wasm.js';
import { GeminiTarget } from '../src/targets/gemini.js';
import { AutoGenTarget } from '../src/targets/autogen.js';
import { KubernetesTarget } from '../src/targets/kubernetes.js';
import { TerraformTarget } from '../src/targets/terraform.js';
import { type V2ModuleNode, type CompilerConfig } from '@mam/ast';

const loc = { start: { line: 1, column: 0 }, end: { line: 5, column: 0 } };

function makeModule(overrides: Partial<V2ModuleNode> & { name: string }): V2ModuleNode {
  return {
    type: 'ModuleNode',
    moduleType: 'agent',
    name: 'test-module',
    role: 'Test agent',
    goal: 'Test goal',
    location: loc,
    ...overrides,
  };
}

const agentModules: V2ModuleNode[] = [
  makeModule({
    name: 'researcher',
    moduleType: 'agent',
    role: 'Researcher',
    goal: 'Research topics',
    tools: ['web-search'],
    handoff: ['writer'],
  }),
];

const toolModules: V2ModuleNode[] = [
  makeModule({
    name: 'web-search',
    moduleType: 'tool',
    provider: 'google',
    capabilities: ['search'],
  }),
];

const workflowModules: V2ModuleNode[] = [
  makeModule({
    name: 'pipeline',
    moduleType: 'workflow',
    steps: [
      { type: 'StepNode', name: 'step-1', location: loc },
      { type: 'StepNode', name: 'step-2', location: loc },
    ],
    edges: [
      { type: 'EdgeNode', source: 'step-1', target: 'step-2', location: loc },
    ],
  }),
];

const teamModules: V2ModuleNode[] = [
  makeModule({
    name: 'dream-team',
    moduleType: 'team',
    members: ['researcher', 'writer'],
  }),
];

const config: CompilerConfig = { target: 'python', includeComments: true };

describe('PythonTargetHandler', () => {
  it('should generate Python code with class and def execute', () => {
    const target = new PythonTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('class');
    expect(output).toContain('def execute');
    expect(output).toContain('"""');
    expect(output).toContain('Generated by MAM Compiler');
    expect(output).toContain('Target: Python');
  });

  it('should generate tool class with provider', () => {
    const target = new PythonTarget();
    const output = target.compile(toolModules, config);

    expect(output).toContain('class');
    expect(output).toContain('google');
    expect(output).toContain('def execute');
  });

  it('should generate workflow with steps and edges', () => {
    const target = new PythonTarget();
    const output = target.compile(workflowModules, config);

    expect(output).toContain('class');
    expect(output).toContain('self.steps');
    expect(output).toContain('self.edges');
    expect(output).toContain('step-1');
    expect(output).toContain('step-2');
  });

  it('should generate team with members', () => {
    const target = new PythonTarget();
    const output = target.compile(teamModules, config);

    expect(output).toContain('class');
    expect(output).toContain('self.members');
  });
});

describe('JavaScriptTargetHandler', () => {
  it('should generate JS code with class and module.exports', () => {
    const target = new JavaScriptTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('class');
    expect(output).toContain('module.exports');
    expect(output).toContain('constructor');
    expect(output).toContain('execute');
    expect(output).toContain('Generated by MAM Compiler');
    expect(output).toContain('Target: JavaScript');
    expect(output).toContain('"use strict"');
  });

  it('should include role and goal in constructor', () => {
    const target = new JavaScriptTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('this.role');
    expect(output).toContain('this.goal');
    expect(output).toContain('Researcher');
    expect(output).toContain('Research topics');
  });

  it('should generate policy with check method', () => {
    const policyModules: V2ModuleNode[] = [
      makeModule({
        name: 'access-policy',
        moduleType: 'policy',
        allow: ['read', 'write'],
        deny: ['delete'],
      }),
    ];

    const target = new JavaScriptTarget();
    const output = target.compile(policyModules, config);

    expect(output).toContain('check');
    expect(output).toContain('this.deny');
    expect(output).toContain('this.allow');
  });
});

describe('GoTargetHandler', () => {
  it('should generate Go code with func and struct', () => {
    const target = new GoTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('struct');
    expect(output).toContain('func');
    expect(output).toContain('package main');
    expect(output).toContain('Generated by MAM Compiler');
    expect(output).toContain('Target: Go');
  });

  it('should generate PascalCase struct name', () => {
    const target = new GoTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('Researcher');
    expect(output).toContain('New');
  });

  it('should include Role and Goal fields', () => {
    const target = new GoTarget();
    const output = target.compile(agentModules, config);

    expect(output).toMatch(/Role\s+string/);
    expect(output).toMatch(/Goal\s+string/);
    expect(output).toMatch(/Tools\s+\[\]string/);
  });
});

describe('OpenAITargetHandler', () => {
  it('should generate OpenAI SDK code with OpenAI client', () => {
    const target = new OpenAITarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('from openai import OpenAI');
    expect(output).toContain('run_researcher');
    expect(output).toContain('client.chat.completions.create');
    expect(output).toContain('Generated by MAM Compiler');
    expect(output).toContain('Target: OpenAI SDK');
  });

  it('should register agent tools as OpenAI function schemas', () => {
    const target = new OpenAITarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('def run_researcher');
    expect(output).toContain('"type": "function"');
    expect(output).toContain('kwargs["tools"]');
  });

  it('should generate tool function with schema', () => {
    const target = new OpenAITarget();
    const output = target.compile(toolModules, config);

    expect(output).toContain('def web_search(**kwargs: object) -> str:');
    expect(output).toContain('def web_search_schema() -> dict:');
    expect(output).toContain('-> str');
  });
});

describe('LangGraphTargetHandler', () => {
  it('should generate LangGraph code with StateGraph', () => {
    const target = new LangGraphTarget();
    const output = target.compile(workflowModules, config);

    expect(output).toContain('StateGraph');
    expect(output).toContain('build_');
    expect(output).toContain('graph.add_node');
    expect(output).toContain('Generated by MAM Compiler');
    expect(output).toContain('Target: LangGraph');
  });

  it('should generate TypedDict for agents', () => {
    const target = new LangGraphTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('TypedDict');
    expect(output).toContain('add_messages');
  });

  it('should include START and END edges', () => {
    const target = new LangGraphTarget();
    const output = target.compile(workflowModules, config);

    expect(output).toContain('graph.add_edge(START');
    expect(output).toContain('END');
  });
});

describe('CrewAITargetHandler', () => {
  it('should generate CrewAI code with Agent and Task', () => {
    const target = new CrewAITarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('Agent(');
    expect(output).toContain('role=');
    expect(output).toContain('goal=');
    expect(output).toContain('from crewai import');
    expect(output).toContain('Generated by MAM Compiler');
    expect(output).toContain('Target: CrewAI');
  });

  it('should generate tool class extending BaseTool', () => {
    const target = new CrewAITarget();
    const output = target.compile(toolModules, config);

    expect(output).toContain('class');
    expect(output).toContain('BaseTool');
    expect(output).toContain('_run');
    expect(output).toContain('_arun');
  });

  it('should generate team with tasks and crew', () => {
    const target = new CrewAITarget();
    const output = target.compile(teamModules, config);

    expect(output).toContain('Task(');
    expect(output).toContain('Crew(');
    expect(output).toContain('Process.sequential');
    expect(output).toContain('researcher');
    expect(output).toContain('writer');
  });
});

describe('CSharpTargetHandler', () => {
  it('should generate C# code with sealed class and Execute method', () => {
    const target = new CSharpTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('public sealed class ResearcherAgent');
    expect(output).toContain('public AgentResult Execute(string task)');
    expect(output).toContain('Success = true');
    expect(output).toContain('Generated by MAM Compiler');
    expect(output).toContain('Target: C#');
  });

  it('should include role and goal as properties', () => {
    const target = new CSharpTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('public string Role');
    expect(output).toContain('public string Goal');
    expect(output).toContain('Researcher');
    expect(output).toContain('Research topics');
  });

  it('should generate tool with provider', () => {
    const target = new CSharpTarget();
    const output = target.compile(toolModules, config);

    expect(output).toContain('public sealed class WebSearchTool');
    expect(output).toContain('google');
    expect(output).toContain('ToolResult Invoke(string action');
  });

  it('should generate policy with Check method', () => {
    const policyModules: V2ModuleNode[] = [
      makeModule({
        name: 'access-policy',
        moduleType: 'policy',
        allow: ['read', 'write'],
        deny: ['delete'],
      }),
    ];

    const target = new CSharpTarget();
    const output = target.compile(policyModules, config);

    expect(output).toContain('bool Check');
    expect(output).toContain('Deny.Contains');
    expect(output).toContain('Allow.Contains');
  });
});

describe('JavaTargetHandler', () => {
  it('should generate Java code with class and public methods', () => {
    const target = new JavaTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('public static class ResearcherAgent');
    expect(output).toContain('AgentResult execute(String task)');
    expect(output).toContain('return new AgentResult(true, task,');
    expect(output).toContain('Generated by MAM Compiler');
    expect(output).toContain('Target: Java');
  });

  it('should include role and goal fields', () => {
    const target = new JavaTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('public final String role');
    expect(output).toContain('public final String goal');
    expect(output).toContain('Researcher');
  });

  it('should generate tool class with provider', () => {
    const target = new JavaTarget();
    const output = target.compile(toolModules, config);

    expect(output).toContain('public static class WebSearchTool');
    expect(output).toContain('google');
    expect(output).toContain('ToolResult invoke(String action');
  });

  it('should generate workflow with steps', () => {
    const target = new JavaTarget();
    const output = target.compile(workflowModules, config);

    expect(output).toContain('public class');
    expect(output).toContain('steps');
    expect(output).toContain('step-1');
    expect(output).toContain('step-2');
  });
});

describe('WasmTargetHandler', () => {
  it('should generate WAT module with agent functions', () => {
    const target = new WasmTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('(module');
    expect(output).toContain('(func');
    expect(output).toContain('(export');
    expect(output).toContain('execute');
    expect(output).toContain('Generated by MAM Compiler');
    expect(output).toContain('Target: WebAssembly (WAT)');
  });

  it('should include memory export', () => {
    const target = new WasmTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('(memory');
    expect(output).toContain('(export "memory")');
  });

  it('should generate tool with provider comment', () => {
    const target = new WasmTarget();
    const output = target.compile(toolModules, config);

    expect(output).toContain('Tool:');
    expect(output).toContain('google');
    expect(output).toContain('(module');
  });

  it('should generate workflow with step count', () => {
    const target = new WasmTarget();
    const output = target.compile(workflowModules, config);

    expect(output).toContain('Workflow: pipeline');
    expect(output).toContain('pipeline_step_count');
    expect(output).toContain('pipeline_edge_count');
  });
});

describe('GeminiTargetHandler', () => {
  it('should generate Gemini SDK code with GenerativeModel', () => {
    const target = new GeminiTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('import google.generativeai as genai');
    expect(output).toContain('GenerativeModel');
    expect(output).toContain('genai.configure');
    expect(output).toContain('Generated by MAM Compiler');
    expect(output).toContain('Target: Google Gemini SDK');
  });

  it('should include role and goal in agent', () => {
    const target = new GeminiTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('Role: Researcher');
    expect(output).toContain('Goal: Research topics');
    expect(output).toContain('genai.GenerativeModel');
  });

  it('should generate tool with provider', () => {
    const target = new GeminiTarget();
    const output = target.compile(toolModules, config);

    expect(output).toContain('google');
    expect(output).toContain('def web_search');
  });

  it('should generate workflow with steps', () => {
    const target = new GeminiTarget();
    const output = target.compile(workflowModules, config);

    expect(output).toContain('Steps:');
    expect(output).toContain('step_1');
    expect(output).toContain('step_2');
  });
});

describe('AutoGenTargetHandler', () => {
  it('should generate AutoGen code with ConversableAgent', () => {
    const target = new AutoGenTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('ConversableAgent');
    expect(output).toContain('from autogen import');
    expect(output).toContain('system_message');
    expect(output).toContain('Generated by MAM Compiler');
    expect(output).toContain('Target: Microsoft AutoGen');
  });

  it('should create agent factory function', () => {
    const target = new AutoGenTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('def make_researcher()');
    expect(output).toContain('_make_agent');
  });

  it('should generate team with GroupChat manager', () => {
    const target = new AutoGenTarget();
    const output = target.compile(teamModules, config);

    expect(output).toContain('GroupChat');
    expect(output).toContain('GroupChatManager');
    expect(output).toContain('researcher');
    expect(output).toContain('writer');
  });

  it('should generate policy with check method', () => {
    const policyModules: V2ModuleNode[] = [
      makeModule({
        name: 'access-policy',
        moduleType: 'policy',
        allow: ['read'],
        deny: ['delete'],
      }),
    ];

    const target = new AutoGenTarget();
    const output = target.compile(policyModules, config);

    expect(output).toContain('ALLOW');
    expect(output).toContain('DENY');
    expect(output).toContain('check');
  });
});

describe('KubernetesTargetHandler', () => {
  it('should generate K8s Deployment manifest', () => {
    const target = new KubernetesTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('apiVersion: apps/v1');
    expect(output).toContain('kind: Deployment');
    expect(output).toContain('mam-type: agent');
    expect(output).toContain('Generated by MAM Compiler');
    expect(output).toContain('Target: Kubernetes');
  });

  it('should include agent metadata in env vars', () => {
    const target = new KubernetesTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('AGENT_ROLE');
    expect(output).toContain('AGENT_GOAL');
    expect(output).toContain('Researcher');
  });

  it('should generate tool deployment with provider', () => {
    const target = new KubernetesTarget();
    const output = target.compile(toolModules, config);

    expect(output).toContain('kind: Deployment');
    expect(output).toContain('mam-type: tool');
    expect(output).toContain('google');
  });

  it('should generate workflow deployment', () => {
    const target = new KubernetesTarget();
    const output = target.compile(workflowModules, config);

    expect(output).toContain('kind: Deployment');
    expect(output).toContain('mam-type: workflow');
    expect(output).toContain('step-1');
  });
});

describe('TerraformTargetHandler', () => {
  it('should generate Terraform resource block', () => {
    const target = new TerraformTarget();
    const output = target.compile(agentModules, config);

    expect(output).toContain('resource "kubernetes_deployment_v1" "researcher"');
    expect(output).toContain('variable "researcher_image"');
    expect(output).toContain('value = "Researcher"');
    expect(output).toContain('value = "Research topics"');
    expect(output).toContain('Generated by MAM Compiler');
    expect(output).toContain('Target: Terraform');
  });

  it('should generate tool resource with provider', () => {
    const target = new TerraformTarget();
    const output = target.compile(toolModules, config);

    expect(output).toContain('resource "kubernetes_deployment_v1" "web_search"');
    expect(output).toContain('value = "google"');
  });

  it('should generate workflow resource with steps', () => {
    const target = new TerraformTarget();
    const output = target.compile(workflowModules, config);

    expect(output).toContain('resource "kubernetes_deployment_v1" "pipeline"');
    expect(output).toContain('value = "step-1,step-2"');
    expect(output).toContain('step-1');
    expect(output).toContain('step-2');
  });

  it('should generate team resource with members', () => {
    const target = new TerraformTarget();
    const output = target.compile(teamModules, config);

    expect(output).toContain('resource "kubernetes_deployment_v1" "dream_team"');
    expect(output).toContain('value = "researcher,writer"');
  });
});
